### PR TITLE
gnrc_lwmac: use uintptr_t to get value of pointer

### LINKED ISSUE #12869: sys\net\gnrc\link_layer\lwmac: cast error with avg-gcc
#### Description
Cast error in gnrc_lwmac while build test/gnrc_lwmac for AVR-based derfmega256 board. 
Similar to #12853.
#### Steps to reproduce the issue
- Take RIOT-OS latest master
- Update the file tests/gnrc_lwmac/Makefile :  
`-BOARD_WHITELIST := samr21-xpro`
`+BOARD_WHITELIST := samr21-xpro derfmega256` 
- Execute `BOARD=derfmega256 make all`

#### Expected results
The tests/gnrc_lwmac builds on deRFmega256 without errors.

#### Actual results
cast error:
`/RIOT/sys/net/gnrc/link_layer/lwmac/lwmac.c: In function ‘rtt_cb’:
/RIOT/sys/net/gnrc/link_layer/lwmac/lwmac.c:679:26: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]`
`     msg.content.value = ((uint32_t) arg) & 0xffff;`
`                          ^`
`cc1: all warnings being treated as errors`

#### Versions
RIOT latest master

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

A pointer is not 32 bit on all platforms.
Since gnrc_lwmac only stores 16 bit in the pointer variable it is still save to cast like this even on AVR, but cast to `uintptr_t` instead of `uint32_t`.

### Testing procedure
`tests/gnrc_lwmac` should still work as well as in master

### Issues/PRs references
fixes #12869

### CODE REVIEW

File: sys/net/gnrc/link_layer/lwmac/lwmac.c [hunk 1]
```diff
@@ -676,7 +676,7 @@ static void rtt_cb(void *arg)
 {
     msg_t msg;
 
-    msg.content.value = ((uint32_t) arg) & 0xffff;
+    msg.content.value = ((uintptr_t) arg) & 0xffff;
```
Comment (miri64) [inline sys/net/gnrc/link_layer/lwmac/lwmac.c]: Not sure if an outer cast might be necessary as well:

```suggestion
    msg.content.value = (uint32_t)(((uintptr_t) arg) & 0xffff);
```

(my intuition says it shouldn't as `sizeof(uintptr_t) <= sizeof(uint32_t)` should always be true. So let's wait for Murdock to give the verdict on that.

Comment (benpicco) [reply sys/net/gnrc/link_layer/lwmac/lwmac.c]: It wouldn't be true for 64 bit architectures.
I suppose casting to `uint16_t` is the better option then.

Comment (miri64) [reply sys/net/gnrc/link_layer/lwmac/lwmac.c]: Now that you say start talking about wider pointers than `uint32_t` ... `msg.content.value` is in a `union` with `msg.content.ptr`. Of course there is the very unlikely case that `arg` is not in the range of `uint16_t`, by why not just do

```suggestion
    msg.content.ptr = arg;
```

?

Comment (miri64) [reply sys/net/gnrc/link_layer/lwmac/lwmac.c]: (of course there should be a comment explaining what's going on there)

Comment (benpicco) [reply sys/net/gnrc/link_layer/lwmac/lwmac.c]: Now that's something I'd like to avoid.
It implicitly makes assumptions on how the memory is layed out in the union if the size of `uint32_t` and `void*` doesn't match.
I wouldn't intuitively know if this works on all architectures - let's rather be explicit.

Comment (miri64) [reply sys/net/gnrc/link_layer/lwmac/lwmac.c]: Ok, then go for the outer cast option.
