### PR TITLE
pkg/semtech-loramac: rework interaction with the MAC

### LINKED ISSUE #11530: pkg/semtech_loramac: deadlock with UNCONFIRMED messages
#### Description

If you are unlucky, `semtech_loramac` package can produce a deadlock when you send `UNCONFIRMED` messages from a thread that doesn't have a message queue.

The simplest way to show why is to explain how `semtech_loramac` package is connected to **LoRaMAC-node** library. This library has 3 interfaces: **MLME**, **MCPS** and **MIB**. When you send an application uplink you use the **MCPS** interface. This interface is asynchronous and can trigger two events: `Confirm` and `Indication`.

LoRMAC architecture

When you send an uplink you first call `semtech_loramac_send` and then `semtech_loramac_recv` to wait for the transmission to finish. Currently `semtech_loramac` handle the two **LoRaMAC-node** events as following:

* when an `UNCONFIRMED` message is sent, `semtech_loramac_recv` returns on `Confirm` event.

* when a `CONFIRMED` message is sent, `Confirm` event [is ignored][confirm-ignored]. As we expect an Ack from the LoRa server, `semtech_loramac_recv` will return on `Indication` event (when this Ack is received). Waiting for `Indication` event allows also to retrieve data from downlinks.

Function `semtech_loramac_recv` is waiting using the message module on the caller thread. When `Confirm` / `Indication` event is received, loramac event loop sends a `MSG_TYPE_LORAMAC_TX_STATUS` message to the caller thread, so it can returns from `semtech_loramac_recv`. If this thread doesn't have a message queue, sending the message blocks the event loops until the caller thread receives the message.

The problem is that when you transmit an `UNCONFIRMED` message you are also waiting for the 2 RX windows. If the LoRa server is sending a downlink to the device, `Indication` event will be fired but loramac event loop has already sent `MSG_TYPE_LORAMAC_TX_STATUS` on `Confirm` event. It will send another `MSG_TYPE_LORAMAC_TX_STATUS` that will block the event loop forever because the caller thread is out of `semtech_loramac_recv`. Even worse, if now the caller thread calls `semtech_loramac_send`, a deadlock occurs.

With the current architecture of `semtech_loramac` package, it is quite difficult to fix this issue. The simplest way would be to ignore `Indication` event when an `UNCONFIRMED` message was sent, but data from downlink messages would be lost.

#### Steps to reproduce the issue

Send an `UNCONFIRMED` message from a thread that doesn't have an message queue to a LoRa server that have a downlink message to transmit to the end device.  
In fact if you are lucky LoRa server can send a downlink by itself if it has MAC parameters to transmit to end device (for example `NewChannelReq`).

The image below describes what happened when a downlink is received after an `UNCONFIRMED` uplink.

Deadlock

The code that was used to produce this example is the following:

```c
loramac.cnf = LORAMAC_TX_UNCNF;
uint8_t ret = semtech_loramac_send(&loramac, (uint8_t *)message, strlen(message));

ret = semtech_loramac_recv(&loramac);
printf("Received: %d\n", ret);

xtimer_sleep(10);
printf("Send second message\n");
ret = semtech_loramac_send(&loramac, (uint8_t *)message, strlen(message));
```

[confirm-ignored]: https://github.com/RIOT-OS/RIOT/blob/master/pkg/semtech-loramac/contrib/semtech_loramac.c#L165

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This is another attempt to fix #11530.
It follows the suggestion of @ParksProjets in https://github.com/RIOT-OS/RIOT/pull/11535#issuecomment-493151047:
- TX status is now only reported after an mcps confirm event
- RX data are notified from mcps indication events
- one needs an external thread to receive data from the MAC. This is much simpler but it consume a little more RAM if one wants to manage downlinks message outside of the MAC. The bonus point with this approach is the ability to correctly support class C devices.

I have tested this PR using OTAA, ABP activations and with CONFIRMED and UNCONFIRMED messages.

Everything is working as expected.

The only small thing is the link check which is not working correctly but it's already the case in master I think.

Finally, I also had to update the `examples/lorawan` application and doxygen documentation to avoid potential lock of autonomous application. Maybe `examples/lorawan` could be later refactored with downling messages better handled or adapted for class C devices.

### Testing procedure

Run `tests/pkg_semtech-loramac`, send messages from the device, send messages from the network using CONFIRMED/UNCONFIRMED (`cnf/uncnf` option of `loramac tx`: everything should work, with this PR, the application doesn't block.

### Issues/PRs references

fixes #11530, closes #11535 (cleaner alternative)

### CODE REVIEW

File: pkg/semtech-loramac/contrib/semtech_loramac.c [hunk 1]
```diff
@@ -839,7 +837,7 @@ uint8_t semtech_loramac_send(semtech_loramac_t *mac, uint8_t *data, uint8_t len)
         return SEMTECH_LORAMAC_NOT_JOINED;
     }
 
-    /* Correctly set the caller pid */
+    /* Correctly set the sender thread pid */
```
Comment (fjmolinas) [inline pkg/semtech-loramac/contrib/semtech_loramac.c]: I think the comment should be inline with the variable names.

File: pkg/semtech-loramac/include/semtech_loramac.h [hunk 2]
```diff
@@ -110,6 +110,7 @@ typedef struct {
 typedef struct {
     mutex_t lock;                                /**< loramac access lock */
     uint8_t caller_pid;                          /**< pid of caller thread */
```
Comment (fjmolinas) [inline pkg/semtech-loramac/include/semtech_loramac.h]: Maybe it makes more sense if this is `tx_pid` if I understand right this thread is in charge of join procedure and sending packets, so tx. Would be more inline with rx_pid (receiver thread)

File: tests/pkg_semtech-loramac/main.c [hunk 3]
```diff
@@ -20,19 +20,49 @@
...
 
+#include "thread.h"
 #include "msg.h"
 #include "shell.h"
 #include "fmt.h"
 
 #include "net/loramac.h"
 #include "semtech_loramac.h"
 
+#define LORAMAC_RECV_MSG_QUEUE                   (4U)
```
Comment (fjmolinas) [inline tests/pkg_semtech-loramac/main.c]: Why 4? Could it be less? Does it need to be more?

File: pkg/semtech-loramac/doc.txt [hunk 4]
```diff
@@ -95,12 +95,6 @@
  *         return 1;
  *     }
  *
- *     /* 5. wait for any potentially received data */
```
Comment (fjmolinas) [inline pkg/semtech-loramac/doc.txt]: Document starting and usage of a receiving thread.

**Comment by fjmolinas** [comment]
Tested it does work and no deadlock, I confirm it fixes #11530. @ParksProjets can you confirm it fixes the issue on your side?

File: tests/pkg_semtech-loramac/main.c (hunk 3 above)
Comment (aabadie) [reply tests/pkg_semtech-loramac/main.c]: This allows optimizing a bit the size in RAM while still allowing to have an asynchronous thread. Since this thread is not heavily loaded, I think it's fine to have a lower value. Previously it was 16 which is unnecessarily high (I have checked and most of RIOT examples uses 8 or 4).

File: pkg/semtech-loramac/doc.txt (hunk 4 above)
Comment (aabadie) [reply pkg/semtech-loramac/doc.txt]: Done

**Comment by aabadie** [comment]
@fjmolinas, I found a problem with the link_check feature. The current refactoring is breaking it. I know how to fix it simply but now that I'm thinking of it, I'd like to try a deeper refactoring of the interaction between the MAC events (MCPS confirm/indication, MLME confirm/indication) and the event loop. I hope this will simplify a bit more all this mess.

**Comment by aabadie** [comment]
@fjmolinas, I've reworked this the PR the way we discussed IRL and now everything is working (including link_check info and received ACKs).

File: pkg/semtech-loramac/contrib/semtech_loramac.c [hunk 5]
```diff
@@ -695,63 +568,194 @@ void *_semtech_loramac_event_loop(void *arg)
...
+                        /* The server signals that it has pending data to be sent.
+                           We schedule an uplink as soon as possible to flush the server. */
+                        DEBUG("[semtech-loramac] MCPS indication: pending data, schedule an "
+                              "uplink\n");
+                        uint8_t prev_port = mac->port;
+                        mac->port = 0;
+                        _semtech_loramac_send(mac, NULL, 0);
+                        mac->port = prev_port;
+                    }
+                    else if (indication->RxData) {
```
Comment (fjmolinas) [inline pkg/semtech-loramac/contrib/semtech_loramac.c]: There is a border case where if a downlink is received when a cnf messaged is sent the `indication-AckReceived` doesn't go up to the application. Although this doesn't matter in class A, in class B or C this could be mixed. If using `if` instead of `elseif` this would work

**Comment by aabadie** [comment]
> I see all my comments have been addressed, can you squash?

Done!

**Comment by aabadie** [comment]
Note that this PR will conflicts with #8855 once merged but I prefer this one being merged first.

**Comment by fjmolinas** [comment]
@aabadie somehow before the squash I oversaw that `waspmote` doesn't fit anymore. I still think this is a good change but reducing supported boards doesn't seem great. Anyway for reducing stack-sizes for constrained boards? Or removing features from the test for constrained boards?

**Comment by fjmolinas** [comment]
> Note that this PR will conflicts with #8855 once merged but I prefer this one being merged first.

Noted!

**Comment by aabadie** [comment]
>  Anyway for reducing stack-sizes for constrained boards? Or removing features from the test for constrained boards?

I think I already tried both:
- reducing stack size was somehow crashing sometimes
- removing features: I tried to make link_check optional but it was not enough. 

For me it's a problem of missing RAM, and waspmote was already very short. Adding a second thread is too much for it.

**Comment by aabadie** [comment]
What about simply disabling RX thread ?

**Comment by fjmolinas** [comment]
> What about simply disabling RX thread ?

I think that would be an acceptable compromise. The previous support had a bug so if fixing it adds some memory usage then I think it's okay to drop some feature support for waspmote, which was already buggy in master. :)

**Comment by aabadie** [comment]
@fjmolinas, I made all RX related code optional using a pseudo-module `semtech_loramac_rx`. Link check is also excluded because it relies on RX.

**Comment by fjmolinas** [comment]
@aabadie everything is good! This commit need to be discarded though `tests/pkg_semtech-loramac: waspmote-pro doesn't fit anymore`.

**Comment by fjmolinas** [comment]
Go!

**Comment by aabadie** [comment]
Great! Thanks a lot for reviewing @fjmolinas :)
Now I have to rebase the other ones ;)
