### PR TITLE
examples/dtls-echo: handle handshake_failure alert

### LINKED ISSUE #12351: examples/dtls-echo: server does not returns handshake failure when no supported cipher suite
#### Description

I came across this while comparing behaviour of dtls-echo against #11943.

According to the Section 7.4.1.2 of TLS 1.2 RFC, the server should return a handshake failure if no matching ciphersuite is found (relevant part marked **bold**):

> The cipher suite list, passed from the client to the server in ClientHello message contains the combinations of algorithms supported by the client in order of the client' preference (favorite choice first).  Each cipher suite defines a exchange algorithm, a bulk encryption algorithm (including secret length), a MAC algorithm, and a PRF.  The server will select a suite or, **if no acceptable choices are presented, return a handshake failure alert and close the connection.**  If the list contains suites the server does not recognize, support, or wish to use, server MUST ignore those cipher suites, and process the ones as usual.

The dtls-echo server returns a close_notify (code 0) alert instead of a handshake_failure (code 40) alert.

#### Steps to reproduce the issue

Server setup:

1. In the Makefile, enable PSK and disable ECC for the server:
```Makefile
CFLAGS += -DDTLS_PSK
#CFLAGS += -DDTLS_ECC
```
2. Compile and start a `native` instance running dtls-echo example with `PORT=tap0 make all term`
3. Start the DTLS server on the instance with `dtlss start`
4. Get IP of the DTLS server with `ifconfig`

Client setup:

For the client, uncomment the  `CFLAGS += -DTINYDTLS_DEBUG` line in dtls-echo Makefile to enable debug output.

1. In the Makefile, enable ECC and disable PSK for the client:
```Makefile
#CFLAGS += -DDTLS_PSK
CFLAGS += -DDTLS_ECC
```
2. Compile and start a `native` instance running dtls-echo example with `PORT=tap1 make all term`
3. Send test string to the server using the IP from step 4. of the server setup: `dtlsc <server ip> TEST`

#### Expected results

The debug output will print lots of things, but we are interested only in the last line:

```
[...]
Oct 01 16:24:16 DEBG receive unencrypted: (2 bytes):
00000000 02 28
```

The last byte (0x28) represents the value for handshake_failure (40) as described by the [TLS RFC](https://tools.ietf.org/html/rfc5246#appendix-A.3)

#### Actual results

```
[...]
Oct 01 16:30:15 DEBG send unencrypted: (2 bytes):
00000000 02 00
```

The last byte (0x00) represents the value for close_notify (0).

### PR DESCRIPTION
**Pull request by pokgak**
### Contribution description

This PR adds handling of handshake_failure alert in the dtls-echo example application and bumps tinydtls pkg to include fixes from the tinydtls repo. With this PR, the client should be able to react to handshake_failure alert sent from the server when e.g. no matching cipher suites are supported.

### Testing procedure

I wrote a test script using pexpect that starts two native instances and sends a packet from the client to the server. [Link to the script.](https://gist.github.com/pokgak/618a0904f95eacd1647decef9c534634) If anybody is using the script, set `BUILD_IN_DOCKER=0` because there is problem passing environment variable set to docker.

##### Steps to use this script

1. Create tap interfaces with `RIOT/dist/tools/tapsetup/tapsetup -c`
2. Change directory to `dtls-echo` example: `cd RIOT/dtls-echo`
3. Run a native instance with `PORT=tap0` and get the IP with `ifconfig`:
```
$ PORT=tap0 make all term
> ifconfig
```
4. Change `<SERVER_IP>` in the script to the one found in step 3.
5. Run script from the dtls-echo example application: `./test-send.py`

### Issues/PRs references

Fixes #12351

### CODE REVIEW

File: examples/dtls-echo/dtls-server.c [hunk 1]
```diff
@@ -122,12 +122,10 @@ static void dtls_handle_read(dtls_context_t *ctx)
 
     if (memcpy(&session.addr, &remote_peer->remote->addr.ipv6, 16) == NULL) {
         puts("ERROR: memcpy failed!");
-        return;
```
Comment (benpicco) [inline examples/dtls-echo/dtls-server.c]: How can `memcpy` ever fail?
This check seems rather pointless.

File: examples/dtls-echo/dtls-client.c [hunk 2]
```diff
@@ -102,18 +104,18 @@ static void dtls_handle_read(dtls_context_t *ctx)
...
-        return;
+        return 0;
     }
 
     ssize_t res = sock_udp_recv(sock, packet_rcvd, DTLS_MAX_BUF,
                                 1 * US_PER_SEC + DEFAULT_US_DELAY,
                                 &remote);
 
-    if (res <= 0) {
+    if (res < 0) {
```
Comment (benpicco) [inline examples/dtls-echo/dtls-client.c]: Does it make sense to continue if `res == 0`, that is

> no received data is available, but everything is in order. <sup>[`sock_udp_recv()`](https://riot-os.org/api/group__net__sock__udp.html#gad1030df9b925878c2bf678487a9c88f7)</sup>

**Comment by benpicco** [comment]
Murdock found some issues.

File: examples/dtls-echo/dtls-client.c (hunk 2 above)
Comment (pokgak) [reply examples/dtls-echo/dtls-client.c]: In this case yes, because DTLS alerts have payload size 0 but are important for the client/server to know if they received any alerts.

File: examples/dtls-echo/dtls-server.c (hunk 1 above)
Comment (pokgak) [reply examples/dtls-echo/dtls-server.c]: I try not to touch unrelated code but I'll push a commit to clean up obvious stuff like this.

File: examples/dtls-echo/dtls-client.c (hunk 2 above)
Comment (benpicco) [reply examples/dtls-echo/dtls-client.c]: So that is UDP payload size? The signalling happens by sending an empty message to the DTLS port?

File: examples/dtls-echo/dtls-client.c [hunk 3]
```diff
@@ -126,20 +128,15 @@ static void dtls_handle_read(dtls_context_t *ctx)
         session.ifindex = remote.netif;
     }
 
-    if (memcpy(&session.addr, &remote.addr.ipv6, 16) == NULL) {
-        puts("ERROR: memcpy failed!");
-        return;
-    }
+    memcpy(&session.addr, &remote.addr.ipv6, 16) == NULL);
```
Comment (benpicco) [inline examples/dtls-echo/dtls-client.c]: typo :wink:

Comment (miri64) [reply examples/dtls-echo/dtls-client.c]: And magic number!

Comment (pokgak) [reply examples/dtls-echo/dtls-client.c]: yeah missed that. Fixed in latest commit.

File: examples/dtls-echo/dtls-client.c [hunk 4]
```diff
@@ -126,20 +128,15 @@ static void dtls_handle_read(dtls_context_t *ctx)
         session.ifindex = remote.netif;
     }
 
-    if (memcpy(&session.addr, &remote.addr.ipv6, 16) == NULL) {
-        puts("ERROR: memcpy failed!");
-        return;
-    }
+    memcpy(&session.addr, &remote.addr.ipv6, sizeof(ipv6_addr_t));
```
[the remark this answers is not in the document]
Comment (pokgak) [reply examples/dtls-echo/dtls-client.c]: fixed.

File: examples/dtls-echo/dtls-client.c (hunk 2 above)
Comment (miri64) [reply examples/dtls-echo/dtls-client.c]: > So just to be clear, that is UDP payload size? 

Yepp, like with normal udp sockets;

**Comment by pokgak** [comment]
Travis is all green except for commit message length and squash check. Should I squash?

**Comment by benpicco** [comment]
Yes please squash.

File: examples/dtls-echo/dtls-client.c (hunk 2 above)
Comment (pokgak) [reply examples/dtls-echo/dtls-client.c]: wait. now that you mention it, I might be wrong here. I'll check again.

Comment (pokgak) [reply examples/dtls-echo/dtls-client.c]: So, I somehow had the wrong idea in mind that a DTLS alert has payload size 0 eventhough I already saw many times in wireshark that it isn't.



> In this case yes, because DTLS alerts have payload size 0 but are important for the client/server to know if they received any alerts.

This statement is wrong.

> The signalling happens by sending an empty message to the DTLS port?

No, the signalling happens by sending a DTLS message with type alert in a DTLS record header, which means the received payload size cannot be 0.

Receiving a UDP payload size 0 is technically not an error *but* it doesn't make sense to continue if  `res == 0` because we are expecting a DTLS packet and not just UDP. So I'll revert this change and check if I made the same mistake at other places.

Sorry for the confusion :)

**Comment by pokgak** [comment]
Fixed https://github.com/RIOT-OS/RIOT/pull/12478#discussion_r336448219. Tests all green :)

**Comment by pokgak** [comment]
ping @benpicco

It would be nice if you could review and ACK this PR. It contains fixes that is needed so that the tests I did in https://github.com/RIOT-OS/RIOT/pull/11943#issuecomment-539625537 all passes :)

File: examples/dtls-echo/dtls-server.c [hunk 5]
```diff
@@ -120,14 +120,9 @@ static void dtls_handle_read(dtls_context_t *ctx)
...
-    if (memcpy(&session.addr, &remote_peer->remote->addr.ipv6, 16) == NULL) {
-        puts("ERROR: memcpy failed!");
-        return;
-    }
-
-    dtls_handle_message(ctx, &session, packet_rcvd, (int)DTLS_MAX_BUF);
-
-    return;
+    memcpy(&session.addr, &remote_peer->remote->addr.ipv6,
+           sizeof(session.addr));
```
Comment (benpicco) [inline examples/dtls-echo/dtls-server.c]: minor not: keep this on one line, the line below is just as long.

**Comment by pokgak** [comment]
Squashed and rebased to latest master.
