### PR TITLE
FIB: remove superfluous things

### LINKED ISSUE #4513: fib_sr: unittests for fib_sr fail sporadically
```
$ CFLAGS="-gdwarf-3 -g" make -C tests/unittests/ tests-fib_sr test
make: Entering directory `/home/martine/Repositories/RIOT-OS/RIOT/tests/unittests'
touch /home/martine/Repositories/RIOT-OS/RIOT/tests/unittests/main.c
Building application "unittests" for "native" with MCU "native".

"make" -C /home/martine/Repositories/RIOT-OS/RIOT/boards/native
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/boards/native/drivers
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/core
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/cpu/native
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/cpu/native/periph
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/drivers
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/sys
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/sys/embunit
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/sys/net/network_layer/fib
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/sys/universal_address
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/sys/xtimer
"make" -C /home/martine/Repositories/RIOT-OS/RIOT/tests/unittests/tests-fib_sr
   text	   data	    bss	    dec	    hex	filename
  65437	    416	  52196	 118049	  1cd21	/home/martine/Repositories/RIOT-OS/RIOT/tests/unittests/bin/native/unittests.elf
RIOT native interrupts/signals initialized.
LED_GREEN_OFF
LED_RED_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2016.03-devel-25-gab9f0f-beutlin-ipv6_hdr/fix/2015.12/ipv6_addr_dep)
......
fib_sr_tests.test_fib_sr_06_create_sr_with_hops (tests/unittests/tests-fib_sr/tests-fib_sr.c 264) exp 0 was -2

fib_sr_tests.test_fib_sr_06_create_sr_with_hops (tests/unittests/tests-fib_sr/tests-fib_sr.c 290) exp 0 was -2
......
run 12 failures 2
XXX: lpm_set(): LPM_POWERDOWN not implemented
```

Note, that sometimes they'll pass regardless.

### PR DESCRIPTION
**Pull request by OlegHahm**
Checking the lifetime of a newly created source route seems pointless to me.

This PR furthermore removes the `now` parameter for the check lifetime function since this function get call `xtimer_now()` itself.

~~Fixes #4513.~~

### CODE REVIEW

File: sys/net/network_layer/fib/fib.c [hunk 1]
```diff
@@ -955,11 +941,6 @@ int fib_sr_entry_add(fib_table_t *table, fib_sr_t *fib_sr,
         return -EFAULT;
     }
 
-    if (fib_sr_check_lifetime(fib_sr, &now) == -ENOENT) {
```
Comment (BytesGalore) [inline sys/net/network_layer/fib/fib.c]: sorry I commented in the commit, I move it here:
> @OlegHahm I don't get why this is obsolete?
Lets say a routing protocol has an aged source route with an expired lifetime.
It doesn't check it, but tries to add an hop into it.
Why should we let it proceed here?

Comment (OlegHahm) [inline sys/net/network_layer/fib/fib.c]: Copied the response: ;-)
> I have to confess that I haven't fully understand how these functions are supposed to work. But from the API documentation and the unittest I don't understand who's supposed to initialize the lifetime and it seems that the function might be called with an uninitialized lifetime.

Comment (BytesGalore) [inline sys/net/network_layer/fib/fib.c]: adding a hop doesn't need to be called only on creating a source route in the FIB.
you can update/change routes at any time :)

Comment (OlegHahm) [inline sys/net/network_layer/fib/fib.c]: Sorry, I guess it was too late yesterday and Iooked at the wrong function documentation (create instead of add). Are you good with the other changes?

**Comment by OlegHahm** [comment]
@BytesGalore,

**Comment by OlegHahm** [comment]
oops, wrong button

**Comment by BytesGalore** [comment]
The other changes looks good :)
I'm not opposing against them, they work so ACK for them.

My intention was to be precise with the moment when the routing protocol accesses a specific source route for operations. So I took the time when the function for an operation was called.

I loosely had kind of race conditions in mind where a routing protocol wants to update things moments before the source route lifetime expires, especially update the lifetime.
This way the update could fail when the time would be taken literally an Ångström after the function was called :).
But I guess the routing protocol should just not start to maintain a route in the FIB on the last minute.

**Comment by OlegHahm** [comment]
Let's postpone this for after the release.

File: sys/net/network_layer/fib/fib.c (hunk 1 above)
Comment (BytesGalore) [inline sys/net/network_layer/fib/fib.c]: I totally agree that the FIB documentation is weak and not helpful.
I will take care of it :)

**Comment by cgundogan** [comment]
>The other changes looks good :)
I'm not opposing against them, they work so ACK for them.

@BytesGalore was that an overall ACK for the whole PR, or just some parts of it? (:

**Comment by BytesGalore** [comment]
@cgundogan I'm still opposing on removing the lifetime check when adding entries to a new source route [1].
But no objections on taking the time in the check function, so this would be an ACK for them.

[1] https://github.com/RIOT-OS/RIOT/pull/4519/files#diff-332818d22f83905c0dd5c550ecf42259L958

**Comment by OlegHahm** [comment]
Removed the lifetime check from the PR and rebased.

**Comment by BytesGalore** [comment]
My ACK holds.
Don't know if this is important, but I would prefer to remove the `bug` label and the RP description part stating this fixes #4513

**Comment by OlegHahm** [comment]
Makes sense.
