### PR TITLE
cpu/cortexm: add __NOP(); after __WFI(); for stm32l152 to avoid hardfault

### LINKED ISSUE #8024: boards/cpu: nucleo-l152 (stm32l1) broken on master
While testing #7687 we discovered, that the `nucleo-l152` (`stm32l1`) is broken since quite a while now. Bisecting lead to the changes in #7385 (specifically to dd49f225321d3929f41c6108749c04eab0eb9571).

The change from `__irq_enable()` to `irq_restore(state)` breaks the L1 for some reason, can't really tell why... 
When doing `s/irq_restore(state);/__enable_irq();/`, everything is working (again). The difference seems to be `/__ASM volatile ("MSR primask, %0" : : "r" (priMask) : "memory");`
vs
`__ASM volatile ("cpsie i" : : : "memory");`

 Any ideas?

### PR DESCRIPTION
**Pull request by kYc0o**
### Contribution description
Currently, the stm32l1x hardfaults due to the irq state being stored in r0, which for some reason is lost after wake-up.
~~This PR fixes that by ensuring that the state is being stored in RAM.~~
The actual, less intrusive, fix is to add a `__NOP();` just after wake up, which also solves the problem.

~~It additionally allows to choose a different Low Speed clock source, since by default LSE (external) is hardcoded. Although this might be in another PR, users of an old revision of nucleo boards cannot test (so far one of the two stm32l1x based supported boards).~~

### Issues/PRs references
Refs #8024

### CODE REVIEW

File: boards/nucleo-l152/include/periph_conf.h [hunk 1]
```diff
@@ -34,9 +34,17 @@ extern "C" {
...
 #define CLOCK_CORECLOCK     (32000000U)             /* targeted core clock frequency */
-/* 0: no external low speed crystal available,
- * 1: external crystal available (always 32.768kHz) */
-#define CLOCK_LSE           (1)
+/*
+ * 0: no external low speed crystal available,
+ * 1: external crystal available (always 32.768kHz)
+ *
+ * LSE might not be available by default in early (C-01) Nucleo boards.
+ * If you're sure it is present, define CLOCL_LSE=1 in your project
```
Comment (aabadie) [inline boards/nucleo-l152/include/periph_conf.h]: `CLOCK_LSE`

Comment (kYc0o) [reply boards/nucleo-l152/include/periph_conf.h]: Oops, addressed.

**Comment by aabadie** [comment]
I just tested the shell with `examples/default` on hardware with and without LSE (I have rev C-03 with a LSE):
* With this PR: works when not using LSE
* Without this PR: crash when not using LSE
* With and without this PR: no shell available in both cases. Maybe the clock init is broken when using LSE ?

**Comment by kYc0o** [comment]
Which boards are you testing?

**Comment by aabadie** [comment]
> Which boards are you testing?

Sorry, it was not clear: I have nucleo-l152 rev c-03

**Comment by kYc0o** [comment]
Can you try to debug and see if it doesn't get stuck here:

```gdb
0x08001530 in stmclk_enable_lfclk () at /Users/facosta/git/RIOT-OS/RIOT/cpu/stm32_common/stmclk_common.c:79
79	        while (!(RCC->REG_LSE & BIT_LSERDY)) {}
```

File: cpu/cortexm_common/include/cpu.h [hunk 2]
```diff
@@ -104,7 +104,8 @@ static inline void cortexm_sleep(int deep)
     }
 
     /* ensure that all memory accesses have completed and trigger sleeping */
-    unsigned state = irq_disable();
+    /* avoid state to be stored in r0 (causes fault in some platforms) */
+    volatile unsigned state = irq_disable();
```
Comment (kaspar030) [inline cpu/cortexm_common/include/cpu.h]: maybe make this optional?

**Comment by kYc0o** [comment]
> Please split the PR's. They're dealing with unrelated issues...

Done.

File: cpu/cortexm_common/include/cpu.h (hunk 2 above)
Comment (kYc0o) [reply cpu/cortexm_common/include/cpu.h]: I see no problem on that, however I cannot see either why this is harmful, and the difference on size is only 4 bytes.

Comment (kaspar030) [reply cpu/cortexm_common/include/cpu.h]: well, it is also an extra memory access (vs. register) on every sleep. Don't know if that matters.

Any other opinions?

**Comment by gebart** [comment]
I would prefer if we could find out why r0 is lost on resume from sleep. Is there a hardware issue with these CPUs or is there a bug in the implementation of one of the ISRs in the periph drivers?

**Comment by kaspar030** [comment]
> I would prefer if we could find out why r0 is lost on resume from sleep.

Definitely... But seeing the time that has been put into debugging this already, IMO it is fine to go with a workaround for now.

Still, it should be documented as such (and not as necessary solution to a problem) and only be enabled for affected platforms.

**Comment by kYc0o** [comment]
> I would prefer if we could find out why r0 is lost on resume from sleep. Is there a hardware issue with these CPUs or is there a bug in the implementation of one of the ISRs in the periph drivers?

As fas as I can tell any interrupt would cause the hardfault (e.g. hello-world example "works", but if you type something in the terminal it hardfaults), thus I'd discard the possibility of a faulty periph implementation.

I'd also like to get #8402 in since it also helps in this situation, actually I thought it would solve the original problem but unfortunately not. The same with #8403. I can debug more to see the "real" source, if there's one, but for now I'd like to have the platform working again before doing "major" reworking on clock and pm.

**Comment by kYc0o** [comment]
>>I would prefer if we could find out why r0 is lost on resume from sleep.

> Definitely... But seeing the time that has been put into debugging this already, IMO it is fine to go with a workaround for now.

I suspect it's something to do with the power modes which maybe need to be configured before going to sleep. In this situation it "wildly" goes to sleep so I'd expect an undefined behaviour of registers and peripherals, here maybe we are just observing a part of it. Thus the importance of #8403 and #8402 .

**Comment by kYc0o** [comment]
I also insist on investigate https://github.com/RIOT-OS/RIOT/issues/8024#issuecomment-356995201

**Comment by kaspar030** [comment]
> I'd also like to get #8402 in since it also helps in this situation

It also solves the hard fault?

**Comment by kYc0o** [comment]
> It also solves the hard fault?

No, that's why I came to this fix.

**Comment by kaspar030** [comment]
> In this situation it "wildly" goes to sleep

What exactly does this mean? Which situation, why "wildly"?

**Comment by kYc0o** [comment]
> What exactly does this mean? Which situation, why "wildly"?

What I mean is that currently we put all cortexes to sleep regardless of the implementation of `pm_set_lowest`. Whenerver the idle thread comes to be scheduled `__WFI` is called, and in platforms where there's no PM implementation it just sleeps without configuring any power/clock mode. I didn't dig deep enough (yet) into the manual (I'm reading as much as I can), but it seems to me that stm32l1x behaves quite differently than other platforms and might require some configuration before just going to sleep. I made extensive tests on other non "L" platforms, namely "F" and the hardfault is not present, even though the compiler still saves `state` in r0.

I'll come with a more formal explanation why r0 is lost in this case (IMHO due to the lack of configuration before sleep) later in other issue or this thread if it's not being merged by then. For that I need to succeed to configure clock/pm as needed and experiment with it.

File: cpu/cortexm_common/include/cpu.h (hunk 2 above)
Comment (cladmi) [reply cpu/cortexm_common/include/cpu.h]: It just makes the variable stored in the stack, so its less than a function call.

**Comment by kYc0o** [comment]
Some [findings](https://community.st.com/thread/41010-wfi-instruction-causes-system-crash) (thanks @kaspar030) suggest that this MCU is particularly behaving "wrong" after idling or sleeping. A simple `__NOP();` works also for this platform, instead of making the variable volatile.

I'll change this PR to reflect the new solution which seems much more intrusive than the current one.

**Comment by kaspar030** [comment]
> I'll change this PR to reflect the new solution which seems much more intrusive than the current one.

;)

**Comment by gebart** [comment]
@kYc0o Where exactly do you add the nop?

**Comment by kYc0o** [comment]
> @kYc0o Where exactly do you add the nop?

Just after `__WFI();`

**Comment by cladmi** [comment]
I would still like to know if it can be broken with the `state` stored on stack with a specific number of `nop` instructions.
If there is a solution that reliably works, I would find it better than just a magic number of `nop` because we know that the compiler does not add one.

Could it be something like one of the instruction should be aligned on 4bytes address and is not for this platform because the compiler does crap ?

Is there the same alignment requirement for instructions than for memory access ?

**Comment by kYc0o** [comment]
I was doing some tests and didn't crash with several NOPs. Thus, I don't experience the same as the issue on the ST webpage.

**Comment by gebart** [comment]
Is the r0 corruption completely random or is it always the same?
Could it be that the memory for the stacked r0 is corrupted in some way during the ISR execution?

**Comment by kYc0o** [comment]
> Is the r0 corruption completely random or is it always the same?

It's always the same.

**Comment by kYc0o** [comment]
Some findings...

Current master (crashes):
```asm
00000000 <pm_set_lowest>:
   0:	4a07      	ldr	r2, [pc, #28]	; (20 <pm_set_lowest+0x20>)
   2:	b508      	push	{r3, lr}
   4:	6913      	ldr	r3, [r2, #16]
   6:	f023 0304 	bic.w	r3, r3, #4
   a:	6113      	str	r3, [r2, #16]
   c:	f7ff fffe 	bl	0 <irq_disable>
  10:	f3bf 8f4f 	dsb	sy
  14:	bf30      	wfi
  16:	e8bd 4008 	ldmia.w	sp!, {r3, lr}
  1a:	f7ff bffe 	b.w	0 <irq_restore>
  1e:	bf00      	nop
  20:	e000ed00 	.word	0xe000ed00
```

With `__NOP();` after `__WFI();` (works):

```asm
00000000 <pm_set_lowest>:
   0:	4a07      	ldr	r2, [pc, #28]	; (20 <pm_set_lowest+0x20>)
   2:	b508      	push	{r3, lr}
   4:	6913      	ldr	r3, [r2, #16]
   6:	f023 0304 	bic.w	r3, r3, #4
   a:	6113      	str	r3, [r2, #16]
   c:	f7ff fffe 	bl	0 <irq_disable>
  10:	f3bf 8f4f 	dsb	sy
  14:	bf30      	wfi
  16:	bf00      	nop
  18:	e8bd 4008 	ldmia.w	sp!, {r3, lr}
  1c:	f7ff bffe 	b.w	0 <irq_restore>
  20:	e000ed00 	.word	0xe000ed00
```

With `volatile unsigned state;` (works):

```asm
00000000 <pm_set_lowest>:
   0:	b507      	push	{r0, r1, r2, lr}
   2:	4a08      	ldr	r2, [pc, #32]	; (24 <pm_set_lowest+0x24>)
   4:	6913      	ldr	r3, [r2, #16]
   6:	f023 0304 	bic.w	r3, r3, #4
   a:	6113      	str	r3, [r2, #16]
   c:	f7ff fffe 	bl	0 <irq_disable>
  10:	9001      	str	r0, [sp, #4]
  12:	f3bf 8f4f 	dsb	sy
  16:	bf30      	wfi
  18:	9801      	ldr	r0, [sp, #4]
  1a:	b003      	add	sp, #12
  1c:	f85d eb04 	ldr.w	lr, [sp], #4
  20:	f7ff bffe 	b.w	0 <irq_restore>
  24:	e000ed00 	.word	0xe000ed00
```

**Comment by gebart** [comment]
Does it work if you remove the nope and add a __ISB() between the WFI and the IRQ restore?

**Comment by kYc0o** [comment]
> Does it work if you remove the nope and add a __ISB() between the WFI and the IRQ restore?

No, it crashes.

**Comment by kYc0o** [comment]
Another thing: it works on current master for stm32l151, the current problem only affects stm32l152 so far. Someone with a L053 can test current master against this PR? @aabadie @vincent-d ?

**Comment by cladmi** [comment]
And does it work for the `stm32l151` with an added `nop` ?

**Comment by gebart** [comment]
If you run with gdb and break in the ISR which wakes the CPU, does the stack contents differ between the two versions? (with/without added nop)
I don't know if you lose connection with gdb when doing low power modes on this CPU, but you can add a `__BKPT(0)` call or `volatile __asm__("bkpt #0")` in the ISR code to put a hard breakpoint there if the debugger doesn't work.
Especially interesting would be to see whether the return address is properly stacked or if there is some ram contents that gets corrupted somehow.

**Comment by gebart** [comment]
@kYc0o could you run with gdb and dump the register contents before the WFI instruction, and after the cpu resumes but before the ldmia instruction, in the broken master version. Especially the stack pointer (sp) is important.

**Comment by cladmi** [comment]
@gebart: whitout this PR the `state` variable is stored in register `r0` only and never on the stack.
In this state, it crashes, the fix I tried with the volatile assumed that, for any reason, the value was somehow lost during sleep or invalid when re-read after.
When watching values with gdb, it does not crash.
When trying to `show` if the value was lost, adding a value comparison to 0 and changing a led already stored the value in ram.

With the assumption that, for some reason, `r0` could be lost, I forced saving the value to the stack with `volatile` and it worked.

When saved on the stack I think there are no cases where it crashed.

**Comment by kYc0o** [comment]
> And does it work for the stm32l151 with an added nop ?

Yes it works.

**Comment by kaspar030** [comment]
> With the assumption that, for some reason, r0 could be lost, I forced saving the value to the stack with volatile and it worked.

The register cannot be lost, only its content. So does the node crash because r0 contains a wrong value, causing it to enable/disable IRQs where it shouldn't have? Seems to me the node crashes because of something else.

**Comment by kYc0o** [comment]
> f you run with gdb and break in the ISR which wakes the CPU, does the stack contents differ between the two versions? (with/without added nop)
I don't know if you lose connection with gdb when doing low power modes on this CPU, but you can add a __BKPT(0) call or volatile __asm__("bkpt #0") in the ISR code to put a hard breakpoint there if the debugger doesn't work.
Especially interesting would be to see whether the return address is properly stacked or if there is some ram contents that gets corrupted somehow.

Without `__NOP();`

```gdb
cortexm_sleep (deep=0) at /Users/facosta/git/RIOT-OS/RIOT/cpu/cortexm_common/include/cpu.h:109
109	    __DSB();
2: state = 0
3: &state = <error: Address requested for identifier "state" which is in register $r0>
(gdb) info registers
r0             0x0	0
r1             0x1	1
r2             0xe000ed00	-536810240
r3             0x10	16
r4             0x4	4
r5             0x5	5
r6             0x6	6
r7             0x7	7
r8             0x8	8
r9             0x9	9
r10            0xa	10
r11            0xb	11
r12            0x0	0
sp             0x20000458	0x20000458 <idle_stack+184>
lr             0x80008d1	134219985
pc             0x80008d0	0x80008d0 <pm_set_lowest+16>
xPSR           0x1000000	16777216
```

Nothing really changes with `__NOP();`

```gdb
cortexm_sleep (deep=0) at /Users/facosta/git/RIOT-OS/RIOT/cpu/cortexm_common/include/cpu.h:111
111	    irq_restore(state);
(gdb) display state
1: state = 0
(gdb) display &state
2: &state = <error: Address requested for identifier "state" which is in register $r0>
(gdb) info registers
cortexm_sleep (deep=0) at /Users/facosta/git/RIOT-OS/RIOT/cpu/cortexm_common/include/cpu.h:112
112	    irq_restore(state);
(gdb) display status
No symbol "status" in current context.
(gdb) display state
1: state = 0
(gdb) display &state
2: &state = <error: Address requested for identifier "state" which is in register $r0>
(gdb) info registers 
r0             0x0	0
r1             0x1	1
r2             0xe000ed00	-536810240
r3             0x3	3
r4             0x4	4
r5             0x5	5
r6             0x6	6
r7             0x7	7
r8             0x8	8
r9             0x9	9
r10            0xa	10
r11            0xb	11
r12            0x0	0
sp             0x20000460	0x20000460 <idle_stack+192>
lr             0x80006cf	134219471
pc             0x80008dc	0x80008dc <pm_set_lowest+28>
xPSR           0x1000000	16777216
```

**Comment by kYc0o** [comment]
`__NOP();` before `__WFI();` crashes. The disassembly:

```asm
080008c0 <pm_set_lowest>:
 80008c0:	4a07      	ldr	r2, [pc, #28]	; (80008e0 <pm_set_lowest+0x20>)
 80008c2:	b508      	push	{r3, lr}
 80008c4:	6913      	ldr	r3, [r2, #16]
 80008c6:	f023 0304 	bic.w	r3, r3, #4
 80008ca:	6113      	str	r3, [r2, #16]
 80008cc:	bf00      	nop
 80008ce:	f7ff febb 	bl	8000648 <irq_disable>
 80008d2:	f3bf 8f4f 	dsb	sy
 80008d6:	bf30      	wfi
 80008d8:	e8bd 4008 	ldmia.w	sp!, {r3, lr}
 80008dc:	f7ff bebc 	b.w	8000658 <irq_restore>
 80008e0:	e000ed00 	.word	0xe000ed00
```

**Comment by kYc0o** [comment]
`__NOP();` before and after doesn't crash:

```asm
080008c0 <pm_set_lowest>:
 80008c0:	4a08      	ldr	r2, [pc, #32]	; (80008e4 <pm_set_lowest+0x24>)
 80008c2:	b508      	push	{r3, lr}
 80008c4:	6913      	ldr	r3, [r2, #16]
 80008c6:	f023 0304 	bic.w	r3, r3, #4
 80008ca:	6113      	str	r3, [r2, #16]
 80008cc:	bf00      	nop
 80008ce:	f7ff febb 	bl	8000648 <irq_disable>
 80008d2:	f3bf 8f4f 	dsb	sy
 80008d6:	bf30      	wfi
 80008d8:	bf00      	nop
 80008da:	e8bd 4008 	ldmia.w	sp!, {r3, lr}
 80008de:	f7ff bebb 	b.w	8000658 <irq_restore>
 80008e2:	bf00      	nop
 80008e4:	e000ed00 	.word	0xe000ed00
```

**Comment by kYc0o** [comment]
I reflected the discussion in my last commit, I changed the volatile variable for a `__NOP();` instruction. I will change the commit message once squashed.

**Comment by gebart** [comment]
Your posted disassembly puts the nop before the call to irq_disable and DSB, what happens when the nop is right before the WFI?

Anyway, I am happy with the WFI followed by a single nop workaround. It is less intrusive than the initial solution with volatile state.

**Comment by kaspar030** [comment]
please fix the PR subject...

**Comment by kYc0o** [comment]
> Your posted disassembly puts the nop before the call to irq_disable and DSB, what happens when the nop is right before the WFI?

The compiler optimises that actually, I can test just for curiosity and post the result.

**Comment by kYc0o** [comment]
PR and commit description changed.

@aabadie can you make a final test on your hardware to see if doesn't break anything?

**Comment by aabadie** [comment]
> @aabadie can you make a final test on your hardware to see if doesn't break anything?

I tested again this PR on nucleo-l152 rev C-03. It works only if I set CLOCK_LSE to 0 in periph_conf. On master it crashes. So I would say that this PR fixes the problem when using LSI.

In any case, it hangs when using CLOCK_LSE to 1.

**Comment by kYc0o** [comment]
Why Murdock doesn't work here?

**Comment by aabadie** [comment]
Just triggered Murdock again and it seems to work now

**Comment by aabadie** [comment]
Can you remove the `fixes` word in the initial comment of this PR, because for me this PR doesn't fully fix the broken nucleo-l152.

**Comment by aabadie** [comment]
@kYc0o, can you also add a reference to the PR that deactivate LSE in the nucleo-l152 board peripheral configuration ? I can't find it. Because to have the nucleo-l152 working again (with both revisions, AFAIU), I think it will be required as soon as this PR gets merged.

**Comment by kYc0o** [comment]
> @kYc0o, can you also add a reference to the PR that deactivate LSE in the nucleo-l152 board peripheral configuration ? I can't find it. Because to have the nucleo-l152 working again (with both revisions, AFAIU), I think it will be required as soon as this PR gets merged.

There was no other PR, unless you mean my first attempt which I don't consider as good.

I'll open a second PR after this gets merged. However that wouldn't really  be the solution for your problem since it should work with the external crystal anyways.

PS. I changed the description.

**Comment by aabadie** [comment]
> However that wouldn't really be the solution for your problem since it should work with the external crystal anyways.

Indeed, but at least this would allow people to use this board, which is not possible at the moment.

**Comment by aabadie** [comment]
strikethrough text is not enough I think, please change `fixes` to `refs`. This is just to avoid the initial issue to be closed when this PR will be merged.

**Comment by kYc0o** [comment]
Ok @aabadie it seems you changed to refs, so you ACK?

**Comment by kYc0o** [comment]
Ok so there's only @kaspar030 ACK left.

**Comment by aabadie** [comment]
@kaspar030 do you ACK this one ?

File: cpu/cortexm_common/include/cpu.h [hunk 3]
```diff
@@ -107,6 +107,14 @@ static inline void cortexm_sleep(int deep)
     unsigned state = irq_disable();
     __DSB();
     __WFI();
+    /*
```
Comment (kaspar030) [inline cpu/cortexm_common/include/cpu.h]: Let's move the comment into the ifdef, and make it a little shorter. E.g.:
```
/* STM32L152RE crashes without this __NOP(). See #8518. */
```

Comment (kYc0o) [reply cpu/cortexm_common/include/cpu.h]: Addressed.

**Comment by aabadie** [comment]
@kYc0o, please squash

**Comment by kYc0o** [comment]
Squashed.
