### PR TITLE
6LBR: fixes

### LINKED ISSUE #3959: 6LBR: Border router advertises SLIP's prefix over LoWPAN
When I start a 6LR before I finished configuring the LoWPAN interface of the 6LBR it receives the prefix for the SLIP interface. This should not happen. @OlegHahm did you see this behavior, too?

### PR DESCRIPTION
**Pull request by authmillenon**
The continue introduced in #3965 wasn't iterating + some general fixes + setting the maximum prefix count for ABRs to the number of interfaces (so border routers can have more than one prefix). Fixes #3959 even more.

### CODE REVIEW

File: sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c [hunk 1]
```diff
@@ -379,14 +379,14 @@ static inline bool _check_prefixes(gnrc_ipv6_netif_addr_t *a, gnrc_ipv6_netif_ad
...
 
     for (int i = 0; i < GNRC_IPV6_NETIF_ADDR_NUMOF; i++) {
         /* skip if prefix has been processed already */
-        processed_before = false;
+        bool processed_before = false;
+
         for (int j = 0; j < i; j++) {
             if ((processed_before =
-                _check_prefixes(&ipv6_iface->addrs[i], &ipv6_iface->addrs[j]))) {
+                     _check_prefixes(&ipv6_iface->addrs[i], &ipv6_iface->addrs[j]))) {
```
Comment (cgundogan) [inline sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c]: why the extra indent here?

**Comment by cgundogan** [comment]
fixes make sense. ACK

File: sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c (hunk 1 above)
Comment (authmillenon) [inline sys/net/gnrc/network_layer/ndp/internal/gnrc_ndp_internal.c]: astyle proposed it, and I thought it makes more sense than the current state.
