### PR TITLE
cpu/nrf5x_common: map hwrng to SoC library if SoftDevice is present

### LINKED ISSUE #11091: gnrc_minimal on nRF52DK do not work anymore
#### Description
The gnrc_minimal example do not work on the nrf52832 anymore

I worked on another branch on the gnrc networking on BLE. So, I checked the old branch and it works fine there. (Last commit on the old branch: 60008cbb2e6afbf3a39116192fcac02b5454e87b)

I also tried to use the nordic ble package without the gnrc packages. Simple ble advertising test. 
Just add the nordic package to your Makefile
```
USEPKG += nordic_softdevice_ble
```
Add this to your main
```bash
    puts("Hello World!");

    printf("You are running RIOT on a(n) %s board.\n", RIOT_BOARD);
    printf("This board features a(n) %s MCU.\n", RIOT_MCU);

    ble_stack_init();
    ble_advertising_init("RIOT BLE");
    ble_advertising_start();
```
and import ble-core.h

This also does not give you any feedback. No ble advertising, no serial console message. So, I guess the problem is somewhere placed in the ble library wrapper or maybe even in the library itself. 

#### Steps to reproduce the issue
1. Checkout the master branch (commit: e3e2b6df153925b16e083f0cea631f10922e2d28)
2. Connect the nRF52 DK board to an USB-to-UART adapter and to your J-Link
3. Open the serial monitor. With term, platformio device monitor, screen or something else.
4. Flash the gnrc_minimal example with a J-Link. 

#### Expected results
Do the same as before, but check out the commit: 60008cbb2e6afbf3a39116192fcac02b5454e87b

Result in the serial console:
```
main(): This is RIOT! (Version: 2018.10-devel-413-g60008-[SOME_HOSTNAME]-HEAD)
RIOT network stack example application
My address is [SOME_ADDRESS]
```

#### Actual results
Empty serial console, no message appears.

#### Versions
Installed compiler toolchains 
```bash
-----------------------------
             native gcc: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                avr-gcc: missing
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
                  clang: missing

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: missing (missing)

Installed development tools
---------------------------
                  cmake: cmake version 3.10.2
               cppcheck: missing
                doxygen: missing
                 flake8: missing
                    git: git version 2.17.1
             coccinelle: missing

```

### PR DESCRIPTION
**Pull request by PeterKietzmann**
### Contribution description

According to [this comment](https://github.com/RIOT-OS/RIOT/issues/11091#issuecomment-470456909) which bases on Nordic documentation, the hardware RNG can't be accessed when the SoftDevice is used. The fix maps our `hwrng_read()` function the the respective library function call (see [here](https://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.s132.api.v3.0.0%2Fgroup___n_r_f___s_o_c___f_u_n_c_t_i_o_n_s.html) for reference)

#### (i)
Build/flash/term *examples/gnrc_networking* for an nrf5X based board.

#### (ii)
Build/flash/term *tests/periph_hwrng* for an nrf5x based board and include the SoftDevice package. E.g.:
`USEPKG=nordic_softdevice_ble BOARD=nrf52dk make -C tests/periph_hwrng flash term`

W/o this fix, there is no output as the initialization hangs before main() is called. W/ this fix, everything should work as expected.

### Issues/PRs references

Fixes #11091

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
@Citrullin please test

**Comment by SemjonKerner** [comment]
Does not compile for `examples/gnrc_networking` and `tests/periph_hwrng` on nrf52840dk.

Also the example does not open a shell on nrf52dk (the same for master, so unrelated but not testable), when using the softdevice. Does open a shell with nrfmin though.

`tests/periph_hwrng` goes through on nrf52dk.

**Comment by PeterKietzmann** [comment]
> Does not compile for examples/gnrc_networking and tests/periph_hwrng on nrf52840dk.

I just found that it doesn't even compile on master when `USEPKG=nordic_softdevice_ble`. I'm not very familiar with the nordic hardware nor with the softdevice. Is this feature expected on the nrf52840?

> Also the example does not open a shell on nrf52dk

I can't reproduce that. Everything works smooth on my machine. Did you check out my branch or merge/pick the commit somehow? Otherwise this seems like a toolchain issue. I'm on:
```
Operating System Environment
-----------------------------
       Operating System: "Ubuntu" "18.04.2 LTS (Bionic Beaver)"
                 Kernel: Linux 4.15.0-50-generic x86_64 x86_64

Installed compiler toolchains
-----------------------------
             native gcc: gcc (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                avr-gcc: missing
       mips-mti-elf-gcc: missing
             msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
   riscv-none-embed-gcc: missing
   xtensa-esp32-elf-gcc: missing
   xtensa-lx106-elf-gcc: missing
                  clang: missing

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
xtensa-esp32-elf-newlib: missing
xtensa-lx106-elf-newlib: missing
               avr-libc: missing (missing)

Installed development tools
---------------------------
                  cmake: cmake version 3.10.2
               cppcheck: missing
                doxygen: 1.8.13
                 flake8: 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.6.7 on Linux
                    git: git version 2.17.1
                   make: GNU Make 4.1
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 2.7.15rc1
                python2: Python 2.7.15rc1
                python3: Python 3.6.7
             coccinelle: missing
```

**Comment by haukepetersen** [comment]
Just checked, the fix seems to do the job for `nrf52832`-based boards. I do however have some improvements regarding the code in mind -> see https://github.com/PeterKietzmann/RIOT/pull/11

AFAIK the softdevice was never verified to work with the `nrf52840`, so no surprise this is not working. I opened a PR introducing an explicit feature to resolve this -> https://github.com/RIOT-OS/RIOT/pull/11769

**Comment by PeterKietzmann** [comment]
Thanks @haukepetersen! I've reviewed, tested and merged your changes into my branch and rebased + squashed this PR afterwards to run CI

File: cpu/nrf5x_common/periph/hwrng.c [hunk 1]
```diff
@@ -62,3 +70,23 @@ void hwrng_read(void *buf, unsigned int num)
...
+    assert(num <= 0xff);
+
+    /* this is not the most efficient, but this way we can assure that there are
+     * enough bytes of random data available */
+    do {
+        sd_rand_application_bytes_available_get(&avail);
+    } while (avail < (uint8_t)num);
+
+    ret = sd_rand_application_vector_get((uint8_t *)buf, (uint8_t)num);
+    assert(ret == NRF_SUCCESS);
```
Comment (miri64) [inline cpu/nrf5x_common/periph/hwrng.c]: Should also be `(void)ret;`'ed, in case assert resolves to NOP.

Comment (haukepetersen) [reply cpu/nrf5x_common/periph/hwrng.c]: yes, I have missed that.

@PeterKietzmann I think its the easiest if you fix that in your branch directly?!

**Comment by PeterKietzmann** [comment]
Ok. Ready to squash?

**Comment by haukepetersen** [comment]
yes, please go ahead

**Comment by PeterKietzmann** [comment]
Squashed

**Comment by haukepetersen** [comment]
Merged :-)
