### PR TITLE
gnrc_sock_[udp|ip]: read return value for _recv after release

### LINKED ISSUE #10365: Use after free in gnrc_sock_udp sock_udp_recv
#### 
Sometimes the sock_udp_recv function in the implementation provided by gnrc_sock_udp returns unexpected values (-12736 or -1 for example). This is probably due to a use after free in this functions return statement. I will provide a pull request for more details.

Affected Code:
-----------------------------
    gnrc_pktbuf_release(pkt);
    return (int)pkt->size;
-----------------------------

#### Steps to reproduce the issue
Read from a udp socket using gnrc_sock_udp implementation with sock_udp_recv and check if the return values is < 0 and none of the expected errors. Only happens when a certain amount of packets is send to the reading host. I wasn't able to reproduce with running valgrind yet. 

I use native arch with a tap network setup as described in https://github.com/RIOT-OS/RIOT/wiki/Virtual-riot-network

#### Expected results
sock_udp_recv should either return a value >= 0 or any of -EADDRNOTAVAIL, -ENOMEM, -EAGAIN, ,EINVAL, -ENOBUFS, -ENOMEM, -EPROTO or -ETIMEDOUT

#### Actual results
Somethimes the function returns random values < 0 or values > 0 which does not match the actual packet size.

#### Versions
Operating System Environment
-----------------------------
       Operating System: "Arch Linux" 
                 Kernel: Linux 4.18.16-arch1-1-ARCH x86_64 unknown

Installed compiler toolchains
-----------------------------
             native gcc: gcc (GCC) 8.2.1 20180831
      arm-none-eabi-gcc: arm-none-eabi-gcc (Arch Repository) 8.2.0
                avr-gcc: avr-gcc (GCC) 8.2.0
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
                  clang: clang version 7.0.0 (tags/RELEASE_700/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                  cmake: cmake version 3.12.4
               cppcheck: missing
                doxygen: 1.8.14
                 flake8: missing
                    git: git version 2.19.1
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 3.7.1
                python2: Python 2.7.15
                python3: Python 3.7.1
             coccinelle: missing

### PR DESCRIPTION
**Pull request by crest42**
### Contribution description

Sometimes the sock_udp_recv function in the implementation provided by gnrc_sock_udp returns unexpected values (-12736 or -1 for example). This is probably due to a use after free in this functions return statement. This PR fixes the bug for me.

### Testing procedure
"ALL TESTS SUCCESSFUL" for tests/gnrc_sock_ip and tests/gnrc_sock_udp as well as my application which triggered the error before.

### Issues/PRs references
Fixes #10365

### CODE REVIEW

File: sys/net/gnrc/sock/ip/gnrc_sock_ip.c [hunk 1]
```diff
@@ -120,8 +120,9 @@ ssize_t sock_ip_recv(sock_ip_t *sock, void *data, size_t max_len,
         return -EPROTO;
     }
     memcpy(data, pkt->data, pkt->size);
+    int pkt_size = (int)pkt->size;
```
Comment (miri64) [inline sys/net/gnrc/sock/ip/gnrc_sock_ip.c]: You could reuse `res` here.

File: sys/net/gnrc/sock/udp/gnrc_sock_udp.c [hunk 2]
```diff
@@ -215,8 +215,9 @@ ssize_t sock_udp_recv(sock_udp_t *sock, void *data, size_t max_len,
         return -EPROTO;
     }
     memcpy(data, pkt->data, pkt->size);
+    int pkt_size = (int)pkt->size;
```
Comment (miri64) [inline sys/net/gnrc/sock/udp/gnrc_sock_udp.c]: Dito.

File: sys/net/gnrc/sock/ip/gnrc_sock_ip.c (hunk 1 above)
Comment (crest42) [reply sys/net/gnrc/sock/ip/gnrc_sock_ip.c]: It would be also possible to let gnrc_sock_recv return the size of the paket (atm it return 0 at the end) and then just return res in the specific _recv function. What would you prefere?

File: sys/net/gnrc/sock/udp/gnrc_sock_udp.c (hunk 2 above)
Comment (crest42) [reply sys/net/gnrc/sock/udp/gnrc_sock_udp.c]: > Please format the commit message properly. Please have a look at our Contribution Guidelines for that. Here's the TL;DR:

Ups i totally missed that part. sorry i will fix it in the next update :)

**Comment by crest42** [comment]
>Please format the commit message properly.
Ups i totally missed that part. sorry i will fix it in the next update :)

File: sys/net/gnrc/sock/ip/gnrc_sock_ip.c (hunk 1 above)
Comment (miri64) [reply sys/net/gnrc/sock/ip/gnrc_sock_ip.c]: I think it is less intrusive (and easier to follow later on), if we do just for now 

```suggestion
    res = (int)pkt->size;
```

and do your proposed optimization in a follow-up. This would also allow us to bring this into the newest release, as this is an easy to follow fix. I'm not sure if the other solution would be.

**Comment by crest42** [comment]
I hope everything is fine now. Thanks a lot for your patience and feedback :)

**Comment by miri64** [comment]
I have to thank you! For your contribution and for one of the easiest reviews ever from a newcomer ;-).

**Comment by miri64** [comment]
Backport provided in #10374
