### PR TITLE
net/gnrc/udp: Adding Null pointer check in gnrc_netif_hdr_build 

### LINKED ISSUE #11631: examples / tests: return value of `gnrc_netif_hdr_build()` not checked in udp.c
#### Description
This is an error that was copied over multiple applications, this is why I can't fix it right now, but I wanted to report it.

The return value of `gnrc_netif_hdr_build()` is not checked in most versions of the `udp send` for GNRC I came across. This results in the node to crash if the packet happens to have a very large payload https://github.com/RIOT-OS/RIOT/blob/6b582fd5d0ad95b1b5b856b89c3d25e454cff1b3/examples/gnrc_networking/udp.c#L90-L93

#### Steps to reproduce the issue
~~Merge #11623 and~~ build any application containing `udp.c` ~~with `USEMODULE=gnrc_ipv6_ext_frag`~~ [edit: you don't need or a large MTU fragmentation to *allocate* a packet] (preferably one that can send large payloads like `tests/gnrc_udp`). Then send a packet that is just big enough to allow for allocation of the payload, the IPv6 header and UDP header.

```
udp send fe80::2806:1aff:fedd:f6d8 20908 6000
```

~~Probably also works with `slipdev` as device, but I did not test that.~~

#### Expected results
The packet should not be send, an error message like e.g.

```
Error: unable to allocate NETIF header
```

should be printed.

#### Actual results
The node crashes due to a NULL pointer dereference.

#### Versions
Current master (https://github.com/RIOT-OS/RIOT/commit/6b582fd5d0ad95b1b5b856b89c3d25e454cff1b3) ~~with #11623~~.

### PR DESCRIPTION
**Pull request by Harisanthosh**
### Contribution description

This PR contains the fix for issue #11631 :

1. Check for Null pointer has been added in **tests/gnrc_udp/udp.c** file where the node was crashing when tried sending a payload over 5992 bytes MTU. By checking the return value of the function **gnrc_netif_hdr_build** before sending the payload to the destination address we avoid the Null pointer Dereferencing.

### Testing procedure

The fix has been tested in "native"

    

1. Have a udps server running and make a note of it's IPv6 address
2. From the tests/gnrc_udp/ folder, build and run the program and try sending a large payload in the following format:
> udp send [dest_addr] [port] [payload in bytes]

`udp send fe80::2806:1aff:fedd:f6d8 8888 5993`

The node will not send the message but will return an error message
    `Error: unable to allocate NETIF header`

Edit by @miri64: Use `pktbuf` to check if packet buffer is cleared in error case.

### Issues/PRs references

Fixes #11631

### CODE REVIEW

**Comment by emmanuelsearch** [comment]
@Harisanthosh can you squash your commits? 
And what about other similar occurrences such as [this one](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_networking/udp.c#L92) or [that one](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_networking_mac/udp.c#L91). I did not check if there are additional similar occurrences on top of those, but there might be ;)

**Comment by emmanuelsearch** [comment]
And what about other similar occurrences such as [this one](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_networking/udp.c#L92) or [that one](https://github.com/RIOT-OS/RIOT/blob/master/examples/gnrc_networking_mac/udp.c#L91). I did not check if there are additional similar occurrences on top of those, but there might be ;)

File: tests/gnrc_udp/udp.c [hunk 1]
```diff
@@ -138,6 +138,11 @@ static void send(char *addr_str, char *port_str, char *data_len_str, unsigned in
         if (iface > 0) {
             gnrc_pktsnip_t *netif = gnrc_netif_hdr_build(NULL, 0, NULL, 0);
 
+            if(netif == NULL) {
+                puts("Error: unable to allocate NETIF header");
+                gnrc_pktbuf_release(payload);
```
Comment (miri64) [inline tests/gnrc_udp/udp.c]: Since `payload` is already part of the list `ip` you should release `ip` here (which in turn also releases `udp` and `payload`).

**Comment by miri64** [comment]
I adapted the OP to add tests for the case I pointed out in my change request and to enable automatic closing of #11631

**Comment by miri64** [comment]
ACK. Tested as described in the testing procedures

```
$ make -C tests/gnrc_udp/ term
make: Entering directory '/home/mlenders/Repositories/RIOT-OS/RIOT/tests/gnrc_udp'
/home/mlenders/Repositories/RIOT-OS/RIOT/tests/gnrc_udp/bin/native/tests_gnrc_udp.elf tap0 
RIOT native interrupts/signals initialized.
LED_RED_OFF
LED_GREEN_ON
RIOT native board initialized.
RIOT native hardware initialization complete.

main(): This is RIOT! (Version: 2019.10-devel-442-gf5833-HEAD)
> udp send fe80::2806:1aff:fedd:f6d8 8888 5993
udp send fe80::2806:1aff:fedd:f6d8 8888 5993
Error: unable to allocate NETIF header
> pktbuf
pktbuf
packet buffer: first byte: 0x5667dd80, last byte: 0x5667f580 (size: 6144)
  position of last byte used: 6144
~ unused: 0x5667dd80 (next: (nil), size: 6144) ~
```

(unused segment of packet buffer is as large as the packet buffer, so the buffer is empty)
