### PR TITLE
debugging: fix openocd closing when pressing Ctrl+C in GDB, fix #3427

### LINKED ISSUE #3427: openocd 0.9: OpenOCD closes when pressing CTRL+C in GDB
OpenOCD closes when pressing CTRL+C in GDB, when openocd is started by `make debug` (`openocd.sh`) and is running in the background of the same terminal as gdb. GDB still receives the ctrl+c as well.

This is not observed if I downgrade openocd to v0.8.0.

Package versions:
 - cross-arm-none-eabi/gdb-7.9.1
 - dev-embedded/openocd-0.9.0
 - kde-apps/konsole-4.14.3

### PR DESCRIPTION
**Pull request by daniel-k**
Hopefully fixes #3427.

Please test this on as many system as possible, especially on Mac OS. The problem seemed to be, that openocd stays in the same process group when forking it (`openocd .... &`). Now in GDB when you press Ctrl+c the `SIGINT` signal will be sent to the parent shell, that redirects it to GDB as well as to openocd.

Solution: detach openocd from process group.

The script also used the wrong environment variable to grab the openocd PID accroding to [this](http://www.tldp.org/LDP/abs/html/exit-status.html#EXSREF).

### CODE REVIEW

File: dist/tools/openocd/openocd.sh [hunk 1]
```diff
@@ -202,7 +202,7 @@ do_debug() {
             -c 'halt' \
             -l /dev/null" &
     # save PID for terminating the server afterwards
-    OCD_PID=$?
+    OCD_PID=$(($!+2))
```
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: the +2 feels kind of arbitrary. Is it guaranteed to be the same every time on every system?

File: dist/tools/openocd/openocd.sh [hunk 2]
```diff
@@ -202,7 +202,7 @@ do_debug() {
             -c 'halt' \
             -l /dev/null" &
     # save PID for terminating the server afterwards
-    OCD_PID=$?
```
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: Whoops! Good catch!

**Comment by gebart** [comment]
related info: http://blog.n01se.net/blog-n01se-net-p-145.html

File: dist/tools/openocd/openocd.sh (hunk 1 above)
Comment (daniel-k) [inline dist/tools/openocd/openocd.sh]: This bugs me too, but I didn't find a better solution using standard POSIX tools. That's why this needs to be tested on many systems. Any suggestions?

Am 12. August 2015 19:17:40 MESZ, schrieb Joakim Gebart <notifications@github.com>:

Comment (gebart) [inline dist/tools/openocd/openocd.sh]: an idea:
use the `$$` variable in combination with some variation of `sh -c "echo \$\$; xxx" &` and some output redirection

Test with: `setsid sh -c "echo child: \$\$; sleep 2" &; echo "setsid: $\!"; echo "shell: $$"`

**Comment by daniel-k** [comment]
@gebart 
Nice idea, even though I've found a slightly different approach now. I didn't dare to mess with output redirection but save the openocd pid in a temporary file.

File: dist/tools/openocd/openocd.sh [hunk 3]
```diff
@@ -191,8 +191,10 @@ do_debug() {
     test_elffile
     test_ports
     test_tui
+    # temporary file that saves OpenOCD pid
+    tmp=openocd_`date +%s`.pid
```
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: use `mktemp` instead.

File: dist/tools/openocd/openocd.sh [hunk 4]
```diff
@@ -200,13 +202,14 @@ do_debug() {
...
-    # save PID for terminating the server afterwards
-    OCD_PID=$?
+            -l /dev/null &> /dev/null & \
+            echo \$! > $tmp" &
     # connect to the GDB server
     ${DBG} ${TUI} -ex "tar ext :${GDB_PORT}" ${ELFFILE}
     # clean up
+    OCD_PID="$(cat $tmp)"
     kill ${OCD_PID}
+    rm $tmp
```
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: use `trap 'rm -f $tmp' EXIT` near line 194 to always delete the PID file regardless of what happens later.

File: dist/tools/openocd/openocd.sh [hunk 5]
```diff
@@ -200,13 +202,14 @@ do_debug() {
             -c 'init' \
             -c 'targets' \
             -c 'halt' \
-            -l /dev/null" &
-    # save PID for terminating the server afterwards
-    OCD_PID=$?
+            -l /dev/null &> /dev/null & \
```
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: change `&` to `&&`

File: dist/tools/openocd/openocd.sh (hunk 3 above)
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: here's an example of using mktemp from another script I wrote:

```sh
TMPFILE=
trap '[ -n "${TMPFILE}"] && rm -f "${TMPFILE}"' EXIT
TMPFILE=$(mktemp "${TARGET_DIR}/my_temp_file.XXXXXXXXXX")

wget "${SOURCE_URI}" -O "${TMPFILE}" && ( chmod a+r "${TMPFILE}"; mv -b -f "${TMPFILE}" "${TARGET_DIR}/the_real_target.zip" )
trap - EXIT
```

File: dist/tools/openocd/openocd.sh [hunk 6]
```diff
@@ -191,8 +191,10 @@ do_debug() {
     test_elffile
     test_ports
     test_tui
+    # temporary file that saves OpenOCD pid
+    tmp=openocd_`date +%s`.pid
     # start OpenOCD as GDB server
-    sh -c "${OPENOCD} -f '${OPENOCD_CONFIG}' \
+    setsid sh -c "${OPENOCD} -f '${OPENOCD_CONFIG}' \
```
Comment (thomaseichinger) [inline dist/tools/openocd/openocd.sh]: `setsid` does not exist on OS X and FreeBSD.

**Comment by thomaseichinger** [comment]
Changes look reasonable, but please make them conditional to Linux. Didn't hear about the `Ctrl+C` problem on these platforms anyway.

**Comment by daniel-k** [comment]
@thomaseichinger Could you please test again on Mac and FreeBSD? Hopefully I used `mktemp` the right way and `trap` also behaves the same as on Linux :)

**Comment by thomaseichinger** [comment]
Seems I was testing against the wrong OpenOCD version. This problem does exist on OS X too. To get this in quickly, could you change to test for presence of `setsid`? Let's try to find a general OS X workaround later.

There does exist a `setsid` [workaround tool](https://github.com/jerrykuch/ersatz-setsid) for OS X which does what it should. (I created a [Formula](https://github.com/thomaseichinger/homebrew-embedded/blob/master/setsid.rb) to install it with homebrew)

**Comment by daniel-k** [comment]
@thomaseichinger done

**Comment by thomaseichinger** [comment]
Works for me. Could an other Linux user verify? But I think you can proceed with squashing.

File: dist/tools/openocd/openocd.sh [hunk 7]
```diff
@@ -191,8 +191,16 @@ do_debug() {
     test_elffile
     test_ports
     test_tui
+    # setsid is needed so that Ctrl+C in GDB doesn't kill OpenOCD
+    [ -n "$(which setsid)" ] && SETSID=setsid
```
Comment (gebart) [inline dist/tools/openocd/openocd.sh]: Actually, it makes more sense to check whether the SETSID variable is null. (sorry for commenting in the commit before)
```sh
[ -n "${SETSID}" ] && SETSID=$(which setsid)
```

Comment (daniel-k) [inline dist/tools/openocd/openocd.sh]:
```bash
[ -n "${SETSID}" ] && SETSID=$(which setsid)
```
I don't get this. If `$SETSID` is not empty, then set it to the output of `which setsid`? Why should `$SETSID` be set in the first place?

Comment (gebart) [inline dist/tools/openocd/openocd.sh]: sorry, I meant `-z`

Comment (daniel-k) [inline dist/tools/openocd/openocd.sh]: Anyway, where is `$SETSID` supposed to be set?

Comment (gebart) [inline dist/tools/openocd/openocd.sh]: The purpose was to allow overriding it from the environment in the case
where you have the osx workaround installed somewhere outside of the normal
path

Comment (daniel-k) [inline dist/tools/openocd/openocd.sh]: I see. And I realized that the checking isn't needed in my solution, because `SETSID="$(which setsid)"` already does it.

**Comment by OlegHahm** [comment]
Wanna squash again?

**Comment by daniel-k** [comment]
@OlegHahm 
Squashed. Did you test again?

**Comment by OlegHahm** [comment]
I never had this problem, but doesn't seem to break anything. @gebart, @authmillenon, can you verify?

**Comment by daniel-k** [comment]
It seems to be related to recent OpenOCD versions, maybe >= 0.9.0

**Comment by gebart** [comment]
I won't be able to verify until the end of next week at the earliest.

**Comment by authmillenon** [comment]
Works for me:

```
[martine@beutlin RIOT]<3 openocd --version
Open On-Chip Debugger 0.9.0-dev-00358-gd3c2679 (2015-04-03-14:36)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.sourceforge.net/doc/doxygen/bugs.html
[martine@beutlin RIOT]<3 uname -a
Linux beutlin 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

If this is enough I give this PR an ACK. If someone else wants to test this, please do.

**Comment by OlegHahm** [comment]
Works for at least four maintainers on different platforms - should be good enough.
