### PR TITLE
gnrc_sixlowpan_iphc: fix _compressible()

### LINKED ISSUE #10947: tests/gnrc_tcp_*: not working on 6Lo-based boards
#### Description
Both test applications *tests/gnrc_tcp_server* and *tests/gnrc_tcp_client* do not work on current master using boards (I tried with samr21-xpro and iotlab-m3). It used to work on 2018.07 release branch though.

#### Steps to reproduce the issue
Build/flash/term one of the aforementioned applications to a board and wait for the serial output.

#### Expected results
The respective application should print some status information, among others IPv6 address, port, ...

#### Actual results
You see nothing because the board sees to hard fault before main() is reached. By enabling `ENABLE_DEBUG` in `auto_init` you can see at least some output before the board crashes.

#### Versions
```
Installed compiler toolchains 
-----------------------------
             native gcc: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                avr-gcc: missing
       mips-mti-elf-gcc: missing
             msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
   riscv-none-embed-gcc: missing
                  clang: missing

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: missing (missing)

Installed development tools
---------------------------
                  cmake: cmake version 3.10.2
               cppcheck: missing
                doxygen: 1.8.13
                 flake8: 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.6.7 on Linux
                    git: git version 2.17.1
             coccinelle: missing
```

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
When either `gnrc_sixlowpan_iphc_nhc` or `gnrc_udp` is not compiled in `_compressible()` never returns `true`. This causes the `dispatch` snip in `gnrc_sixlowpan_iphc_send()` to be of length 0, meaning `dispatch->data` is `NULL`, causing possible crashes when trying to send IPv6 packets over 6LoWPAN without NHC or UDP.

### Testing procedure
`tests/gnrc_tcp_server` and `tests/gnrc_tcp_client` should work on a 6Lo-based board.
`examples/gnrc_networking` should still be able to exchange UDP packets. Those packets should be compressed with NHC (check with sniffer).

### Issues/PRs references
Fixes #10947

### CODE REVIEW

File: sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c [hunk 1]
```diff
@@ -647,8 +647,8 @@ static inline bool _compressible(gnrc_pktsnip_t *hdr)
         case GNRC_NETTYPE_IPV6:
 #if defined(MODULE_GNRC_SIXLOWPAN_IPHC_NHC) && defined(MODULE_GNRC_UDP)
         case GNRC_NETTYPE_UDP:
-            return true;
```
Comment (miri64) [inline sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c]: @cgundogan I remember some discussion about this line, I believe with you... however this exists since 0a9793c, so I'm not sure when and where this happened.

Comment (cgundogan) [reply sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c]: hm, tbh I do not remember such a discussion, but the change is clearly an improvement ..

Comment (miri64) [reply sys/net/gnrc/network_layer/sixlowpan/iphc/gnrc_sixlowpan_iphc.c]: Ok, then we agree, that this change fixes things :-)

**Comment by PeterKietzmann** [comment]
Tested the following with this PR:

**native - native**
*gnrc_networking*
`ping6 1000 <addr>1000 0 0`: ok
`udp send <addr> 1234 1234567890`: ok

Wireshark dump looks ok (no 6Lo of course)

**samr21-xpro - samr21-xpro**
*gnrc_networking*
`ping6 1000 <addr>1000 0 0`: ok
`udp send <addr> 1234 1234567890`: ok

Wireshark dump looks ok, see
udp_samr21

*gnrc_tcp_**
Both applications build and run on a samr21-xpro. **But** they don't work as expected. Only thing I see is Router Solicitations from both nodes. No Neighbor Discovery, no nothing. Is there an other module missing?

**Comment by miri64** [comment]
> _gnrc_tcp__*
> Both applications build and run on a samr21-xpro. **But** they don't work as expected. Only thing I see is Router Solicitations from both nodes. No Neighbor Discovery, no nothing. Is there an other module missing?

First of all, we need to make sure they ever worked on this board? If no, and they don't crash this is non-blocking as it has nothing to do with this PR (but might still have to do with #10947).

**Comment by miri64** [comment]
Of course it doesn't work. The client tries to connect to `fe80::affe` which 6Lo neighbor discovery [reverse translates](https://tools.ietf.org/html/rfc6775#section-5.6) to a link-layer address. Since `fe80::affe` is not based on a link-layer address next-hop determination fails => the TCP client can't connect.

**Comment by miri64** [comment]
@PeterKietzmann can you try with the `TCP_TARGET_ADDR` environment variable set to the auto-configured link-layer address of the server?

**Comment by PeterKietzmann** [comment]
(btw: yes packets are dropped in `gnrc_ipv6` due to missing NC entry)

**Comment by brummer-simon** [comment]
> > _gnrc_tcp__*
> > Both applications build and run on a samr21-xpro. **But** they don't work as expected. Only thing I see is Router Solicitations from both nodes. No Neighbor Discovery, no nothing. Is there an other module missing?
> 
> First of all, we need to make sure they ever worked on this board? If no, and they don't crash this is non-blocking as it has nothing to do with this PR (but might still have to do with #10947).

I developed and test gnrc_tcp mostly on the samr21-xpro. Both application worked.

**Comment by PeterKietzmann** [comment]
So I'm gonna open a separate issue. ACK for the fix in this PR

**Comment by miri64** [comment]
I just tested the `gnrc_tcp` tests for `native`. There I get a `ECONNRESET` from the server :-/.

**Comment by PeterKietzmann** [comment]
That's an other issue. Please read #10945 carefully. If you start the client shortly before the server, it should directly work.

I'm gonna open a separate issue for the missing ND.

**Comment by miri64** [comment]
> I'm gonna open a separate issue for the missing ND.

The ND is not *missing*. The test is using it wrong.

**Comment by miri64** [comment]
> That's an other issue. Please read #10945 carefully. If you start the client shortly before the server, it should directly work.

Didn't know about that issue yet ;-).

**Comment by PeterKietzmann** [comment]
> The ND is not _missing_. The test is using it wrong.

Then how about you open a new issue? Because all I see is missing ND, an empty NIB and I don't really know how a correct usage would look like.

**Comment by brummer-simon** [comment]
> > I'm gonna open a separate issue for the missing ND.
> 
> The ND is not _missing_. The test is using it wrong.

How to use it right then? I mean the test are crappy currently but I want to keep them alive until I find the time to replace them.

**Comment by miri64** [comment]
I don't know. I had to look into what's going on there exactly. However, since they are the only networking-related tests having problems ATM, my assessment is rather that something weird is happening there, than in the networking layer.

**Comment by brummer-simon** [comment]
Okay well then,

the highest priority for the existing TCP test should be, cause as less problems as possible.
You mentioned that link local addresses could cause problems. What prefix would you suggest to use for testing then?

Secondly, I am working more or less frequently on replacing the existing gnrc_tcp tests. 
This is the feature branch: https://github.com/brummer-simon/RIOT/tree/gnrc_tcp-improve_tests
Would you take a look sometime to check if am on the right track? You have clearly more experience in the automation of network tests.

**Comment by miri64** [comment]
Backport provided in #10954

**Comment by miri64** [comment]
> What prefix would you suggest to use for testing then?

Link-local addresses are fine. Everything else would require even more network bootstrapping (configuring routes etc). However, the suffix should be based on the link-local address for 6Lo-based networks (see [RFC 6775](https://tools.ietf.org/html/rfc6775#section-5.6) for why that is).

> Would you take a look sometime to check if am on the right track? You have clearly more experience in the automation of network tests.

Will do when I find the time.
