### PR TITLE
drivers/sx127x: make paselect configurable in the driver params

### LINKED ISSUE #8813: LoraMAC-node does not work
#### Description
Seems like LoraMAC-node package is not working.

I'm trying to join Nucleo-F446 + Modtronix InAir9b (SX1276 w/ PA_BOOST enabled i.e. +20dB) to a LoRaWAN network.

Similar setup but with bluepill + Modtronix InAir9b does not work either.

This has been done with the pkg_semtech-loramac in tests/.

Extra info:

I did a simple Lora (not LoraWAN) test between the nucleo and the bluepill with the driver_sx127x. One in listen, the other in transmit mode. Payload goes between the transceivers, so it doesn't seem to be a hardware problem.

Usually when an OTAA is attempted a package is send over the air. I don't have my spectrum analyzer with me, but I'm mostly sure that no package is send when either OTAA or TX is attempted, as the gateway usually reacts and I can see both debug on the console and even simple visual ack from the LEDs on the gateway. Nothing like that, so I'm almost certain that no packet is generated at all. I took a look at the code, but I get lost in it and couldn't find out what would be the reason for MAC timer timeout.

Also LoraMAC-node is already on version 4.4.1 but I don't feel like trying to switch to that version on my own.

#### Steps to reproduce the issue
Connect a bluepill or a Nucleo with SX1276 and attempt to do either an OTAA join, or TX with APB.

#### Expected results
OTAA Join request send, reply by the LoraWAN gateway, and eventually join in the network
#### Actual results
```
2018-03-22 01:58:35,294 - INFO # reboot
2018-03-22 01:58:35,304 - INFO # �main(): This is RIOT! (Version: 2018.04-devel-727-g0f07b-ws2)
2018-03-22 01:58:35,307 - INFO # [semtech-loramac] initializing loramac
2018-03-22 01:58:35,312 - INFO # [semtech-loramac] initialize loramac for EU868 region
2018-03-22 01:58:35,316 - INFO # sx127x: peripherals initialized with success
2018-03-22 01:58:35,319 - INFO # SX1276 transceiver detected.
2018-03-22 01:58:35,321 - INFO # All up, running the shell now
> 2018-03-22 01:58:35,339 - INFO #  [DEBUG] Set channel: 868000000
2018-03-22 01:58:35,347 - INFO # [DEBUG] Set channel: 434000000
2018-03-22 01:58:35,350 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 01:58:35,352 - INFO # [DEBUG] set modem: 1
2018-03-22 01:58:35,354 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 01:58:35,357 - INFO # [DEBUG] Set op mode: RECEIVER
2018-03-22 01:58:35,392 - INFO # [DEBUG] Set sleep
2018-03-22 01:58:35,395 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 01:58:35,397 - INFO # [DEBUG] Change state: IDLE
2018-03-22 01:58:35,399 - INFO # [DEBUG] Set syncword: 34
2018-03-22 01:58:35,401 - INFO # [DEBUG] Set sleep
2018-03-22 01:58:35,403 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 01:58:35,406 - INFO # [DEBUG] Change state: IDLE
2018-03-22 01:58:35,410 - INFO # [semtech-loramac] EU868 region: use default channels
2018-03-22 01:58:35,413 - INFO # [semtech-loramac] set dr 0
2018-03-22 01:58:35,415 - INFO # [semtech-loramac] set adr 0
2018-03-22 01:58:35,419 - INFO # [semtech-loramac] set public network 1
2018-03-22 01:58:35,421 - INFO # [DEBUG] Set syncword: 34
2018-03-22 01:58:35,423 - INFO # [semtech-loramac] set class 0
2018-03-22 01:58:35,425 - INFO # [DEBUG] Set sleep
2018-03-22 01:58:35,427 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 01:58:35,430 - INFO # [DEBUG] Change state: IDLE
```

loramac set deveui _my deveui_
loramac set appkey _my appkey_
loramac set appeui _my appeui_ (by the way this is not required per se, as this should be done by the server for various reasons, it is used only by TTN. In the network here any appeui can be set or just 16 zeros can be used) <- this has no relation to the problem

loramac join otaa 
_follows the short join request, not all frequencies_
```
2018-03-22 02:10:02,892 - INFO # loramac join otaa
2018-03-22 02:10:02,895 - INFO # [semtech-loramac] loramac cmd
2018-03-22 02:10:02,898 - INFO # [semtech-loramac] starting OTAA join
2018-03-22 02:10:02,901 - INFO # [DEBUG] already using modem: 1
2018-03-22 02:10:02,904 - INFO # [DEBUG] Set op mode: RECEIVER
2018-03-22 02:10:02,939 - INFO # [DEBUG] Set sleep
2018-03-22 02:10:02,941 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 02:10:02,944 - INFO # [DEBUG] Change state: IDLE
2018-03-22 02:10:02,947 - INFO # [DEBUG] Set channel: 868500000
2018-03-22 02:10:02,950 - INFO # [DEBUG] already using modem: 1
2018-03-22 02:10:02,952 - INFO # [DEBUG] Set freq hop: 0
2018-03-22 02:10:02,954 - INFO # [DEBUG] Set bandwidth: 0
2018-03-22 02:10:02,957 - INFO # [DEBUG] Set coding rate: 1
2018-03-22 02:10:02,959 - INFO # [DEBUG] Set spreading factor: 7
2018-03-22 02:10:02,961 - INFO # [DEBUG] Set CRC: 1
2018-03-22 02:10:02,964 - INFO # [DEBUG] Set freq hop: 0
2018-03-22 02:10:02,966 - INFO # [DEBUG] Set Hop period: 0
2018-03-22 02:10:02,969 - INFO # [DEBUG] Set fixed header length: 0
2018-03-22 02:10:02,971 - INFO # [DEBUG] Set IQ invert: 0
2018-03-22 02:10:02,974 - INFO # [DEBUG] Set payload len: 0
2018-03-22 02:10:02,976 - INFO # [DEBUG] Set power: 13
2018-03-22 02:10:02,979 - INFO # [DEBUG] Set preamble length: 8
2018-03-22 02:10:02,981 - INFO # [DEBUG] Set RX single: 0
2018-03-22 02:10:02,984 - INFO # [DEBUG] Set TX timeout: 3000000
2018-03-22 02:10:02,987 - INFO # [DEBUG] Set max payload len: 23
2018-03-22 02:10:02,989 - INFO # [DEBUG] Set payload len: 23
2018-03-22 02:10:02,991 - INFO # [DEBUG] Set standby
2018-03-22 02:10:02,994 - INFO # [DEBUG] Set op mode: STANDBY
2018-03-22 02:10:02,997 - INFO # [DEBUG] Change state: IDLE
2018-03-22 02:10:03,000 - INFO # [DEBUG] Change state: TX
2018-03-22 02:10:03,003 - INFO # [DEBUG] Set op mode: TRANSMITTER
2018-03-22 02:10:03,067 - INFO # [DEBUG] Change state: IDLE
2018-03-22 02:10:03,069 - INFO # [DEBUG] Set sleep
2018-03-22 02:10:03,071 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 02:10:03,074 - INFO # [DEBUG] Change state: IDLE
2018-03-22 02:10:03,075 - INFO # [DEBUG] Set sleep
2018-03-22 02:10:03,078 - INFO # [DEBUG] Set op mode: SLEEP
2018-03-22 02:10:03,080 - INFO # [DEBUG] Change state: IDLE
2018-03-22 02:10:03,084 - INFO # [semtech-loramac] Transmission completed
2018-03-22 02:10:03,940 - INFO # [semtech-loramac] MAC timer timeout


```

#### Versions
Latest RIOT from master.
**Host:** Fedora 28 (x86_64)
**gcc:**
arm-none-eabi-gcc-cs-7.1.0-5.fc27.x86_64
arm-none-eabi-gcc-cs-c++-7.1.0-5.fc27.x86_64

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR adds an extra configuration parameter for power amplifier selection to the SX127x driver. As reported in #8813, this should be made easily configurable by the user.

RFO selection mode is kept as the default since it is the one that works in EU868 with mbed shields. Apparently BOOST mode can only be used in Europe with EU433 band or in the US915 band.

cc @dylad and @ilf-S who might be interested

### Issues/PRs references

Should fix #8813

### CODE REVIEW

File: drivers/sx127x/sx127x_getset.c [hunk 1]
```diff
@@ -707,23 +707,13 @@ void sx127x_set_payload_length(sx127x_t *dev, uint8_t len)
     sx127x_reg_write(dev, SX127X_REG_LR_PAYLOADLENGTH, len);
 }
 
-static inline uint8_t sx127x_get_pa_select(uint32_t channel)
+static inline uint8_t sx127x_get_pa_select(const sx127x_t *dev)
```
Comment (dylad) [inline drivers/sx127x/sx127x_getset.c]: What about unify SX1272 and SX1276 in this function ?

Comment (aabadie) [reply drivers/sx127x/sx127x_getset.c]: I'm not sure to understand your comment. This is already unified and more flexible I think: the new parameter `paselect` can be updated depending on the type of radio or how it is soldered on a breakout board.

Comment (dylad) [reply drivers/sx127x/sx127x_getset.c]: Oops sorry I didn't check the right version. I'll take another look.

**Comment by aabadie** [comment]
All green, so I guess I can merge this one.
