### PR TITLE
cpu/sam0: provide interface to query GCLK frequency

### LINKED ISSUE #12037: cpu/sam0_common: i2c baudrate calculation fails if CLOCK_CORECLOCK > 51 MHz
#### Description
The I2C baudrate is always derived from `CLOCK_CORECLOCK`, even if a different `.gclk_src` is selected. If `CLOCK_CORECLOCK` is too high, the resulting baudrate will is too big and a check in [`i2c_init()`](https://github.com/RIOT-OS/RIOT/blob/master/cpu/sam0_common/periph/i2c.c#L144) silently fails, leaving the I2C uninitialized.

Any resulting access to the i2c bus will fail.

#### Steps to reproduce the issue
in `examples/default`:
 - `USEMODULE += i2c_scan`
 - `make BOARD=same54-xpro flash`
 - run `i2c_scan 0`

#### Expected results
```
2019-08-20 14:01:01,264 - INFO #  > i2c_scan 0
2019-08-20 14:01:01,270 - INFO # Scanning I2C device 0...
2019-08-20 14:01:01,279 - INFO # addr not ack'ed = "-", addr ack'ed = "X", addr reserved = "R", error = "E"
2019-08-20 14:01:01,283 - INFO #      0 1 2 3 4 5 6 7 8 9 a b c d e f
2019-08-20 14:01:01,286 - INFO # 0x00 R R R R R R R R R R R R R R - -
2019-08-20 14:01:01,287 - INFO # 0x10 - - - - - - - - - - - - - - - -
2019-08-20 14:01:01,288 - INFO # 0x20 - - - - - - - - X - - - - - - -
2019-08-20 14:01:01,296 - INFO # 0x30 X - - - - - X - - - - - - - - -
2019-08-20 14:01:01,298 - INFO # 0x40 - - - - - - - - - - - - - - - -
2019-08-20 14:01:01,304 - INFO # 0x50 X - - - - - X - X - - - - - X -
2019-08-20 14:01:01,309 - INFO # 0x60 X - - - - - - - - - - - - - - -
2019-08-20 14:01:01,313 - INFO # 0x70 - - - - - - - - R R R R R R R R
```

#### Actual results
```
2019-08-20 13:56:22,893 - INFO # > i2c_scan 0
2019-08-20 13:56:22,895 - INFO # Scanning I2C device 0...
2019-08-20 13:56:22,901 - INFO # addr not ack'ed = "-", addr ack'ed = "X", addr reserved = "R", error = "E"
2019-08-20 13:56:22,906 - INFO #      0 1 2 3 4 5 6 7 8 9 a b c d e f
```
the program hangs indefinitely in an `-EAGAIN` loop.

#### Versions
RIOT master

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The sam0 family offers multiple GCLKs that can be sourced from different timers.
However, all peripherals were effectively always clocked by the hard-coded `CLOCK_CORECLOCK`.

This causes several issues:

 - on high CPU frequencies (> 51 MHz) the available I2C divider is too small to produce the required I2C baud rate 
- on low CPU frequencies the available frequency is too low to produce high UART baudrates.

This introduces a `sam0_gclk_freq()` function to query the frequency of  the individual GCLKs, so other GCLKs than 0 can be used for peripherals.

This would also allow to change the CPU frequency at run-time without affecting peripherals, unless they use GCLKs sourced from GCLK0.

The first commit in this series also changes the `.gclk_src` config struct from a bit mask to the GCLK ID.
While not strictly necessary, it cleans up the board configurations and removes the need to differentiate between samd2x and later MCUs.

### Testing procedure

In only tested the changes on `samr21-xpro` and `same54-xpro`

On `same54-xpro` you will find that `i2c_scan` (and I2C in general) now works (`USEMODULE += i2c_scan`), before it would get stuck due to a wrong clock frequency.

### Issues/PRs references
fixes #12037

### CODE REVIEW

File: cpu/samd5x/cpu.c [hunk 1]
```diff
@@ -105,6 +105,41 @@ static void gclk_connect(uint8_t id, uint8_t src, uint32_t flags) {
...
+        return CLOCK_CORECLOCK;
+    case 1:
+        return 32768;
+    case 5:
+        return 8000000;
+    case 6:
+        return SAM0_DFLL_FREQ_HZ;
+    default:
+        return 0;
+    }
```
Comment (keestux) [inline cpu/samd5x/cpu.c]: May I suggest that we firmly document the GCLKs and the frequencies, somewhere?
Also, the numbers in this `switch` have special meaning, and there are defines floating around that have to match. For example, `SAM0_GCLK_32KHZ` => 32768. Perhaps we can use this define instead the 1 (and instead of 2 for the samd21, and instead of 1 for saml1x)

File: boards/sodaq-autonomo/include/periph_conf.h [hunk 2]
```diff
@@ -52,7 +52,7 @@ static const uart_conf_t uart_config[] = {
         .rx_pad   = UART_PAD_RX_1,
         .tx_pad   = UART_PAD_TX_2,
         .flags    = UART_FLAG_NONE,
-        .gclk_src = GCLK_CLKCTRL_GEN_GCLK0
+        .gclk_src = 0
```
Comment (SodaqMoja) [inline boards/sodaq-autonomo/include/periph_conf.h]: I prefer a comma, even on the last initializer

File: boards/samd21-xpro/include/periph_conf.h [hunk 3]
```diff
@@ -242,7 +242,8 @@ static const spi_conf_t spi_config[] = {
         .mosi_mux = GPIO_MUX_D,
         .clk_mux  = GPIO_MUX_D,
         .miso_pad = SPI_PAD_MISO_0,
-        .mosi_pad = SPI_PAD_MOSI_2_SCK_3
+        .mosi_pad = SPI_PAD_MOSI_2_SCK_3,
+        .gclk_src = 0
```
Comment (SodaqMoja) [inline boards/samd21-xpro/include/periph_conf.h]: Here you see how the lack of a comma makes the diff bigger than it should be

Comment (keestux) [reply boards/samd21-xpro/include/periph_conf.h]: BTW. This was me.

**Comment by keestux** [comment]
Let me mention it once more. There are now a lot of places where the code has `0`, `1`, `5`, etc, but these numbers mean nothing unless you know the (undocumented) values. For example, `0` is for the core clock, `1` is a 1MHz clock, etc.

In the mean time a define was added in `periph_cpu.h`, namely `SAM0_GCLK_32KHZ`. Why don't we extend this section and have defines for the other GCLKs? We can add (a brief) description what the GCLK is (frequency, power down mode, etc). Maybe just as a start. And if you're adventurous you could change all these
```
    .gclk_src       = 0,
...
    .gclk_src       = 1,
```
into
```
    .gclk_src       = SAM0_GCLK_MAIN,
...
    .gclk_src       = SAM0_GCLK_1MHZ,
```

**Comment by benpicco** [comment]
Alright, that makes sense!
I'll do a separate commit.

File: cpu/samd21/cpu.c [hunk 4]
```diff
@@ -72,6 +94,22 @@ static void clk_init(void)
     while (!(SYSCTRL->PCLKSR.reg & SYSCTRL_PCLKSR_OSC8MRDY)) {}
 #endif
 
+    /* Setup GCLK2 with divider 1 (32.768kHz) */
+    GCLK->GENDIV.reg  = (GCLK_GENDIV_ID(2)  | GCLK_GENDIV_DIV(0));
+    GCLK->GENCTRL.reg = (GCLK_GENCTRL_ID(2) | GCLK_GENCTRL_GENEN
```
Comment (keestux) [inline cpu/samd21/cpu.c]: We should either add `SAM0_GCLK_32KHZ` in the comment. Or else we can change the 2 in `SAM0_GCLK_32KHZ`.

File: cpu/samd21/include/periph_cpu.h [hunk 5]
```diff
@@ -44,6 +44,18 @@ extern "C" {
...
 
+/**
+ * @name   SAMD21 GCLK definitions
+ * @{
+ */
+enum {
+    SAM0_GCLK_MAIN = 0,                 /**< 48 MHz main clock      */
+    SAM0_GCLK_1MHZ,                     /**< 1 MHz clock for xTimer */
+    SAM0_GCLK_32KHZ,                    /**< 32 kHz clock           */
+    SAM0_GCLK_1KHZ,                     /**< 1 kHz clock            */
```
Comment (keestux) [inline cpu/samd21/include/periph_cpu.h]: The enums must get hard coded values. No?

File: cpu/samd5x/cpu.c [hunk 6]
```diff
@@ -105,6 +105,41 @@ static void gclk_connect(uint8_t id, uint8_t src, uint32_t flags) {
     while (GCLK->SYNCBUSY.reg & GCLK_SYNCBUSY_GENCTRL(id)) {}
 }
 
+void sam0_gclk_enable(uint8_t id)
+{
+    /* clocks 0 & 1 are always running */
+
+    switch (id) {
+    case 5:
```
Comment (keestux) [inline cpu/samd5x/cpu.c]: 5 -> SAM0_GCLK_8MHZ; 6 -> SAM0_GCLK_48MHZ

File: cpu/saml21/cpu.c [hunk 7]
```diff
@@ -109,6 +127,11 @@ void cpu_init(void)
 
     /* Setup GCLK generators */
     _gclk_setup(0, GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_OSC16M);
+#if EXTERNAL_OSC32_SOURCE
+    _gclk_setup(1, GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_XOSC32K);
+#else
+    _gclk_setup(1, GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_OSCULP32K);
```
Comment (keestux) [inline cpu/saml21/cpu.c]: 1 -> SAM0_GCLK_32KHZ ?

File: cpu/sam0_common/periph/rtc.c [hunk 8]
```diff
@@ -65,8 +65,8 @@ static inline void _rtc_set_enabled(bool on)
 #ifdef CPU_SAMD21
 static void _rtc_clock_setup(void)
 {
-    /* Use 1024 Hz GCLK4 */
-    GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN(4) | GCLK_CLKCTRL_ID_RTC;
+    /* Use 1024 Hz GCLK3 */
+    GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN(3) | GCLK_CLKCTRL_ID_RTC;
```
Comment (keestux) [inline cpu/sam0_common/periph/rtc.c]: Is this `SAM0_GCLK_1KHZ`? If yes then we should either add that in the comment, or change the 3 to `SAM0_GCLK_1KHZ`.

File: cpu/samd21/include/periph_cpu.h (hunk 5 above)
Comment (keestux) [reply cpu/samd21/include/periph_cpu.h]: So, `SAM0_GCLK_1KHZ` is 3 (meaning GCLK3). This breaks `cpu/sam0_common/periph/wdt.c` for SAMD21, because that still uses GCLK4.

Comment (benpicco) [reply cpu/samd21/include/periph_cpu.h]: Good catch! Changed it to `GCLK_CLKCTRL_GEN(SAM0_GCLK_1KHZ)`

File: boards/sodaq-autonomo/include/periph_conf.h (hunk 2 above)
Comment (benpicco) [reply boards/sodaq-autonomo/include/periph_conf.h]: I added commas everywhere.

File: cpu/samd21/cpu.c [hunk 9]
```diff
@@ -72,19 +94,35 @@ static void clk_init(void)
...
+                        GCLK_GENDIV_ID(SAM0_GCLK_1MHZ));
     GCLK->GENCTRL.reg = (GCLK_GENCTRL_GENEN |
                          GCLK_GENCTRL_SRC_OSC8M |
-                         GCLK_GENCTRL_ID(1));
-    GCLK->CLKCTRL.reg = (GCLK_CLKCTRL_GEN(1) |
-                         GCLK_CLKCTRL_ID(1) |
+                         GCLK_GENCTRL_ID(SAM0_GCLK_1MHZ));
+    GCLK->CLKCTRL.reg = (GCLK_CLKCTRL_GEN(SAM0_GCLK_1MHZ) |
+                         GCLK_CLKCTRL_ID(SAM0_GCLK_1MHZ)  |
                          GCLK_CLKCTRL_CLKEN);
```
Comment (keestux) [inline cpu/samd21/cpu.c]: Let me apologize upfront, because I am constantly confused about clock generators. So I may talk nonsense.
I'm afraid that `GCLK_CLKCTRL_ID(SAM0_GCLK_1MHZ)` is not correct. The `1` in this case is `DPLL`.
And `GCLK_GENCTRL_ID(SAM0_GCLK_1MHZ)` is probably not correct either. The `1` in this case is `GCLKIN`. No?

File: cpu/samd21/cpu.c [hunk 10]
```diff
@@ -118,25 +156,14 @@ static void clk_init(void)
...
-                        GCLK_GENCTRL_GENEN |
-                        GCLK_GENCTRL_RUNSTDBY |
-                        GCLK_GENCTRL_SRC_XOSC32K;
+                         GCLK_GENCTRL_ID(SAM0_GCLK_1MHZ));
     while (GCLK->STATUS.reg & GCLK_STATUS_SYNCBUSY) {}
 
-    /* set GCLK3 as source for DFLL */
-    GCLK->CLKCTRL.reg = (GCLK_CLKCTRL_GEN_GCLK3 |
+    /* set GCLK2 as source for DFLL */
+    GCLK->CLKCTRL.reg = (GCLK_GENDIV_ID(SAM0_GCLK_32KHZ) |
```
Comment (keestux) [inline cpu/samd21/cpu.c]: Oops, that should be `GCLK_CLKCTRL_GEN()`

File: cpu/samd21/include/periph_cpu.h (hunk 5 above)
Comment (keestux) [reply cpu/samd21/include/periph_cpu.h]: I strongly suggest to add the value of each enum.

File: cpu/samd21/cpu.c [hunk 11]
```diff
@@ -215,7 +226,7 @@ static void clk_init(void)
 #endif
 
     /* redirect all peripherals to a disabled clock generator (7) by default */
-    for (int i = 0x3; i <= 0x22; i++) {
+    for (int i = SAM0_GCLK_NUM; i <= 0x22; i++) {
```
Comment (keestux) [inline cpu/samd21/cpu.c]: No, that's not correct. The loop is about peripherals (users of the GCLKs). In the code above we initialize 0 , 1 and 2. The loop initializes the remaining peripherals to use GCLK7.
The number 0x22 isn't correct either. It depends on the SAM0 variant how many peripherals there are. I don't know if there is a specific define for it. I know that SAMD21 has `I2S_1` 0x24.

File: cpu/samd21/cpu.c (hunk 9 above)
Comment (benpicco) [reply cpu/samd21/cpu.c]: Yea let's not use `GCLK_CLKCTRL_ID()` when more explicit defines are available instead.
`GCLK_GENCTRL_ID(SAM0_GCLK_1MHZ)` should point to `GCLKGEN1` which is fine.

File: cpu/samd21/cpu.c (hunk 10 above)
Comment (benpicco) [reply cpu/samd21/cpu.c]: Thank you!

File: cpu/samd21/cpu.c (hunk 11 above)
Comment (benpicco) [reply cpu/samd21/cpu.c]: I changed it back to what is was before.
I wonder if this is necessary to begin with.

File: cpu/samd21/include/periph_cpu.h (hunk 5 above)
Comment (benpicco) [reply cpu/samd21/include/periph_cpu.h]: I'd rather discourage the use of the raw numbers altogether.

Comment (keestux) [reply cpu/samd21/include/periph_cpu.h]: OK, I'm not going to complain too much because I think you've done a terrific job so far.

File: cpu/samd21/cpu.c (hunk 9 above)
Comment (keestux) [reply cpu/samd21/cpu.c]: OK

File: cpu/samd21/cpu.c [hunk 12]
```diff
@@ -168,8 +195,8 @@ static void clk_init(void)
     while ((SYSCTRL->PCLKSR.reg & mask) != mask) { } /* Wait for DFLL lock */
 
     /* select the DFLL as source for clock generator 0 (CPU core clock) */
-    GCLK->GENDIV.reg =  (GCLK_GENDIV_DIV(1U) | GCLK_GENDIV_ID(0));
-    GCLK->GENCTRL.reg = (GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_DFLL48M | GCLK_GENCTRL_ID(0));
+    GCLK->GENDIV.reg =  (GCLK_GENDIV_DIV(1U) | GCLK_GENDIV_ID(SAM0_GCLK_MAIN));
+    GCLK->GENCTRL.reg = (GCLK_GENCTRL_GENEN | GCLK_GENCTRL_SRC_DFLL48M | GCLK_GENCTRL_ID(SAM0_GCLK_MAIN));
     GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0;
```
Comment (keestux) [inline cpu/samd21/cpu.c]: Perhaps we should change this line as well, just to make everything consistent.
```
GCLK->CLKCTRL.reg = GCLK_CLKCTRL_CLKEN | GCLK_CLKCTRL_GEN_GCLK0;
```
=>
```
GCLK->CLKCTRL.reg = GCLK_CLKCTRL_GEN(SAM0_GCLK_MAIN) |
                                       GCLK_CLKCTRL_ID_DFLL48 |
                                       GCLK_CLKCTRL_CLKEN;
```

Comment (benpicco) [reply cpu/samd21/cpu.c]: Good idea!

**Comment by dylad** [comment]
I ran `dist/tools/compile_and_test_for_board/compile_and_test_for_board.py` for SAML10, SAML11, SAML21 and SAME54, so far so good.
If @keestux 's comments were addressed and if SAMD21 is also happy, we should be good to go.

File: cpu/samd5x/cpu.c [hunk 13]
```diff
@@ -105,6 +105,41 @@ static void gclk_connect(uint8_t id, uint8_t src, uint32_t flags) {
...
 
+void sam0_gclk_enable(uint8_t id)
+{
+    /* clocks 0 & 1 are always running */
+
+    switch (id) {
+    case SAM0_GCLK_8MHZ:
+        /* 8 MHz clock used by xtimer */
+#if USE_DPLL
+        gclk_connect(SAM0_GCLK_8MHZ, GCLK_SOURCE_DPLL0, GCLK_GENCTRL_DIV(DPLL_DIV * CLOCK_CORECLOCK / 8000000));
```
Comment (dylad) [inline cpu/samd5x/cpu.c]: Could you split it into two lines please ?

File: cpu/samd5x/cpu.c [hunk 14]
```diff
@@ -105,6 +105,41 @@ static void gclk_connect(uint8_t id, uint8_t src, uint32_t flags) {
...
+#else
+        gclk_connect(SAM0_GCLK_8MHZ, GCLK_SOURCE_DFLL, GCLK_GENCTRL_DIV(SAM0_DFLL_FREQ_HZ / 8000000));
```
Comment (dylad) [inline cpu/samd5x/cpu.c]: same here

File: cpu/samd5x/cpu.c (hunk 13 above)
Comment (benpicco) [reply cpu/samd5x/cpu.c]: Ok!

File: cpu/samd5x/cpu.c (hunk 14 above)
Comment (benpicco) [reply cpu/samd5x/cpu.c]: Done.

**Comment by keestux** [comment]
It looks good to me.
ACK

**Comment by dylad** [comment]
> It looks good to me.
ACK

Nice ! 

@benpicco Please squash !

**Comment by benpicco** [comment]
Squashed & rebased to the master.

**Comment by dylad** [comment]
Here we go.

**Comment by benpicco** [comment]
Thank you all for reviewing & testing this!

File: cpu/samd21/cpu.c [hunk 15]
```diff
@@ -72,19 +94,35 @@ static void clk_init(void)
     while (!(SYSCTRL->PCLKSR.reg & SYSCTRL_PCLKSR_OSC8MRDY)) {}
 #endif
 
+    /* Setup GCLK2 with divider 1 (32.768kHz) */
```
Comment (fjmolinas) [inline cpu/samd21/cpu.c]: @benpicco why did you move this up? `GCLK->CTRL.reg = GCLK_CTRL_SWRST`resets what is done here, can I move it back down in #13306? Iget the same drift as before otherwise.

Comment (fjmolinas) [reply cpu/samd21/cpu.c]: I see you use it for the dfll, I'll move `GCLK->CTRL.reg = GCLK_CTRL_SWRS` up.

Comment (benpicco) [reply cpu/samd21/cpu.c]: Hm previously this was in the `#if CLOCK_USE_PLL` block, but a 32kHz clock is always needed so I moved it here.
I must have missed the `GCLK_CTRL_SWRS` bit.
