### PR TITLE
sock_udp: allow creation with ephemeral ports

### LINKED ISSUE #9376: net/sock_udp: assign ephemeral source port on `sock_udp_create()`
#### Description
In the current sock/udp implementation for GNRC (and probably others as well), an ephemeral source port is assigned only when calling `sock_udp_send()` for the first time. This casts IMO unnecessary restrictions on the interface, and this seems to be counter intuitive to me. 

Take the following example, using a dedicated listener thread to handle incoming data: 
- thread_1 is started during system init as pure listener thread
- thread_1: calls `sock_udp_create()` with `local := NULL`
- thread_1: enters its main loop and calls `sock_udp_recv()`
- main_thread: the user app calls (most likely indirectly) `sock_udp_send()` at some later point in time

This example will not work -> the call to `sock_udp_recv()` will return `-EADDRNOTAVAIL` as no local port has been assigned.

**Solution: I suggest to move the assignment of the ephemeral source port into `sock_udp_create()`.**

This has two advantages:
1. the sock interface is more flexible (see example above)
2. we can assert the `sock.local` field to be configured in the `sock_udp_send` function and thus save a tiny amount of run time overhead

TODOs that follow from this proposal:
- [ ] fix sock_udp documentation: state more specifically when, where, and how ephemeral source ports are assigned
- [ ] adapt existing sock implementations
  - [ ] GNRC
  - [ ] lwip
  - [ ] emb6

#### Steps to reproduce the issue
n/a

#### Expected results
Ephemeral source port is assigned to socket when `sock_udp_create()` is called with `local := NULL`

#### Actual results
Ephemeral source port is assigned on the first call of `sock_udp_send()

#### Versions
n/a

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This change allows the port for local endpoint to be zero 0. If this is the case the `sock_udp_create()` function binds the object to an ephemeral port.

This also provides the port for GNRC, lwIP, and emb6 (including an update to the tests of GNRC and lwIP). Since GNRC doesn't support ephemeral ports natively (something like a UDP end-point isn't modeled in `netapi`) the port for this is a little bit more involved, but still a 5 liner. lwIP and emb6 handle this situation already internally, so only the assert for `local` needed to be removed.

This also piggy-backs a change for the return value of `sock_udp_send()` since the return value for when no ephemeral ports are available anymore shouldn't be `-EINVAL` (the input wasn't invalid, but some internal state isn't able to deliver).

### Issues/PRs references
Fixes #9376

### CODE REVIEW

File: sys/include/net/sock/udp.h [hunk 1]
```diff
@@ -318,7 +318,8 @@ typedef struct sock_udp sock_udp_t;
  *
  * @return  0 on success.
  * @return  -EADDRINUSE, if `local != NULL` and @p local is already used
- *         elsewhere
+ *          elsewhere or if `local->port == 0` but the pool of ephemeral ports
```
Comment (cgundogan) [inline sys/include/net/sock/udp.h]: > but the pool of ephemeral ports is depleted.

I would not expect `-EADDRINUSE` for the above condition.

Rather use `-ENOBUFS` or `-ENOMEM` like specified [here](http://pubs.opengroup.org/onlinepubs/007904875/functions/sendto.html):

>[ENOBUFS]
    Insufficient resources were available in the system to perform the operation.
[ENOMEM]
    Insufficient memory was available to fulfill the request.

File: sys/include/net/sock/udp.h [hunk 2]
```diff
@@ -419,6 +420,8 @@ ssize_t sock_udp_recv(sock_udp_t *sock, void *data, size_t max_len,
  *                      sock_udp_ep_t::port may not be 0.
  *
  * @return  The number of bytes sent on success.
+ * @return  -EADDRINUSE, if `sock` has no local end-point or was `NULL` and the
+ *          pool of available ephemeral ports is depleted.
```
Comment (cgundogan) [inline sys/include/net/sock/udp.h]: see above.

Comment (cgundogan) [reply sys/include/net/sock/udp.h]: and also for the implementation below.

File: sys/include/net/sock/udp.h (hunk 1 above)
Comment (miri64) [reply sys/include/net/sock/udp.h]: In any case: this is not a memory problem. This is just a problem of a range of numbers not being available anymore. So I think both `ENOBUFS` and `ENOMEM` are sufficient. I wasn't able to find out how Linux syscalls are reporting this error, or if they even consider it.

Comment (cgundogan) [reply sys/include/net/sock/udp.h]: did you mean **in**sufficient?

Nevertheless, I had a quick look at linux. Looks like the case is not clearly handled there and oftentimes they also just return `-EADDRINUSE` or `-EAGAIN`. Let's keep it this way then.

**Comment by miri64** [comment]
Travis error must be unrelated.

**Comment by cgundogan** [comment]
>Travis error must be unrelated.

mhm, yes, looks like that. GO
