### PR TITLE
lwip: improve and fix documentation

### LINKED ISSUE #8664: pkg: doxygen documentation is not fully processed
#### Description

While looking for Semtech-loramac API documentation on https://doc.riot-os.org, I noticed that the public API is not referenced (see http://doc.riot-os.org/group__pkg__semtech-loramac.html)

And this problem is more general because it's also the case with openthread, lwip, nordic_softdevice_ble, etc

After looking at the [doxygen configuration file](https://github.com/RIOT-OS/RIOT/blob/master/doc/doxygen/riot.doxyfile), I noticed that all pkg directories are skipped by doxygen (see [here](https://github.com/RIOT-OS/RIOT/blob/master/doc/doxygen/riot.doxyfile#L830))

#### Steps to reproduce the issue

Run the following command:

```
make doc
```

Here is the list of packages with the problem (because they expose a public API, compatible with RIOT, on top the package API):

- [x] emb6 (#12389)
- [ ] lwip (#12403)
- [x] nordic_softdevice_ble (#8667)
- [x] openthread (#8666)
- [x] semtech-loramac (#8668)

I'll come up with PRs fixing some of them.

#### Expected results

API documentation of packages are parsed and appear in the generated html documentation

#### Actual results

API documentation of packages are not parsed and doesn't appear in the generated html documentation

#### Versions

```
Installed toolchain versions
----------------------------
          native gcc: gcc (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
          msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
             avr-gcc: missing/error
   arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2017-q4-major) 7.2.1 20170904 (release) [ARM/embedded-7-branch revision 255204]
    mips-mti-elf-gcc: mips-mti-elf-gcc (Codescape GNU Tools 2016.05-03 for MIPS MTI Bare Metal) 4.9.2
               clang: clang version 4.0.1-6 (tags/RELEASE_401/final)
arm-none-eabi-newlib: "2.5.0"
 mips-mti-elf-newlib: "2.1.0"
            avr-libc: missing/error (missing/error)
            cppcheck: Cppcheck 1.80
          coccinelle: spatch version 1.0.4 with Python support and with PCRE support
                 git: git version 2.14.1
```

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This fixes and improves the documentation of the lwIP porting layer to make it build again. While I was reading lwIP's documentation on porting, I noticed that some defines were not required anymore, which I removed, rather than documented in a piggy-backed commit.

### Testing procedure
```
make doc
```

passes and shows lwIP now under Packages (and Networking).

lwIP applications should still build with the removed macros.

### Issues/PRs references
Fixes #8664

### CODE REVIEW

**Comment by aabadie** [comment]
Please rebase. #12389 was just merged :)

**Comment by miri64** [comment]
Rebased.

**Comment by aabadie** [comment]
There's a "RIOT lwIP port" group name that appears in the top level module goupr list (below packages). And now it doesn't build (I wanted to test `tests/lwip`):
```
make: Entering directory '/work/riot/RIOT/tests/lwip'
Building application "tests_lwip" for "native" with MCU "native".

rm -Rf /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip
mkdir -p /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip
/work/riot/RIOT/dist/tools/git/git-cache clone "https://git.savannah.nongnu.org/git/lwip.git" "159e31b689577dbf69cf0683bbaffbd71fa5ee10" "/work/riot/RIOT/tests/lwip/bin/pkg/native/lwip"
Cloning into '/work/riot/RIOT/tests/lwip/bin/pkg/native/lwip'...
remote: Counting objects: 52871, done.
remote: Compressing objects: 100% (12380/12380), done.
remote: Total 52871 (delta 39833), reused 52871 (delta 39833)
Receiving objects: 100% (52871/52871), 10.13 MiB | 1.06 MiB/s, done.
Resolving deltas: 100% (39833/39833), done.
HEAD is now at 159e31b6 Prepare 2.1.2 release
touch /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip/.git-downloaded
if [ 159e31b689577dbf69cf0683bbaffbd71fa5ee10 != 159e31b689577dbf69cf0683bbaffbd71fa5ee10 ] ; then \
	git -C /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip clean -xdff ; \
	git -C /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip fetch "https://git.savannah.nongnu.org/git/lwip.git" "159e31b689577dbf69cf0683bbaffbd71fa5ee10" ; \
	git -C /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip checkout -f 159e31b689577dbf69cf0683bbaffbd71fa5ee10 ; \
	touch /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip/.git-downloaded ; \
fi
"make" -C /work/riot/RIOT/pkg/lwip
"make" -f /work/riot/RIOT/Makefile.base MODULE=lwip_api -C /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip/src/api
In file included from /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip/src/include/lwip/sys.h:95,
                 from /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip/src/include/lwip/api.h:48,
                 from /work/riot/RIOT/tests/lwip/bin/pkg/native/lwip/src/api/api_lib.c:62:
/work/riot/RIOT/pkg/lwip/include/arch/sys_arch.h:96:16: error: ‘SYS_MBOX_SIZE’ undeclared here (not in a function); did you mean ‘TCPIP_MBOX_SIZE’?
     msg_t msgs[SYS_MBOX_SIZE];      /**< queue for the mbox */
                ^~~~~~~~~~~~~
                TCPIP_MBOX_SIZE
make[2]: *** [/work/riot/RIOT/Makefile.base:85: /work/riot/RIOT/tests/lwip/bin/native/lwip_api/api_lib.o] Error 1
make[1]: *** [Makefile:24: lwip_api] Error 2
make: *** [/work/riot/RIOT/tests/lwip/../../Makefile.include:602: pkg-build-lwip] Error 2
make: Leaving directory '/work/riot/RIOT/tests/lwip'
```

**Comment by aabadie** [comment]
The `doc.txt` file in `pkg/lwip/contrib` should be removed I guess.

**Comment by aabadie** [comment]
After fixing the build issue (by adding the missing SYS_MBOX_SIZE define), all `tests/lwip_*` tests run fine.

**Comment by miri64** [comment]
> There's a "RIOT lwIP port" group name that appears in the top level module goupr list (below packages). And now it doesn't build (I wanted to test `tests/lwip`):

Mhh for me it built locally... Can you retry with a `make distclean` before, please?

**Comment by aabadie** [comment]
> Can you retry with a make distclean before, please?

Still failing. See [here](https://github.com/RIOT-OS/RIOT/pull/12403/files#diff-4d07bad5fc4738d6ca6c3232d3e58d6aR96), `SYS_MBOX_SIZE` is not defined anywhere (removed [here](https://github.com/RIOT-OS/RIOT/pull/12403/files#diff-4d07bad5fc4738d6ca6c3232d3e58d6aL39))

**Comment by miri64** [comment]
I mean

```
[mlenders@sarajevo RIOT]<3 git grep -B 1 PKG_VERSION -- pkg/lwip/Makefile
pkg/lwip/Makefile-# lwIP v2.1.2
pkg/lwip/Makefile:PKG_VERSION=159e31b689577dbf69cf0683bbaffbd71fa5ee10
[mlenders@sarajevo RIOT]<3 cd ../lwip/
[mlenders@sarajevo lwip]<3  git checkout STABLE-2_1_2_RELEASE 
HEAD is now at 159e31b6 Prepare 2.1.2 release
[mlenders@sarajevo lwip]<3 git show --stat 
commit 159e31b689577dbf69cf0683bbaffbd71fa5ee10 (HEAD, tag: STABLE-2_1_2_RELEASE)
Author: Simon Goldschmidt <goldsimon@gmx.de>
Date:   Thu Nov 22 20:57:02 2018 +0100

    Prepare 2.1.2 release

 doc/doxygen/lwip.Doxyfile | 2 +-
 src/Filelists.cmake       | 2 +-
 src/include/lwip/init.h   | 2 +-
 3 files changed, 3 insertions(+), 3 deletions(-)
[mlenders@sarajevo lwip]<3 git grep SYS_MBOX_SIZE | wc -l
0
```

The macro should not be there.

**Comment by miri64** [comment]
Ah, sorry nvm... Apearently that is my own macro... weird that my local test worked though :-/

**Comment by miri64** [comment]
Removed the removal of `SYS_MBOX_SIZE` in the first commit and moved it to the correct grouping in the second. Since this was pretty hard to do in an understandable form as fixup commits, I squashed directly.

File: pkg/lwip/include/arch/sys_arch.h [hunk 1]
```diff
@@ -34,29 +35,69 @@
...
+
+/**
+ * @name    Mailboxes OS abstraction layer definitions
+ * @see     https://www.nongnu.org/lwip/2_1_x/group__sys__mbox.html
+ * @{
+ */
+/**
+ * @brief   Platform specific mailbox type
+ */
+#define SYS_MBOX_SIZE               (8)
```
Comment (aabadie) [inline pkg/lwip/include/arch/sys_arch.h]: The brief description doesn't correspond to the define ;)

**Comment by aabadie** [comment]
> The doc.txt file in pkg/lwip/contrib should be removed

Don't forget to remove this file as well !

**Comment by miri64** [comment]
Addressed comments, I think... Sorry digging in some #11818-related stuff atm and am a bit distracted by that.

File: pkg/lwip/include/arch/sys_arch.h [hunk 2]
```diff
@@ -34,29 +35,69 @@
...
+#define SYS_ARCH_PROTECT(x)         mutex_lock(&x)
+#define SYS_ARCH_UNPROTECT(x)       mutex_unlock(&x)
+#define SYS_ARCH_DECL_PROTECT(x)    mutex_t x = MUTEX_INIT
+/** @} */
 
-typedef mutex_t sys_mutex_t;
-typedef sema_t sys_sem_t;
-typedef kernel_pid_t sys_thread_t;
+/**
+ * @name    Semaphors definitions
```
Comment (aabadie) [inline pkg/lwip/include/arch/sys_arch.h]: Typo here: s/Semaphors/Semaphore/

This is my last comment, you can squash and we are good.

Comment (miri64) [reply pkg/lwip/include/arch/sys_arch.h]: Following the schema of the rest of this file (taking the titles from the lwIP doc and appending "definitions") it should be "Semaphores", but yes will do :-)

**Comment by miri64** [comment]
Squashed.
