### PR TITLE
cpu/esp32: fix and improve UART initialization

### LINKED ISSUE #19138: bug: esp32-wroom-32 some test failures
These esp32-wroom-32 tests fail:

- [ ] tests/log_color
- [ ] tests/log_printfnoformat
- [ ] tests/sys_arduino

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes issue #19138 that was introduced with PR #19100. It contains the following changes to fix the problems and to improve the UART initialization:

- If `LOG_LEVEL` is greater or equal 4, such as in `tests/log_printfnoformat`, the ESP-IDF config function called for the GPIO pins of the UART will output the configuration with `printf` before the `_GLOBAL_REENT` structure is initialized. This causes a crash during system startup. Therefore the initialization by `syscalls_init` must be called by `earlier in the startup procedure.
- Since PR #19100 it is possible to define:
   - other pins for `UART_DEV(0)` than the default pins
   - different `UART_DEV(0)` pins for the bootloader and RIOT
   
   To allow correct reinitialization of the UART pins used by the bootloader as well as their usage for other purposes, the pin usage for the default UART0 pins and the UART pinsused by the bootloader are reset to `_GPIO`. This is done in `uart_system_init` which has to be called earlier in the startup procedure.
- To avoid garbage on reconfiguring the UART console pins, e.g. in initialization of the `arduino` module, pins that are already configured as UART pins must not be initialized.
- To avoid a several msec long LOW pulse resulting in some garbage during the UART initialization, the TX line is set to HIGH and temporarily configured as a pull-up open-drain output before configuring it as a push-pull output.

The PR requires a backport to 2023.1

### Testing procedure

The following tests should work with this PR:
- [ ] `tests/log_color`
- [ ] `tests/log_printfnoformat`
- [ ] `tests/sys_arduino`

### Issues/PRs references

Fixes #19138

### CODE REVIEW

**Comment by maribu** [comment]
At least the log_noformat test was run prior to cancelation and succeeded, so this indeed seems to fix the issue.

**Review by maribu — APPROVED** [review]
bors merge

Code looks good and at least one test previously failing now succeeds in the CI.

File: cpu/esp_common/periph/uart.c [hunk 1]
```diff
@@ -166,30 +168,34 @@ int uart_init(uart_t uart, uint32_t baudrate, uart_rx_cb_t rx_cb, void *arg)
...
-
-    /* try to initialize the pins as GPIOs first */
-    if ((uart_config[uart].txd != GPIO_UNDEF &&
-         gpio_init(uart_config[uart].txd, GPIO_OUT)) ||
-        (uart_config[uart].rxd != GPIO_UNDEF &&
-         gpio_init(uart_config[uart].rxd, GPIO_IN_PU))) {
-        return -1;
-    }
+    assert(uart_config[uart].txd != GPIO_UNDEF);
+    assert(uart_config[uart].rxd != GPIO_UNDEF);
```
Comment (benpicco) [inline cpu/esp_common/periph/uart.c:172]: There are use cases of TX only / RX only UARTs.
This is generally allowed by other UART implementations, e.g sam0_common.

**Comment by benpicco** [comment]
bors cancel

File: cpu/esp_common/periph/uart.c (hunk 1 above)
Comment (gschorcht) [reply cpu/esp_common/periph/uart.c:172]: OK understand, also the ESP8266 has a second UART device which can only be TX.

But this change is not a regression from the previous implementation, which didn't really work for TX-only and RX-only interface, because it didn't handle the TX and RX pin separately.

For now, this PR would fix the problem in the release version. The handling of TX- or RX-only UARTs could be improved as a follow-up.

Comment (benpicco) [reply cpu/esp_common/periph/uart.c:172]: Ok, let’s do that as a follow-up then

bors merge

**Comment by gschorcht** [comment]
Thanks for reviewing and testing.
