### PR TITLE
License pattern fixes

### LINKED ISSUE #392: clean up license headers
There exist various license headers throughout RIOTs sources. Also some files don't have license headers at all.

* Unify all lgpl license headers.
* Unify all 'other license' headers for each `other license`.
* Identify files without licenses, contact their original authors and get them to explicitly license the respective files under the lgplv2. (see #560)

### PR DESCRIPTION
**Pull request by OlegHahm**
fixes #392

### CODE REVIEW

**Comment by authmillenon** [comment]
ACK and go, when Travis agrees.

**Comment by LudwigKnuepfer** [comment]
Uhm, are we allowing gplv2 into RIOT now?

**Comment by OlegHahm** [comment]
Was there ever a reason against it?

**Comment by OlegHahm** [comment]
I mean for a particular board support or driver it should be okay in a single file.

**Comment by kaspar030** [comment]
Uh, I'm with Ludwig here, for the code that ends up on the board we've been only allowing lgplv2 and compatible so far. For the tools it doesn't matter,

**Comment by authmillenon** [comment]
@LudwigKnuepfer 
> Uhm, are we allowing gplv2 into RIOT now?

@kaspar030 
> Uh, I'm with Ludwig here, for the code that ends up on the board we've been only allowing lgplv2 and compatible so far. For the tools it doesn't matter,

Well, with `boards/x86-multiboot-common/include/multiboot.h` there is already a GPLv2 file in here ;-)

**Comment by Kijewski** [comment]
[Here](https://www.gnu.org/software/grub/manual/multiboot/html_node/multiboot_002eh.html) is a newer release of multiboot.h with an MIT license.

**Comment by kaspar030** [comment]
> Well, with boards/x86-multiboot-common/include/multiboot.h there is already a GPLv2 file in here ;-)

Not that the license would matter for a header. ;-)

**Comment by authmillenon** [comment]
\o/ then let's take out the GPLv2 pattern of this PR and change multiboot with the updated version in another PR.

**Comment by authmillenon** [comment]
@Kijewski are you free to do that?

**Comment by Kijewski** [comment]
@authmillenon, nope not right now, sorry. But ping me if some code needs to be adapted for the new file.

**Comment by authmillenon** [comment]
I have no capabilities right now either… :(

**Comment by OlegHahm** [comment]
Slackers!

**Comment by OlegHahm** [comment]
Updated the header.

File: boards/x86-multiboot-common/include/multiboot.h [hunk 1]
```diff
@@ -32,107 +36,198 @@
 extern "C" {
 #endif
 
-#define MULTIBOOT_HEADER_MAGIC 0x1BADB002 /**< The magic number for the Multiboot header. */
-#define MULTIBOOT_HEADER_FLAGS 0x00010003 /**< The flags for the Multiboot header. */
-#define MULTIBOOT_HEADER_CHECKSUM (-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS)) /**< The checksum for the Multiboot header.  */
```
Comment (authmillenon) [inline boards/x86-multiboot-common/include/multiboot.h]: If I see this correctly there is no replacement for this.

**Comment by authmillenon** [comment]
How can I test this replacement works?

File: boards/x86-multiboot-common/include/multiboot.h (hunk 1 above)
Comment (OlegHahm) [inline boards/x86-multiboot-common/include/multiboot.h]: That's correct.

**Comment by OlegHahm** [comment]
I don't know. I simple tried `default` example on i386-qemu, but the shell seems to be broken anyway.

**Comment by authmillenon** [comment]
Confirmed (might be because it does not implement `uart_stdio`?). ACK. Please squash

**Comment by OlegHahm** [comment]
squashed

File: boards/x86-multiboot-common/startup.c [hunk 2]
```diff
@@ -52,7 +52,7 @@ extern const multiboot_header_t multiboot_header __attribute__((section("._multi
 const multiboot_header_t multiboot_header = {
     .magic = MULTIBOOT_HEADER_MAGIC,
     .flags = MULTIBOOT_HEADER_FLAGS,
-    .checksum = MULTIBOOT_HEADER_CHECKSUM,
+    .checksum = (-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS)),
```
Comment (A-Paul) [inline boards/x86-multiboot-common/startup.c]: Maybe

> #ifndef MULTIBOOT_HEADER_CHECKSUM
#define MULTIBOOT_HEADER_CHECKSUM = (-(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS))
#endif

at top of file and still use the macro?

Comment (OlegHahm) [inline boards/x86-multiboot-common/startup.c]: Actually, I wrote this intentionally as is to avoid similarities to the GPL version. (I know that legally this is rather useless.)

**Comment by LudwigKnuepfer** [comment]
The purpose of the license checker is to warn about files with non-compatible licenses.
Of course we are at liberty to ignore this warning in certain situations, but in order to  not let RIOT become riddled with non-compatible parts we need the checker to continue warning us.

**Comment by authmillenon** [comment]
> Not that the license would matter for a header. ;-)

As far as my copyright knowledge goes (which is not much I have to say) the documentation needs also be freed from the authors copyright via the license. Otherwise, the sole copyright lies with the author and we wouldn't be able to take the documentation for our own. INAL, but regarding this: yes, license in a header *does* matter.

**Comment by OlegHahm** [comment]
> The purpose of the license checker is to warn about files with non-compatible licenses.

But GPLv2 is compatible with LGPLv2.

**Comment by authmillenon** [comment]
This PR doesn't introduce GPLv2 checks so I merge now.

**Comment by kaspar030** [comment]
> > The purpose of the license checker is to warn about files with non-compatible licenses.
> 
> But GPLv2 is compatible with LGPLv2.

Have to be careful with those statements. Distributing binaries with GPLv2 inside requires the whole code to be distributed as GPLv2. In this case, GPLv2 is viral. I don't think that's what most people expect when talking about "compatibility" of licenses.

**Comment by OlegHahm** [comment]
> Distributing binaries with GPLv2 inside requires the whole code to be distributed as GPLv2.

That's why I wrote "I mean for a particular board support or driver it should be okay in a single file." Particular for the qemu (or native) support, I don't see reasons against GPL.

> In this case, GPLv2 is viral. 

Is there any case where GPL is not viral?

> I don't think that's what most people expect when talking about "compatibility" of licenses.

The stupidity of the mass is not my fault. ;)
