### PR TITLE
sc_random: use a default seed if no xtimer is present

### LINKED ISSUE #4639: Building with module "random" requires building with "xtimer" also to succeed.
Building with just "random" results in the following error:

```sys/shell/commands/sc_random.c: In function '_random_init':
sys/shell/commands/sc_random.c:51:5: error: 'initval' may be used uninitialized in this function [-Werror=maybe-uninitialized]
     genrand_init(initval);```

### PR DESCRIPTION
**Pull request by cgundogan**
Use a default seed if no `xtimer` is present and no seed is passed to `random_init`

fixes #4639

### CODE REVIEW

**Comment by haukepetersen** [comment]
Better idea: just print an error message in case no argument given and no xtimer present - I mean it's a shell command after all...

**Comment by haukepetersen** [comment]
ACK

File: sys/shell/commands/sc_random.c [hunk 1]
```diff
@@ -40,7 +40,9 @@ int _random_init(int argc, char **argv)
         printf("PRNG initialized to current time: %d\n", initval);
 #else
         (void)initval;
-        printf("xtimer module not compiled in, can't initialize by time.\n");
+        printf("xtimer module not compiled in, can't initialize by time.\n"
```
Comment (BytesGalore) [inline sys/shell/commands/sc_random.c]: how about `puts`?

**Comment by cgundogan** [comment]
@BytesGalore I replaced printf with puts and amended the change

**Comment by BytesGalore** [comment]
ACK, merge at will

**Comment by authmillenon** [comment]
Needs rebase due to #3309
