### PR TITLE
gnrc: Fix #3597 (multi-hop ping)

### LINKED ISSUE #3597: Multi-Hop ping6 broken
Given the following scenario on the IoT-Lab testbed:

Node 1 configured to have IPv6 address: `abcd::1` and `fe80::1`.
Node 2 configured to have IPv6 address: `abcd::2` and `fe80::2`.
Node 3 configured to have IPv6 address: `abcd::3` and `fe80::3`.

Furthermore, the following routes are configured manually in the fib:
Node 1:
```
fibroute
abcd::2 via fe80::2
fe80::2 via fe80::2
abcd::3 via fe80::3
fe80::3 via fe80::3
```
Node 2:
```
fibroute
:: via fe80::1
```
Node 3:
```
fibroute
:: via fe80::1
```

Then:
`ping6 abcd::1` from Node 2 **does work** as expected.
`ping6 abcd::2` from Node 1 **does work** as expected.
`ping6 abcd::1` from Node 3 **does work** as expected.
`ping6 abcd::3` from Node 1 **does work** as expected.
`ping6 abcd::3` from Node 2 **does not work** (100% packet loss).
`ping6 abcd::2` from Node 3 **does not work** (100% packet loss).

### PR DESCRIPTION
**Pull request by authmillenon**
Fixes #3597 

Less invasive alternative to #3622.

### CODE REVIEW

**Comment by OlegHahm** [comment]
I would still strongly argue for splitting next-hop and neighbor cache lookup into separate functions. Even more splitting of this function would be beneficial.

File: sys/net/network_layer/ng_ipv6/ng_ipv6.c [hunk 1]
```diff
@@ -689,6 +689,7 @@ static void _receive(ng_pktsnip_t *pkt)
             ipv6->next = pkt;           /* reorder for sending */
             pkt->next = NULL;
             _send(ipv6, false);
+            return;
```
Comment (OlegHahm) [inline sys/net/network_layer/ng_ipv6/ng_ipv6.c]: Ah, that was probably the cause for the segfaults I saw yesterday.

**Comment by OlegHahm** [comment]
The fix itself **looks** good. Will test now

**Comment by OlegHahm** [comment]
Confirmed working. ACK

**Comment by authmillenon** [comment]
Squashed.

**Comment by OlegHahm** [comment]
Please squash.
