### PR TITLE
gnrc_ipv6_nib: fix inconsistent ABR valid lifetime representation

### LINKED ISSUE #17512: gnrc/ipv6nib: Something seems strange happend around that valid_until
#### Description

while replacing the evtimer-minutes #17411 in gnrc/ipv6nib: i found it read somehow strange.

if there is no/0  ltime in an abr packed it is assument to be 10000 and the (ev)timer is set accordingly but the valid until time isn't set to now + 10000 but to 0. This may lead to a missrepreasentation least if this information is printed using the print function in `sys/net/gnrc/network_layer/ipv6/nib/nib_abr.c` it s miss represented as 10000 minutes left in any case the is a valid until of 0  even though some time might have passed.

This behavior isn't changed by the above mentioned PR -> i will go on with it 

#### See
comments in  #17411

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Fixes inconsistent representation of the ABR valid lifetime as described in #17512.

### Testing procedure
Run a `gnrc_border_router` and a `gnrc_networking` application on a 6LoWPAN-compatible device. `nib abr` should now list the lifetimes correctly and it should be updated to the original 10000min, whenever the BR sends another ABRO.

### Issues/PRs references
Fixes #17512.

### CODE REVIEW

**Review by benpicco — APPROVED** [review]

File: sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c [hunk 1]
```diff
@@ -196,9 +196,17 @@ static gnrc_pktsnip_t *_build_ext_opts(gnrc_netif_t *netif,
...
+
+        /* update valid time */
+        abr->valid_until_ms = evtimer_now_msec() + (
+            SIXLOWPAN_ND_OPT_ABR_LTIME_DEFAULT * MS_PER_SEC * SEC_PER_MIN
+        );
+    }
+    else {
+        ltime_min = _nib_abr_entry_valid_offset(abr);
+    }
     (void)ltime_min;    /* gnrc_sixlowpan_nd_opt_abr_build might evaluate to NOP */
```
Comment (kfessel) [inline sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c:210]: I think this line can be removed (either case of the previous `if` sets `ltime_min`)
