### PR TITLE
cpu/native/can/candev_linux: add check for real can 

### LINKED ISSUE #13309: cpu/native/can: Segmentation fault when manipulating vcan's through socketcan
#### Description
I'm currently preparing a few PR's related to can-drivers and candev test-apps. During development, I experienced segmentation faults when executing the `_init()` for the native candriver. 
I traced them back to the `can_do_xxx()` calls of libsocketcan. To rule out an issue with libsocketcan, I made a small C-file with only these functions, and compiled it with gcc: the functions return -1 or 0. This is what they should do according to the spec.
When I move the same code to a RIOT example, I get the segmentation fault again. 
This was odd... is libsocketcan incompatible with RIOT for some reason? 
No... Because conn_can also uses it. I tried to figure out what other stuff conn_can does, in order to make the socketcan-calls possible (e.g. auto_init_can), but I couldn't find anything. Removing the auto_init code from conn_can still made the socketcan functions behave according to spec, and adding the auto_init stuff to the experiment-app still made it segfault. 

After a long search: I found a difference: conn_can starts an (unrelated) thread in main. When removing this thread-start, conn_can also segfaults. 
Well... then there's some initialization done in this thread, right? Well... no... When I replace this thread with ONLY a `return 0`, it still works without a segfault! I'm really puzzled about this...
Same in the experiment-app: it works when I start a thread that only returns 0...

Regardless of the above behavior, I did some more research, and my current hypothesis is that it has to do with the `vcan`. I think the segfaults occur when you use these functions to send physical commands to virtual interfaces. Why this hypothesis?
- The issue only occurs when the interface is a `vcan`, not a `can`. (Have to admit: when testing, one time it also happened when a regular can was used, but I wasn't able to reproduce it anymore afterwards, so my guess it was a different issue)
- In the conn_can readme, on line 114, it says you can not set a bitrate on `vcan`'s. The functions that cause the segfault are only used in the `_set_bitrate()` function in conn_can.
- In cpu/native/can/candev_native.c in the _set() function (line 295) when you're trying to set the bittimings, it will do a check first if the can-interface is a `vcan` or real `can`. If it's not a real can, it will give an error and return EINVAL. However, this check is NOT done when the same function is called from `_init`.
- In [this](https://blog.mbedded.ninja/programming/operating-systems/linux/how-to-use-socketcan-with-c-in-linux/) page, they mention: "Warning Although libsocketcan seems to work fine for physical CAN interfaces (e.g. can0), I have had issues when using it with a virtual CAN interface (e.g. vcan0). Specifically, functions such as can_get_state() do not seem to work correctly."

The solution I propose is doing the same check for virtual-devices as is done in the `_set()` function in the `_init()` function. I tested this, and it appears to work perfectly. (Not only tested this in the experiment-app, but also in the candev-test-app for which I'm preparing a PR)

Even though this fixes the issue, it does not explain why creating an empty thread also solves this issue... 
Also: it does not explain why it works when I compile the same script with plain gcc and run it. can or vcan, I wasn't able to ever get a segmentation fault there... 

That's why I opened this Issue before opening a PR for this patch, because I'm not 100% sure if my hypotheses is correct. Maybe there's a bigger issue (in RIOT? In thread.h? In libsocketcan?) present, and by applying this patch we're simply curing the symptoms instead of the cause.

#### Steps to reproduce the issue
- Install libsocketcan (see README of conn_can, it contains a guide on installing it in a way that works with RIOT)
- Run [this](https://github.com/wosym/RIOT/blob/experiment_libsocketcan/examples/libsocketcantest/main.c) experiment-app (You can uncomment line 7 to add the magic-fix).
 --> It will segfault (at least on my computer it did. Tested both on Arch and Ubuntu)

#### Expected results
The functions should (probably) fail in this case, returning -1. They return 0 when they succeed. 

#### Actual results
Segmentation fault when any of the `can_do_xxx()` functions are called.

#### Versions
OS: Arch and Ubuntu 18.04
Build environment: gcc 9.2.0

### PR DESCRIPTION
**Pull request by wosym**
# Contribution description

This is the fix  I proposed in #13309. Like I said there: it's still up for debate whether this fix is the one we want/need, or if there is something else that needs patching (because it's possible that this patch only suppresses the symptoms, and does not address the root cause). 

Anyhow, for me it seems it does not break conn_can (which, as far as I can tell is currently the only app using the code that is altered by this PR), and it does fix the issue for other uses of the candev_native.
Also: it makes this function call consistent with other calls, because the same check is done before these others (see line 305 in candev_linux.c).
And even more so: it makes conn_can compliant with its own "rules". 

### Testing procedure
- Run tests/conn_can: it should not be broken after this fix

### Issues/PRs references

Fixes  #13309.

### CODE REVIEW

**Comment by kaspar030** [comment]
@wysman can you elaborate on why and how this fix works?

**Comment by wosym** [comment]
@kaspar030 I guess you meant to tag me instead of wysman?

I wrote down my entire thoughtprocess in #13309. 
In short: 
With libsocketcan you can enable and disable can-interfaces using the can_do_stop/start() functions. This should always return 0 or -1, according to the docs. However, it doesn't (always) do this when the can interface is a virtual one (vcanx). Then segfaults can occur under some (currently still unknown) circumstances. 
The docs don't specify that you're not allowed to use these functions on vcans (and to be honest: I would see no reason why you shouldn't be), but I read other reports on Google of people having issues using these libsocketcan functions on vcans. My guess is that this is more an issue with libsocketcan than with RIOT.
The README of conn_can also mentions this:
`You can also set a bitrate (this won't work on native with vcan, only with real
interfaces`. 
(The set_bitrate function is the function using the faulty functioncalls. )

Also: I think this patch is how it was originally intended I think, because on line 305 the exact same check is done when calling _set_bitrate. It was probably overlooked at the time of writing.

**Comment by kaspar030** [comment]
> I guess you meant to tag me instead of wysman?

Yes :) sorry @wysman.

Thanks for the detailed explanation. Could you add a short comment, as in, `/* only set bitrate on real can interfaces. Not supported on virtual can interfaces ("vcanX") */`?

**Comment by wosym** [comment]
@kaspar030 : Sure, done! 
I added it to both the original check, and to the new one. (Because I think if one place requires the comment, it also requires it the second time such a check is done)
I hope this is ok?

**Comment by vincent-d** [comment]
I didn't remember there was this check already in the code. This looks a bit hacky to me because it relies on the name, and I can create a virtual CAN called `can0`. But I guess we don't have a better solution to check if the interface is a virtual one or a real one.

**Comment by wosym** [comment]
Fair point vincent. Maybe we should add some warning for it in the readme? 
Something along the lines of
`Warning: when using virtual can devices, they must always be named 'vcanX'`

**Comment by wosym** [comment]
@kaspar030 : what do you think? Add the extra warning, or merge straight away?

File: cpu/native/can/candev_linux.c [hunk 1]
```diff
@@ -195,7 +195,11 @@ static int _init(candev_t *candev)
 
     real_bind(dev->sock, (struct sockaddr *)&addr, sizeof(addr));
 
-    _set_bittiming(dev, &candev->bittiming);
+    /* Only set bitrate on real can interfaces.
+     * Not supported on virtual can interfaces ("vcanX") */
+    if (!strncmp(dev->conf->interface_name, "can", strlen("can"))) {
+        _set_bittiming(dev, &candev->bittiming);
```
Comment (benpicco) [inline cpu/native/can/candev_linux.c]: Maybe add
```C
else {
    LOG_INFO("not setting bitrate on virtual can interface %s\n", dev->conf->interface_name);
}
```

so if `udev` devices can devices should now follow the same naming scheme as network devices, there is at least a chance of finding out why it broke 😉

Comment (smlng) [reply cpu/native/can/candev_linux.c]: 👍 and maybe change the logic to match the one below in `_set`, i.e. 

```
if (strncmp(dev->conf->interface_name, "can", strlen("can"))) {
    LOG_INFO(...);
}
else {
    _set_bittiming(dev, &candev->bittiming);
}
```

**Comment by smlng** [comment]
otherwise this looks good to me

**Comment by wosym** [comment]
I squashed the commits to make Travis happy. (He complained about the length of the commit-message)
However, now Murdock seems to be complaining, but I'm not sure what's happening:
"dwqw: command timed out"
Is the CI broken somehow? Other PR's seem to be having a similar issue.

File: cpu/native/can/candev_linux.c [hunk 2]
```diff
@@ -195,7 +196,14 @@ static int _init(candev_t *candev)
 
     real_bind(dev->sock, (struct sockaddr *)&addr, sizeof(addr));
 
-    _set_bittiming(dev, &candev->bittiming);
+    /* Only set bitrate on real can interfaces.
+     * Not supported on virtual can interfaces ("vcanX") */
+    if (strncmp(dev->conf->interface_name, "can", strlen("can"))) {
+        LOG_INFO("not setting bitrate on virtual can interface %s\n", dev->conf->interface_name);
```
Comment (smlng) [inline cpu/native/can/candev_linux.c]: I would not mix different types of debug output, i.e. please use `DEBUG` as throughout this file. Also could use same message as below

Comment (wosym) [reply cpu/native/can/candev_linux.c]: Aha, had already thought about it, but I assumed that LOG_INFO did something extra over DEBUG, hence the request to use that type. 
I'll fix it straight away!

Comment (smlng) [reply cpu/native/can/candev_linux.c]: its okay to use `LOG_INFO` and similar in general, but as said I would rather not mix them with `DEBUG`.

**Comment by wosym** [comment]
CI issue seems to be fixed. Ready to ACK?
