### PR TITLE
cpu/esp32: Fixes the maximum packet size of 255 bytes in the esp_eth netdev driver of ESP32 mcu.

### LINKED ISSUE #10594: cpu/esp32: esp_eth is not working correctly for packet size > 255 octets
#### Description

`ping6` from an ESP32 board does not work as expected when different payload lengths are used. Following behavior could be observed:
```
ping6 fe80::345b:6598:1369:5bf4
ping6 fe80::345b:6598:1369:5bf4 189
ping6 2003:c1:e72f:6c40:203b:b247:a518:3c7b
```
work as expected.

But
```
ping6 fe80::345b:6598:1369:5bf4 190
```
gives a timeout while
```
ping6 2003:c1:e72f:6c40:203b:b247:a518:3c7b 1
```
gives the error message `error: malformed address`.

It seems that there is a buffer problem that may also be related to the length of the destination address.

#### Steps to reproduce the issue

Use an ESP32 board and compile it with `esp_eth netdev`, e.g.:
```
USEMODULE=esp_eth make BOARD=esp32-olimex-evb -C examples/gnrc_networking flash
```
Execute ping commands to another host in the same LAN with the commands shown above.

#### Expected results

`ping6` works for different address lengths and different payload sizes.

#### Actual results

Timeout or malformed address errors when `ping6` is used for global unicast addresses used with the size argument or link local addresses are used with more than 189 byte payload length.

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes the following problems:
- Mainly it fixes the problem described in issue #10594 that packets with a size > 255 bytes  cannot be received.
- In addition, it replaces `LOG_ERROR` by `DEBUG` when receive buffer is to small in `_recv` to avoid error messages for an usual case
- In addition, the `_recv` function is restructured to return `-ENOBUFS` if the receive buffer is too small, and in all other cases, the size of the packet or the bytes read.

### Testing procedure

Compile and flash `example/gnrc_networking` for an ESP32 board with an Ethernet interface and activate the `esp_eth` module, e.g.,
```
USEMODULE=esp_eth make flash -C examples/gnrc_networking BOARD=esp32-olimex-evb
```
After flashing, just ping any link local address from RIOT shell with an ICMP data size greater than 255 byte, e.g.
```
ping6 fe80::345b:6598:1369:5bf4 1232
```

### Issues/PRs references

Fixes #10594

### CODE REVIEW

**Comment by gschorcht** [comment]
@TimoRoth It would be interesting whether your ESP Gateway is working with these bug fixes as expected.

**Comment by TimoRoth** [comment]
With this applied I can now ping the gateway itself with a ping size of up to 1434 bytes(which is a packet size of exactly 1500).
And I can ping a client behind the gateway with a ping size of up to 200 bytes, which translates to an ESP-NOW package of exactly 250 bytes.
If I try to ping with 201 bytes I can see one single 246 byte sized ESP-NOW package coming in on the client, but never the second fragment. Same behaviour when pinging from the RIOT shell. Which is weird, because that already worked when I tested it yesterday.
Not an issue with this PR though, the lack of fragmentation support is a different issue entirely.

**Comment by gschorcht** [comment]
> With this applied I can now ping the gateway itself with a ping size of up to 1434 bytes(which is a packet size of exactly 1500).

Not really clear why 1434. ICMPv6 Echo request header has 8 byte and IPv6 header without extensions has 40 bytes. Therefore, I would expect 1452 byte as maximum or missed I something?

> Since your output interface has a MTU of 1280, your ICMPv6 Echo requests should be forwarded only for a data size of 1232 byte if fragmentation is not supported or not allowed.

> If I try to ping with 201 bytes I can see one single 246 byte sized ESP-NOW package coming in on the client, but never the second fragment. Same behaviour when pinging from the RIOT shell. Which is weird, because that already worked when I tested it yesterday.

I checked out your last commit, it works for me as expected. I can ping using ESP-NOW with a data size of up to 1232 byte.

**Comment by gschorcht** [comment]
> Is there a link layer header as well in there?

I don't know, @TimoRoth?.

If Ethernet II frame formatting is used, IPv6 should be directly the payload and should be able to use the whole MTU. If he uses a Linux PC to ping, I would guess this should be the case.

**Comment by TimoRoth** [comment]
I'm using Windows ping, I'm not exactly sure what it does, but when I do "ping -6 -l 1434" the package reaching the esp-eth interface has a size of exactly 1500 bytes. Didn't investigate any further why it's exactly that size.

**Comment by TimoRoth** [comment]
I'm using a VM with Linux. But it does not have access to the Wifi where the router is on, so I need to do that from the Windows host.

Looks like this on Wireshark. Not sure there the extra 4 Byte on the esp-eth end come from.

image

**Comment by gschorcht** [comment]
@TimoRoth Thanks. This is what I supposed, Ethernet II formatted MAC frame with 40 bytes IPv6 header and 8 bytes ICMPv6 echo reply header as payload. The frame size of 1496 on wire includes the 14 bytes Ethernet II header. But, Ethernet II MTU size is always the limit for the payload of the Ethernet frame. That is, usually it should be possible to have 1514 bytes on wire.

**Comment by gschorcht** [comment]
@miri64 May I ask you to review this fix for `esp_eth` netdev driver? It would be great to get it merged as soon as possible.

File: cpu/esp32/esp-eth/esp_eth_netdev.h [hunk 1]
```diff
@@ -37,11 +37,11 @@ typedef struct
...
     netdev_t netdev;                    /**< netdev parent struct */
 
-    uint8_t rx_len;                     /**< number of bytes received */
-    uint8_t rx_buf[ETHERNET_DATA_LEN];  /**< receive buffer */
+    uint16_t rx_len;                     /**< number of bytes received */
+    uint8_t  rx_buf[ETHERNET_DATA_LEN];  /**< receive buffer */
 
-    uint8_t tx_len;                     /**< number of bytes in transmit buffer */
-    uint8_t tx_buf[ETHERNET_DATA_LEN];  /**< transmit buffer */
+    uint16_t tx_len;                     /**< number of bytes in transmit buffer */
```
Comment (miri64) [inline cpu/esp32/esp-eth/esp_eth_netdev.h]: Maybe group the length's together? this might save some bytes of RAM, since the `uint16_t`s don't cause padding then, so that the arrays are aligned.

**Comment by gschorcht** [comment]
Maybe @TimoRoth could it retest even though he already tried the changes https://github.com/RIOT-OS/RIOT/pull/10604#issuecomment-446924240.

**Comment by tcschmidt** [comment]
@PeterKietzmann should also have access to the hardware - and is experienced with the netdev interface.

**Comment by TimoRoth** [comment]
Just tested it again on top of current master.
Pinging the board works great up until the packet size exceeds the MTU, which is to be expected.

**Comment by miri64** [comment]
Then, once my change request is addressed I think we can merge.

**Comment by gschorcht** [comment]
@miri64 Changed

**Comment by gschorcht** [comment]
@miri64 Could you give your ACK for the requested change?

**Comment by gschorcht** [comment]
> Untested ACK.

Thanks. Was tested again by @TimoRoth https://github.com/RIOT-OS/RIOT/pull/10604#issuecomment-450505480
