### PR TITLE
cpu/stm32f4: Fix DMA race bug (#4716)

### LINKED ISSUE #4716: stm32f4: UART DMA causes lockup in xtimer_drift test
Current tests/xtimer_drift in master does not run for me on stm32f4discovery, it hangs after trying to start the first slacker thread.
Disabling DMA in the UART TX by commenting out code seem to make the problem go away.

I suspect there is a race between the main thread using printf/puts right before the thread_create call and the newly created thread also using printf immediately after creation.

### PR DESCRIPTION
**Pull request by gebart**
Fixes #4716 by adding an implicit mutex for all UART writes from thread context.

### CODE REVIEW

File: cpu/stm32f4/periph/uart.c [hunk 1]
```diff
@@ -128,13 +130,15 @@ void uart_write(uart_t uart, const uint8_t *data, size_t len)
...
     else {
+        mutex_lock(&_tx_lock[uart]);
         DMA_Stream_TypeDef *stream = dma_stream(uart_config[uart].dma_stream);
         /* configure and start DMA transfer */
         stream->M0AR = (uint32_t)data;
         stream->NDTR = (uint16_t)len;
         stream->CR |= DMA_SxCR_EN;
         /* wait for transfer to complete */
-        mutex_lock(&tx_sync[uart]);
+        mutex_lock(&_tx_dma_sync[uart]);
```
Comment (DipSwitch) [inline cpu/stm32f4/periph/uart.c]: shouldn't this go before the stream enable? Else it can get unlocked withouth being locked :)

Comment (DipSwitch) [inline cpu/stm32f4/periph/uart.c]: No that is no good eather since you are trying to signal the waiting thread. Is it locked on initialization? Sorry, first coffee ^_^

**Comment by DipSwitch** [comment]
Nevermind the comments, ACK and GO if you ask me.

File: cpu/stm32f4/periph/uart.c (hunk 1 above)
Comment (gebart) [inline cpu/stm32f4/periph/uart.c]: @DipSwitch yes, the mutex is initially locked by `uart_init`. I merely changed the name of the mutex variable to better suit the purpose.

**Comment by gebart** [comment]
Added label and kicked Travis.

**Comment by gebart** [comment]
Travis is happy -> go
