### PR TITLE
gnrc_tftp: Add minimum packet length check

### LINKED ISSUE #10927: gnrc_tftp: Missing minimum length check
#### Description

gnrc_tftp is missing a minimum packet length check in the `_tftp_decode_start` function and might thus perform an out-of-bounds read.

#### Steps to reproduce the issue

On native:

1. Add `USEMODULE += gnrc_pktbuf_malloc` to `examples/gnrc_tftp/Makefile`
2. Build `examples/gnrc_tftp` using `make all-valgrind`
3. Run the application using `make term-valgrind`
4. Start the TFTP server using `tftps start` and wait until it started
5. Send a UDP packet to the server using `printf '\x00\x02' | nc -u '[ip-address%tap0]' 69`

#### Expected results

Valgrind shouldn't report any invalid reads.

#### Actual results

Valgrind reports various invalid reads of size 1.

### PR DESCRIPTION
**Pull request by nmeum**
### Contribution description

Adds a minimum packet length check. If I understand [RFC 1350](https://tools.ietf.org/html/rfc1350) correctly, the shortest valid packet should be:

```
 2 bytes     2 bytes
 ---------------------
| Opcode |   Block #  |
 ---------------------

 Figure 5-3: ACK packet
```

Thus the minimum length of a valid packet should be 4 bytes.

### Testing procedure

See #10927.

### Issues/PRs references

Fixes #10927
See also: #11737 

CC: @smlng

### CODE REVIEW

File: sys/net/gnrc/application_layer/tftp/gnrc_tftp.c [hunk 1]
```diff
@@ -51,6 +51,7 @@ static kernel_pid_t _tftp_kernel_pid;
 
 #define TFTP_TIMEOUT_MSG            0x4000
 #define TFTP_STOP_SERVER_MSG        0x4001
+#define TFTP_MIN_PACKET_LEN         4
```
Comment (miri64) [inline sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: `4U` for portability.

**Comment by PeterKietzmann** [comment]
Green lights

**Comment by miri64** [comment]
CI did not point it out, so I decided to just roll with it.

**Comment by miri64** [comment]
@nmeum can you please provide a backport to 2019.07-branch? You can use the [backport script](https://github.com/RIOT-OS/RIOT/tree/master/dist/tools/backport_pr) for that

**Comment by nmeum** [comment]
Sorry for not responding to your initial feedback was pretty busy this week.

> @nmeum can you please provide a backport to 2019.07-branch? 

Sure, I cherry-picked the commit. See #11850
