### PR TITLE
eclipsesym/cmdline2xml.sh: introduce workaround readlink function

### LINKED ISSUE #4276: dist/tools/eclipsesym: not working under OS X
Hi,

Using `make eclipsesym` doesn't work under OS X. It outputs the following:

```
printf "%s\n" arm-none-eabi-gcc -DDEVELHELP -Werror -DMODULE_AUTO_INIT -DMODULE_CORE -DMODULE_CORTEXM_COMMON -DMODULE_CPU -DMODULE_EMLIB -DMODULE_NEWLIB -DMODULE_PERIPH -DMODULE_PERIPH_COMMON -DMODULE_SYS -DMODULE_TSRB -DMODULE_UART_STDIO -mcpu=cortex-m3 -mlittle-endian -mthumb -mfloat-abi=soft -mno-thumb-interwork -std=gnu99 -Wall -Wstrict-prototypes -Werror=implicit-function-declaration -ffunction-sections -fdata-sections -fno-builtin -fshort-enums -ggdb -g3 -Os -DCOREIF_NG=1 -DCPU_MODEL_EFM32LG990F256 -DCPU_ARCH_CORTEX_M3 -DBOARD_STK3600=\"stk3600\" -DRIOT_BOARD=BOARD_STK3600 -DCPU_EFM32LG=\"efm32lg\" -DRIOT_CPU=CPU_EFM32LG -DMCU_EFM32LG=\"efm32lg\" -DRIOT_MCU=MCU_EFM32LG -fno-delete-null-pointer-checks -Wstrict-prototypes -Werror=strict-prototypes -Wold-style-definition -Werror=old-style-definition -fno-common -Wall -DRIOT_VERSION=\"2015.12-devel-504-gd108-MacBook-van-Bas.lan\" -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/core/include -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/drivers/include -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/sys/include -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/boards/stk3600/include -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/cpu/efm32lg/emlib/inc -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/cpu/efm32lg/include -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/cpu/cortexm_common/include  -I/Users/basilfx/SimplicityStudio/v3_workspace/lib/sys/libc/include  | \
		/Users/basilfx/SimplicityStudio/v3_workspace/lib/dist/tools/eclipsesym/cmdline2xml.sh > /Users/basilfx/SimplicityStudio/v3_workspace/src/eclipsesym.xml
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
readlink: illegal option -- m
usage: readlink [-n] [file ...]
```

I believe it has something to do with OS X `readlink` not being compatible with GNU `readlink`. I have homebrew installed, which installs `greadlink`. If I manually change `readlink` to `greadlink` (in `dist/tools/eclipsesym/cmdline2xml.sh`), the problem is solved for my machine.

Using up-to-date `master` branch with OS X 10.11.

### PR DESCRIPTION
**Pull request by thomaseichinger**
readlink for OS X and FreeBSD does not offer -m flag to canonicalise the
file's path. Implement a workaround shell function to simulate behaviour.

Fixes #4276

### CODE REVIEW

**Comment by thomaseichinger** [comment]
@basilfx Could you give this change a try?

File: dist/tools/eclipsesym/cmdline2xml.sh [hunk 1]
```diff
@@ -26,6 +26,10 @@ if [ $# -ne 0 ]; then
     exit 2
 fi
 
+if [ `uname` == "Darwin" ]|| [ `uname` == "FreeBSD" ]; then
```
Comment (cgundogan) [inline dist/tools/eclipsesym/cmdline2xml.sh]: nit-picking: insert a space between `]`  and `||`

Comment (thomaseichinger) [inline dist/tools/eclipsesym/cmdline2xml.sh]: Nit-pickers are my favourites.

File: dist/tools/eclipsesym/cmdline2xml.sh [hunk 2]
```diff
@@ -26,6 +26,10 @@ if [ $# -ne 0 ]; then
     exit 2
 fi
 
+if [ `uname` == "Darwin" ] || [ `uname` == "FreeBSD" ]; then
+    function readlink () { echo $(cd $(dirname $2); pwd)/$(basename $2); }
```
Comment (Kijewski) [inline dist/tools/eclipsesym/cmdline2xml.sh]: `function name() {…}` is bash'ism and disregarded, because it is not widely compatible. Better is the POSIX variant `name() {…}`.

Also, it shouldn't hurt do use this function in Linux, too, does it? Then you could remove the guard so users of maybe OpenBSD are happy, too.

Comment (thomaseichinger) [inline dist/tools/eclipsesym/cmdline2xml.sh]: @Kijewski addressed, although we use `#! ... bash` anyway for now.

**Comment by basilfx** [comment]
This fixes the issue for me. It generates `eclipsesym.xml` without errors.

**Comment by thomaseichinger** [comment]
@basilfx Great, can you also verify it generates valid/usable files?

**Comment by basilfx** [comment]
The generated file looks OK. I didn't have time to import it, but I will test this tonight.

**Comment by thomaseichinger** [comment]
@basilfx Great, please let us know. Thank you for the effort.

**Comment by basilfx** [comment]
My workaround vs this fix doesn't produce different files. I can import and use both files without problems.

For the record: https://gist.github.com/basilfx/e4dfdd42ab26e8c8e6c0/revisions (note that revision 2 doesn't list any changes).

**Comment by thomaseichinger** [comment]
@basilfx Thanks for verifying.
@Kijewski @cgundogan @gebart Do I hear an ACK? (Travis does not test this anyway so we shouldn't bother him)

**Comment by daniel-k** [comment]
Didn't test and I'm not sure if this may be needed somewhere, but your `readlink` implementation doesn't resolve/follow symlinks and `..` anymore:

```
daniel:/tmp $ readlink () { echo $(cd $(dirname $1); pwd)/$(basename $1); }
daniel:/tmp $ readlink ..
/tmp/..
```

vs. linux readlink
```
daniel:/tmp $ readlink -m ..
/
```

Just saw this and wanted to share.

**Comment by thomaseichinger** [comment]
@daniel-k You are right. On my system this however only occurs with `..` as suffix. If it is in the path somewhere in-between it works for me. Could you check? I'd argue that for this use case the suffix will be something with `*/include`.

**Comment by daniel-k** [comment]
> @daniel-k You are right. On my system this however only occurs with `..` as suffix. If it is in the path somewhere in-between it works for me. Could you check?

Same for me if I remember correctly. I've always used `readlink -f` for cases where my scripts should also run on Mac OSX.

**Comment by thomaseichinger** [comment]
You mean `stat -f `? `readlink` only supports `-n` on OS X.

**Comment by daniel-k** [comment]
Okay strange, maybe this changed or it really never worked on OS X :smile:  I really meant `readlink -f`. But then nevermind. If it works for this use-case, keep it. I'm not too involved with this script anyway, just stumbled upon this PR.

**Comment by thomaseichinger** [comment]
@gebart Are you ok with these changes?

**Comment by cgundogan** [comment]
tested on Arch and `make eclipsesym` produces the same output with and without this patch.
Also verified on @thomaseichinger's OS X machine that without this patch `make eclipsesym` is broken.

ACK. Let's wait for travis and merge when green

**Comment by cgundogan** [comment]
squash please

**Comment by thomaseichinger** [comment]
Squashed. @cgundogan the changes is not tested in any way by Travis. Should we skip it?

**Comment by cgundogan** [comment]
Sure you are right. GO
