### PR TITLE
native: workaround for thread_t name collision

### LINKED ISSUE #4973: thread_t is already defined by OS X
Compiling native platform on OS X (10.11.3) results in the following error:

```
~/src/RIOT/core/include/sched.h:98:24: error: typedef redefinition with different types
      ('struct _thread' vs 'mach_port_t' (aka 'unsigned int'))
typedef struct _thread thread_t;
                       ^
/usr/include/mach/mach_types.h:119:22: note: previous definition is here
typedef mach_port_t             thread_t;
```

#4578 renames `tcb_t` to `thread_t`.

Dependency graph:

`cpu/native/periph/timer.c → mach/mach_host.h → mach/mach_types.h`

Possible fixes:

- rename to `tcb_t`
- rename to `riot_thread_t`
- rename to `thrd_t`
- rename to `process_t`
- `#define thread_t riot_thread_t` in sched.h
- other?

### PR DESCRIPTION
**Pull request by Yonezawa-T2**
Fixes #4973.
Implements @Kijewski's idea.

### CODE REVIEW

File: cpu/native/periph/timer.c [hunk 1]
```diff
@@ -27,6 +27,8 @@
 #include <mach/mach_init.h>
 #include <mach/mach_port.h>
 #include <mach/mach_host.h>
+/* Both OS X and RIOT typedef thread_t. timer.c does not use either thread_t. */
+#define thread_t riot_thread_t
```
Comment (authmillenon) [inline cpu/native/periph/timer.c]: Shouldn't this rather be `mac_thread_t`? Yes, this file doesn't use either, but at least the type shoult point to the right implementation ;-).

Comment (Yonezawa-T2) [inline cpu/native/periph/timer.c]: Do you mean this?
```C
/* Both OS X and RIOT typedef thread_t. timer.c does not use either thread_t. */
#define thread_t mac_thread_t
#include <mach/clock.h>
#include <mach/mach_init.h>
#include <mach/mach_port.h>
#include <mach/mach_host.h>
#undef thread_t
```

Comment (authmillenon) [inline cpu/native/periph/timer.c]: Now I'm confused... I thought one of the headers above includes OSX's `thread_t` and you are redefining it in this line.

Comment (Kijewski) [inline cpu/native/periph/timer.c]: @authmillenon defines work for latter code, not prior. The name `riot_thread_t` makes sense, because the latter declaration (our thread_t) is renamed, not the prior (OSX's thread_t).

Comment (Yonezawa-T2) [inline cpu/native/periph/timer.c]: `#define thread_t riot_thread_t` means “replace every occurrence of `thread_t` after this line to `riot_thread_t`”, so it replaces `typedef struct _thread thread_t;` in `RIOT/core/include/sched.h` to `typedef struct _thread riot_thread_t;` because `sched.h` is included after the line.

The essence of the problem is:
```C
/* mach_types.h */
typedef mach_port_t             thread_t;

/* sched.h */
typedef struct _thread thread_t;
```

This PR works around by:
```C
/* mach_types.h */
typedef mach_port_t             thread_t;

#define thread_t riot_thread_t

/* sched.h */
typedef struct _thread thread_t;
```

that results in:

```C
/* mach_types.h */
typedef mach_port_t             thread_t;

/* sched.h */
typedef struct _thread riot_thread_t;
```

Comment (authmillenon) [inline cpu/native/periph/timer.c]: Got it! :)

**Comment by authmillenon** [comment]
ACK & go when Murdock is happy
