### PR TITLE
tests/thread_flood: account for all threads already in use

### LINKED ISSUE #14180: Test thread_flood is failing since we have a new thread "usbus"
#### Description
Test thread_flood is a simple test to see if the maximum number of tests can be created. It counts the number of threads created and subtracts two (for "main" and "idle") and checks if that counts up to `MAXTHREADS`. However we now can also have a thread for "usbus", so the test is not correct anymore.

#### Steps to reproduce the issue
```
BOARD=sodaq-autonomo make -C tests/thread_flood flash term
```
This can be any board with USBUS.

#### Expected results
```
[SUCCESS] created 30
```

#### Actual results
```
[ERROR] expected 30, created 29

### PR DESCRIPTION
**Pull request by keestux**
Before there were only two: "main" and "idle". But now there can also be
a thread for "usbus". The code will now first count how many there are in
use when the tests starts. It subtracts that number from MAXTHREADS.

This resolves issue #14180 (fixes #14180)

### CODE REVIEW

File: tests/thread_flood/main.c [hunk 1]
```diff
@@ -39,7 +39,15 @@ int main(void)
 {
     kernel_pid_t thr_id = KERNEL_PID_UNDEF;
     unsigned thr_cnt = 0;
+    unsigned thr_in_use = 0;
 
+    for (kernel_pid_t ix = KERNEL_PID_FIRST; ix <= KERNEL_PID_LAST; ix++) {
+        volatile thread_t *thread;
+        thread = thread_get(ix);
+        if (thread) {
```
Comment (aabadie) [inline tests/thread_flood/main.c:47]: It also works with the following:
```suggestion
        if (thread_get(ix)) {
```
Is `volatile` really needed and, if yes, why ?

Comment (keestux) [reply tests/thread_flood/main.c]: Ah the volatile. I would be happy if these get removed, as in PR #11073
But it seems nobody dares to touch it.

Anyway, I've made a change to remove that variable

**Comment by keestux** [comment]
There are more tests suffering from this, e.g. `tests/cond_order`. Perhaps we can collect corrections for all of them

**Comment by keestux** [comment]
And `tests/cpp11_thread`
```
/* http://en.cppreference.com/w/cpp/thread/thread */
int main() {
  puts("\n************ C++ thread test ***********");

  expect(sched_num_threads == 2); // main + idle
```

File: tests/thread_flood/main.c (hunk 1 above)
Comment (keestux) [reply tests/thread_flood/main.c]: I've cleaned up this initial loop because there is a `sched_num_threads` which already gives what we want.

**Comment by keestux** [comment]
Can I add more fixes to this PR to solve similar problems? I have fixes for `tests/cond_order`, `tests/mutex_order` and `tests/cpp11_thread`.

**Comment by kaspar030** [comment]
> Can I add more fixes to this PR to solve similar problems? I have fixes for `tests/cond_order`, `tests/mutex_order` and `tests/cpp11_thread`.

rather open individual PRs, faster to test.

BTW, #14224 also needs this!

**Comment by kaspar030** [comment]
`tests/rmutex` is also affected.

**Comment by kaspar030** [comment]
I used this to test: https://github.com/RIOT-OS/RIOT/pull/14227

Works with dummy thread and this PR, fails with dummy thread on master.

ACK.
