### PR TITLE
cpu/arm: fixes necessary for toolchain upgrade

### LINKED ISSUE #13434: drivers/bmx280: CI should fail, but apparently doesn't?
#### Description
When I compile tests/driver_bmx280, I get several compiler errors notifying me of arrays going out of bounds in the _read_calibration_data function in drivers/bmx280/bmx280.c
When I check this file, as far as I can tell, these errors are justified:
BMX280_DIG_P9_LSB_REG = 0x9E
OFFSET_TP(x) is (x - CALIB_T_P_BASE)
CALIB_T_P_BASE = BMX280_DIG_T1_LSB_REG = 0x88
--> maximum offset = 0x9E - 0x88 = 0x16 = 0d22

The buffer which gets read has a size of CALIB_T_P_LEN, which is defined as 17. 
17 < 22, so we definitely read out of the defined array size. (Even more so, because the array is read by offset+1.

So the errors my compiler spews out seem justified to me. However... The CI does not appear to complain about this. One might say that this is a CI issue, but... When I mentioned this issue on IRC, @benpicco said he did not experience this behavior when he tried to compile the exact same program.

Maybe this is because of a gcc version mismatch? In any case, to me it feels like it's important that the compiler (or CI, because we don't have control over what compiler people use) at least warns us of these types of errors. 
 
#### Steps to reproduce the issue
compile /tests/driver_bmx280 with the default board.

#### Expected results
The CI should notify us of the errors.

#### Actual results
On my machine? Exactly what I would expect.
On the CI (and some other machines?): no errors.

#### Versions
```
Operating System Environment
----------------------------
         Operating System: "Arch Linux" 
                   Kernel: Linux 5.4.3-arch1-1 x86_64 unknown
             System shell: GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)
             make's shell: GNU bash, version 5.0.11(1)-release (x86_64-pc-linux-gnu)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (GCC) 9.2.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
                  avr-gcc: avr-gcc (GCC) 9.2.0
         mips-mti-elf-gcc: missing
               msp430-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: missing

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.1.0"
      mips-mti-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                   ccache: missing
                    cmake: missing
                 cppcheck: missing
                  doxygen: 1.8.16
                      git: git version 2.24.1
                     make: GNU Make 4.2.1
                  openocd: Open On-Chip Debugger 0.10.0
                   python: Python 3.8.0
                  python2: Python 2.7.17
                  python3: Python 3.8.0
                   flake8: error: /usr/bin/python3: No module named flake8
               coccinelle: missing
```

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

The ARM toolchain upgrade (https://github.com/RIOT-OS/riotdocker/pull/78) slipped through some new compiler warnings (which turn into errors now).

This PR tries to fix them.

### Issues/PRs references

Fixes #13434.

### CODE REVIEW

**Comment by kaspar030** [comment]
Fixes these:

- https://ci.riot-os.org/RIOT-OS/RIOT/13455/9b4dac7f3e6ed8ce831e305bf1b0f2d82b526544/output/compile/tests/driver_bmx280/blackpill-128kib:gnu.txt

- https://ci.riot-os.org/RIOT-OS/RIOT/13415/442ddc134673afb72a23e8c258c9a6d2e7d76795/output/compile/examples/openthread/samr21-xpro:gnu.txt

**Comment by kaspar030** [comment]
I whish there was a "high priority" option in Murdock...

File: drivers/bmx280/include/bmx280_internals.h [hunk 1]
```diff
@@ -113,7 +113,7 @@ extern "C" {
  * @{
  */
 #define CALIB_T_P_BASE                  (BMX280_DIG_T1_LSB_REG)
-#define CALIB_T_P_LEN                   (17U)
+#define CALIB_T_P_LEN                   (32U) /* might be larger than neeeded */
```
Comment (aabadie) [inline drivers/bmx280/include/bmx280_internals.h]:
```suggestion
#define CALIB_T_P_LEN                   (32U) /* might be larger than needed */
```

Comment (kaspar030) [inline drivers/bmx280/include/bmx280_internals.h]: previous value was "17". The highest accessed index that popped up int the warning was "23". I chose 32 as the next highest power of two, on stack it would probably have chosen "24".

**Comment by kaspar030** [comment]
@RIOT-OS/ci @RIOT-OS/maintainers pls ACK. :)

**Comment by benpicco** [comment]
This will also fix #13434

**Comment by kaspar030** [comment]
> This will also fix #13434

There it is, didn't find the issue.

File: drivers/bmx280/include/bmx280_internals.h (hunk 1 above)
Comment (benpicco) [reply drivers/bmx280/include/bmx280_internals.h]: > The 8-bit registers are named calib00...calib41 and are stored at memory addresses 0x88...0xA1 and 0xE1...0xE7.

so 26 should do

File: drivers/bmx280/include/bmx280_internals.h [hunk 2]
```diff
@@ -113,7 +113,7 @@ extern "C" {
  * @{
  */
 #define CALIB_T_P_BASE                  (BMX280_DIG_T1_LSB_REG)
-#define CALIB_T_P_LEN                   (17U)
+#define CALIB_T_P_LEN                   (32U) /* might be larger than needed */
```
Comment (bergzand) [inline drivers/bmx280/include/bmx280_internals.h]: If I'm correct this should be `0x17` or `0d22`. But we can change that in a follow-up with some more thorough testing. `32U` should definitely be enough.

File: drivers/bmx280/include/bmx280_internals.h (hunk 1 above)
Comment (bergzand) [reply drivers/bmx280/include/bmx280_internals.h]: If I'm correct this should be 0x17 or 0d22. But we can change that in a follow-up with some more thorough testing. 32U should definitely be enough.

**Comment by kaspar030** [comment]
There's still this:
```
/home/kaspar/src/riot/tests/unittests/tests-core/tests-core-atomic.c: In function 'test_atomic_inc_negative':
/home/kaspar/src/riot/tests/unittests/tests-core/tests-core-atomic.c:53:1: error: insn does not satisfy its constraints:
   53 | }                                                        
      | ^                                                        
(insn 145 144 146 4 (set (reg:SI 3 r3 [139])          
        (plus:SI (reg:SI 12 ip [orig:110 _1 ] [110])
            (const_int 1 [0x1]))) "/home/kaspar/src/riot/tests/unittests/tests-core/tests-core-atomic.c":50:9 811 {*thumb1_addsi3}
     (nil))                                                      
during RTL pass: cprop_hardreg                                   
/home/kaspar/src/riot/tests/unittests/tests-core/tests-core-atomic.c:53:1: internal compiler error: in extract_constrain_insn, at r
ecog.c:2211                                                      
Please submit a full bug report,        
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
make[2]: *** [/home/kaspar/src/riot/Makefile.base:110: /home/kaspar/src/riot/tests/unittests/bin/saml11-xpro/tests-core/tests-core-
atomic.o] Error 1                                                                                                                  
```

... when compiling the unittests for saml11-xpro...

I propose blacklisting until we have a fix.

File: tests/unittests/Makefile [hunk 3]
```diff
@@ -1,6 +1,9 @@
 DEVELHELP ?= 0
 include ../Makefile.tests_common
 
+# temporarily disable building, see #13456.
+BOARD_BLACKLIST := saml11-xpro
```
Comment (benpicco) [inline tests/unittests/Makefile]:
```suggestion
BOARD_BLACKLIST := saml10-xpro saml11-xpro
```

Comment (benpicco) [inline tests/unittests/Makefile]: Or better yet
```suggestion
FEATURES_BLACKLIST += cortex-m23
```

**Comment by kaspar030** [comment]
> cortex-m23

not exposed as arch feature :(

**Comment by kaspar030** [comment]
> /home/kaspar/src/riot/tests/unittests/tests-core/tests-core-atomic.c:53:1: internal compiler error: in extract_constrain_insn, at recog.c:2211

Sometimes I wonder, if RIOT's cute little compile test exposes something like this, what's gcc's or ARM's CI compiling?

File: drivers/bmx280/include/bmx280_internals.h (hunk 1 above)
Comment (benpicco) [reply drivers/bmx280/include/bmx280_internals.h]: Reading the data sheets, it should be ~~26~~ 24 (last byte is reserved) for both [bmp280](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmp280-ds001.pdf) and [bme280](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bme280-ds002.pdf)

Comment (benpicco) [reply drivers/bmx280/include/bmx280_internals.h]: Since those are turned into register reads, I'd rather not read additional random registers without knowing if there might be some effect on-read.

Comment (kaspar030) [reply drivers/bmx280/include/bmx280_internals.h]: Ok, let's merge as is then I open a PR for the correct value?

Comment (benpicco) [reply drivers/bmx280/include/bmx280_internals.h]: Why not use the right value right away?

Comment (bergzand) [reply drivers/bmx280/include/bmx280_internals.h]: > Why not use the right value right away?

Because it will block all PRs for another 20 minutes :|

Comment (bergzand) [reply drivers/bmx280/include/bmx280_internals.h]: > Ok, let's merge as is then I open a PR for the correct value?

Yes please!

**Comment by kaspar030** [comment]
Thanks everyone!

**Comment by benpicco** [comment]
Looks like this also needs a backport, otherwise other packports are failing CI.

**Comment by fjmolinas** [comment]
> Looks like this also needs a backport, otherwise other backports are failing CI.

@kaspar030 @benpicco are there other toolchain changes since the last release? I do not like the fact that whatever we are backporting will be tested with a different toolchain.

**Comment by fjmolinas** [comment]
Backport provided in #13536
