### PR TITLE
ng_sixlowpan: fix #3588

### LINKED ISSUE #3588: Receiving of fragmented 6LoWPAN UDP packets does not work
See pcap here, send by Linux: https://www.cloudshark.org/captures/980bc3eb4583

Which produces log messages (6lo and ipv6) as follows:
```
2015-08-07 23:34:00,448 - INFO # > 6lo: NG_NETDEV_MSG_TYPE_RCV received
2015-08-07 23:34:00,451 - INFO # 6lo: received 6LoWPAN fragment
2015-08-07 23:34:00,453 - INFO # 6lo rbuf: 1st fragment.
2015-08-07 23:34:00,456 - INFO # 6lo: waiting for incoming message.
2015-08-07 23:34:05,454 - INFO # 6lo: NG_NETDEV_MSG_TYPE_RCV received
2015-08-07 23:34:05,457 - INFO # 6lo: waiting for incoming message.
2015-08-07 23:34:05,460 - INFO # ipv6: NG_NETAPI_MSG_TYPE_RCV received
2015-08-07 23:34:05,470 - INFO # ipv6: Received (src = fe80::c07d:1441:7d0d:9fef, dst = fe80::5855:5f70:108b:c07e, next header = 58, length = 40)
2015-08-07 23:34:05,473 - INFO # ipv6: handle ICMPv6 packet (nh = 58)
2015-08-07 23:34:05,476 - INFO # ipv6: forward nh = 58 to other threads
2015-08-07 23:34:05,482 - INFO # ipv6: unable to forward packet as no one is interested in it
2015-08-07 23:34:05,485 - INFO # ipv6: waiting for incoming message.
2015-08-07 23:34:05,488 - INFO # ipv6: NG_NETAPI_MSG_TYPE_SND received
2015-08-07 23:34:05,493 - INFO # ipv6: set payload length to zu (network byteorder 0018)
2015-08-07 23:34:05,496 - INFO # ipv6: set next header to 58
2015-08-07 23:34:05,500 - INFO # ipv6: set packet source to fe80::5855:5f70:108b:c07e
2015-08-07 23:34:05,504 - INFO # ipv6: calculate checksum for upper header.
2015-08-07 23:34:05,507 - INFO # ipv6: removed old interface header
2015-08-07 23:34:05,510 - INFO # ipv6: add interface header to packet
2015-08-07 23:34:05,513 - INFO # ipv6: send unicast over interface 7
2015-08-07 23:34:05,516 - INFO # ipv6: send to 6LoWPAN instead
2015-08-07 23:34:05,519 - INFO # 6lo: NG_NETDEV_MSG_TYPE_SND received
2015-08-07 23:34:05,523 - INFO # 6lo: iface->max_frag_size = 102 for interface 7
2015-08-07 23:34:05,527 - INFO # 6lo: Send SND command for 0x200025d4 to 7
```

It's current master, only added the ```6lo rbuf: 1st fragment``` line to see what code is executed.
The packet is never passed to my UDP server thread listening for it. For packets build from a single frame, they are passed to the UDP server thread.

### PR DESCRIPTION
**Pull request by authmillenon**
Fixes #3588.

### CODE REVIEW

**Comment by OlegHahm** [comment]
Can you be a bit more verbose, about what this PR does? ;)

**Comment by authmillenon** [comment]
This PR changes gnrc's 6LoWPAN implementation in that manner that for fragmented IPHC frames the datagram size and offset's are of the uncompressed IPv6 packet and not the IPHC frame. As such, the IPHC dispatch gets decoded directly when the first fragment is received, rather than after the frame is reassembled. For this the API of both `ng_sixlowpan_frag` and `ng_sixlowpan_iphc` needed some adaption, too.

**Comment by OlegHahm** [comment]
thx

**Comment by tfar** [comment]
@authmillenon ok. I gave this a test, and after removing od_hex_dump in sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c I was able to build it. Receiving fragmented UDP packets works. So does sending and receiving pings, including fragmented pings. So +1 for merging this PR.

File: sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c [hunk 1]
```diff
@@ -89,23 +89,24 @@ static inline bool _context_overlaps_iid(ng_sixlowpan_ctx_t *ctx,
...
+    DEBUG("6lo iphc: ng_sixlowpan_iphc_decode(%p, %p, %u)\n",
+          (void *)ipv6, (void *)pkt, (unsigned)offset);
+
+    assert(ipv6 != NULL);
+    assert(ipv6->size >= sizeof(ng_ipv6_hdr_t));
 
     ipv6_hdr = ipv6->data;
+    iphc_hdr += offset;
+
+    od_hex_dump(iphc_hdr, pkt->size - offset, 0);
```
Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c]: You mean this one? This needs to be removed, yes.

Comment (tfar) [inline sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c]: Well..yeah but I had to remove it because it was complaining about undeclared(or undefined, don't remember) function.

Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c]: So, it's going to be removed?

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c]: Yes, as soon as I have some keyboard under my hand again ;)

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/iphc/ng_sixlowpan_iphc.c]: Fixed.

File: sys/net/network_layer/ng_sixlowpan/frag/rbuf.c [hunk 2]
```diff
@@ -137,18 +153,14 @@ void rbuf_add(ng_netif_hdr_t *netif_hdr, ng_sixlowpan_frag_t *frag,
...
-        }
-        else {
-            DEBUG("6lo rbuf: datagram complete, send to IPv6 listeners\n");
-            if (!ng_netapi_dispatch_receive(NG_NETTYPE_IPV6, NG_NETREG_DEMUX_CTX_ALL,
-                                            entry->pkt)) {
-                DEBUG("6lo rbuf: No receivers for this packet found\n");
-                ng_pktbuf_release(entry->pkt);
-            }
+        DEBUG("6lo rbuf: datagram complete, send to IPv6 listeners\n");
+        ng_ipv6_hdr_print(entry->pkt->data);
```
Comment (tfar) [inline sys/net/network_layer/ng_sixlowpan/frag/rbuf.c]: Is this print debugging/testing code?

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/rbuf.c]: Jupp, and it shouldn't be their either -.-. Cleaned it up now :)

**Comment by tfar** [comment]
Looks good to me now.

**Comment by authmillenon** [comment]
Removed some more carelessly introduced debug outputs.

File: sys/net/network_layer/ng_sixlowpan/frag/rbuf.c [hunk 3]
```diff
@@ -204,7 +213,7 @@ static bool _rbuf_update_ints(rbuf_t *entry, uint16_t offset, size_t frag_size)
           new->start, new->end, ng_netif_addr_to_str(l2addr_str,
                   sizeof(l2addr_str), entry->src, entry->src_len));
     DEBUG("%s, %u, %u)\n", ng_netif_addr_to_str(l2addr_str,
-          sizeof(l2addr_str), entry->dst, entry->dst_len),
+            sizeof(l2addr_str), entry->dst, entry->dst_len),
```
Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/rbuf.c]: Those are parameters of `ng_netif_addr_to_str()` so that's why there was an indentation introduced here.

File: sys/net/network_layer/ng_sixlowpan/frag/rbuf.c [hunk 4]
```diff
@@ -227,7 +236,7 @@ static void _rbuf_gc(void)
         else if ((rbuf[i].pkt != NULL) &&
                  ((now.seconds - rbuf[i].arrival) > RBUF_TIMEOUT)) {
             DEBUG("6lo rfrag: entry (%s, ", ng_netif_addr_to_str(l2addr_str,
-                  sizeof(l2addr_str), rbuf[i].src, rbuf[i].src_len));
+                    sizeof(l2addr_str), rbuf[i].src, rbuf[i].src_len));
```
Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/rbuf.c]: Same here

File: sys/net/network_layer/ng_sixlowpan/frag/rbuf.c [hunk 5]
```diff
@@ -305,7 +313,7 @@ static rbuf_t *_rbuf_get(const void *src, size_t src_len,
         DEBUG("%s, %u, %u) created\n",
               ng_netif_addr_to_str(l2addr_str, sizeof(l2addr_str), res->dst,
                                    res->dst_len), (unsigned)res->pkt->size,
-                                   res->tag);
+              res->tag);
```
Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/rbuf.c]: Otherway around: now `res->tag` is a parameter of DEBUG.

**Comment by authmillenon** [comment]
I reassign to a maintainer now.

File: sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c [hunk 6]
```diff
@@ -80,17 +80,17 @@ static uint16_t _send_1st_fragment(ng_sixlowpan_netif_t *iface, ng_pktsnip_t *pk
                                    size_t payload_len, size_t datagram_size)
 {
     ng_pktsnip_t *frag;
-    uint16_t max_frag_size = _floor8(iface->max_frag_size -
-                                     (payload_len - datagram_size) -
-                                     sizeof(ng_sixlowpan_frag_t));
     uint16_t local_offset = 0;
+    int payload_diff = (datagram_size - payload_len);
+    /* virtually add compressed bytes and remove dispatches */
```
Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: Please describe why they are added.

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: They?

Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: well, "added and removed"

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: Because they don't count to the datagram size and the offset, so the fragment size needs to be a multiple of 8 (because the offset is in units of 8 bit) + dispatches - compressed fields, so that it fits the virtual frame size (max_frame_size + compressed fields). Does this make any sense?

Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: Comment in the code, please.

Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: Could you also document what these variables contain? `datagram_size` is the size of full IPv6 packet, I assume? `payload_len` is the size for the IPv6 payload?

**Comment by OlegHahm** [comment]
I think something is broken: strider is well. ;-)

File: sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c (hunk 6 above)
Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: addressed

**Comment by tfar** [comment]
Is there anything missing here except squashing and merging it?

**Comment by OlegHahm** [comment]
Mostly an ACK is missing. I wasn't sure if you did an actual review of the change or just tested the code.

**Comment by tfar** [comment]
@OlegHahm I've tested the code and been using it. It works fine so far. However, I currently don't have the time for an in depth review of this change.

**Comment by authmillenon** [comment]
@OlegHahm I wasn't sure if @tfar is a maintainer so I re-assigned to you.

**Comment by OlegHahm** [comment]
Yes, I know, I was trying to find the time (and concentration) to review this for about one week...

**Comment by authmillenon** [comment]
Shall I squash?

**Comment by OlegHahm** [comment]
yes, please

**Comment by authmillenon** [comment]
Wait something went wrong.

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by authmillenon** [comment]
Was quite a knot, please check if everything is still in order (will do it myself too)

**Comment by tfar** [comment]
@authmillenon I'm seeing the following error trying to build this locally:
```
RIOT/sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c: In function '_receive':
RIOT/sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c:128:63: error: 'ng_ipv6_hdr_t' undeclared (first use in this function)
         ng_pktsnip_t *ipv6 = ng_pktbuf_add(NULL, NULL, sizeof(ng_ipv6_hdr_t),
                                                               ^
RIOT/sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c:128:63: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by authmillenon** [comment]
Japp, saw them too and amended the fix already. My test (ping6 <linux host> 120) was successful again.

**Comment by tfar** [comment]
Yes. Now it builds and my app still works using this version.

**Comment by authmillenon** [comment]
:+1:

**Comment by authmillenon** [comment]
Travis is happy too again. :-)

**Comment by OlegHahm** [comment]
Pinging between two native nodes (IPv6 only) I get this:
```
ping6 5 fe80::3439:95ff:fe76:2684 1000
error: unexpected parameters
1008 bytes from fe80::3439:95ff:fe76:2684: id=86 seq=1 hop limit=64 time = 0.117 ms
1008 bytes from fe80::3439:95ff:fe76:2684: id=86 seq=2 hop limit=64 time = 0.113 ms
1008 bytes from fe80::3439:95ff:fe76:2684: id=86 seq=3 hop limit=64 time = 0.104 ms
1008 bytes from fe80::3439:95ff:fe76:2684: id=86 seq=4 hop limit=64 time = 0.104 ms
--- fe80::3439:95ff:fe76:2684 ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 4.061238 s
rtt min/avg/max = 0.104/0.158/0.353 ms
```

**Comment by OlegHahm** [comment]
On master all five echo requests get through without the "unexpected parameters" error.

**Comment by authmillenon** [comment]
@OlegHahm is that repeatable? I don't get this kind of error.

**Comment by authmillenon** [comment]
```
kernel_init(): This is RIOT! (Version: 2014.12-2791-g1129-ng_sixlowpan/fix/issue-3588)
kernel_init(): jumping into first task...
UART0 thread started.
uart0_init() [OK]
RIOT network stack example application
All up, running the shell now
> ping6 5 fe80::9c8f:2eff:fe4c:9e75 1000
ping6 5 fe80::9c8f:2eff:fe4c:9e75 1000
1008 bytes from fe80::9c8f:2eff:fe4c:9e75: id=83 seq=1 hop limit=64 time = 1.033 ms
1008 bytes from fe80::9c8f:2eff:fe4c:9e75: id=83 seq=2 hop limit=64 time = 0.567 ms
1008 bytes from fe80::9c8f:2eff:fe4c:9e75: id=83 seq=3 hop limit=64 time = 0.473 ms
1008 bytes from fe80::9c8f:2eff:fe4c:9e75: id=83 seq=4 hop limit=64 time = 0.461 ms
1008 bytes from fe80::9c8f:2eff:fe4c:9e75: id=83 seq=5 hop limit=64 time = 0.468 ms
```

**Comment by authmillenon** [comment]
Also: your latencies look curiously short. You sure you did not ping the node itself?

**Comment by authmillenon** [comment]
(which works for me as expected too btw):

```
kernel_init(): This is RIOT! (Version: 2014.12-2791-g1129-ng_sixlowpan/fix/issue-3588)
kernel_init(): jumping into first task...
UART0 thread started.
uart0_init() [OK]
RIOT network stack example application
All up, running the shell now
> ping6 5 fe80::60e2:2cff:fe2a:874f 1000
ping6 5 fe80::60e2:2cff:fe2a:874f 1000
1008 bytes from fe80::60e2:2cff:fe2a:874f: id=83 seq=1 hop limit=64 time = 0.190 ms
1008 bytes from fe80::60e2:2cff:fe2a:874f: id=83 seq=2 hop limit=64 time = 0.169 ms
1008 bytes from fe80::60e2:2cff:fe2a:874f: id=83 seq=3 hop limit=64 time = 0.170 ms
1008 bytes from fe80::60e2:2cff:fe2a:874f: id=83 seq=4 hop limit=64 time = 0.170 ms
1008 bytes from fe80::60e2:2cff:fe2a:874f: id=83 seq=5 hop limit=64 time = 0.178 ms
--- fe80::60e2:2cff:fe2a:874f ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 4.062118 s
rtt min/avg/max = 0.169/0.175/0.190 ms
```

**Comment by OlegHahm** [comment]
Hm, I tested twice before and was able to reproduce, but apparently not anymore. And yes, I was pinging the wrong address: accidentally the bridge instead of the other node.

**Comment by OlegHahm** [comment]
Weird, cannot reproduce now.

**Comment by authmillenon** [comment]
Would have been very weird too, since this PR does not touch any files used by native (at least without ZEP).

**Comment by OlegHahm** [comment]
Maybe I was receiving other ICMPv6 traffic from bridge somehow?

**Comment by authmillenon** [comment]
Should not really interfere, since you are registered to ping replies only, but true that could have been what was happening. We should investigate this, but it's unrelated to this PR.

File: sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c [hunk 7]
```diff
@@ -80,18 +80,19 @@ static uint16_t _send_1st_fragment(ng_sixlowpan_netif_t *iface, ng_pktsnip_t *pk
                                    size_t payload_len, size_t datagram_size)
 {
     ng_pktsnip_t *frag;
-    uint16_t max_frag_size = _floor8(iface->max_frag_size -
-                                     (payload_len - datagram_size) -
-                                     sizeof(ng_sixlowpan_frag_t));
     uint16_t local_offset = 0;
+    /* payload_len: actual size of the packet vs
+     * datagram_size: size of the uncompressed IPv6 packet */
+    int payload_diff = (datagram_size - payload_len);
```
Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: So, this is basically `-dispatch_len` from https://github.com/RIOT-OS/RIOT/blob/master/sys/net/network_layer/ng_sixlowpan/ng_sixlowpan.c#L251?

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: Yes and no. It would be wrong to call it that, since with IPHC you don't really have a `dispatch_len` anymore as you had in the line you were referring to. In the case of IPHC it is basically `sizeof(ipv6_hdr_t) - len(iphc_dispatch)`. For UNCOMP you are right.

Comment (OlegHahm) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: I'm not proposing to *call* it like this, I'm just trying to understand what it *contains*.

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: I've chosen the pseudo code `len(iphc_dispatch)` to make clear, that though this is the dispatch length, it is different from what `dispatch_len` was before (which only applied to non-IPHC dispatches ;-)).

Comment (authmillenon) [inline sys/net/network_layer/ng_sixlowpan/frag/ng_sixlowpan_frag.c]: > I'm not proposing to call it like this, I'm just trying to understand what it contains.

For UNCOMP: length of dispatch, for IPHC: number of bytes compressed.

**Comment by OlegHahm** [comment]
ACK and go!
