### PR TITLE
cpu/stm32: fix timer speed for STM32F1 and F2

### LINKED ISSUE #6287: stm32f1: xtimer clock running at twice the speed
I've noticed this when running the timer_periodic_wakeup example from the RIOT examples directory.
cpu: STM32F103RCBT6
Hardware: [maple-mini](https://github.com/phectori/RIOT/tree/maple-mini/boards/maple-mini) (Clock configuration seems identical to the nucleo-f103 board

expected to receive a message every second. A message is received every 500ms.
RIOT seems to think that a second has elapsed:
```
main(): This is RIOT! (Version: 2017.01-devel-295-g6a757-dystopia-maple-mini-work)
slept until 1014640
slept until 2014640
slept until 3014640
```

### PR DESCRIPTION
**Pull request by haukepetersen**
fixes #6287

### CODE REVIEW

File: cpu/stm32_common/periph/timer.c [hunk 1]
```diff
@@ -53,8 +53,14 @@ int timer_init(tim_t tim, unsigned long freq, timer_cb_t cb, void *arg)
     dev(tim)->CR1  = 0;
     dev(tim)->CR2  = 0;
     dev(tim)->ARR  = timer_config[tim].max;
-    /* set prescaler */
+    /* set prescaler: the stm32f1 introduces a clock multiplier of 2 in the case
+     * the APB1 prescaler is != 1, so we need to catch that
+     * -> see reference manual section 7.2.1 */
+#if defined(CPU_FAM_STM32F1) && (CLOCK_APB1 != CLOCK_CORECLOCK)
```
Comment (OlegHahm) [inline cpu/stm32_common/periph/timer.c]: If I read the manual correctly
```C
if defined(CPU_FAM_STM32F1) && (CLOCK_APB1 < CLOCK_CORECLOCK)
```
would be more precise, but since `CLOCK_APB1` cannot be bigger than `CLOCK_CORECLOCK` anyway, that's doesn't change anything.

Comment (haukepetersen) [inline cpu/stm32_common/periph/timer.c]: true

**Comment by haukepetersen** [comment]
s/(CLOCK_APB1 != CLOCK_CORECLOCK)/(CLOCK_APB1 < CLOCK_CORECLOCK)/

**Comment by vincent-d** [comment]
It seems to apply to stm32f2 as well.

> The timer clock frequencies are automatically set by hardware. There are two cases:
> 1. If the APB prescaler is 1, the timer clock frequencies are set to the same frequency as
> that of the APB domain to which the timers are connected.
> 2. Otherwise, they are set to twice (×2) the frequency of the APB domain to which the
> timers are connected.

(reference manual part 5.2)

**Comment by OlegHahm** [comment]
ACK upholds

**Comment by vincent-d** [comment]
Tested OK on stm32f2.
