### PR TITLE
at86rf2xx: fix EUI64 computation

### LINKED ISSUE #2962: at8r6rf231/iot-lab_M3: long address is not unique
Using the [at86rf2xx test application](https://github.com/RIOT-OS/RIOT/tree/master/tests/driver_at86rf2xx) results in identical long hardware address: `32:ff:dd:05:33:48:32:36` at least on iot-lab_m3. The short address seems to be okay.

### PR DESCRIPTION
**Pull request by OlegHahm**
fixes #2962

### CODE REVIEW

**Comment by authmillenon** [comment]
I'd prefer to keep it completely independent from `hashes`. I'm already annoyed by `native` when it changes the hardware address everytime I restart and I forget the `-i` flag. I don't like it to be the case for every board to have a different address depending on the modules I compile in.

**Comment by OlegHahm** [comment]
Ok, I agree. Here's another approach, that's mostly taken from OpenWSN. It seems a little bit arbitrary, but at least we will have the same EUI-64 addresses on the IoT-LAB.

**Comment by authmillenon** [comment]
Why not the XOR method you had earlier?

File: sys/include/net/ng_ieee802154.h [hunk 1]
```diff
@@ -58,6 +60,15 @@ extern "C" {
 #define NG_IEEE802154_FCF_SRC_ADDR_LONG     (0xc0)
 /** @} */
 
+/**
+ * @brief Data type to represent an EUI-64.
+ */
+typedef union __attribute__((packed)) {
+    uint64_t uint64;    /**< represented as 64 bit value */
+    uint8_t uint8[8];   /**< split into 8 8-bit words. */
+    uint16_t uint16[4]; /**< split into 4 16-bit words. */
```
Comment (authmillenon) [inline sys/include/net/ng_ieee802154.h]: I'd prefer some sort of enforced byteorder here... Either `le_uintX_t` (to keep the spirit of IEEE 802.15.4) or `network_uintX_t` (to be compatible with everything else).

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c [hunk 2]
```diff
@@ -101,28 +102,39 @@ void ng_at86rf2xx_reset(ng_at86rf2xx_t *dev)
...
-    memcpy(&addr_long, cpuid, 8);
-    ng_at86rf2xx_set_addr_long(dev, addr_long);
+    ng_at86rf2xx_set_addr_long(dev, addr_long.uint64);
     /* now compress the long addr to form the short address */
     for (int i = 2; i < 8; i++) {
         cpuid[i & 0x01] ^= cpuid[i];
     }
-    memcpy(&addr_short, cpuid, 2);
-    ng_at86rf2xx_set_addr_short(dev, addr_short);
+    ng_at86rf2xx_set_addr_short(dev, addr_long.uint16[3]);
```
Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: I don't really see an advantage in making the short address dependent on the long address (I don't see a clear disadvantage either o this is just my opinion)

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: It makes it much easier to identify a node. IoT-LAB cli-tools for example print only the 16bit short address.

File: sys/include/net/ng_ieee802154.h (hunk 1 above)
Comment (OlegHahm) [inline sys/include/net/ng_ieee802154.h]: I will adapt.

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 2 above)
Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Still don't get why you need the relationship then. Per default our devices use the short address, too.

**Comment by OlegHahm** [comment]
> Why not the XOR method you had earlier? 

I think it makes things easier if we have the same UIDs at least in OpenWSN and RIOT.

**Comment by authmillenon** [comment]
Then you maybe should adapt the xbee driver, too (if you want to make it dependent on the EUI-64)

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 2 above)
Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Yes, but a different one. If I do, e.g. `experiment-cli info -l --site grenoble` I get something like:
```json
        {
            "archi": "m3:at86rf231",
            "mobile": 0,
            "mobility_type": " ",
            "network_address": "m3-204.grenoble.iot-lab.info",
            "state": "Alive",
            "uid": "b877",
            "x": "18.95",
            "y": "0.75",
            "z": "-0.04"
        },
```
where uid is the 16 bit short address. It's much easier to identify a node if this uid matches our default short address.

**Comment by OlegHahm** [comment]
> Then you maybe should adapt the xbee driver, too (if you want to make it dependent on the EUI-64)

I cannot test this device and I don't understand the parts in brackets.

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 2 above)
Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: I don't understand? Is this uid related to the EUI-64 or not? Are you sure it is a device related ID and not just *your* user ID on that node?

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > Is this uid related to the EUI-64 or not?

It is. These are the last two bytes of the EUI-64.

>  Are you sure it is a device related ID and not just your user ID on that node? 

Yes, I am.

**Comment by authmillenon** [comment]
> I don't understand the parts in brackets.

Currently the short address for this device is generated from CPU ID, too. However, if we take the scheme you proposed to take bytes of the EUI-64 for that, we should do that on the xbee device too (where the EUI-64 I is preinitialized by the vendor).

**Comment by OlegHahm** [comment]
Ah, okay. Yes, I'm much in favor of this.

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 2 above)
Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Okay, then leave it as it is. Should I PR a patch for xbee? To this branch or to master?

File: sys/include/net/ng_ieee802154.h (hunk 1 above)
Comment (OlegHahm) [inline sys/include/net/ng_ieee802154.h]: But IEEE 802.15.4 addresses are little-endian, right?

Comment (authmillenon) [inline sys/include/net/ng_ieee802154.h]: With the EUI-64 I'm never sure 😕

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 2 above)
Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: I can make the change if it 's just taking the last two bytes of the EUI-64, but would be great if you could test.

File: sys/include/net/ng_ieee802154.h (hunk 1 above)
Comment (OlegHahm) [inline sys/include/net/ng_ieee802154.h]: Shouldn't the EUI-64 in the driver be a data type with enforced endianess, too?

**Comment by OlegHahm** [comment]
Updated. Endianess not yet addressed, because a) I'm not sure what the right endianess and b) I think the driver should reflect this, too. Maybe another PR for that?

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c [hunk 3]
```diff
@@ -101,28 +102,39 @@ void ng_at86rf2xx_reset(ng_at86rf2xx_t *dev)
...
-    }
+    /* for consistency taken from OpenWSN, https://github.com/openwsn-berkeley/openwsn-fw,
+     * bsp/boards/iot-lab_M3/eui64.c */
+    const uint8_t const *luid = (const uint8_t *const) &(cpuid[CPUID_ID_LEN - 8]);
+
+    /* Pseudo-OUI */
+    addr_long.uint8[0] = cpuid[3];
+    addr_long.uint8[1] = luid[7];
+    addr_long.uint8[2] = cpuid[0];
+    addr_long.uint8[3] = cpuid[1];
```
Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: I just realized, that this is not really an OUI, right? Maybe for the platforms that OpenWSN supports, but we support way more boards than them.

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > but we support way more boards than them.

Actually, I think they support more boards with 802.15.4 support than RIOT. But this code is taken from the iot-lab implementation. We could make it iot-lab specific, but wanted to avoid this.

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: You think we should that the first three bytes to `000425`, Atmels OUI here?

Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > You think we should that the first three bytes to 000425, Atmels OUI here?

no, I think that is a bad idea… I'd prefer the XOR solution above this solution actually :/

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > no, I think that is a bad idea…

Why? It is an Atmel device.

> I'd prefer the XOR solution above this solution actually :/

Why?

Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Because Atmel is handling its device identifiers => a collision is bound to happen. And I don't know how the legal situation is. Also: since it is still a pseudo EUI-64 this way the correct prefix would be 020425, since the universal/local-bit must be set.

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Do you see a way to make sure not collide with any vendor?

Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: No, but I don't see the benefit in making some pseudo-Atmel (actually not) sanctioned EUI-64 over a completely "randomised" one out of the whole range of the CPU ID.

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Ok, so, I leave the PR as is.

**Comment by OlegHahm** [comment]
@cladmi, do you have some insights how to sensibly compute an EUI64 for the at86rf2xx?

**Comment by authmillenon** [comment]
And what is @haukepetersen's opinion on this?

**Comment by authmillenon** [comment]
@OlegHahm I would prefer a method that can be generally applied for ALL IEEE 802.15.4 devices (as long as they allow for that), not just the at86rf2xx ones.

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c [hunk 4]
```diff
@@ -101,28 +102,39 @@ void ng_at86rf2xx_reset(ng_at86rf2xx_t *dev)
...
 #if CPUID_ID_LEN
     cpuid_get(cpuid);
-#if CPUID < 8
+#if CPUID_ID_LEN < 8
     /* in case CPUID_ID_LEN < 8, fill missing bytes with zeros */
     for (int i = CPUID_ID_LEN; i < 8; i++) {
         cpuid[i] = 0;
     }
+    /* copy and set long address */
+    memcpy(&addr_long, cpuid, 8);
```
Comment (authmillenon) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: This + https://github.com/RIOT-OS/RIOT/pull/2963/files#diff-1042c565e8e083247b2102811d2f02ecR137 will result in the short address always being 0 ;-)

**Comment by OlegHahm** [comment]
>  I would prefer a method that can be generally applied for ALL IEEE 802.15.4 devices (as long as they allow for that), not just the at86rf2xx ones.

Apparently, that's not possible if weird devices as the XBEE not even allow to set the EUI-64.

**Comment by authmillenon** [comment]
That's why I wrote "**(as long as they allow for that)**".

**Comment by authmillenon** [comment]
Exceptions gonna except... let's at least have a general case for non-exceptions is all I'm saying.

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 4 above)
Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: Why?

**Comment by OlegHahm** [comment]
Do you have a proposal?

**Comment by authmillenon** [comment]
As I proposed yesterday and ignored since then 😒: using "sliding XOR"

```C 
#if CPUID_ID_LEN
     uint8_t cpuid[CPU_ID_LEN];

     cpuid_get(cpuid);
#if CPUID_ID_LEN < 8
     /* in case CPUID_ID_LEN < 8, lead with zeros */
     for (int i = 0; i < (8 - CPUID_ID_LEN); i++) {
         addr_long[i] = 0;
     }

     for (int i = 0; i < CPUID_ID_LEN; i++) {
         addr_long[i + (8 - CPUID_ID_LEN)] = cpuid[i];
     }

 #else
    memset(addr_long, 0, 8);

    for (int i = 0; i < (CPUID_ID_LEN - 8); i++) {
         for (int j = i; j < 8; j++) {
             addr_long[j] ^= cpuid[i + j];
         } 
    }
#endif
#endif
```

**Comment by OlegHahm** [comment]
I'm not ignoring it, but you haven't answered why you prefer this solution. I don't see how this is more generic. The CPUID is vendor specific anyway.

**Comment by authmillenon** [comment]
Oh… sorry I somehow oversaw your question. I prefer it, since it uses the entire CPUID compared to just parts of it.

**Comment by OlegHahm** [comment]
Ok, let's recap the requirements:
1. we want to have a generic solution
2. we want to have standard compliant solution
3. we want a unique ID if possible
4. we want to be as compatible as possible to other implementations
5. we want to easily use testbeds

Did I forget something?

While I agree that using the full CPUID seems to be the cleaner approach, I fail to see why the chances for an unique ID should be higher. All other requirements seems to be fulfilled for the proposed solution. Anyway I will ask on the OpenWSN mailing list what lead to their implementation. Maybe this makes things clearer.

**Comment by gebart** [comment]
>While I agree that using the full CPUID seems to be the cleaner approach, I fail to see why the chances for an unique ID should be higher.

The CPUID is defined by the manufacturer and may or may not have some logical pattern in it, so we can't know for sure which bits are going to change between two units from the same manufacturing batch. i.e. the last bit might not be the "LSB" that changes between every unit and they may have some slow changing information there instead like the manufacturing date, the batch number, the silicon version etc.
This is why I think it is better to use the entire CPUID for when we hope to avoid possible collisions between devices running RIOT.

**Comment by gebart** [comment]
@authmillenon 
>I'd prefer to keep it completely independent from `hashes`.
What is wrong with the djb2_hash approach using the hash module? Is it code-size you are worried about?

**Comment by OlegHahm** [comment]
It's really difficult. I understand all your reasons and I agree. However, for practicable reasons, it feels really inconvenient if a) we have different default short addresses for RIOT on IoT-LAB or b) having the default short address decoupled from the long address.

File: drivers/xbee/xbee.c [hunk 5]
```diff
@@ -452,24 +452,10 @@ int xbee_init(xbee_t *dev, uart_t uart, uint32_t baudrate,
...
-    }
-#else
-    dev->addr_short[0] = (uint8_t)(XBEE_DEFAULT_SHORT_ADDR >> 8);
-    dev->addr_short[1] = (uint8_t)(XBEE_DEFAULT_SHORT_ADDR);
-#endif
-    _set_addr(dev, dev->addr_short, 2);
     /* load long address (we can not set it, its read only for Xbee devices) */
     _get_addr_long(dev, dev->addr_long, 8);
     /* set default channel */
+    _set_addr(dev, ((ieee_802154_long_t) dev->addr_short).uint16[3], 2);
```
Comment (haukepetersen) [inline drivers/xbee/xbee.c]: `_set_addr()` is taking a `uint8_t *` as second argument, look to me like there is a cast missing...

**Comment by haukepetersen** [comment]
Actually I agree with @gebart, that we should definitely use the complete CPUID to generate the EUI, as every vendor has it's own scheme, and what might work on the iot-lab might not work on some Freescale system. Also we should be careful not to put something in the driver, that might be motivated from some iot-lab specific requirements...

I would propose the following solution:
 
 1. we centralize the computation of the EUI by either putting it's own module. There we would have a simple function `eui64_get(uint8_t *eui)` or similar. This is then used by all driver that need to generate an EUI. Further we are then able to specify default values/behaviors in case the CPUID is not available.
2. we always use the 16 LSB of the EUI as short address. This will lead to consistent behavior and is useful as a side-effect for the iot-lab testbed.

@OlegHahm, @authmillenon, what do you say?

File: drivers/xbee/xbee.c (hunk 5 above)
Comment (OlegHahm) [inline drivers/xbee/xbee.c]: true, will fix

**Comment by OlegHahm** [comment]
> we always use the 16 LSB of the EUI as short address. This will lead to consistent behavior and is useful as a side-effect for the iot-lab testbed.

Only, this only helps if the EUI64 is calculated in a way that the last two octets are identical with the iot-lab and OpenWSN.

> we centralize the computation of the EUI by either putting it's own module. There we would have a simple function eui64_get(uint8_t *eui) or similar. This is then used by all driver that need to generate an EUI. Further we are then able to specify default values/behaviors in case the CPUID is not available.

I thought about this, too, and think this might be a good solution, because we could then define additional board dependent modules that an application developer could use instead. E.g. MODULE_EUI64 as default and something like MODULE_EUI64_BOARD that could be used instead.

**Comment by OlegHahm** [comment]
As a compromise: We merge this now as is and I prepare an additional PR with separated EUI-64 module. Rationale: EUI-64 computation is broken (at least on IoT-Lab) without this (or another) change.

**Comment by cladmi** [comment]
Don't take the IoT-Lab case as blocking, it can also be changed on our side.

We had the need for a 16bit UID across all the testbed (or a least for one site) for the cases where a 16bit address was needed, like in some mac layers.

I decided, for documentation simplicity, coherency, and to be easy to be use, to also use it as node address identifier for IPv6 in Contiki. https://github.com/iot-lab/contiki/blob/master/platform/iotlab/platform-addr.c
This lead OpenWSN and RIOT to use our specific addressing.

If another EUI64 calculation is decided, we can change it in IoT-Lab too. It will only add a field in the nodes description saying 'EUI64', and some documentation.

**Comment by cladmi** [comment]
My remaining question is what happens if two nodes share the same EUI64?
And more and if we deduce the 16bit address from the EUI64, what happens if two nodes have the same 16bit address. Which is quite likely to happen.

**Comment by OlegHahm** [comment]
> My remaining question is what happens if two nodes share the same EUI64?

I think there's no way to prevent this.

> And more and if we deduce the 16bit address from the EUI64, what happens if two nodes have the same 16bit address. Which is quite likely to happen.

Isn't it the task of the PAN coordinator to prevent this?

**Comment by OlegHahm** [comment]
> If another EUI64 calculation is decided, we can change it in IoT-Lab too. It will only add a field in the nodes description saying 'EUI64', and some documentation.

Great, that eases things a lot. Thanks!

**Comment by haukepetersen** [comment]
With this new informtation, I would really opt for adjusting this PR to something that uses the complete CPUID for EUI computation.

**Comment by haukepetersen** [comment]
Now I know why I was so confused. Actually your fix in line 105 of `drivers/ng_at86rf2xx/ng_at86rf2xx.c` should be already sufficient to generate (more or less) unique EUIs for the IoT-Lab nodes. So I would suggest the following: cut down this PR to that single change and we merge it quickly. Lets then decide how we handle the EUI generation in the long term. How does that sound?

**Comment by OlegHahm** [comment]
> Now I know why I was so confused. Actually your fix in line 105 of drivers/ng_at86rf2xx/ng_at86rf2xx.c should be already sufficient to generate (more or less) unique EUIs for the IoT-Lab nodes.

No, because it takes only the first 8 bytes of the CPUID which are pretty identical for many nodes.

**Comment by cladmi** [comment]
If one algorithm is decided for EUI64, it would be great to also include OpenWSN in the discussion, and also maybe Contiki.
Because, on my side IoT-Lab, if there are 3 different algorithms, it will the users that will suffer from it instead of the maintainers.

**Comment by OlegHahm** [comment]
> If one algorithm is decided for EUI64, it would be great to also include OpenWSN in the discussion, and also maybe Contiki.

Makes sense.

**Comment by OlegHahm** [comment]
@authmillenon, @haukepetersen, what do you think of this proposal for now, basing on sliding XOR.

**Comment by OlegHahm** [comment]
xbee is fixed as well

File: drivers/include/xbee.h [hunk 6]
```diff
@@ -109,7 +105,7 @@ typedef struct {
     ng_nettype_t proto;                 /**< protocol the interface speaks */
     uint8_t options;                    /**< options field */
     uint8_t addr_short[2];              /**< onw 802.15.4 short address */
-    uint8_t addr_long[8];               /**< own 802.15.4 long address */
+    ieee_802154_long_t addr_long;       /**< own 802.15.4 long address */
```
Comment (authmillenon) [inline drivers/include/xbee.h]: *If* we have to introduce a type for that, I'd prefer `eui64_t`. It's shorter, more general and the IEEE 802.15.4 is exactly that.

**Comment by OlegHahm** [comment]
> If we have to introduce a type for that, I'd prefer eui64_t. It's shorter, more general and the IEEE 802.15.4 is exactly that.

Actually, it's not new, but ported from the old stack and updated. I strongly prefer to have dedicated data types as much as possible, but I agree that the renaming is much better.

**Comment by OlegHahm** [comment]
Updated.

**Comment by OlegHahm** [comment]
@authmillenon, @haukepetersen, @gebart, the current version uses all bits from CPUID. If you don't have any particular reasons against this approach, let's merge this to fix EUI-64 on IoT-LAB. We can think about a better solution later.

**Comment by authmillenon** [comment]
I'm fine with the current version. Third of an ACK by me. (I think you can squash ;-))

**Comment by OlegHahm** [comment]
Squashed.

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c [hunk 7]
```diff
@@ -115,14 +117,15 @@ void ng_at86rf2xx_reset(ng_at86rf2xx_t *dev)
...
+#if (CPUID_ID_LEN > 8)
+    for (size_t i = 0; i < 8; i++) {
+        cpuid[i] ^= cpuid[i + (CPUID_ID_LEN - 8)];
     }
-    memcpy(&addr_short, cpuid, 2);
-    ng_at86rf2xx_set_addr_short(dev, addr_short);
+#else
+#endif
+    memcpy(&addr_long, cpuid, 8);
+    ng_at86rf2xx_set_addr_long(dev, byteorder_swapll(addr_long.uint64.u64));
```
Comment (gebart) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: This will reverse the address on both big-endian and little-endian machines, is that intentional?

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: No, that's not intentional and there was another leftover. Cleaned both.

File: drivers/xbee/xbee.c [hunk 8]
```diff
@@ -452,24 +448,10 @@ int xbee_init(xbee_t *dev, uart_t uart, uint32_t baudrate,
...
-#else
-    dev->addr_short[0] = (uint8_t)(XBEE_DEFAULT_SHORT_ADDR >> 8);
-    dev->addr_short[1] = (uint8_t)(XBEE_DEFAULT_SHORT_ADDR);
-#endif
-    _set_addr(dev, dev->addr_short, 2);
     /* load long address (we can not set it, its read only for Xbee devices) */
-    _get_addr_long(dev, dev->addr_long, 8);
+    _get_addr_long(dev, dev->addr_long.uint8, 8);
     /* set default channel */
+    _set_addr(dev, &((dev->addr_long).uint8[7]), 2);
```
Comment (haukepetersen) [inline drivers/xbee/xbee.c]: I think you mean `&((dev->addr_long).uint8[`**6**`])` here, as you copy byte 7 and 8!?

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c [hunk 9]
```diff
@@ -115,14 +117,14 @@ void ng_at86rf2xx_reset(ng_at86rf2xx_t *dev)
...
     /* copy and set long address */
-    memcpy(&addr_long, cpuid, 8);
-    ng_at86rf2xx_set_addr_long(dev, addr_long);
-    /* now compress the long addr to form the short address */
-    for (int i = 2; i < 8; i++) {
-        cpuid[i & 0x01] ^= cpuid[i];
+#if (CPUID_ID_LEN > 8)
+    for (size_t i = 0; i < 8; i++) {
+        cpuid[i] ^= cpuid[i + (CPUID_ID_LEN - 8)];
     }
```
Comment (haukepetersen) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: I still don't quite understand, while we loop through the upper bytes (`cpuid[i]; with i >= CPUID_ID_LEN`) twice. Here and also in lines 112-114. I would say we can drop these lines here. Further they do not neccessarily take every byte of the CPUID into account, what if `CPUID_ID_LEN > 16`?

File: drivers/xbee/xbee.c (hunk 8 above)
Comment (OlegHahm) [inline drivers/xbee/xbee.c]: yupp, will fix

File: drivers/ng_at86rf2xx/ng_at86rf2xx.c (hunk 9 above)
Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > I still don't quite understand, while we loop through the upper bytes (cpuid[i]; with i >= CPUID_ID_LEN) twice. Here and also in lines 112-114. I would say we can drop these lines here. 

I don't understand the purpose of lines 112-114, so I left them untouched.

> Further they do not neccessarily take every byte of the CPUID into account, what if CPUID_ID_LEN > 16?

Any known case?

Comment (haukepetersen) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > I don't understand the purpose of lines 112-114, so I left them untouched

They XOR every `cpuid[i]; i >= CPUID_ID_LEN` byte cyclically with the first 8 bytes, so creating an ID from ALL available bytes. Actually very similar to what you do here... 

> Any known case?

Currently not. But why make assumptions here that might not be true in the future and that can easily prevented!

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > They XOR every cpuid[i]; i >= CPUID_ID_LEN byte cyclically with the first 8 bytes, so creating an ID from ALL available bytes. Actually very similar to what you do here... 

But what the purpose of using only the last 4 bits?

Comment (OlegHahm) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: > Currently not. But why make assumptions here that might not be true in the future and that can easily prevented!

As discussed: we will probably adopt this implementation anyway, but yes, it's duplicated and wrong as I just discovered.

Comment (haukepetersen) [inline drivers/ng_at86rf2xx/ng_at86rf2xx.c]: ok, just tested with the two iot-labs I have available here: If you remove lines 120 to 124, you should get unique EUIs:
```
node1: 36:32:48:33:46:d5:9f:26
node2: 36:32:48:33:46:d8:9e:16
```

**Comment by haukepetersen** [comment]
Looks good to me, just one remark: If we take `addr_long.uint16[0].u16` as short address for the atxx driver, the short addresses seem not to be unique, right? looking at these two generated addresses:
```
node1: 36:32:48:33:46:d5:9f:26
node2: 36:32:48:33:46:d8:9e:16
```
doesn't it make more sense to use `addr_long.uint16[`**3**`].u16` as default short address for now?

**Comment by haukepetersen** [comment]
Looks good to me know, ACK when squashed and Travis is happy.

**Comment by OlegHahm** [comment]
Too bad, just found a duplicate long address with this scheme on IoT-LAB. :(

**Comment by OlegHahm** [comment]
Without the last commit but puting
```C
    /* make sure we mark the address as non-multicast and not globally unique */
    cpuid[0] &= ~(0x01);
    cpuid[0] |= 0x02;
```
in the right place the duplicate is gone...

Tested with 150 nodes on IoT-Lab. Don't have time to check for duplicates on all nodes.

**Comment by haukepetersen** [comment]
What do you mean with right place? Isn't it in the right place in the current code?

**Comment by OlegHahm** [comment]
Yes, but not in the version before the last commit.

**Comment by haukepetersen** [comment]
Ah, I understand :-) Do you want to squash?

**Comment by OlegHahm** [comment]
This code definitely result in duplicate EUI64 addresses on IoT-LAB. I have a somewhat weird patch that doesn't reveal duplicates on the 160 nodes I tested, but I'm not sure, what's the better approach.

**Comment by haukepetersen** [comment]
Hm, are the CPUIDs on IoT-Lab nodes definitely unique?

**Comment by OlegHahm** [comment]
You should probably ask ST, but I think, yes, they are. It's impossible to guarantee any uniqueness here if we don't know the exact nature of the CPUID. What I propose for the IoT-Lab case: we leave the calculation in this driver as it is with the current state of this PR and add something to the netif auto_init that set different addresses if required (indicated by, e.g., the board or the user).

**Comment by haukepetersen** [comment]
sounds good. What I do not quite understand is the duplicate EUIs in the IoT-Lab, as XORed results from unique CPUIDs should acutally lead to unique EUIs. But anyhow, lets merge and improve afterwards.

ACK

**Comment by OlegHahm** [comment]
Rebased without merge conflicts.

**Comment by OlegHahm** [comment]
> What I do not quite understand is the duplicate EUIs in the IoT-Lab, as XORed results from unique CPUIDs should acutally lead to unique EUIs. 

We're basically mapping a (probably unique) 12 bit value to a an 8 bit value. Collisions may occur with every mapping scheme.

**Comment by cladmi** [comment]
@OlegHahm: I can run my UID scripts to provide you all the CPUIDs of the working IoT-Lab nodes. I hope to give it by tomorrow evening, ping me on IRC if I don't.

**Comment by cladmi** [comment]
https://gist.github.com/cladmi/06c5969be4f1e6e3254b

Almost every nodes. However half of grenoble,m3 nodes are missing because an experiment is currently run. The UID is printed in the uid8[0]->uid8[11] order and it also includes Paris that should be deployed "soon".

**Comment by gebart** [comment]
@OlegHahm @cladmi I checked the list that @cladmi posted using , there are no duplicates among the full CPUIDs
`cat IoT-Lab\ CPUID | awk -F: '{ print $2; }' | sed -e 's/[", ]//g' -e '/^[ ]*$/d'| sort | uniq`

**Comment by haukepetersen** [comment]
When looking at these numbers, I get the feeling that i does make sense, to make the EUI creation platform dependent (-> then we can use known characteristics of the CPUIDs). So I am thinking, that it could make sense, to extend the cpuid module by a second function, maybe something like
```c
void cpuid_get_unique_token(uint8_t res, sizte_t len);
```
In the implementation of that function we can than focus on known relevant bytes (e.g. bytes 3,9,10 for the iot-lab).

**Comment by OlegHahm** [comment]
I think I like the idea. But should we merge this for now and make follow-up PR? Some duplicate EUI64s are less bad than identical EUI64s for *all*. :wink:

**Comment by haukepetersen** [comment]
Agreed. re-ACK and go.
