### PR TITLE
fix DNS resolution in ping6

### LINKED ISSUE #13447: gnrc_sock_dns is not working
#### Description
Thanks to #13307 I now have a proper border router and all my 6lo-nodes can connect to the Internet.
Since IPv6 addresses can be quite tiresome to type by hand, I wanted to make use of DNS.
I've noticed `ping6` already has support for DNS, so I assumed it should suffice to add `USEMODULE += sock_dns` to `examples/gnrc_networking` to try that out.

But `ping6 riot-os.org` would just print

```
2020-02-22 14:40:23,827 #  ping6 riot-os.org
2020-02-22 14:40:23,872 # ping6 [-c <count>] [-h] [-i <ms interval>] [-s <packetsize>]
2020-02-22 14:40:23,874 #      [-t hoplimit] [-W <ms timeout>] <host>[%<interface>]
2020-02-22 14:40:23,875 #      count: number of pings (default: 3)
2020-02-22 14:40:23,877 #      ms interval: wait interval milliseconds between sending (default: 1000)
2020-02-22 14:40:23,879 #      packetsize: number of bytes in echo payload; must be >= 4 to measure round trip time (default: 4)
2020-02-22 14:40:23,881 #      hoplimit: Set the IP time to life/hoplimit (default: interface config)
2020-02-22 14:40:23,893 #      ms timeout: Time to wait for a resonse in milliseconds (default: 1000). The option affects only timeout in absence of any responses, otherwise wait for two RTTs
```

So I've turned to `tests/gnrc_sock_dns` to manually set the DNS server, but to no avail.

The behavior is the same no matter if connected directly via WiFi (`esp8266-esp-12x`) or via border router (`mcb2388` + `mrf24j40md` or `avr-rss2`), with the only exception that the AVR board will crash when attempting the DNS lookup, the other boards just fail.

To simplify things I'm describing the direct WiFi connection case:

#### Steps to reproduce the issue

In `tests/gnrc_sock_dns` replace `USEMODULE += stdio_ethos` with `USEMODULE += esp_wifi` and add `USEMODULE += gnrc_icmpv6_echo` to ease debugging.

You will also need to add 

```
CFLAGS += -DESP_WIFI_SSID=\"Your SSID\"
CFLAGS += -DESP_WIFI_PASS=\"Your Password\"
```

On the shell, add a dns server:

```
> dns server 2620:119:35::35
2020-02-22 14:47:58,661 # DNS server: [2620:119:35::35]:53
```

Ensure that you can reach the DNS server:

```
2020-02-22 14:48:58,803 #  ping6 2620:119:35::35
2020-02-22 14:48:58,880 # 12 bytes from 2620:119:35::35: icmp_seq=0 ttl=59 time=23.592 ms
2020-02-22 14:48:59,881 # 12 bytes from 2620:119:35::35: icmp_seq=1 ttl=59 time=23.758 ms
2020-02-22 14:49:00,883 # 12 bytes from 2620:119:35::35: icmp_seq=2 ttl=59 time=26.299 ms
```

Ensure the DNS server works on a Linux host:
```
> nslookup -type=AAAA riot-os.org 2620:119:35::35
Server:		2620:119:35::35
Address:	2620:119:35::35#53

Non-authoritative answer:
Name:	riot-os.org
Address: 2a01:4f8:151:64::11
```

Now try to loop up the name on RIOT:

```
> dns request riot-os.org
```

#### Expected results
The IP address of the requested host is returned.

#### Actual results

```
2020-02-22 14:50:28,002 #  dns request riot-os.org
2020-02-22 14:50:28,055 # error resolving riot-os.org
```

#### Versions
RIOT master

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Previously DNS resolution in `ping6` would always fail.
This was due to a slew of minor bugs in `sock_dns` and `gnrc_icmpv6_echo`.
This PR fixes them, so DNS resolution is working properly now.

### Testing procedure

If you are using a board with direct WiFi or Ethernet connection (e.g. esp8266 or esp32), it should suffice to add `USEMODULE += sock_dns` to `examples/gnrc_networking`.

On a 6LoWPAN device, the border router (`examples/gnrc_border_router`) doesn't seem to forward DNS information, so you have to resort to `tests/gnrc_sock_dns` to being able to set the DNS server manually by calling e.g. `dns server 2620:119:35::35:`.

You should now be able to ping a host by name:

```
2020-02-22 20:10:44,986 #  ping6 riot-os.org
2020-02-22 20:10:45,114 # 12 bytes from 2a01:4f8:151:64::11: icmp_seq=0 ttl=56 time=71.772 ms
2020-02-22 20:10:46,071 # 12 bytes from 2a01:4f8:151:64::11: icmp_seq=1 ttl=56 time=29.318 ms
2020-02-22 20:10:47,122 # 12 bytes from 2a01:4f8:151:64::11: icmp_seq=2 ttl=56 time=79.199 ms
```

### Issues/PRs references

fixes #13447
follow-up on #13443

### CODE REVIEW

File: sys/net/application_layer/dns/dns.c [hunk 1]
```diff
@@ -157,21 +157,21 @@ static int _parse_dns_reply(uint8_t *buf, size_t len, void* addr_out, int family
...
 
         memcpy(addr_out, bufpos, addrlen);
-        return addrlen;
+        return 0;
     }
 
     return -1;
 }
 
+static uint8_t reply_buf[512];
```
Comment (benpicco) [inline sys/net/application_layer/dns/dns.c]: The replies I got were 56 bytes max - do we really need such a huge buffer?

File: sys/net/application_layer/dns/dns.c [hunk 2]
```diff
@@ -157,21 +157,21 @@ static int _parse_dns_reply(uint8_t *buf, size_t len, void* addr_out, int family
             return -EBADMSG;
         }
         bufpos += RR_RDLENGTH_LENGTH;
-        if ((bufpos + addrlen) >= buflim) {
+        if ((bufpos + addrlen) > buflim) {
```
Comment (miri64) [inline sys/net/application_layer/dns/dns.c]: This introduces an off-by-one/out-of-bound error. `buflim` is the first byte _after_ `buf` (= `buf + len`, see above), so if (`bufpos - buf + addrlen` is just one byte longer than `len`, you cause a buffer overflow with this.

File: sys/net/application_layer/dns/dns.c [hunk 3]
```diff
@@ -162,7 +162,7 @@ static int _parse_dns_reply(uint8_t *buf, size_t len, void* addr_out, int family
         }
 
         memcpy(addr_out, bufpos, addrlen);
-        return addrlen;
+        return 0;
```
Comment (miri64) [inline sys/net/application_layer/dns/dns.c]: In l.226, the return value of is `_parse_dns_reply()` checked if it is >0. I'm also not sure which doc you are referring to in your commit message... `_parse_dns_reply()` does not have any.

File: sys/net/application_layer/dns/dns.c (hunk 1 above)
Comment (miri64) [reply sys/net/application_layer/dns/dns.c]: Might be even better to make it compile-time configurable with default of 64?

File: sys/net/application_layer/dns/dns.c (hunk 3 above)
Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: The documentation of [`sock_dns_query()`](https://doc.riot-os.org/group__net__sock__dns.html#ga508b47ec287a3846ca8f8fc2c0bbe9bd).

Maybe we should instead change the documentation to match the implementation - otherwise it's not possible to find out if the function returned an IPv4 or IPv6 address in the `AF_UNSPEC` case.

File: sys/net/application_layer/dns/dns.c (hunk 2 above)
Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: Huh that's odd. I would see the function always return error here, upon closer inspection I would get

```
2020-02-23 17:48:15,409 #  dns request riot-os.org
2020-02-23 17:48:15,416 # got 57 bytes from DNS
2020-02-23 17:48:15,418 # 0x3fff3efd + 16 < 0x3fff3f0d ?
```
or 
```
2020-02-23 17:48:07,632 #  dns request golem.de
2020-02-23 17:48:07,645 # got 54 bytes from DNS
2020-02-23 17:48:07,648 # 0x3fff3efa + 16 < 0x3fff3f0a ?
```

And I would get a valid address when reading the additional byte.

I'm giving that a closer look.

Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: Let's assume `len = addrlen` and `bufpos = buf` -> `buflim = buf + addrlen`

That means `memcpy(out, buf, len)` should be as valid as `memcpy(out, bufpos, addrlen)`, so the change is correct.

File: sys/net/application_layer/dns/dns.c (hunk 3 above)
Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: But looks like the`AF_UNSPEC` case is broken too 🤷‍♂️

File: sys/net/application_layer/dns/dns.c (hunk 1 above)
Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: I've decided for 128 bytes (phoronix.com gives me a 86 byte reply), but to re-use the reply buffer for the request too as we never need both at the same time.

File: sys/net/application_layer/dns/dns.c (hunk 3 above)
Comment (miri64) [reply sys/net/application_layer/dns/dns.c]: But... this isn't `sock_dns_query()` but `_parse_dns_reply()`.

Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: The return value was simply passed on.

Comment (miri64) [reply sys/net/application_layer/dns/dns.c]: Then you fix either

1. the check below as well
2. not pass on the value

;-) just changing the return value seems wrong.

Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: I already changed it in https://github.com/RIOT-OS/RIOT/pull/13450/commits/1c0d75f7e57a0504b5262fac50813177d310bbef, I'm just not happy with the API.

File: sys/net/application_layer/dns/dns.c (hunk 2 above)
Comment (miri64) [reply sys/net/application_layer/dns/dns.c]: Right, because `bufpos + addrlen` is also the first byte after the address.... Sorry for the noise...

File: sys/net/application_layer/dns/dns.c [hunk 4]
```diff
@@ -168,11 +168,9 @@ static int _parse_dns_reply(uint8_t *buf, size_t len, void* addr_out, int family
     return -1;
 }
 
+static uint8_t dns_buf[SOCK_DNS_BUF_LEN];
```
Comment (miri64) [inline sys/net/application_layer/dns/dns.c]: *If* you want to make this global you need to protect it now. If two threads call `sock_dns_query()` now, they are in a race for the buffer space. I would prefer keeping it in the stack though (less complicated and doesn't lead to side effects).

Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: I moved it back on the stack.

**Comment by benpicco** [comment]
I restored the test to use `AF_UNSPEC` and `sock_dns_query()` to return the size of the address again, updated the documentation to reflect that.

The test is passing now again on `native`.

**Comment by miri64** [comment]
I've marked it as an API change due to the doc change. However, since the doc is just adopted to the behavior, I don't think we need two ACKs here.

File: sys/net/application_layer/dns/dns.c [hunk 5]
```diff
@@ -216,14 +188,43 @@ int sock_dns_query(const char *domain_name, void *addr_out, int family)
     }
 
     for (int i = 0; i < SOCK_DNS_RETRIES; i++) {
+        uint8_t *buf = dns_buf;
+
+        sock_dns_hdr_t *hdr = (sock_dns_hdr_t*) buf;
+        memset(hdr, 0, sizeof(*hdr));
+        hdr->id = 0; /* random? */
```
Comment (miri64) [inline sys/net/application_layer/dns/dns.c]: I know this is just pulled down, but this should at least come from a variable now, that it is re-set on every retry.

Comment (benpicco) [reply sys/net/application_layer/dns/dns.c]: `random_bytes(&hdr->id, sizeof(hdr->id));`?

File: sys/net/application_layer/dns/dns.c [hunk 6]
```diff
@@ -216,14 +188,43 @@ int sock_dns_query(const char *domain_name, void *addr_out, int family)
     }
 
     for (int i = 0; i < SOCK_DNS_RETRIES; i++) {
+        uint8_t *buf = dns_buf;
+
+        sock_dns_hdr_t *hdr = (sock_dns_hdr_t*) buf;
+        memset(hdr, 0, sizeof(*hdr));
+        hdr->id++; /* random? */
```
Comment (miri64) [inline sys/net/application_layer/dns/dns.c]: This wasn't what I was asking of you... This is not correct AFAIK.

1. The `id` should not increase with every retry, but every transaction.
2. It is now just 1 every time...

What I actually wanted is
```suggestion
        hdr->id = id;
```

with `id` being declared as

```C
uint16_t id = 0; /* random? */
```

outside of the for-loops scope. This way, you

1. don't change behavior
2. allow for future devs that do want to introduce requested randomness to not fall into the same trap you just did ;-).

**Comment by miri64** [comment]
Regarding the border router not forwarding the RDNSS option:

1. Did you set `GNRC_IPV6_NIB_CONF_DNS=1`?
2. Is `sock_dns_server` set correctly in `_handle_rdnsso()`? https://github.com/RIOT-OS/RIOT/blob/63f805c5b7407e3d6dfe8a29a2c2d19394ca05d1/sys/net/gnrc/network_layer/ipv6/nib/nib.c#L1366-L1422 
3. Is the option for the sent router advertisement constructed correctly in `_build_ext_opts()`?
https://github.com/RIOT-OS/RIOT/blob/63f805c5b7407e3d6dfe8a29a2c2d19394ca05d1/sys/net/gnrc/network_layer/ipv6/nib/_nib-router.c#L137-L156

**Comment by benpicco** [comment]
> Did you set `GNRC_IPV6_NIB_CONF_DNS=1`?

I didn't know such option exists, but it gets set automatically if `gnrc_ipv6_nib_dns` is used - for `tests/gnrc_sock_dns` this is the case.

I will investigate the 2. & 3. when I'm home.

**Comment by miri64** [comment]
> I didn't know such option exists, but it gets set automatically if `gnrc_ipv6_nib_dns` is used - for `tests/gnrc_sock_dns` this is the case.
> 
> I will investigate the 2. & 3. when I'm home.

but not for `gnrc_border_router`, right?

**Comment by benpicco** [comment]
When I add `gnrc_ipv6_nib_dns` to `gnrc_border_router` it will indeed forward the DNS server information!

**Comment by benpicco** [comment]
And with `CFLAGS += -DTHREAD_STACKSIZE_DEFAULT=1024` the crashes on ATmega also stop.
