### PR TITLE
pkg/semtech-loramac: Reduce timeout in timer

### LINKED ISSUE #10103: semtech-loramac not joining with DR above 2 after update
#### Description
While trying to run the lorawan example I found that any join attempt after setting the Data Rate to a number above 2 fails. This seems to be related to the recently merged PR that updates the semtech-loramac implementation #8864. I tested the lorawan example with the previous version (checked out a commit before the PR was merged) and it works.

#### Steps to reproduce the issue
1. Enable debug on ```semtech_loramac.c```.
2. Run the lorawan example:
```
BOARD=b-l072z-lrwan1 make clean flash term -C examples/lorawan/
```
You can also try to modify the Data Rate, and check that it works:
```C
    semtech_loramac_set_dr(&loramac, LORAMAC_DR_2);
```

#### Expected results
Get something like 
```
INFO # Starting join procedure
INFO # [semtech-loramac] Starting join procedure: 0
INFO # [semtech-loramac] loramac cmd msg
INFO # [semtech-loramac] starting OTAA join
INFO # [semtech-loramac] Transmission completed
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MLME confirm event
INFO # [semtech-loramac] join succeeded
```

#### Actual results
```
INFO # Starting join procedure
INFO # [semtech-loramac] Starting join procedure: 0
INFO # [semtech-loramac] loramac cmd msg
INFO # [semtech-loramac] starting OTAA join
INFO # [semtech-loramac] Transmission completed
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] RX timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] RX timer timeout
INFO # [semtech-loramac] MAC timer timeout
INFO # [semtech-loramac] MLME confirm event
INFO # [semtech-loramac] join not successful
INFO # [semtech-loramac] loramac join notification msg
INFO # Join procedure failed
```
----

#### Further tests
I also tried running the ```tests/pkg_semtech-loramac``` application but it does not join when the Data Rate is above 2:
```
> loramac set dr 5
INFO #  loramac set dr 5

> loramac get dr
INFO #  loramac get dr
INFO # DATARATE: 5

> loramac join otaa
INFO #  loramac join otaa
INFO # Join procedure failed!

> loramac set dr 0
INFO #  loramac set dr 0

> loramac join otaa
INFO #  loramac join otaa
INFO # Join procedure succeeded!
```

### PR DESCRIPTION
**Pull request by leandrolanzieri**
### Contribution description
This modifies the time in which the timeout is triggered in advance in the semtech-loramac timer module.
This value has been reduced for the latest version update of semtech_loramac package (#8864), but for datarates above 2 the downlink messages in the join process are missed (see #10103).

### Testing procedure
1- Run the `lorawan` example with the current master. As it uses DR 5 it should fail to join.
2- Apply the patch and the join should succeed.

### Issues/PRs references
Fixes #10103
#8864

### CODE REVIEW

File: pkg/semtech-loramac/contrib/semtech_loramac_timer.c [hunk 1]
```diff
@@ -62,9 +62,10 @@ void TimerSetValue(TimerEvent_t *obj, uint32_t value)
 
     /* According to the lorawan specifications, the data sent from the gateway
        could arrive with a short shift in time of +/- 20ms. Here the timeout is
-       triggered 22ms in advance to make sure the radio switches to RX mode on
-       time and doesn't miss any downlink messages. */
-    obj->timeout = (value - 22) * US_PER_MS;
+       triggered 50ms in advance to make sure the radio switches to RX mode on
+       time and doesn't miss any downlink messages, taking in consideration
+       possible xtimer innaccuracies. */
```
Comment (aabadie) [inline pkg/semtech-loramac/contrib/semtech_loramac_timer.c]: I think it's `inaccuracies`

Comment (leandrolanzieri) [reply pkg/semtech-loramac/contrib/semtech_loramac_timer.c]: oops...

**Comment by leandrolanzieri** [comment]
Done!

**Comment by fesselk** [comment]
According to the LoRa specs  https://lora-alliance.org/resource-hub/lorawantm-specification-v11 Paragraph 3.3.1 the Receive Windows after Transmitting should account for a 22 **micro**seconds (us or µs) delay inaccuracy  the comment in current master:pkg/semtech-loramac/contrib/semtech_loramac_timer.c contains a comment starting at  line 63
seems wrong to me ( stating milliseconds). I am not sure about the inaccuracy of xtimer but 50ms or 22ms  seem huge for me. This might have caused on #10352
