### PR TITLE
dist/tools/usb-serial: call ttys.py with its path

### LINKED ISSUE #19805: Not able to flash binary on samr21-xpro boards choosing serial number
#### Description
Not able to flash binary on samr21-xpro boards choosing serial number.

#### Steps to reproduce the issue

I am trying to work with 2 samr21-xpro boards, however, I can't flash binary on the board I want when I am choosing a Serial number.

Below, commands I have executed : 
```shell
git clone https://github.com/RIOT-OS/RIOT.git
cd RIOT/
git checkout 2023.04-branch
make list-ttys 
```
This last command shows the 2 boards I use with their Serial number. 
To show you the bug, I used the hello-world example : 
```shell
cd examples/hello-world
make flash term BOARD=samr21-xpro SERIAL=ATML2127031800003035 
```
It respond : 
```shell 
/home/dev/RIOT/dist/tools/usb-serial/find-tty.sh: ligne 10: ./ttys.py: Aucun fichier ou dossier de ce type
/home/dev/RIOT/makefiles/boards/sam0.inc.mk:11: *** Did not find a device with serial ATML2127031800003035. Arrêt.
```
However, without Serial parameter, RIOT works as expected : 
```shell 
make flash term BOARD=samr21-xpro
```

#### Expected results

I can choose which board I would like to flash using serial number.
#### Actual results

When I try to specify serial number, it respond : 
```shell 
/home/dev/RIOT/dist/tools/usb-serial/find-tty.sh: ligne 10: ./ttys.py: Aucun fichier ou dossier de ce type
/home/dev/RIOT/makefiles/boards/sam0.inc.mk:11: *** Did not find a device with serial ATML2127031800003035. Arrêt.
```
#### Versions

OS : Ubuntu 22.04.2 LST
Build environment : 
    - native gcc: gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
    - arm-none-eabi-gcc: arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description
This PR provides a fix for #19805
When calling `SERIAL=xxx make flash` the command failed because the script `dist/tools/usb-serial/find-ttys.sh` tries to call `ttys.py` but it doesn't find it. So pass the full path to `ttys.py` to get rid of the problem.

### Testing procedure
Connect at least two boards to your computer
run `make list-ttys ` to get the ID of your boards
Try to flash one of them with (replace SERIAL with the one you get with the previous command):
`BOARD=xxx SERIAL=xxx make -C tests/leds flash`
It fails on master.
It should works with this PR.

### Issues/PRs references

Fixes #19805

### CODE REVIEW

**Review by maribu — APPROVED** [review]

**Comment by maribu** [comment]
bors merge

File: dist/tools/usb-serial/find-tty.sh [hunk 1]
```diff
@@ -7,7 +7,7 @@
 exit_code=1
 
 for serial in "$@"; do
-    if ./ttys.py --format path --serial "$serial"; then
+    if ${RIOTTOOLS}/usb-serial/ttys.py --format path --serial "$serial"; then
```
Comment (maribu) [inline dist/tools/usb-serial/find-tty.sh:10]:
```suggestion
    if "${RIOTTOOLS}/usb-serial/ttys.py" --format path --serial "$serial"; then
```

Maybe we should also fall back `RIOTTOOLS` to `.` when not provided, so that `./find-tty.sh` still works?

**Comment by maribu** [comment]
bors cancel

File: dist/tools/usb-serial/find-tty.sh (hunk 1 above)
Comment (dylad) [reply dist/tools/usb-serial/find-tty.sh:10]: Sure I'll change.

**Comment by dylad** [comment]
I've applied @maribu patch to both `list-tty.sh` and `find-tty.sh` scripts. That should do the trick.

**Comment by maribu** [comment]
bors merge

**Comment by dylad** [comment]
Thanks @maribu

**Comment by maribu** [comment]
Backport provided in #19830

**Comment by maribu** [comment]
Backport provided in #19831
