### PR TITLE
pkg/semtech-loramac: improve TX status management after sending a message

### LINKED ISSUE #10352: lorawan-example not working
LoRaWAN stopped working for my application, to verify my Application isn't wrong i tested the lorawan-example and found it also not working. 

#### Description
lorawan-example does not work any more (branch: master) it stops after trying to send the message.

last working commit:6dfc07b0761abe685b6a935cc0b4a1fc87178394
just before "adapt to v4.4.1" 

my REGION is set to EU868.

#### Steps to reproduce the issue

enable debugging in  semtech-loramac.c 
build and flash the loramac-example
'''
#make clean flash term

xx:30:07,821 - INFO # [semtech-loramac] MAC timer timeout
xx:30:08,063 - INFO # [semtech-loramac] MAC timer timeout
xx:30:08,156 - INFO # [semtech-loramac] MLME confirm event
xx:30:08,160 - INFO # [semtech-loramac] join succeeded
xx:30:08,164 - INFO # [semtech-loramac] loramac join notification msg
xx:30:08,166 - INFO # Join procedure succeeded
xx:30:08,168 - INFO # Sending: This is RIOT!
xx:30:08,172 - INFO # [semtech-loramac] loramac cmd msg
xx:30:08,177 - INFO # [semtech-loramac] send frame This is RIOT!
xx:30:08,186 - INFO # [semtech-loramac] MCPS request: confirmed TX
xx:30:08,191 - INFO # [semtech-loramac] MCPS request: dutycycle restricted
xx:30:08,201 - INFO # [semtech-loramac] loramac TX status msg
''''

#### Expected results

working example
'''
xx:45:23,723 - INFO # [semtech-loramac] MAC timer timeout
xx:45:24,612 - INFO # [semtech-loramac] MAC timer timeout
xx:45:25,568 - INFO # [semtech-loramac] MAC timer timeout
xx:45:26,524 - INFO # [semtech-loramac] MAC timer timeout
xx:45:27,480 - INFO # [semtech-loramac] MAC timer timeout
xx:45:27,721 - INFO # [semtech-loramac] MAC timer timeout
xx:45:27,820 - INFO # [semtech-loramac] MLME confirm event
xx:45:27,823 - INFO # [semtech-loramac] join succeeded
xx:45:27,827 - INFO # [semtech-loramac] loramac join notification
xx:45:27,829 - INFO # Join procedure succeeded
xx:45:27,832 - INFO # Sending: This is RIOT!
xx:45:27,834 - INFO # [semtech-loramac] loramac cmd
xx:45:27,838 - INFO # [semtech-loramac] send frame This is RIOT!
xx:45:27,841 - INFO # [semtech-loramac] MCPS_CONFIRMED
xx:45:27,850 - INFO # [semtech-loramac] MCPS request OK
xx:45:28,802 - INFO # [semtech-loramac] MAC timer timeout
xx:45:29,758 - INFO # [semtech-loramac] MAC timer timeout
xx:45:30,713 - INFO # [semtech-loramac] MAC timer timeout
xx:45:30,858 - INFO # [semtech-loramac] TX timer timeout
xx:45:31,670 - INFO # [semtech-loramac] MAC timer timeout
xx:45:31,673 - INFO # [semtech-loramac] MCPS confirm event
xx:45:31,674 - INFO # [semtech-loramac] loramac TX failed
xx:45:31,678 - INFO # [semtech-loramac] MAC reply received: 5
'''
#### Actual results

see above

#### Versions
Operating System Environment
-----------------------------
       Operating System: "Debian GNU/Linux" 
                 Kernel: Linux 4.18.0-2-amd64 x86_64 unknown

Installed compiler toolchains
-----------------------------
             native gcc: gcc (Debian 8.2.0-9) 8.2.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (15:7-2018-q2-4) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                avr-gcc: avr-gcc (GCC) 5.4.0
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
                  clang: clang version 6.0.1-9.2 (tags/RELEASE_601/final)

Installed compiler libs
-----------------------
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                  cmake: cmake version 3.12.3
               cppcheck: Cppcheck 1.84
                doxygen: 1.8.13
                 flake8: missing
                    git: git version 2.19.1
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 2.7.15+
                python2: Python 2.7.15+
                python3: Python 3.6.7
             coccinelle: missing

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is an attempt to fix #10352. The idea is to better manage the TX status returned by the MAC right after a send.

The caller code has to take care of this return code (ok, error, mac_busy, dutycycle_restriction, etc) and not call the receive function in not ok.

To achieve a status returned by the send function, I fixed a missing management of the status IPC messages returned from the MAC. Now all cases are correctly taken into account. This improves things. 

The `examples/lorawan` and `tests/pkg_semtech-loramac` have been adapted accordingly to the change.

The doxygen documentation of the send/recv functions has also been adapted.

### Testing procedure

- Run the `tests/pkg_semtech-loramac` application, configure the device, join a network (OTAA or ABP) and send frames using different datarates. The node should always be responsive after a receive or after an error happens with the send (dutycycle for example).
- Configure and run the `examples/lorawan`, it should work smoothly.

### Issues/PRs references

Probably fixes #10352

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
Testing now, will get back with the results.

File: pkg/semtech-loramac/contrib/semtech_loramac.c [hunk 1]
```diff
@@ -834,7 +834,14 @@ uint8_t semtech_loramac_send(semtech_loramac_t *mac, uint8_t *data, uint8_t len)
 
     _semtech_loramac_call(_send, &params);
 
-    return SEMTECH_LORAMAC_TX_SCHEDULE;
+    /* Wait for TX status information from the MAC */
```
Comment (leandrolanzieri) [inline pkg/semtech-loramac/contrib/semtech_loramac.c]: I think setting the `caller_pid` before calling `_semtech_loramac_call(...)` is missing, otherwise the msg never arrives
```C
mac->caller_pid = thread_getpid();
```

Comment (aabadie) [reply pkg/semtech-loramac/contrib/semtech_loramac.c]: Should be fixed now, can you try again @leandrolanzieri ? (I did and it works much better indeed :) )

**Comment by fesselk** [comment]
seems to work since 7d49dff
`
2019-01-30 16:49:33,537 - INFO # [semtech-loramac] Transmission completed
2019-01-30 16:49:33,540 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:34,509 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:35,515 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:36,522 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:37,526 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:37,531 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:37,615 - INFO # [semtech-loramac] MLME confirm event
2019-01-30 16:49:37,618 - INFO # [semtech-loramac] join succeeded
2019-01-30 16:49:37,622 - INFO # [semtech-loramac] loramac join notification msg
2019-01-30 16:49:37,625 - INFO # Join procedure succeeded
2019-01-30 16:49:37,627 - INFO # Sending: This is RIOT!
2019-01-30 16:49:37,630 - INFO # [semtech-loramac] loramac cmd msg
2019-01-30 16:49:37,633 - INFO # [semtech-loramac] send frame This is RIOT!
2019-01-30 16:49:37,638 - INFO # [semtech-loramac] MCPS request: confirmed TX
2019-01-30 16:49:37,644 - INFO # [semtech-loramac] MCPS request: dutycycle restricted
2019-01-30 16:49:37,647 - INFO # [semtech-loramac] received TX status
2019-01-30 16:49:37,652 - INFO # [semtech-loramac] forward TX status to caller thread
2019-01-30 16:49:37,657 - INFO # Cannot send message 'This is RIOT!', ret code: 11
2019-01-30 16:49:56,843 - INFO # Sending: This is RIOT!
2019-01-30 16:49:56,846 - INFO # [semtech-loramac] loramac cmd msg
2019-01-30 16:49:56,849 - INFO # [semtech-loramac] send frame This is RIOT!
2019-01-30 16:49:56,853 - INFO # [semtech-loramac] MCPS request: confirmed TX
2019-01-30 16:49:56,862 - INFO # [semtech-loramac] MCPS request: OK
2019-01-30 16:49:56,865 - INFO # [semtech-loramac] received TX status
2019-01-30 16:49:56,870 - INFO # [semtech-loramac] forward TX status to caller thread
2019-01-30 16:49:56,924 - INFO # [semtech-loramac] Transmission completed
2019-01-30 16:49:57,864 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:57,873 - INFO # [semtech-loramac] MAC timer timeout
2019-01-30 16:49:57,967 - INFO # [semtech-loramac] MCPS confirm event
2019-01-30 16:49:57,971 - INFO # [semtech-loramac] MCPS confirm event OK
2019-01-30 16:49:57,975 - INFO # [semtech-loramac] MCPS confirm event: CONFIRMED
2019-01-30 16:49:57,979 - INFO # [semtech-loramac] MCPS indication event
2019-01-30 16:49:57,983 - INFO # [semtech-loramac] MCPS indication Unconfirmed
2019-01-30 16:49:57,986 - INFO # [semtech-loramac] MCPS indication: TX done
2019-01-30 16:49:57,990 - INFO # [semtech-loramac] received TX status
2019-01-30 16:49:57,995 - INFO # [semtech-loramac] forward TX status to caller thread
2019-01-30 16:49:57,998 - INFO # [semtech-loramac] MAC reply received: 6
2019-01-30 16:50:17,187 - INFO # Sending: This is RIOT!

`

File: pkg/semtech-loramac/contrib/semtech_loramac.c (hunk 1 above)
Comment (leandrolanzieri) [reply pkg/semtech-loramac/contrib/semtech_loramac.c]: This fixes the issue. I tested using the example and the pkg test app, both on b-l072z-lrwan1 and lobaro-lorabox boards :+1:

**Comment by aabadie** [comment]
@leandrolanzieri, thanks a lot for your sensible review and testing!

**Comment by leandrolanzieri** [comment]
@aabadie thank you for this fix!
