### PR TITLE
cpu/esp: esp_now_netdev fixes and optimizations

### LINKED ISSUE #10682: cpu/esp_common: esp_now netdev problems
#### Description

Although the problems described in issue #10672 were solved, there seem to be further problems that occur on heavy load, at least for ESP-NOW:

1. sometimes 6Lo fragments are kept in the packet buffer
2. a single ping with no data is not possible after heavy load with ping timeouts

#### Steps to reproduce the issue

Precondition:
- Test with two ESP32 nodes, one pinging and one answering.
- Test with heavy traffic and `ping timeout`s executed: 
    ```
    ping6 1000 fe80::32ae:a4ff:fe18:7a3d 1232 0
    ```
- Packet buffers on both sides are empty after the test!

Send one single small ping:
```
ping6 1 fe80::32ae:a4ff:fe18:7a3d
```
On air, we can dump the following WiFi frame
```
0040   ** ** ** ** dd 3b 18 fe 34 04 01 01 41 60 00 00
0050   00 00 0c 3a 40 fe 80 00 00 00 00 00 00 32 ae a4
0060   ff fe 41 60 f9 fe 80 00 00 00 00 00 00 32 ae a4
0070   ff fe 18 7a 3d 80 00 52 cc 00 54 00 01 58 58 58
0080   58
```
where `dd 3b 18 fe 34 04 01 01` is the ESP-NOW header including the one byte `esp_now_header_t`.

On answering node this leads to
```
6lo rfrag: entry 0x3ffbc53c (30:AE:A4:41:60:F9, 30:AE:A4:18:7A:3D, 1280, 49) created
6lo rfrag: add interval (1200, 1279) to entry (30:AE:A4:41:60:F9, 30:AE:A4:18:7A:3D, 1280, 49)
```

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR provides a fix of problem 2 in issue #10682.

As described in #10682, a single ping without data was not possible anymore after heavy load with ping timeouts. The reason was that ISR events got lost and messed up the ringbuffer used in `esp_now_netdev`.

This PR is rather an evolution than only a fix. All different steps are realized as separate commits which contain the following changes:

1. `_recv` function of `esp_now_netdev` simplified according to the possible parameter values.
2. `_recv` function of `esp_now_netdev` updated to drop the frame as documented in new API if the parameter `len` is smaller than the received frame.
3. Lost of `NETDEV_EVENT_ISR` events in `esp_now_netdev` fixed.

In further extensive stress tests the following could be figured out:

- Function `esp_now_recv_cb` is executed in the context of the `wifi` thread (this was already known).
- The ISRs which handle the hardware interrupts from the WiFi interface only pass events to a message queue of the `wifi` thread.
- The `wifi` thread then processes the events sequentially and executes registered callback functions like `esp_now_recv_cb` asynchronously.
- This corresponds to the `NETDEV_EVENT_ISR` approach in GNRC.

This results in the following facts:

- Function `esp_now_recv_cb` will not be reentered.
- Execution of function `esp_now_recv_cb` is executed in the context of the highest priority thread and is therefore not interrupted or superseded by other threads.

These facts allow the following optimizations which are provided step by step as separate commits.

1. `NETDEV_EVENT_ISR` events are not needed. The execution of `netif::_recv` and thus `esp_now_netdev::_recv` can be triggered directly with `NETDEV_EVENT_RX_COMPLETE` on the receiption of a frame in `esp_now_recv_cb`.
2. Mutual exclusion is not required anymore since `esp_now_recv_cb` and `esp_now_netdev::_recv` are executed sequentially in same thread context.
3. Handling of critical section by disabling/enabling interrupts is not needed.
4. If `esp_now_netdev::_recv` is executed immediately in `esp_now_recv_cb` and in same thread context, there is no need for a ring buffer anymore.
5. There is even no buffer required. Received data can be copied directly from the buffer of the `wifi` thread.

Although function `esp_now_recv_cb` will not be reentered, it is secured by an additional boolean variable to avoid potential data inconsistencies. If the NDEBUG macro is undefined, an assertion is used instead for debugging purposes.

### Testing procedure

Use at least two or more ESP32 nodes and flash them with `examples/gnrc_networking`, e.g.:
```
USEMODULE=esp_now make -C examples/gnrc_networking BOARD=esp32-wroom-32 flash
```
Use the `ping` command to ping from each node another node to produce heavy load, either with two nodes
```
node1> ping6 10000 <node2_addr> 1232 0
node2> ping6 10000 <node1_addr> 1232 0
```
or with three nodes
```
node1> ping6 10000 <node2_addr> 1232 0
node2> ping6 10000 <node3_addr> 1232 0
node3> ping6 10000 <node1_addr> 1232 0
```
A further test is bombarding one node from two other nodes:
```
node1> ping6 10000 <node3_addr> 1232 0
node2> ping6 10000 <node3_addr> 1232 0
node3> 
```

### Issues/PRs references

This PR fixes #10682 problem 2, the stucked gnrc buffer problem remains.
This PR is a follow-on PR of #10581, #10679, #10680.

### CODE REVIEW

**Comment by gschorcht** [comment]
@TimoRoth Sorry, I used the wrong issue by mistake when I was asking you to take a look to the changes for esp_now.

**Comment by gschorcht** [comment]
@miri64 
> I don't have the hardware to test this :-/

I know, but it would be really great if you could take a look to the changes in `esp_now_netdev::esp_now_recv_cn` and `esp_now_netdev::_recv` whether the approach without using `NETDEV_EVENT_ISR` events and buffers is ok from your point of view. I have tried to document carefully by comments why I think that is possible to it in that way.

**Comment by gschorcht** [comment]
@TimoRoth Could you test the changes? I would like to make some progress with these changes since they increase the stability a lot.

**Comment by MrKevinWeiss** [comment]
Here are some results from my testing:  node0 = `esp32-wroom-32`, node1 = `esp32-wrover-32`


It seems the uart or USB get messed up on the esp32-wrover-32 board.
*NODE0*
```
2019-01-08 11:14:57,718 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2931 hop limit=64 time = 84.577 ms
2019-01-08 11:14:57,802 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2932 hop limit=64 time = 83.304 ms
2019-01-08 11:14:57,878 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2933 hop limit=64 time = 74.932 ms
2019-01-08 11:14:57,951 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2934 hop limit=64 time = 72.539 ms
2019-01-08 11:14:58,024 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2935 hop limit=64 time = 72.540 ms
2019-01-08 11:14:58,103 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2936 hop limit=64 time = 78.065 ms
2019-01-08 11:14:58,183 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2937 hop limit=64 time = 79.280 ms
2019-01-08 11:14:58,261 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2938 hop limit=64 time = 79.139 ms
2019-01-08 11:14:58,341 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2939 hop limit=64 time = 77.204 ms
2019-01-08 11:14:58,419 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2940 hop limit=64 time = 78.482 ms
2019-01-08 11:14:58,498 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2941 hop limit=64 time = 77.370 ms
2019-01-08 11:14:58,579 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2942 hop limit=64 time = 79.045 ms
2019-01-08 11:14:58,653 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2943 hop limit=64 time = 73.726 ms
2019-01-08 11:14:58,730 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2944 hop limit=64 time = 75.850 ms
2019-01-08 11:14:58,802 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2945 hop limit=64 time = 72.761 ms
2019-01-08 11:14:58,879 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2946 hop limit=64 time = 74.112 ms
2019-01-08 11:14:58,951 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2947 hop limit=64 time = 71.935 ms
2019-01-08 11:14:59,029 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2948 hop limit=64 time = 76.500 ms
2019-01-08 11:14:59,107 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2949 hop limit=64 time = 77.375 ms
2019-01-08 11:14:59,181 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2950 hop limit=64 time = 73.162 ms
2019-01-08 11:14:59,258 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2951 hop limit=64 time = 75.760 ms
2019-01-08 11:14:59,330 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2952 hop limit=64 time = 72.998 ms
2019-01-08 11:14:59,432 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2953 hop limit=64 time = 101.460 ms
2019-01-08 11:14:59,508 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2954 hop limit=64 time = 73.229 ms
2019-01-08 11:14:59,584 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2955 hop limit=64 time = 75.480 ms
2019-01-08 11:14:59,717 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2956 hop limit=64 time = 131.115 ms
2019-01-08 11:14:59,792 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2957 hop limit=64 time = 74.951 ms
2019-01-08 11:14:59,867 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2958 hop limit=64 time = 73.815 ms
2019-01-08 11:14:59,947 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2959 hop limit=64 time = 79.875 ms
2019-01-08 11:15:00,028 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2960 hop limit=64 time = 79.608 ms
2019-01-08 11:15:00,110 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2961 hop limit=64 time = 82.444 ms
2019-01-08 11:15:00,178 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2962 hop limit=64 time = 68.543 ms
2019-01-08 11:15:00,258 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2963 hop limit=64 time = 76.824 ms
2019-01-08 11:15:00,343 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2964 hop limit=64 time = 83.344 ms
2019-01-08 11:15:00,424 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2965 hop limit=64 time = 82.344 ms
2019-01-08 11:15:00,507 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2966 hop limit=64 time = 81.331 ms
2019-01-08 11:15:00,583 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2967 hop limit=64 time = 75.460 ms
2019-01-08 11:15:00,669 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2968 hop limit=64 time = 84.321 ms
2019-01-08 11:15:00,751 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2969 hop limit=64 time = 80.685 ms
2019-01-08 11:15:00,832 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2970 hop limit=64 time = 81.880 ms
2019-01-08 11:15:00,909 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2971 hop limit=64 time = 74.584 ms
2019-01-08 11:15:00,984 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2972 hop limit=64 time = 74.699 ms
2019-01-08 11:15:01,059 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2973 hop limit=64 time = 74.293 ms
2019-01-08 11:15:01,141 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=84 seq=2974 hop limit=64 time = 80.718 ms
```


*NODE1*
```
2019-01-08 11:14:15,962 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2376 hop limit=64 time = 81.370 ms
2019-01-08 11:14:16,041 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2377 hop limit=64 time = 76.094 ms
2019-01-08 11:14:16,107 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2378 hop limit=64 time = 71.438 ms
2019-01-08 11:14:16,186 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2379 hop limit=64 time = 76.080 ms
2019-01-08 11:14:16,251 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2380 hop limit=64 time = 73.562 ms
2019-01-08 11:14:16,332 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2381 hop limit=64 time = 75.593 ms
2019-01-08 11:14:16,410 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2382 hop limit=64 time = 70.731 ms
2019-01-08 11:14:16,488 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2383 hop �њ time = 77.245 ms
2019-01-08 11:14:16,602 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2384 hop limit=64 time = 116.016 ms
2019-01-08 11:14:16,681 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2385 hop limit=64 time = 75.181 ms
2019-01-08 11:14:16,764 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2386 hop limit=64 time = 80.035 ms
2019-01-08 11:14:16,840 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2387 hop limit=64 time = 74.040 ms
2019-01-08 11:14:16,904 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2388 hop limit=64 time = 73.843 ms
2019-01-08 11:14:16,986 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2389 hop limit=64 time = 77.222 ms
2019-01-08 11:14:17,066 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2390 hop limit=64 time = 76.392 ms
2019-01-08 11:14:17,236 - INFO # 1240 bytes from fe80::260a:c4ff:feT��1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2392 hop limit=64 time = 86.195 ms
2019-01-08 11:14:17,316 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2393 hop limit=64 time = 82.384 ms
2019-01-08 11:14:17,411 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2394 hop limit=64 time = 84.167 ms
2019-01-08 11:14:17,476 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2395 hop limit=64 time = 73.625 ms
2019-01-08 11:14:17,555 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2396 hop limit=64 time = 70.197 ms
2019-01-08 11:14:17,618 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2397 hop limit=64 time = 69.015 ms
2019-01-08 11:14:17,699 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2398 hop limit=64 time = 77.064 ms
2019-01-08 11:14:17,779 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2399 hop limit=64 time = 74.943 ms
2019-01-08 11:14:17,844 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2400 hop limit=64 time = 70.537 ms
2019-01-08 11:14:17,923 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2401 hop limit=64 time = 73.576 ms
2019-01-08 11:14:18,003 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2402 hop limit=64 time = 76.886 ms
2019-01-08 11:14:18,067 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2403 hop limit=64 time = 71.928 ms
2019-01-08 11:14:18,147 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2404 hop limit=64 time = 72.434 ms
2019-01-08 11:14:18,226 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2405 hop limit=64 time = 80.470 ms
2019-01-08 11:14:18,305 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2406 hop limit=64 time = 71.933 ms
2019-01-08 11:14:18,372 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2407 hop limit=64 time = 70.834 ms
2019-01-08 11:14:18,451 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2408 hop limit=64 time = 75.880 ms
2019-01-08 11:14:18,530 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2409 hop limit=64 time = 77.091 ms
2019-01-08 11:14:18,609 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2410 hop limit=64 time = 76.993 ms
2019-01-08 11:14:18,684 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5:�+�hop limit=64 time = 76.889 ms
2019-01-08 11:14:18,798 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2412 hop limit=64 time = 116.548 ms
2019-01-08 11:14:18,875 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2413 hop limit=64 time = 69.755 ms
2019-01-08 11:14:18,941 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2414 hop limit=64 time = 75.997 ms
2019-01-08 11:14:19,022 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2415 hop limit=64 time = 78.834 ms
2019-01-08 11:14:19,148 - WARNING # Serial port disconnected, waiting to get reconnected...
2019-01-08 11:14:20,150 - WARNING # Serial port disconnected, waiting to get reconnected...
2019-01-08 11:14:21,151 - WARNING # Try to reconnect to /dev/ttyUSB2 again...
2019-01-08 11:14:21,153 - INFO # Reconnected to serial port /dev/ttyUSB2
2019-01-08 11:14:21,188 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2442 hop limit=64 time = 84.206 ms
2019-01-08 11:14:21,252 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2443 hop limit=64 time = 74.897 ms
2019-01-08 11:14:21,332 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2444 hop limit=64 time = 68.712 ms
2019-01-08 11:14:21,408 - INFO # 1240 bytes from fe80::260a:c4ff:f�B�q=2445 hop limit=64 time = 76.813 ms
2019-01-08 11:14:21,490 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2446 hop limit=64 time = 84.011 ms
2019-01-08 11:14:21,570 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2447 hop limit=64 time = 79.632 ms
2019-01-08 11:14:21,652 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2448 hop limit=64 time = 82.304 ms
2019-01-08 11:14:21,728 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2449 hop limit=64 time = 75.713 ms
2019-01-08 11:14:21,808 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2450 hop limit=64 time = 76.323 ms
2019-01-08 11:14:21,889 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2451 hop limit=64 time = 78.089 ms
2019-01-08 11:14:21,968 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2452 hop limit=64 time = 76.258 ms
2019-01-08 11:14:22,033 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2453 hop limit=64 time = 70.562 ms
2019-01-08 11:14:22,114 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2454 hop limit=64 time = 76.445 ms
2019-01-08 11:14:22,194 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2455 hop limit=64 time = 84.667 ms
2019-01-08 11:14:22,273 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2456 hop limit=64 time = 80.265 ms
2019-01-08 11:14:22,354 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2457 hop limit=64 time = 73.375 ms
2019-01-08 11:14:22,435 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2458 hop limit=64 time = 79.934 ms
2019-01-08 11:14:22,513 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2459 hop limit=64 time = 79.051 ms
2019-01-08 11:14:22,626 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2460 hop limit=64 time = 108.357 ms
2019-01-08 11:14:22,704 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2461 hop limit=64 time = 75.510 ms
2019-01-08 11:14:22,786 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2462 hop limit=64 time = 89.153 ms
2019-01-08 11:14:22,864 - INFO # 1240 bytes from fe80::260a:c4ff:fe0d:beb5: id=85 seq=2463 hop limit=64 time = 78.156 ms
```

**Comment by MrKevinWeiss** [comment]
With master I get something a but different...

node1 seems to transmit very fast.

*NODE0*
```
2019-01-08 11:20:30,426 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=876 hop limit=64 time = 43.896 ms
2019-01-08 11:20:30,469 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=877 hop limit=64 time = 41.664 ms
2019-01-08 11:20:30,519 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=878 hop limit=64 time = 49.910 ms
2019-01-08 11:20:30,566 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=879 hop limit=64 time = 46.098 ms
2019-01-08 11:20:30,614 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=880 hop limit=64 time = 46.396 ms
2019-01-08 11:20:30,665 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=881 hop limit=64 time = 50.211 ms
2019-01-08 11:20:30,716 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=882 hop limit=64 time = 50.726 ms
2019-01-08 11:20:30,762 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=883 hop limit=64 time = 44.962 ms
2019-01-08 11:20:30,807 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=884 hop limit=64 time = 45.691 ms
2019-01-08 11:20:30,864 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=885 hop limit=64 time = 55.993 ms
2019-01-08 11:20:30,913 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=886 hop limit=64 time = 46.950 ms
2019-01-08 11:20:30,964 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=887 hop limit=64 time = 51.093 ms
2019-01-08 11:20:31,011 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=888 hop limit=64 time = 44.513 ms
2019-01-08 11:20:31,058 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=889 hop limit=64 time = 47.317 ms
2019-01-08 11:20:32,075 - INFO # ping timeout
2019-01-08 11:20:32,126 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=890 hop limit=64 time = 40.475 ms
2019-01-08 11:20:33,165 - INFO # ping timeout
2019-01-08 11:20:33,225 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=891 hop limit=64 time = 49.040 ms
2019-01-08 11:20:33,263 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=892 hop limit=64 time = 38.490 ms
2019-01-08 11:20:33,306 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=893 hop limit=64 time = 41.638 ms
2019-01-08 11:20:33,354 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=894 hop limit=64 time = 47.216 ms
2019-01-08 11:20:33,401 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=895 hop limit=64 time = 46.423 ms
2019-01-08 11:20:33,446 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=896 hop limit=64 time = 45.140 ms
2019-01-08 11:20:33,491 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=897 hop limit=64 time = 44.716 ms
2019-01-08 11:20:33,533 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=898 hop limit=64 time = 38.847 ms
2019-01-08 11:20:33,573 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=899 hop limit=64 time = 39.839 ms
2019-01-08 11:20:33,615 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=900 hop limit=64 time = 41.459 ms
2019-01-08 11:20:33,656 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=901 hop limit=64 time = 39.716 ms
```

*NODE1*
```
2019-01-08 11:20:36,434 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4872 hop limit=64 time = 0.769 ms
2019-01-08 11:20:36,437 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4873 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,449 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4874 hop limit=64 time = 0.773 ms
2019-01-08 11:20:36,451 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4875 hop limit=64 time = 0.712 ms
2019-01-08 11:20:36,465 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4876 hop limit=64 time = 1.228 ms
2019-01-08 11:20:36,468 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4877 hop limit=64 time = 0.774 ms
2019-01-08 11:20:36,481 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4878 hop limit=64 time = 0.713 ms
2019-01-08 11:20:36,483 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4879 hop limit=64 time = 0.716 ms
2019-01-08 11:20:36,497 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4880 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,500 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4881 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,513 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4882 hop limit=64 time = 0.707 ms
2019-01-08 11:20:36,516 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4883 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,519 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4884 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,531 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4885 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,533 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4886 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,547 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4887 hop limit=64 time = 0.707 ms
2019-01-08 11:20:36,551 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4888 hop limit=64 time = 0.707 ms
2019-01-08 11:20:36,563 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4889 hop limit=64 time = 0.708 ms
2019-01-08 11:20:36,566 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4890 hop limit=64 time = 0.804 ms
2019-01-08 11:20:36,578 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4891 hop limit=64 time = 0.712 ms
2019-01-08 11:20:36,582 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4892 hop limit=64 time = 0.704 ms
2019-01-08 11:20:36,594 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4893 hop limit=64 time = 0.703 ms
2019-01-08 11:20:36,597 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4894 hop limit=64 time = 0.703 ms
2019-01-08 11:20:36,610 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4895 hop limit=64 time = 0.703 ms
2019-01-08 11:20:36,613 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4896 hop limit=64 time = 0.704 ms
2019-01-08 11:20:36,626 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4897 hop limit=64 time = 0.704 ms
2019-01-08 11:20:36,629 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4898 hop limit=64 time = 0.703 ms
2019-01-08 11:20:36,641 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4899 hop limit=64 time = 0.966 ms
2019-01-08 11:20:36,644 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4900 hop limit=64 time = 0.717 ms
2019-01-08 11:20:36,657 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4901 hop limit=64 time = 0.704 ms
2019-01-08 11:20:36,660 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4902 hop limit=64 time = 0.704 ms
2019-01-08 11:20:36,673 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4903 hop limit=64 time = 0.770 ms
2019-01-08 11:20:36,676 - INFO # 1240 bytes from fe80::860d:8eff:fe18:7e31: id=83 seq=4904 hop limit=64 time = 1.575 ms
2019-01-08 11:20:37,665 - INFO # ping timeout
2019-01-08 11:20:38,673 - INFO # ping timeout
2019-01-08 11:20:39,666 - INFO # ping timeout
2019-01-08 11:20:39,668 - INFO # error: packet buffer full
2019-01-08 11:20:39,669 - INFO # error: packet buffer full
2019-01-08 11:20:39,681 - INFO # error: packet buffer full
2019-01-08 11:20:39,683 - INFO # error: packet buffer full
```

**Comment by gschorcht** [comment]
@MrKevinWeiss Strange, I have stress tested over hours, but I have never seen that the UART interface is affected. UART is realized in Hardware with a buffer oft 128 characters. 
Is it reproducable? Could you try it with another terminal program?

**Comment by MrKevinWeiss** [comment]
I am not too worried about it, I am running things through a usb hub.  Keep in mind it is a different board (node1=esp32-wrover-32).  I will investigate!

**Comment by MrKevinWeiss** [comment]
Yup, just my usb ports, switched to the ones directly connected to the cpu and have 0% packet loss with 1000 pings.  The testing show a noticeable improvement! :+1:

**Comment by gschorcht** [comment]
@MrKevinWeiss Thanks for testing :smile:

**Comment by gschorcht** [comment]
How do we continue with this PR? PR #9917 depends these changes.

File: cpu/esp_common/esp-now/esp_now_netdev.c [hunk 1]
```diff
@@ -200,40 +202,56 @@ static IRAM_ATTR void esp_now_recv_cb(const uint8_t *mac, const uint8_t *data, i
...
+     * callback functions such as `esp_now_recv_cb`.
+     *
+     * It should be therefore not possible to reenter function
+     * `esp_now_recv_cb`. To avoid inconsistencies this is checked by an
+     * additional boolean variable . This can not be realized by a mutex
+     * because `esp_now_recv_cb` would be reentered from same thread context.
+     * If the NDEBUG macro is undefined, an assertion is used instead for
+     * debugging purposes.
+     */
+    assert(!_in_recv_cb);
```
Comment (smlng) [inline cpu/esp_common/esp-now/esp_now_netdev.c]: this seems redundant in light of the following `if`, or not?

File: cpu/esp_common/esp-now/esp_now_netdev.c [hunk 2]
```diff
@@ -200,40 +202,56 @@ static IRAM_ATTR void esp_now_recv_cb(const uint8_t *mac, const uint8_t *data, i
...
-    ringbuffer_add(&_esp_now_dev.rx_buf, (char*)mac, ESP_NOW_ADDR_LEN);
-    ringbuffer_add(&_esp_now_dev.rx_buf, (char*)data, len);
+    _esp_now_dev.rx_mac = (uint8_t*)mac;
+    _esp_now_dev.rx_data = (uint8_t*)data;
+    _esp_now_dev.rx_len = len;
 
+    /*
+     * Since we are not in the interrupt context, we do not have to pass
+     * `NETDEV_EVENT_ISR` first. We can call the receive function directly.
+     * But we have to unlock the mutex and enable interrupts before.
```
Comment (smlng) [inline cpu/esp_common/esp-now/esp_now_netdev.c]: which mutex?

Comment (gschorcht) [reply cpu/esp_common/esp-now/esp_now_netdev.c]: The comments is from  the time when a mutex was used. I forgot to change it it when I removed :wink:

File: cpu/esp_common/esp-now/esp_now_netdev.c (hunk 1 above)
Comment (gschorcht) [reply cpu/esp_common/esp-now/esp_now_netdev.c]: It was added intentionally rather to see when this happens in stress tests during the development process than to suppress it silently. 
Should I remove it?

Comment (gschorcht) [reply cpu/esp_common/esp-now/esp_now_netdev.c]: @smlng I decided to remove it.

**Comment by gschorcht** [comment]
@TimoRoth Thanks for testing again :smile:

File: cpu/esp_common/esp-now/esp_now_netdev.c (hunk 2 above)
Comment (smlng) [reply cpu/esp_common/esp-now/esp_now_netdev.c]: please remove then, afterwards this seems good to go

Comment (gschorcht) [reply cpu/esp_common/esp-now/esp_now_netdev.c]: Of course. Thank you for the review.

**Comment by smlng** [comment]
@TimoRoth thx for reporting, with the tests by @MrKevinWeiss I'd say this is good to go then!

**Comment by gschorcht** [comment]
Thank you all for your support.
