### PR TITLE
ztimer: periph_rtt: ensure RTT_MAX_VALUE is honored

### LINKED ISSUE #13920: stm32: ztimer RTT backend overflow
# Description
Overflow In RTT backend for ztimer on platforms with RTT bit-width smaller than 32-bit. Tested on STM32L4. Issue causes assertion to fail in stm32's RTT implementation.

# Steps to reproduce the issue
In Makefile:
```
USEMODULE += ztimer_msec
USEMODULE += ztimer_periph_rtt
```

Use the following snippet:
```
while (1) {
  ztimer_sleep(ZTIMER_MSEC, 10000);
  foo();
}
```

# Expected results
Function foo() to be called every 10 seconds.

# Actual results
Function foo() is called 3-4 times, then assertion fails in stm32's RTT implementation:
in file cpu/stm32_common/periph/rtt.c at line 157 in function  rtt_set_alarm().

# Versions
Operating System Environment
----------------------------
         Operating System: "Ubuntu" "19.04 (Disco Dingo)"
                   Kernel: Linux 5.0.0-38-generic x86_64 x86_64
             System shell: /usr/bin/dash (probably dash)
             make's shell: /usr/bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 8.3.0-6ubuntu1) 8.3.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (15:7-2018-q2-6) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                  avr-gcc: missing
         mips-mti-elf-gcc: missing
               msp430-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: clang version 8.0.0-3 (tags/RELEASE_800/final)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.1.0"
      mips-mti-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: missing
                    cmake: missing
                 cppcheck: missing
                  doxygen: missing
                      git: git version 2.20.1
                     make: GNU Make 4.2.1
                  openocd: Open On-Chip Debugger 0.10.0
                   python: Python 2.7.16
                  python2: Python 2.7.16
                  python3: Python 3.7.3
                   flake8: error: /usr/bin/python3: No module named flake8
               coccinelle: missing

# Patch
[0002-fix-overflow-at-RTT-back-end-of-ztimer-relevant-for-.patch.txt](https://github.com/RIOT-OS/RIOT/files/4513063/0002-fix-overflow-at-RTT-back-end-of-ztimer-relevant-for-.patch.txt)

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Previously, ztimer would happily set an absolute RTT alarm value that exceeds
RTT's maximum value (though not a longer interval), as the `val` was
simply added to `rtt_get_counter()`.
This commit ensures that the target value wraps around RTT_MAX_VALUE.

Fixes #13920.

### Testing procedure

See #13920.

### Issues/PRs references

Reported wonderfully in #13920.

### CODE REVIEW

File: sys/ztimer/periph_rtt.c [hunk 1]
```diff
@@ -50,7 +51,8 @@ static void _ztimer_periph_rtt_set(ztimer_clock_t *clock, uint32_t val)
     }
 
     unsigned state = irq_disable();
-    rtt_set_alarm(rtt_get_counter() + val, _ztimer_periph_rtt_callback, clock);
+    /* warning: RTT_MAX_VALUE needs to be (2^n) - 1 */
```
Comment (bergzand) [inline sys/ztimer/periph_rtt.c:54]: This requirement should either be asserted in the init and/or be documented somewhere more obvious. Otherwise it is going to lead to hard to debug issues when a RTT peripheral doesn't adhere to this.

Comment (maribu) [reply sys/ztimer/periph_rtt.c:54]: I'm not sure if an assert here is effort well spend. It is very likely that the limit comes from the size of registers holding the current timer value and the next alarm value. And unless some strange stuff like BCD encoding is used, the maximum value will just naturally be `(2^n) - 1`.

And if someone indeed starts producing RTTs with BCD encoding internally used, I'd say it is fine to just never support those.

But it clearly wouldn't hurt to document this requirement. The lowest value could also be documented. But it should be equally unlikely that someone allows negative values in an RTT. (That would make some sense for the year register in an RTC, but I guess no one in her/his right mind would use signed counters here.)

Comment (kaspar030) [reply sys/ztimer/periph_rtt.c]: hm did github eat my reply? I agree that non-`(2^n) - 1` is unlilely. I've added a static_assert anyways.

Comment (kaspar030) [reply sys/ztimer/periph_rtt.c]: I was a bit puzzled why gcc doesn't do this on its own when specifying plain modulo.

Comment (maribu) [reply sys/ztimer/periph_rtt.c]: :+1: for static assert. (I misinterpreted the suggestion as adding a plain assert() with runtime cost)

Comment (bergzand) [reply sys/ztimer/periph_rtt.c]: > +1 for static assert. (I misinterpreted the suggestion as adding a plain assert() with runtime cost)

Well, I would be fine with an assert in the init code, but not in the `_ztimer_periph_rtt_set` function

**Comment by bergzand** [comment]
Please squash!

**Comment by leandrolanzieri** [comment]
Backport provided in #13938
