### PR TITLE
cpu/esp: improve thread safety in newlib locking functions

### LINKED ISSUE #18534: `tests/thread_priority_inversion` failing with `esp32-wroom-32`
#### Description

Nightlies and any PR requiring `CI: run tests` are failing due to this.

#### Steps to reproduce the issue

```
BOARD=esp32-wroom-32 make flash test -C tests/thread_priority_inversion
```

Or look at the nightlies

#### Expected results
Test passes

#### Actual results
Test fails
<details>

```
-- running on worker pi-67e8efb7 thread 1, build number 24423.
-- executing tests for tests/thread_priority_inversion on esp32-wroom-32 (compiled with gnu toolchain):
- executing hook run_test_pre
- resetting USB power...
- waiting for tty to re-attach...
- hook run_test_pre finished
make: Entering directory '/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion'
esptool.py --chip esp32 --port /dev/ttyUSB0 --baud 460800 --before default_reset write_flash -z --flash_mode dout --flash_freq 40m --flash_size detect 0x1000 /tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion/bin/esp32-wroom-32/esp_bootloader/bootloader.bin 0x8000 /tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion/bin/esp32-wroom-32/partitions.bin 0x10000 /tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion/bin/esp32-wroom-32/tests_thread_priority_inversion.elf.bin
esptool.py v2.6
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32D0WDQ6 (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
MAC: 30:ae:a4:f4:7a:e0
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash params set to 0x0320
Compressed 17088 bytes to 11709...

Writing at 0x00001000... (100 %)
Wrote 17088 bytes (11709 compressed) at 0x00001000 in 0.3 seconds (effective 427.1 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 85...

Writing at 0x00008000... (100 %)
Wrote 3072 bytes (85 compressed) at 0x00008000 in 0.0 seconds (effective 3649.1 kbit/s)...
Hash of data verified.
Compressed 103952 bytes to 45598...

Writing at 0x00010000... (33 %)
Writing at 0x00014000... (66 %)
Writing at 0x00018000... (100 %)
Wrote 103952 bytes (45598 compressed) at 0x00010000 in 1.2 seconds (effective 667.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
make: Nothing to be done for 'termdeps'.
make: Leaving directory '/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion'
make: Entering directory '/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion'
r
socat - open:/dev/ttyUSB0,b115200,echo=0,raw,cs8,parenb=0,cstopb=0 
r
r
r
r
ets Jun  8 2016 00:22:57



rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)

configsip: 0, SPIWP:0xee

clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00

mode:DOUT, clock div:2

load:0x3fff0030,len:1360

load:0x40078000,len:12788

ho 0 tail 12 room 4

load:0x40080400,len:2848

entry 0x40080410

Pro cpu up.

Single core mode

Traceback (most recent call last):
  File "/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion/tests/01-run.py", line 21, in <module>
    sys.exit(run(testfunc))
  File "/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/dist/pythonlibs/testrunner/__init__.py", line 28, in run
    logfile=sys.stdout if echo else None)
  File "/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/dist/pythonlibs/testrunner/spawn.py", line 95, in setup_child
    sync_child(child, env)
  File "/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/dist/pythonlibs/testrunner/spawn.py", line 134, in sync_child
    TEST_INTERACTIVE_DELAY)
  File "/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/dist/pythonlibs/testrunner/utils.py", line 30, in test_utils_interactive_sync
    _test_utils_interactive_sync(child, retries, delay)
  File "/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/dist/pythonlibs/testrunner/utils.py", line 22, in _test_utils_interactive_sync
    child.expect_exact(ready_exp, timeout=0)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/spawnbase.py", line 421, in expect_exact
    return exp.expect_loop(timeout)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/expect.py", line 181, in expect_loop
    return self.timeout(e)
  File "/usr/local/lib/python3.5/dist-packages/pexpect/expect.py", line 144, in timeout
    raise exc
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x769d2ad0>
command: /usr/bin/make
args: [b'/usr/bin/make', b'cleanterm']
buffer (last 100 chars): 'de\r\r\n'
before (last 100 chars): 'o 0 tail 12 room 4\r\r\nload:0x40080400,len:2848\r\r\nentry 0x40080410\r\r\nPro cpu up.\r\r\nSingle core mode\r\r\n'
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 3554
child_fd: 5
closed: False
timeout: 10
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_string:
    0: 'READY'
/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/makefiles/tests/tests.inc.mk:22: recipe for target 'test' failed
make: *** [test] Error 1
make: Leaving directory '/tmp/dwq.0.356379192510457/3af8f868589d03099f720231dddc28e8/tests/thread_priority_inversion'
```
</details>

#### Versions
Fails on the CI

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR improves the thread safety of the newlib locking functions as following:

- Dynamic allocation and initialization of the mutex used by a newlib locking variable must not be interrupted. Since a thread context switch can occur on exit from an ISR, the allocation and initialization of such a mutex is guarded by disabling interrupts. The same is done for the release of such a mutex.
- Locking functions implicitly allocate and initialize the mutex used by a newlib locking variable if necessary. This implicit allocation and initialization as well as the subsequent acquiring must not be interrupted. Since a thread context switch can occur on exit from an ISR, the implicit allocation and initialization and the subsequent acquiring of such a newlib locking variable must be guarded by disabling interrupts. The same must be done for the release of such a newlib locking variable.
- Module `malloc_thread_safe` is not needed any longer.

This PR fixes issue #18534 and reverts the change made in PR #18535.

### Testing procedure

```
BOARD=esp32-wroom-32 make flash test -C tests/thread_priority_inversion flash test
```
should work with this PR.
```
BOARD=esp32-wroom-32 make-C tests/malloc_thread_safe flash test 
```
should still work.

### Issues/PRs references

Fixes #18534

### CODE REVIEW

File: cpu/esp_common/syscalls.c [hunk 1]
```diff
@@ -82,13 +82,16 @@ void IRAM_ATTR _lock_init(_lock_t *lock)
...
+    uint32_t state = irq_disable();
     mutex_t* mtx = malloc(sizeof(mutex_t));
 
     if (mtx) {
         memset(mtx, 0, sizeof(mutex_t));
         *lock = (_lock_t)mtx;
     }
     /* cppcheck-suppress memleak; mtx is stored in lock */
+
+    irq_restore(state);
```
Comment (maribu) [inline cpu/esp_common/syscalls.c:94]: I think it would be safe to move this up directly after the call to `malloc()`

File: cpu/esp_common/syscalls.c [hunk 2]
```diff
@@ -102,13 +105,16 @@ void IRAM_ATTR _lock_init_recursive(_lock_t *lock)
...
+    uint32_t state = irq_disable();
     rmutex_t* rmtx = malloc(sizeof(rmutex_t));
 
     if (rmtx) {
         memset(rmtx, 0, sizeof(rmutex_t));
         *lock = (_lock_t)rmtx;
     }
     /* cppcheck-suppress memleak; rmtx is stored in lock */
+
+    irq_restore(state);
```
Comment (maribu) [inline cpu/esp_common/syscalls.c:117]: Same

File: cpu/esp_common/syscalls.c [hunk 3]
```diff
@@ -142,13 +156,17 @@ void IRAM_ATTR _lock_acquire(_lock_t *lock)
 
     assert(lock != NULL);
 
+    uint32_t state = irq_disable();
```
Comment (maribu) [inline cpu/esp_common/syscalls.c:159]: This should not be needed, the `mutex_lock()` below should disable IRQs at critical sections already

File: cpu/esp_common/syscalls.c [hunk 4]
```diff
@@ -176,13 +194,17 @@ void IRAM_ATTR _lock_acquire_recursive(_lock_t *lock)
...
```
Comment (maribu) [inline cpu/esp_common/syscalls.c:197]: Same

**Comment by gschorcht** [comment]
@maribu Two questions regarding this PR:
- The stack size `THREAD_STACKSIZE_SMALL` for the duelling threads is too small for ESP8266 in `tests/malloc_thread_safe`. What would be the best way from your point of view to increase it only for ESP8266. Should I override `THREAD_STACKSIZE_SMALL` in `cpu/esp8266/include/cpu_conf.h`?
- What might be the reason that the following assertion fails https://github.com/RIOT-OS/RIOT/blob/b024458b432410e232278cc889002b31d0ec53ea/core/lib/rmutex.c#L131 if interrupts are disabled in `_lock_acquire_recursive` here https://github.com/RIOT-OS/RIOT/blob/432a57b390d94985aa95c5e8e22ddeadd80602fe/cpu/esp_common/syscalls.c#L197?

File: cpu/esp_common/syscalls.c [hunk 5]
```diff
@@ -194,16 +216,22 @@ int IRAM_ATTR _lock_try_acquire(_lock_t *lock)
...
```
Comment (maribu) [inline cpu/esp_common/syscalls.c:219]: Same

File: cpu/esp_common/syscalls.c [hunk 6]
```diff
@@ -215,16 +243,22 @@ int IRAM_ATTR _lock_try_acquire_recursive(_lock_t *lock)
...
```
Comment (maribu) [inline cpu/esp_common/syscalls.c:246]: Same

**Review by maribu — COMMENTED** [review]
Code looks good to me. If I didn't miss anything, no IRQ disabling is needed in the lock acquire functions.

**Comment by maribu** [comment]
> The stack size THREAD_STACKSIZE_SMALL for the duelling threads in tests/malloc_thread_safe is too small for ESP8266. What would be the best way from your point of view to increase it only for ESP8266. Should I override THREAD_STACKSIZE_SMALL in cpu/esp8266/include/cpu_conf.h?

Sounds good to me. Those definitions are a bit finicky, but to my understanding the basic idea is that if a given program runs fine on Cortex M with the given stack size define, it *should* also run on all others.

> What might be the reason that the following assertion fails for ESP8266 [...]

The assertion should actually detect when one thread is unlocking the rmutex owned by another (something that is perfectly fine for mutex, btw). Assuming that lock operations and unlock operations are matching (that is the same number of unlocks as locks is issued and only an rmutex actually owned by the calling thread is unlocked), I would guess some kind of memory corruption has happened.

File: cpu/esp_common/syscalls.c (hunk 1 above)
Comment (gschorcht) [reply cpu/esp_common/syscalls.c:94]: Hm, as long as `mtx` is not assigned `*lock`, the locking variable looks to be uninitialized. That is, another thread could try to reinitialize the same variable if a context switch occurs after `malloc` what might be the case if interrupts are pending and the interrupts are enabled. This wouldn't be a problem if all locking variables were initialized before scheduling becomes active. Unfortunately, most locking variables in the newlib are implicitly initialized when `_lock_acquire_*` is called the first time. That's why I guarded the whole function.

File: cpu/esp_common/syscalls.c (hunk 3 above)
Comment (gschorcht) [reply cpu/esp_common/syscalls.c:159]: This is what I thought too. But without disabling interrupts, `tests/malloc_thread_safe` crashes on ESP32.

**Comment by gschorcht** [comment]
I had to change a lot to get the locking working for both ESP8266 and ESP32:

- The initialization of locking variables with retargetable locking had to be added to avoid their implicit initialization in `_lock_acquire*` functions. Now the locking variables are either statically defined and initialized or they have to be allocated and initialized explicitly by calling `_lock_init*`. `assert`s ensure that locking variables are initialized when `_lock_acquire*` functions are called.
- For ESP32, the operations on recursive locking variables had to be guarded by disabling interrupts to prevent unintended context switches. For ESP8266, interrupts must not be disabled, otherwise the intended context switch doesn't work when trying to lock a `rmutex` that is already locked by another thread. That was the reason for the `assert` in `rmutex_unlock`.

With these changes `tests/malloc_thread_safety` and `tests/thread_priority_inversion` work absolutely stable on ESP32. Without these changes, `tests/malloc_thread_safety` crashes often, probably because of unintended context switches on exit from ISRs. I wasn't able to catch the problem in debugger.

**Comment by gschorcht** [comment]
Compilation was successful in CI, however 225 of 227 tests failed for ESP32 [log](https://ci.riot-os.org/RIOT-OS/RIOT/18544/670cfea9943f23bfe052cdb5b047b7b5a44fd544/output.html) with error message:
```
make: *** No rule to make target 'flash-only'.  Stop.
```
which seems to be completely unrelated.

**Comment by MrKevinWeiss** [comment]
Can you limit your build so we can test a bit more?

```diff
diff --git a/.murdock b/.murdock
index e2432b2c09..49f1f98b96 100755
--- a/.murdock
+++ b/.murdock
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 # uncomment and change this to limit builds, e.g.,
-#export BOARDS="samr21-xpro native"
+export BOARDS="esp32-wroom-32"
 # and / or
-#export APPS="examples/hello-world tests/unittests"
+export APPS="tests/thread_priority_inversion"
 
 #
 : ${TEST_BOARDS_AVAILABLE:="esp32-wroom-32 samr21-xpro"}
```

**Comment by MrKevinWeiss** [comment]
AFAIK the pi fleet only has 1 esp32-wroom-32 still working, if that has gone down than hardware tests may be a bit of a challenge.

**Comment by MrKevinWeiss** [comment]
Whoa, the HiL actually did what I wanted it too.  The pi-fleet is in fact broken now.  I think @kaspar030 is on it.  Meanwhile it looks like this PR fixes the one test.  It seems like there is a problem in the `arduino-mega2560` unrelated to this PR but probably good to look into.

**Comment by gschorcht** [comment]
> * The initialization of locking variables with retargetable locking had to be added to avoid their implicit initialization in `_lock_acquire*` functions. Now the locking variables are either statically defined and initialized or they have to be allocated and initialized explicitly by calling `_lock_init*`. `assert`s ensure that locking variables are initialized when `_lock_acquire*` functions are called.

After some further testing, I'm afraid I have to admit that it's not possible after all to assume that a lock variable is already assigned and initialized the first time `_lock_acquire*` is used. When `esp_wifi` is used, some ESP IDF sources are used that use various static lock variables without allocating and initializing them using `_lock_init*`. They simply use `_lock_acquire*` and `_lock_release` and rely on implicit allocation and initialization.

That is, I have to revert some changes. @maribu Would it perhaps be better to completely squash and rebase the changes rather than fix the fixes of the fixes?

**Comment by maribu** [comment]
Do as you consider is best.

And more generally: My review-workflow doesn't really profit from the "squash only when asked" policy. So if a PR has only reviews of me, you can safely assume implicit approval to squashing at will ;)

**Comment by maribu** [comment]
Oh, regarding squashing: @MrKevinWeiss also reviewed this PR. Sorry that I lost track. This omission was not intentional, but human error due to more context switching between task than my brain can safely handle :/

Anyway, from my side you have both implicit and explicit support for squashing ;)

**Comment by gschorcht** [comment]
> Can you limit your build so we can test a bit more?

@MrKevinWeiss [Log](https://ci.riot-os.org/RIOT-OS/RIOT/18544/5b713f7b621ba23974179f33c7ef15961c8e653f/output.html)

**Comment by gschorcht** [comment]
@maribu With commits be0e5307b2c95875253cfe5690ace0035ceb0478 and 2b1ab9f84635b65b380dc0e2823fedd48b01f85d `tests/thread_priority_inversion` also works for ESP8266. Should I split off these commits as a separate PR or would the change of the title to cover all the commits ok?

**Comment by MrKevinWeiss** [comment]
Just do it in the one pr. I can start another hil test when I'm free to see if the esp8266 is fixed too.

**Comment by gschorcht** [comment]
All tests runs were now successful [log](https://ci.riot-os.org/RIOT-OS/RIOT/18544/966930e0b087c7bd1df5c8a32252f3c183a7ce89/output.html).

**Review by maribu — COMMENTED** [review]
Code looks good to me. The CI found a few typos and one instance of two subsequent blank lines.

The doccheck will need and entry in `exclude_pattern` to not complain about the stack size (or an Doxygen comment). Both is fine with me.

**Comment by gschorcht** [comment]
> Code looks good to me. The CI found a few typos and one instance of two subsequent blank lines.
> 
> The doccheck will need and entry in `exclude_pattern` to not complain about the stack size (or an Doxygen comment). Both is fine with me.

I squashed the fixes of static tests directly to avoid additional CI load by an extra compilation test cycle. Since all tests were already successful ([log](https://ci.riot-os.org/RIOT-OS/RIOT/18544/966930e0b087c7bd1df5c8a32252f3c183a7ce89/output.html)), I removed label `CI: run tests` for these "cosmetic" corrections.

**Review by maribu — APPROVED** [review]
ACK. Looks good to me and the CI did the testing :)
