### PR TITLE
test: trickle: fix condition for success

### LINKED ISSUE #10317: tests/trickle: nondeterministic failure
#### Description
I've got results very random results with the `trickle` test. This snippet has been reported in at least `samr21-xpro`, `arduino-mega2560`, `iotlab-m3` and `nucleo-l152re`.
This is the kind of output of the test:
```
make RIOT_CI_BUILD=1 CC_NOCOLOR=1 --no-print-directory -C /home/kevinweiss/WorkingDirectory/RIOT/tests/trickle test
ssh -oProxyCommand="ssh weiss@riot-ci.inet.haw-hamburg.de -W %h:%p" -t pi@10.28.48.11 'socat - open:/dev/ttyACM0,b115200,echo=0,raw'
main(): This is RIOT! (Version: buildtest)
[START]
now = 44987, prev_now = 3935, diff = 41052
now = 138904, prev_now = 44987, diff = 93917
now = 380000, prev_now = 138904, diff = 241096
now = 830277, prev_now = 380000, diff = 450277
now = 1648560, prev_now = 830277, diff = 818283
[TRICKLE_RESET]
now = 1666973, prev_now = 1648560, diff = 18413
now = 1694341, prev_now = 1666973, diff = 27368
now = 1772710, prev_now = 1694341, diff = 78369
now = 1845080, prev_now = 1772710, diff = 72370
[FAILURE]
Timeout in expect script at "child.expect(u"now = \d+, prev_now = \d+, diff = \d+")" (tests/trickle/tests/01-run.py:22)

/home/kevinweiss/WorkingDirectory/RIOT/tests/trickle/../../Makefile.include:557: recipe for target 'test' failed
make: *** [test] Error 1

Return value: 2
```

This doesn't seem to be related to #9052 

#### Steps to reproduce the issue
This bug is hard to reproduce. However, it's run via `make -C tests/trickle flash test`.

#### Expected results

Test passes
#### Actual results

Test fails randomly.

### PR DESCRIPTION
**Pull request by cgundogan**
### Contribution description

The current test implementation wrongly assumes that the diff between
two fired events (e1, e2) must always increase. That is not true, as
event e1 may reside on the upper part of [I/2, I) and e2 on the lower
part of [I, 2*I).

This commit fixes the test to look at the actual time that was randonmly
chosen from both intervals (t1, t2). Given that the intervals are
doubled, t1 must always be smaller than t2.

### Testing procedure
--

### Issues/PRs references
Fixes #10317

### CODE REVIEW

**Comment by jia200x** [comment]
oh, Travis complains because of `flake8` :(

**Comment by jia200x** [comment]
(I replaced `see` with `Fixed`, so it's close automatically when this gets merged)

**Comment by jia200x** [comment]
I tested it with the same seed as described in #10317 and works as described

**Comment by jia200x** [comment]
I will backport this because it affects the Release Specs in certain cases

**Comment by cgundogan** [comment]
Murdock is fine with this. GO

File: tests/trickle/main.c [hunk 1]
```diff
@@ -31,36 +31,37 @@
 #define FIRST_ROUND     (5)
 #define SECOND_ROUND    (12)
 
-static uint32_t prev_now = 0, prev_diff = 0;
+static uint32_t old_t = 0;
```
Comment (miri64) [inline tests/trickle/main.c]: I find the name `old_t` a little bit confusing. I read the code before I read the definitions and was confused that *a type* got assigned a value.

Sorry for the late look at this, but I fell a little behind on my mails ;-).
