### PR TITLE
drivers/at86rf2xx: Switch SRT mode to get random values.

### LINKED ISSUE #18285: at86rf2xx_internal: Don't get a random number with the function at86rf2xx_get_random
#### Description
I need to get a seed cryptographically secure and I used the PR #4989, but the test described in that PR won't work with the board samr21-xpro.

#### Steps to reproduce the issue

Tested with the following change in file tests/driver_at86rf2xx/main.c on samr21-xpro board :
```

   for (int i = 0; i < 10; i++) {
       unsigned int test = 0;
        at86rf2xx_get_random(devs, (uint8_t *)&test, sizeof(test));
        printf("%08x\n", test);
  }

```

#### Expected results

If I put this line:
```
prev_state = at86rf2xx_set_state(dev, AT86RF2XX_STATE_SLEEP);
```
at the end of ```at86rf2xx_configure_phy``` function in drivers/at86rf2xx/at86rf2xx_internal.c

The results are:
```
2022-06-28 23:39:54,159 # Initialization successful - starting the shell now
> 2022-06-28 23:39:56,422 # main(): This is RIOT! (Version: 2021.10-devel-4249-g5f574-HEAD)
2022-06-28 23:39:56,424 # AT86RF2xx device driver test
2022-06-28 23:39:56,428 # Initializing AT86RF2xx radio at SPI_0
2022-06-28 23:39:56,432 # a4cebbd9
2022-06-28 23:39:56,434 # e28fc5e1
2022-06-28 23:39:56,435 # 02161afd
2022-06-28 23:39:56,436 # 71cd3348
2022-06-28 23:39:56,437 # 772d4273
2022-06-28 23:39:56,438 # 07c145b7
2022-06-28 23:39:56,440 # 1340606d
2022-06-28 23:39:56,441 # 99afd90d
2022-06-28 23:39:56,442 # 593021bc
2022-06-28 23:39:56,443 # f790bba0
2022-06-28 23:39:56,448 # Initialization successful - starting the shell now
```
Note: when I reset the device I get different randoms numbers.  

The problem with this solution is that I don't know how this change affects other parts on the module. 
#### Actual results
 I get the following answer:

````
2022-06-28 23:39:26,082 # AT86RF2xx device driver test
2022-06-28 23:39:26,086 # Initializing AT86RF2xx radio at SPI_0
2022-06-28 23:39:26,092 # gnrc_netdev: possibly lost interrupt.
2022-06-28 23:39:26,093 # ffffffff
2022-06-28 23:39:26,094 # ffffffff
2022-06-28 23:39:26,096 # ffffffff
2022-06-28 23:39:26,097 # ffffffff
2022-06-28 23:39:26,098 # ffffffff
2022-06-28 23:39:26,099 # ffffffff
2022-06-28 23:39:26,101 # ffffffff
2022-06-28 23:39:26,102 # ffffffff
2022-06-28 23:39:26,103 # ffffffff
2022-06-28 23:39:26,104 # ffffffff
2022-06-28 23:39:26,109 # Initialization successful - starting the shell now
> 2022-06-28 23:39:38,542 # Exiting Pyterm
````

#### Versions
RIOT version Release 2022.04

### PR DESCRIPTION
**Pull request by eduazocar**
### Contribution description
This Pr is dedicated to resolve the random generation numbers from at86rf233, this should establish the device in a basic operation mode states. also needs to the preamble detector is disabled (RX_PDT_DIS=1). Something else that should be considered is the state of Smart Receiver Technology (SRT), this is an element used to manage the Reception Power Consumption (RPC) and it's affecting the `random_number_generator()` of the `at86rf2xx`. Well this Pull request add the functionality to disable temporarily the `smart_idle_mode` because the random number generator needs take values from RSSI register. When the SRT is active could won´t get the wished random values).

Also to integrate the number generator by the driver implementation, also let's to manipulate the functionality by network options (`netopts`), adding support in the `NETOPT_RANDOM`

### Testing procedure
run and falsh the test/driver_at86rf_2xx.
```
make -C tests/driver_at86rf2xx flash term
```
When it has loaded the shell type `random` ( This is a command added only to the test ). 
```
2022-07-01 16:20:56,261 # random
2022-07-01 16:20:56,267 # Random number for device 0 via native API: a2f979f9
2022-07-01 16:20:56,271 # Random number for device 0 via netopt: c200fa9d
```
Also try checking resetting the device to be sure that the self value is not repeating.
```
2022-07-01 16:21:03,653 # main(): This is RIOT! (Version: 2022.07-devel-900-g162cf-feature/at86rf2xx_random_numbers)
2022-07-01 16:21:03,655 # AT86RF2xx device driver test
2022-07-01 16:21:03,659 # Initializing AT86RF2xx radio at SPI_0
2022-07-01 16:21:03,665 # gnrc_netdev: possibly lost interrupt.
2022-07-01 16:21:03,670 # Initialization successful - starting the shell now
> random
2022-07-01 16:21:06,149 # random
2022-07-01 16:21:06,154 # Random number for device 0 via native API: a8f63524
2022-07-01 16:21:06,159 # Random number for device 0 via netopt: c0fe3169
> reboot
2022-07-01 16:21:17,349 # reboot
2022-07-01 16:21:17,381 # main(): This is RIOT! (Version: 2022.07-devel-900-g162cf-feature/at86rf2xx_random_numbers)
2022-07-01 16:21:17,383 # AT86RF2xx device driver test
2022-07-01 16:21:17,386 # Initializing AT86RF2xx radio at SPI_0
2022-07-01 16:21:17,392 # gnrc_netdev: possibly lost interrupt.
2022-07-01 16:21:17,397 # Initialization successful - starting the shell now
> random
2022-07-01 16:21:19,013 # random
2022-07-01 16:21:19,018 # Random number for device 0 via native API: eccf2f1c
2022-07-01 16:21:19,023 # Random number for device 0 via netopt: 7abc92e6
```

### Issues/PRs references

Fix #18285 
You can get more information about the SRT in the samr21-xpro-datasheet in the page 1034, section 40.10.

### CODE REVIEW

File: tests/driver_at86rf2xx/cmd.c [hunk 1]
```diff
@@ -301,6 +301,28 @@ static int send(int iface, le_uint16_t dst_pan, uint8_t *dst, size_t dst_len,
...
+{
+    netdev_ieee802154_t *dev = &devs[idx].netdev;
+    int (*get)(netdev_t *, netopt_t, void *, size_t) = dev->netdev.driver->get;
+    get(&dev->netdev, NETOPT_RANDOM, value, sizeof(uint32_t));
 }
 
+int random(int argc, char **argv)
+{
+    (void) argc;
+    (void) argv;
```
Comment (maribu) [inline tests/driver_at86rf2xx/cmd.c:316]:
```suggestion
    (void)argc;
    (void)argv;
```

I personally prefer it to have casts formatted like unary operators.

File: tests/driver_at86rf2xx/cmd.c [hunk 2]
```diff
@@ -301,6 +301,28 @@ static int send(int iface, le_uint16_t dst_pan, uint8_t *dst, size_t dst_len,
...
+    at86rf2xx_disable_smart_idle(devs);
+    uint32_t test = 0;
+    at86rf2xx_get_random(devs, (uint8_t *)&test, sizeof(test));
+    printf("Random number basic: %lx\n", test);
+    at86rf2xx_enable_smart_idle(devs);
+    for (unsigned int i = 0; i < AT86RF2XX_NUM; i++) {
+        random_net_api(i , &test);
+    }
+    printf("Random number By the netopts: %lx\n", test);
```
Comment (maribu) [inline tests/driver_at86rf2xx/cmd.c:325]:
```suggestion
    for (unsigned int i = 0; i < AT86RF2XX_NUM; i++) {
        uint32_t test = 0;
        at86rf2xx_get_random(&devs[i], (uint8_t *)&test, sizeof(test));
        printf("Random number for device %u via native API: %" PRIx32 "\n", i, test);
        test = 0;
        random_net_api(i , &test);
        printf("Random number for device %u via netopt: %" PRIx32 "\n", i, test);
    }
```

Note: This drops the smart idle disabling / restoring, assuming that this will be moved to `at86rf2xx_get_random()` to avoid forgetting it.

**Review by maribu — COMMENTED** [review]
Thanks for PRing a fix. Some nitpicks inline.

**Comment by eduazocar** [comment]
Thanks for your suggestions @maribu, I applied your recommendations, this could be reviewed again

File: drivers/at86rf2xx/at86rf2xx_netdev.c [hunk 3]
```diff
@@ -460,6 +460,13 @@ static int _get(netdev_t *netdev, netopt_t opt, void *val, size_t max_len)
 
 #endif /* MODULE_NETDEV_IEEE802154_OQPSK */
 
+        case NETOPT_RANDOM:
+            assert(max_len >= sizeof(uint32_t));
+            at86rf2xx_disable_smart_idle(dev);
+            at86rf2xx_get_random(dev, (uint8_t*)val, sizeof(val));
+            at86rf2xx_enable_smart_idle(dev);
```
[the remark this answers is not in the document]
Comment (eduazocar) [reply drivers/at86rf2xx/at86rf2xx_netdev.c]: you are right, this is only used when the call to àt86rf2xx_get_random()` is required, this will require a small change in its parameters, I removed the const assignment from the `at86rf_2xx_t dev` parameter for the SRT mode variation

**Review by maribu — APPROVED** [review]
ACK. I tested on the `samr21-xpro` and I can confirm that in `master` `0xff` bytes are returned:

```
> random
2022-07-02 10:05:56,785 # Random number for device 0 via native API: ffffffff
2022-07-02 10:05:56,789 # Random number for device 0 via netopt: 0
> 2022-07-02 10:05:58,269 # random
2022-07-02 10:05:58,274 # Random number for device 0 via native API: ffffffff
2022-07-02 10:05:58,278 # Random number for device 0 via netopt: 0
> 2022-07-02 10:05:58,893 # random
2022-07-02 10:05:58,898 # Random number for device 0 via native API: ffffffff
2022-07-02 10:05:58,902 # Random number for device 0 via netopt: 0
```

(the netopt version doesn't change the zero-initialized value as it is not implemented in `master`)


but with this PR, the output appear to contain a high level of entropy:

```
> random
2022-07-02 10:04:52,783 # random
2022-07-02 10:04:52,788 # Random number for device 0 via native API: 2a613db0
2022-07-02 10:04:52,793 # Random number for device 0 via netopt: 38ec93e2
> random
2022-07-02 10:04:55,725 # random
2022-07-02 10:04:55,730 # Random number for device 0 via native API: dda44bc2
2022-07-02 10:04:55,735 # Random number for device 0 via netopt: 452e984d
> random
2022-07-02 10:04:57,700 # random
2022-07-02 10:04:57,705 # Random number for device 0 via native API: dff3f25d
2022-07-02 10:04:57,710 # Random number for device 0 via netopt: ca0be5c9
```

Thanks for addressing the issue!

File: drivers/at86rf2xx/at86rf2xx_netdev.c [hunk 4]
```diff
@@ -460,6 +460,11 @@ static int _get(netdev_t *netdev, netopt_t opt, void *val, size_t max_len)
 
 #endif /* MODULE_NETDEV_IEEE802154_OQPSK */
 
+        case NETOPT_RANDOM:
+            assert(max_len >= sizeof(uint32_t));
+            at86rf2xx_get_random(dev, (uint8_t*)val, sizeof(val));
+            break;
+
```
Comment (maribu) [inline drivers/at86rf2xx/at86rf2xx_netdev.c:467]:
```suggestion
 #if AT86RF2XX_RANDOM_NUMBER_GENERATOR
        case NETOPT_RANDOM:
            assert(max_len >= sizeof(uint32_t));
            at86rf2xx_get_random(dev, (uint8_t*)val, sizeof(val));
            break;
#endif

```

Looks like not every revision of the transceiver has claims about the entropy for the RSSI value in the datasheet. E.g. see

https://github.com/RIOT-OS/RIOT/blob/932c58d89f732b86988219d5f17dd3ef6842524d/drivers/include/at86rf2xx.h#L124-L139

File: drivers/at86rf2xx/include/at86rf2xx_registers.h [hunk 5]
```diff
@@ -532,6 +532,7 @@ extern "C" {
 #define AT86RF2XX_TRX_RPC_MASK__PLL_RPC_EN                      (0x08)
 #define AT86RF2XX_TRX_RPC_MASK__XAH_TX_RPC_EN                   (0x04)
 #define AT86RF2XX_TRX_RPC_MASK__IPAN_RPC_EN                     (0x02)
+#define AT86RF2XX_TRX_RPC_MASK__RX_RPC__CTRL_DISABLED           (0xC1)
```
Comment (maribu) [inline drivers/at86rf2xx/include/at86rf2xx_registers.h:535]: The CI is uphappy that this is undocumented (the CI only enforces this on new code (via an ugly hack), that's why the CI is not frowning upon the other lines). Since you have to touch this anyway to get this past the CI, how about this instead:

```suggestion
/**
 * @brief   Bits to set to enable smart idle
 */
#define AT86RF2XX_TRX_RPC_MASK__RX_RPC__SMART_IDLE \
        (AT86RF2XX_TRX_RPC_MASK__RX_RPC_EN \
        | AT86RF2XX_TRX_RPC_MASK__PDT_RPC_EN \
        | AT86RF2XX_TRX_RPC_MASK__PLL_RPC_EN \
        | AT86RF2XX_TRX_RPC_MASK__XAH_TX_RPC_EN \
        | AT86RF2XX_TRX_RPC_MASK__IPAN_RPC_EN)
```

Than this could be used to enable smart idle:

```C
void at86rf2xx_enable_smart_idle(at86rf2xx_t *dev)
{
#if AT86RF2XX_SMART_IDLE_LISTENING
    uint8_t tmp = at86rf2xx_reg_read(dev, AT86RF2XX_REG__TRX_RPC);
    tmp |= AT86RF2XX_TRX_RPC_MASK__RX_RPC__SMART_IDLE;
    at86rf2xx_reg_write(dev, AT86RF2XX_REG__TRX_RPC, tmp);
    at86rf2xx_set_rxsensitivity(dev, RSSI_BASE_VAL);
#else
    (void) dev;
#endif
}
```

and to disable it:

```C
void at86rf2xx_disable_smart_idle(at86rf2xx_t *dev)
{
    #if AT86RF2XX_SMART_IDLE_LISTENING
    uint8_t tmp = at86rf2xx_reg_read(dev, AT86RF2XX_REG__TRX_RPC);
    tmp &= ~AT86RF2XX_TRX_RPC_MASK__RX_RPC__SMART_IDLE;
    at86rf2xx_reg_write(dev, AT86RF2XX_REG__TRX_RPC, tmp);
    #else
        (void) dev;
    #endif
}
```

Btw: Feel free to squash afterwards.

**Comment by eduazocar** [comment]
Hi, I've updated the PR with the new changes required, Thanks @maribu

File: drivers/at86rf2xx/at86rf2xx_netdev.c [hunk 6]
```diff
@@ -459,11 +459,17 @@ static int _get(netdev_t *netdev, netopt_t opt, void *val, size_t max_len)
...
+        case NETOPT_RANDOM:
+            assert(max_len >= sizeof(uint32_t));
+            at86rf2xx_get_random(dev, (uint8_t*)val, sizeof(val));
+            break;
 
         default:
             res = -ENOTSUP;
             break;
     }
+#endif
```
Comment (maribu) [inline drivers/at86rf2xx/at86rf2xx_netdev.c:472]: That `#endif` has to come prior to the `default:` case. That's why the build in the CI flailed. Please squash afterwards.

File: tests/driver_at86rf2xx/common.h [hunk 7]
```diff
@@ -41,6 +41,7 @@ extern at86rf2xx_t devs[AT86RF2XX_NUM];
 void recv(netdev_t *dev);
 int ifconfig(int argc, char **argv);
 int txtsnd(int argc, char **argv);
+int random(int argc, char **argv);
```
Comment (maribu) [inline tests/driver_at86rf2xx/common.h:44]: There already is a `random()` function in the standard C lib causing the compilation error. So, this function has to be renamed to get the CI passing :-(

Please squash again after renaming it. I have my fingers crossed that the CI is pleased afterwards and it can be finally be merged :)

File: tests/driver_at86rf2xx/main.c [hunk 8]
```diff
@@ -38,6 +38,7 @@ at86rf2xx_t devs[AT86RF2XX_NUM];
 static const shell_command_t shell_commands[] = {
     { "ifconfig", "Configure netdev", ifconfig },
     { "txtsnd", "Send IEEE 802.15.4 packet", txtsnd },
+    { "random", "Get a value from Random Number Generator", random_by_at86rf2xx },
```
Comment (maribu) [inline tests/driver_at86rf2xx/main.c:41]:
```suggestion
#if AT86RF2XX_SMART_IDLE_LISTENING
    { "random", "Get a value from Random Number Generator", random_by_at86rf2xx },
#endif
```

File: tests/driver_at86rf2xx/cmd.c [hunk 9]
```diff
@@ -301,6 +301,26 @@ static int send(int iface, le_uint16_t dst_pan, uint8_t *dst, size_t dst_len,
         puts(")");
     }
     return 0;
+
```
Comment (maribu) [inline tests/driver_at86rf2xx/cmd.c:304]:
```suggestion
```

File: tests/driver_at86rf2xx/cmd.c [hunk 10]
```diff
@@ -301,6 +301,26 @@ static int send(int iface, le_uint16_t dst_pan, uint8_t *dst, size_t dst_len,
...
+}
+void random_net_api(uint8_t idx, uint32_t *value)
```
Comment (maribu) [inline tests/driver_at86rf2xx/cmd.c:306]:
```suggestion

#if AT86RF2XX_SMART_IDLE_LISTENING
void random_net_api(uint8_t idx, uint32_t *value)
```

File: tests/driver_at86rf2xx/cmd.c [hunk 11]
```diff
@@ -301,6 +301,26 @@ static int send(int iface, le_uint16_t dst_pan, uint8_t *dst, size_t dst_len,
...
+    for (unsigned int i = 0; i < AT86RF2XX_NUM; i++) {
+        uint32_t test = 0;
+        at86rf2xx_get_random(&devs[i], (uint8_t *)&test, sizeof(test));
+        printf("Random number for device %u via native API: %" PRIx32 "\n", i, test);
+        test = 0;
+        random_net_api(i, &test);
+        printf("Random number for device %u via netopt: %" PRIx32 "\n", i, test);
+    }
+    return 0;
+}
```
Comment (maribu) [inline tests/driver_at86rf2xx/cmd.c:325]:
```suggestion
}
#endif
```

**Review by maribu — COMMENTED** [review]
The shell command in the test is making use of the random function even when the driver is not providing, resulting in the remaining compilation errors. But that is quick to fix.

Please squash afterwards :)

**Comment by maribu** [comment]
Thanks for fixing the issue!

**Comment by eduazocar** [comment]
I'm happy to contribute with RIOT, thanks for the help @maribu
