### PR TITLE
sys/net/dhcpv6: discard stale replies

### LINKED ISSUE #13834: DHCPv6 client ends up in busy loop after a while
#### Description
I noticed that after a while, the DHCP client would get stuck [in a loop](https://github.com/RIOT-OS/RIOT/blob/master/sys/net/application_layer/dhcpv6/client.c#L823).

#### Steps to reproduce the issue

```patch
--- a/sys/net/application_layer/dhcpv6/client.c
+++ b/sys/net/application_layer/dhcpv6/client.c
@@ -448,6 +448,7 @@ static void _schedule_t2(void)
 static void _schedule_t1_t2(void)
 {
     if (server.t1 < UINT32_MAX) {
+        server.t1 = 10;
         uint64_t t1_usec = server.t1 * US_PER_SEC;
 
         xtimer_remove(&timer);
```

This was with `examples/gnrc_border_router` with `CFLAGS=-DDHCPV6_CLIENT_PFX_LEASE_MAX=2 USE_DHCPV6=1` and two 6lowpan interfaces.
The issue also occurs with only one 6LoWPAN interface.

#### Expected results
The DHCPv6 client is reliable & stable.

#### Actual results

<details>
<summary>transaction ID gets out of sync</summary>

```
DHCPv6 client: send RENEW
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
```
will repeat until the node is restarted.
</details>

#### Versions
RIOT master

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The DHCPv6 server might send reposes [multiple times](https://github.com/RIOT-OS/RIOT/files/4449928/DHCPv6_multiple_replies.pcapng.zip).
The DHCPv6 client will only handle the first response, if additional responses are comming in they are left in the RX queue.

That results in the client always reading the response of a previous transaction on any subsequent transactions.
In this case the client will try again, creating a new transaction - that will again only read the previous response.
This essential creates a life-lock with the client not reacting to any input anymore as it is spending all it's time on sending DHCP requests. 

To fix this, discard previous responses by flushing the RX queue before sending a new message to the DHCPv6 server.

### Testing procedure

    make -C examples/gnrc_border_router USE_DHCPV6=1 flash term

The condition will only trigger on `RENEW`, so use this patch to avoid having to wait an hour :wink: 

```patch
--- a/sys/net/application_layer/dhcpv6/client.c
+++ b/sys/net/application_layer/dhcpv6/client.c
@@ -445,6 +455,7 @@ static int _preparse_advertise(uint8_t *adv, size_t len, uint8_t **buf)
 static void _schedule_t2(void)
 {
     if (t2 < UINT32_MAX) {
+        t2 = 20;
         uint64_t t2_usec = t2 * US_PER_SEC;
 
         rebind_time = (xtimer_now_usec64() / US_PER_SEC) + t2;
@@ -459,6 +470,8 @@ static void _schedule_t2(void)
 static void _schedule_t1_t2(void)
 {
     if (server.t1 < UINT32_MAX) {
+        server.t1 = 10;
+
         uint64_t t1_usec = server.t1 * US_PER_SEC;
 
         xtimer_remove(&timer);
```

After 10s the DHCPv6 client will send a `RENEW` message and immediately receive the reply to the previous `REQUEST` message.
Because the transaction ID does not match, the client will send a new `RENEW` message with a new transaction ID, but immediately receives the stale reply to the previous `RENEW` with the wrong transaction ID.
So the client will send another fresh `RENEW` message with a new transaction ID… 
This process will repeat forever.

You might have to enable debugging to see it:

```patch
--- a/sys/net/application_layer/dhcpv6/client.c
+++ b/sys/net/application_layer/dhcpv6/client.c
@@ -25,7 +25,7 @@
 #include "xtimer.h"
 #include "xtimer/implementation.h"
 
-#define ENABLE_DEBUG (0)
+#define ENABLE_DEBUG (1)
 #include "debug.h"
```

With this patch the stale responses are discarded before sending a new request, so the live-lock is avoided. 

### Issues/PRs references

fixes #13834

### CODE REVIEW

File: sys/net/application_layer/dhcpv6/client.c [hunk 1]
```diff
@@ -369,6 +369,15 @@ static bool _check_sid_opt(dhcpv6_opt_duid_t *sid)
             (memcmp(sid->duid, server.duid.u8, server.duid_len) == 0));
 }
 
+/* discard stale messages in the receive buffer */
+static void _flush_stale_replies(sock_udp_t *sock)
+{
+    int res;
+    while ((res = sock_udp_recv(sock, recv_buf, sizeof(recv_buf), 0, NULL)) > 0) {
```
Comment (miri64) [inline sys/net/application_layer/dhcpv6/client.c:376]: Probably not really going to happen, but better save than sorry
```suggestion
    while ((res = sock_udp_recv(sock, recv_buf, sizeof(recv_buf), 0, NULL)) >= 0) {
```

**Comment by miri64** [comment]
@benpicco anything to address https://github.com/RIOT-OS/RIOT/pull/13837#pullrequestreview-390252963?

**Comment by benpicco** [comment]
Hm, maybe this was only with two interfaces?

On `master` with `samr21-xpro` I get

```
DHCPv6 client: send SOLICIT
DHCPv6 client: resend SOLICIT
2020-06-25 11:59:24.095 INFO  [kea-dhcp6.dhcp6/276264] DHCP6_STARTING Kea DHCPv6 server version 1.6.2 starting
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: scheduling RENEW in 10 sec
DHCPv6 client: scheduling REBIND in 20 sec
ifconfig
ifconfig
Iface  7  HWaddr: 0E:50:4A:D4:34:26 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::c50:4aff:fed4:3426  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffd4:3426
          inet6 group: ff02::1:ff00:2
          
Iface  6  HWaddr: 71:A0  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 5A:06:59:C9:2C:36:7D:7B 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::5806:59c9:2c36:7d7b  scope: link  VAL
          inet6 addr: 2001:db8:0:2:5806:59c9:2c36:7d7b  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff36:7d7b
          
> DHCPv6 client: send RENEW
DHCPv6 client: received REPLY
DHCPv6 client: send REBIND
DHCPv6 client: send SOLICIT
DHCPv6 client: initial transmission, collect best advertise
DHCPv6 client: received ADVERTISE
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
```

whereas `same54-xpro` with `at86rf215` and 

```patch
--- a/sys/include/net/dhcpv6/client.h
+++ b/sys/include/net/dhcpv6/client.h
@@ -50,7 +50,7 @@ extern "C" {
 #define DHCPV6_CLIENT_SERVER_MAX    (1U)    /**< maximum number of servers to store */
 #endif
 #ifndef DHCPV6_CLIENT_PFX_LEASE_MAX
-#define DHCPV6_CLIENT_PFX_LEASE_MAX (1U)    /**< maximum number of prefix leases to store */
+#define DHCPV6_CLIENT_PFX_LEASE_MAX (2U)    /**< maximum number of prefix leases to store */
 #endif
 
 /**
```

I just get

```
DHCPv6 client: send SOLICIT
DHCPv6 client: resend SOLICIT
2020-06-25 12:06:51.250 INFO  [kea-dhcp6.dhcp6/279089] DHCP6_STARTING Kea DHCPv6 server version 1.6.2 starting
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: resend REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: scheduling RENEW in 10 sec
DHCPv6 client: scheduling REBIND in 20 sec
ifconfig
Iface  8  HWaddr: 2E:B7:9E:B1:31:55 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::2cb7:9eff:feb1:3155  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffb1:3155
          inet6 group: ff02::1:ff00:2
          
Iface  7  HWaddr: 01:55  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 1A:F9:8F:5F:30:5D:05:8C 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::18f9:8f5f:305d:58c  scope: link  VAL
          inet6 addr: 2001:db8:0:3:18f9:8f5f:305d:58c  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff5d:58c
          
Iface  6  HWaddr: 01:57  Channel: 0  Page: 2  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 1A:F9:8F:5F:30:5D:05:8E 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::18f9:8f5f:305d:58e  scope: link  VAL
          inet6 addr: 2001:db8:0:4:18f9:8f5f:305d:58e  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff5d:58e
          
> DHCPv6 client: send RENEW
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: packet too small or transaction ID wrong
DHCPv6 client: send REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: send REBIND
DHCPv6 client: send SOLICIT
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: resend REQUEST
DHCPv6 client: received REPLY
```

With this patch

```
DHCPv6 client: send SOLICIT
DHCPv6 client: resend SOLICIT
2020-06-25 12:10:57.806 INFO  [kea-dhcp6.dhcp6/279713] DHCP6_STARTING Kea DHCPv6 server version 1.6.2 starting
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: resend REQUEST
DHCPv6 client: received REPLY
DHCPv6 client: scheduling RENEW in 10 sec
DHCPv6 client: scheduling REBIND in 20 sec
ifconfig
ifconfig
Iface  8  HWaddr: 2E:B7:9E:B1:31:55 
          L2-PDU:1500 MTU:1500  HL:64  RTR  
          Source address length: 6
          Link type: wired
          inet6 addr: fe80::2cb7:9eff:feb1:3155  scope: link  VAL
          inet6 addr: fe80::2  scope: link  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ffb1:3155
          inet6 group: ff02::1:ff00:2
          
Iface  7  HWaddr: 01:55  Channel: 26  Page: 0  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 1A:F9:8F:5F:30:5D:05:8C 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::18f9:8f5f:305d:58c  scope: link  VAL
          inet6 addr: 2001:db8:0:3:18f9:8f5f:305d:58c  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff5d:58c
          
Iface  6  HWaddr: 01:57  Channel: 0  Page: 2  NID: 0x23  PHY: O-QPSK 
          
          Long HWaddr: 1A:F9:8F:5F:30:5D:05:8E 
           TX-Power: 0dBm  State: IDLE  max. Retrans.: 3  CSMA Retries: 4 
          AUTOACK  ACK_REQ  CSMA  L2-PDU:102 MTU:1280  HL:64  RTR  
          RTR_ADV  6LO  IPHC  
          Source address length: 8
          Link type: wireless
          inet6 addr: fe80::18f9:8f5f:305d:58e  scope: link  VAL
          inet6 addr: 2001:db8:0:4:18f9:8f5f:305d:58e  scope: global  VAL
          inet6 group: ff02::2
          inet6 group: ff02::1
          inet6 group: ff02::1:ff5d:58e
          
> DHCPv6 client: send RENEW
DHCPv6 client: discarding 126 stale bytes
DHCPv6 client: discarding 126 stale bytes
DHCPv6 client: discarding 126 stale bytes
DHCPv6 client: received REPLY
DHCPv6 client: send REBIND
DHCPv6 client: send SOLICIT
DHCPv6 client: discarding 126 stale bytes
DHCPv6 client: initial transmission, collect best advertise
DHCPv6 client: received ADVERTISE
DHCPv6 client: initial transmission, collect best advertise
DHCPv6 client: received ADVERTISE
DHCPv6 client: resend SOLICIT
DHCPv6 client: received ADVERTISE
DHCPv6 client: scheduling REQUEST
DHCPv6 client: send REQUEST
DHCPv6 client: resend REQUEST
DHCPv6 client: received REPLY
```
