### PR TITLE
treewide: compile fixes for native

### LINKED ISSUE #14667: Undefined behavior in `pkg/semtech-loramac/contrib/`
#### Description

The C standard takes Harvard Architectures into account, for which program and data memory are distinct address spaces. This also means that they can have different address sizes, which e.g. for the AVR platform is the case: RAM addresses are always 16 bit wide and ROM addresses [can be 22 bit wide (look up the program counter size)](http://www.bound-t.com/targets/avr/index.html#description).

As a result, the C standard forbids to cast function pointers (ROM address) to data pointers (RAM addresses). (This includes that `void *` pointers cannot be used to store a function address.)

#### Steps to reproduce the issue

Check this chunks of code:

https://github.com/RIOT-OS/RIOT/blob/7e4b3d0f402c7943e3680c411025979dc013b457/pkg/semtech-loramac/contrib/semtech_loramac_timer.c#L41-L49

https://github.com/RIOT-OS/RIOT/blob/7e4b3d0f402c7943e3680c411025979dc013b457/pkg/semtech-loramac/contrib/semtech_loramac.c#L609-L615

#### Expected results

No cast from function pointer to data pointer and vice versa.

#### Actual results

A cast from function pointer to data pointer and the other direction is present.

#### Versions

Current master.

----

Discussion started in https://github.com/RIOT-OS/RIOT/pull/14663

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`char` is unsigned on ARM but signed on x86.
This lead to a few compile errors when adding the `periph_gpio` feature to `native`, because now code that was previously never build for x86 got hit by this difference.
The host compiler is also usually newer than the embedded one, which usually means it is stricter.

This makes offending `chars` explicitly `unsigned` and works around some pedantry.

### Testing procedure

No logic changes. In fact, the binaries should stay the same.

### Issues/PRs references

split off & needed for  #12451
fixes #14667

### CODE REVIEW

File: drivers/cc110x/include/cc110x_settings.h [hunk 1]
```diff
@@ -38,7 +38,7 @@ extern "C" {
 /**
  * @brief   Configuration register values for CC1100/CC1101 transceivers
  */
-extern const char cc110x_conf[CC110X_CONF_SIZE];
+extern const unsigned char cc110x_conf[CC110X_CONF_SIZE];
```
Comment (maribu) [inline drivers/cc110x/include/cc110x_settings.h:41]:
```suggestion
extern const uint8_t cc110x_conf[CC110X_CONF_SIZE];
```

Let's go for `uint8_t`, to keep it consistent.

File: drivers/cc110x/include/cc110x_settings.h [hunk 2]
```diff
@@ -51,7 +51,7 @@ extern const char cc110x_conf[CC110X_CONF_SIZE];
  * transceiver configuration, those numbers should be checked again with the
  * SmartRF Studio
  */
-extern const char cc110x_magic_registers[3];
+extern const unsigned char cc110x_magic_registers[3];
```
Comment (maribu) [inline drivers/cc110x/include/cc110x_settings.h:54]:
```suggestion
extern const uint8_t cc110x_magic_registers[3];
```

File: drivers/kw2xrf/include/overwrites.h [hunk 3]
```diff
@@ -39,8 +39,8 @@ extern "C" {
 #endif
 
 typedef struct overwrites_tag {
-    char address;
-    char data;
+    unsigned char address;
+    unsigned char data;
```
Comment (maribu) [inline drivers/kw2xrf/include/overwrites.h:43]:
```suggestion
    uint8_t address;
    uint8_t data;
```

File: drivers/atwinc15x0/atwinc15x0_bsp.c [hunk 4]
```diff
@@ -83,7 +83,7 @@ void nm_bsp_register_isr(tpfNmBspIsr pfIsr)
 {
     assert(atwinc15x0);
 
-    DEBUG("%s %p\n", __func__, pfIsr);
+    DEBUG("%s %p\n", __func__, (void*)(uintptr_t)pfIsr);
```
Comment (maribu) [inline drivers/atwinc15x0/atwinc15x0_bsp.c:86]:
```suggestion
    DEBUG("%s %p\n", __func__, (void *)(uintptr_t)pfIsr);
```

I get why here two casts are needed, as casting a function pointer to a pointer is undefined behavior. (They have Harvard architectures in mind, in which the size of a function pointer can be different to the size of a data pointer, as they operate in different address spaces.)

File: drivers/atwinc15x0/atwinc15x0_netdev.c [hunk 5]
```diff
@@ -345,7 +345,7 @@ static int _atwinc15x0_get(netdev_t *netdev, netopt_t opt, void *val,
     assert(dev == atwinc15x0);
 
     DEBUG("%s dev=%p opt=%u val=%p max_len=%u\n", __func__,
-          netdev, opt, val, max_len);
+          (void*)(uintptr_t)netdev, opt, val, max_len);
```
Comment (maribu) [inline drivers/atwinc15x0/atwinc15x0_netdev.c:348]:
```suggestion
          (void *)netdev, opt, val, max_len);
```

But here a data pointer is casted to a data pointer. I don't think that two casts in a row improve readability.

File: drivers/atwinc15x0/atwinc15x0_netdev.c [hunk 6]
```diff
@@ -395,7 +395,7 @@ static int _atwinc15x0_set(netdev_t *netdev, netopt_t opt, const void *val,
     assert(val);
 
     DEBUG("%s dev=%p opt=%u val=%p max_len=%u\n", __func__,
-          netdev, opt, val, max_len);
+          (void*)(uintptr_t)netdev, opt, val, max_len);
```
Comment (maribu) [inline drivers/atwinc15x0/atwinc15x0_netdev.c:398]:
```suggestion
          (void *)netdev, opt, val, max_len);
```

File: drivers/atwinc15x0/atwinc15x0_netdev.c [hunk 7]
```diff
@@ -415,7 +415,7 @@ static int _atwinc15x0_init(netdev_t *netdev)
     assert(dev);
     assert(dev == atwinc15x0);
 
-    DEBUG("%s dev=%p\n", __func__, dev);
+    DEBUG("%s dev=%p\n", __func__, (void*)(uintptr_t)dev);
```
Comment (maribu) [inline drivers/atwinc15x0/atwinc15x0_netdev.c:418]:
```suggestion
    DEBUG("%s dev=%p\n", __func__, (void *)dev);
```

File: drivers/atwinc15x0/atwinc15x0_netdev.c [hunk 8]
```diff
@@ -492,7 +492,7 @@ static void _atwinc15x0_isr(netdev_t *netdev)
...
```
Comment (maribu) [inline drivers/atwinc15x0/atwinc15x0_netdev.c:495]:
```suggestion
    DEBUG("%s dev=%p\n", __func__, (void *)dev);
```

File: pkg/semtech-loramac/contrib/semtech_loramac.c [hunk 9]
```diff
@@ -609,7 +609,7 @@ void *_semtech_loramac_event_loop(void *arg)
                 case MSG_TYPE_MAC_TIMEOUT:
                 {
                     DEBUG("[semtech-loramac] MAC timer timeout\n");
-                    void (*callback)(void) = msg.content.ptr;
+                    void (*callback)(void) = (void (*)(void))(uintptr_t)msg.content.ptr;
```
Comment (maribu) [inline pkg/semtech-loramac/contrib/semtech_loramac.c:612]: This is actually problematic. On the AVR the program counter is up to 22 bit wide, while addresses in RAM are always 16 bit wide.

(In the DEBUG print in the WIFI driver above it would also be problematic, but a broken debug message is nothing I personally care much about. Here, it would result in a broken application.)

But maybe this is something better suited for a follow up PR, as this is not really related with the issue this PR wants to address and the issue is not introduced by this PR.

File: pkg/semtech-loramac/contrib/semtech_loramac_timer.c [hunk 10]
```diff
@@ -44,7 +44,7 @@ void TimerStart(TimerEvent_t *obj)
     xtimer_t *timer = &(obj->dev);
     msg_t *msg = &(obj->msg);
     msg->type = MSG_TYPE_MAC_TIMEOUT;
-    msg->content.ptr = obj->cb;
+    msg->content.ptr = (void*)(uintptr_t)obj->cb;
```
Comment (maribu) [inline pkg/semtech-loramac/contrib/semtech_loramac_timer.c:47]: Maybe using `msg->content.value` (which is of type `uint32_t`) would be a solution, as 32 bit should be wide enough for ROM addresses of constrained devices for quite some time. But I have the feeling that casting between `uint32_t` and function pointers is nothing the compiler will just accepted, when at least a modest level of warnings is enabled.

Maybe it is indeed better to have this discussion separately from this PR.

**Comment by maribu** [comment]
Feel free to squash

**Comment by maribu** [comment]
Is it only me, or are the inline comments gone?

**Comment by benpicco** [comment]
I don't see it

**Comment by maribu** [comment]
OK, the comments was a another `(void*)` to `(void *)` that I initially overlooked, but you already fixed it. And the `-Wno-pedantic` indeed does only apply to the package and we cannot fix code outside of RIOTs tree.

So, both comments are addressed already.
