### PR TITLE
mtd: add page addressed operations to allow access > 4GiB on SD cards

### LINKED ISSUE #14773: Can't read SD cards filled with more then 4 GiB data
#### Description

When a SD card has data on it beyond the 4 GiB boundary, it will appear to RIOT as corrupted, file listings do not work anymore.

#### Steps to reproduce the issue

Prepare a sufficiently large SD card with the FAT file system.
Copy some files onto the SD with a combined size > 4 GiB.
Alternatively you can also use a RIOT application that will write data to the SD card.

Run `examples/filesystem` to mount the file system and list the files

#### Expected results

The file system can be mounted, all files are listed and can be read.
```
>  mount
2020-06-25 00:46:14,191 # /sda successfully mounted
> ls /sda
2020-06-25 00:46:16,773 # TEST.TXT
2020-06-25 00:46:16,773 # LINED.C
2020-06-25 00:46:16,774 # HELLO.TXT
2020-06-25 00:46:16,775 # SYSTEM~1
2020-06-25 00:46:16,778 # WESTWO~1.MKV
2020-06-25 00:46:16,779 # WESTWO~2.MKV
2020-06-25 00:46:16,780 # WESTWO~3.MKV
2020-06-25 00:46:16,783 # WESTWO~4.MKV
2020-06-25 00:46:16,783 # WUT.TXT
2020-06-25 00:46:16,785 # total 9 files
> cat /sda/wut.txt
2020-06-25 00:46:20,925 # I never saw a purple cow.
2020-06-25 00:46:20,927 # I never hope to see one.
2020-06-25 00:46:20,929 # But I can tell you anyhow
2020-06-25 00:46:20,932 # I'd rather see than be one.
```

#### Actual results

File listing fails

```
>  mount
2020-06-25 00:39:50,589 # /sda successfully mounted
> ls /sda
2020-06-25 00:40:03,007 #  ls /sda
2020-06-25 00:40:03,010 # vfs_readdir error: -EIO
```

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

Currently `read()`, `write()` and `erase()` all use 32 bit addressing.
This is a problem when writing to media > 4 GiB, e.g. SD cards.

The current implementation would wrap around after 4 GiB and corrupt data.

To avoid this, add functions to the MTD subsystem that allow for page-wise addressing.
This is how most of the underling storage drivers and the file-systems above work anyway.

In the future we should then deprecate the 32-bit functions if all drivers are converted.

### Testing procedure

~~So far only the SD card and FAT drivers have been converted~~ - `tests/pkg_fatfs_vfs` should still work. But it should now also work if you previously filled up the SD card > 4 GiB

SD card filled with 4 files ~1 GiB each, `examples/filesystem`:

#### master

```
>  mount
2020-06-25 00:39:50,589 # /sda successfully mounted
> ls /sda
2020-06-25 00:40:03,007 #  ls /sda
2020-06-25 00:40:03,010 # vfs_readdir error: -EIO
```

#### this PR

```
>  mount
2020-06-25 00:46:14,191 # /sda successfully mounted
> ls /sda
2020-06-25 00:46:16,773 # TEST.TXT
2020-06-25 00:46:16,773 # LINED.C
2020-06-25 00:46:16,774 # HELLO.TXT
2020-06-25 00:46:16,775 # SYSTEM~1
2020-06-25 00:46:16,778 # WESTWO~1.MKV
2020-06-25 00:46:16,779 # WESTWO~2.MKV
2020-06-25 00:46:16,780 # WESTWO~3.MKV
2020-06-25 00:46:16,783 # WESTWO~4.MKV
2020-06-25 00:46:16,783 # WUT.TXT
2020-06-25 00:46:16,785 # total 9 files
> cat /sda/wut.txt
2020-06-25 00:46:20,925 # I never saw a purple cow.
2020-06-25 00:46:20,927 # I never hope to see one.
2020-06-25 00:46:20,929 # But I can tell you anyhow
2020-06-25 00:46:20,932 # I'd rather see than be one.
```

### Issues/PRs references

fixes #14773

### CODE REVIEW

File: drivers/include/mtd.h [hunk 1]
```diff
@@ -101,6 +101,27 @@ struct mtd_desc {
...
+     * @param[in]  offset   Byte offset from the start of the page
+     * @param[in]  size     Number of bytes
+     *
+     * @return 0 on success
+     * @return < 0 value on error
+     */
+    int (*read_page)(mtd_dev_t *dev,
+                void *buff,
+                uint32_t page,
+                uint16_t offset,
```
Comment (maribu) [inline drivers/include/mtd.h:122]: `page_size` is `uint32_t`. For consistency, this should IMO also be `uint32_t`.

I'm not a storage expert and missing the qualification reason if 16 bit are wide enough. However, a short search seems to indicate that SSDs typically have block sizes 256 KiB and 4 MiB (each consisting typically of 128 or 256 pages with each page sized 2 KiB, 4 KiB, 8 KiB, or 16 KiB). If someone would want to add an SSD driver that maps an MTD page to an SSD block, this would require an `uint32_t` offset. But again: I have no idea if this would make sense to map the MTD page to the SSD block rather than to the SSD page.

Still: With current hardware already having 16KiB pages, maybe it will not take too long until pages > 64KiB are used somewhere.  So I would say it might make sense to use `uint32_t` not just for consistency, but also to future proof the API.

File: drivers/include/mtd.h [hunk 2]
```diff
@@ -199,6 +273,29 @@ int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count);
...
+ * @brief   Write data to a MTD device with pagewise addressing
+ *
+ * @p offset + @p count must be inside a page boundary.
+ * Some devices might not support an @p offset != 0.
+ *
+ * @param      mtd   the device to write to
+ * @param[in]  src   the buffer to write
+ * @param[in]  page  the start page to write to
+ * @param[in]  offset byte offset from the start of the page
+ * @param[in]  count the number of bytes to write
```
Comment (maribu) [inline drivers/include/mtd.h:286]: Can you give it a more speaking name? E.g. `size` or `n_bytes`? With `count` it is not immediately obvious that it is the number of bytes, not the number of sectors. (Sure, number of sectors makes no sense with an `offset` parameter there as well, but that takes ~ 1 second to realize.)

Some for the other APIs where a size in bytes is given.

File: drivers/mtd/mtd.c [hunk 3]
```diff
@@ -50,6 +50,21 @@ int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count)
     }
 }
 
+int mtd_read_page(mtd_dev_t *mtd, void *dest, uint32_t page, uint16_t offset, uint32_t count)
+{
+    if (!mtd || !mtd->driver) {
+        return -ENODEV;
+    }
+
```
Comment (maribu) [inline drivers/mtd/mtd.c:58]: It would be super nice of have a range check here, so that the MTD backends could simply assume never being called with out of range read, write or erase requests. However, it seems this would require a bunch of multiplication for each call to `mtd_read_page()` to be able to do so :-/

File: drivers/mtd_sdcard/mtd_sdcard.c [hunk 4]
```diff
@@ -79,6 +63,28 @@ static int mtd_sdcard_read(mtd_dev_t *dev, void *buff, uint32_t addr,
...
+
+    mtd_sdcard_t *mtd_sd = (mtd_sdcard_t*)dev;
+    sd_rw_response_t err;
+    sdcard_spi_read_blocks(mtd_sd->sd_card, page,
+                           buff, SD_HC_BLOCK_SIZE,
+                           size / SD_HC_BLOCK_SIZE, &err);
+
+    if (err == SD_RW_OK) {
+        return 0;
+    }
```
Comment (maribu) [inline drivers/mtd_sdcard/mtd_sdcard.c:84]: What happens when `size % SD_HC_BLOCK_SIZE != 0`? The API doc does not contain a warning that the backend might require the size to a multiple of the block size.

How many MTD backends are expected to be support `offset != 0` and/or `size % BLOCK_SIZE != 0`? If there are few, maybe the API could drop the `offset` parameter and expect the number of blocks instead of the number of bytes?

Also: Is it only me, or is it super ugly that the SD-Card API returns the error via a pointer? Maybe this is something to touch in a follow up PR....

File: drivers/include/mtd.h [hunk 5]
```diff
@@ -176,6 +232,24 @@ int mtd_init(mtd_dev_t *mtd);
...
 int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count);
 
+/**
+ * @brief   Read data from a MTD device with pagewise addressing
+ *
+ * @param      mtd   the device to read from
+ * @param[out] dest  the buffer to fill in
+ * @param[in]  page  the start page to read from
+ * @param[in]  offset offset from the start of the page (in bytes)
+ * @param[in]  count the number of bytes to read
```
Comment (maribu) [inline drivers/include/mtd.h:242]: Missing indent/alignment of of the descriptions after the parameter name. More instances below.

File: drivers/mtd/mtd.c (hunk 3 above)
Comment (benpicco) [reply drivers/mtd/mtd.c:58]: Yea I also noticed that with the current MTD API, the burden is on the *file system* adaption code to ensure writes to not exceed a page and implement the chunking.
This is of course a silly duplication and the point of the intermediate layer should be that the consumers don't have to care about the implementation details.

That's why I added WIP - I'll change the low-level `write_page` function to operate like the internal [`_write_page`](https://github.com/RIOT-OS/RIOT/blob/master/drivers/at25xxx/at25xxx.c#L84) in `at25xxx.c`. Write as many bytes as fit into the current page, don't try anything clever and return the number of written bytes.

`mtd_write_page()` will then use that to split up however many bytes the user wants to write (like [`at25xxx_write()`](https://github.com/RIOT-OS/RIOT/blob/master/drivers/at25xxx/at25xxx.c#L125)

That way we can pull that logic out of the drivers and into a common place - and users of the MTD API don't have to care about the properties of the underlying storage media.

**Comment by benpicco** [comment]
This turned out to need some mayor rework - I'll squash when I'm done with it if you don't mind, so there is a clean starting state again.

File: drivers/mtd_sdcard/mtd_sdcard.c (hunk 4 above)
Comment (benpicco) [reply drivers/mtd_sdcard/mtd_sdcard.c]: All other backends support size != blocksize and offsets.
Currently the SD card backend only works with the FAT file system which will only ever operate on whole sectors.

I think it should be possible to modify `sdcard_spi` to support offsets on read - even if the SD card protocol only allows for sector-wise access, we can just ignore the first bytes.

File: drivers/include/mtd.h [hunk 6]
```diff
@@ -101,6 +101,27 @@ struct mtd_desc {
...
 
+    /**
+     * @brief   Read from the Memory Technology Device (MTD) using
+     *          pagewise addressing.
+     *
+     * @p offset should not exceed the page size
+     *
+     * @param[in]  dev      Pointer to the selected driver
+     * @param[out] buff     Pointer to the data buffer to store read data
+     * @param[in]  page     Starting page address
```
Comment (bergzand) [inline drivers/include/mtd.h:112]: I find this a bit ambiguous, shouldn't this be?
```suggestion
     * @param[in]  page     Page number to start reading from
```

File: drivers/include/mtd.h [hunk 7]
```diff
@@ -120,6 +141,27 @@ struct mtd_desc {
...
 
+    /**
+     * @brief   Write to the Memory Technology Device (MTD) using
+     *          pagewise addressing.
+     *
+     * @p offset should not exceed the page size
+     *
+     * @param[in]  dev      Pointer to the selected driver
+     * @param[out] buff     Pointer to the data to be written
+     * @param[in]  page     Starting page address
```
Comment (bergzand) [inline drivers/include/mtd.h:152]:
```suggestion
     * @param[in]  page     Page number to start writing to
```

File: drivers/include/mtd.h [hunk 8]
```diff
@@ -176,6 +232,29 @@ int mtd_init(mtd_dev_t *mtd);
...
+ * @brief   Read data from a MTD device with pagewise addressing
+ *
+ * The MTD layer will take care of splitting up the transaction into multiple
+ * reads if it is required by the underlying storage media.
+ *
+ * @p offset must be smaller than the page size
+ *
+ * @param      mtd      the device to read from
+ * @param[out] dest     the buffer to fill in
+ * @param[in]  page     the start page to read from
```
Comment (bergzand) [inline drivers/include/mtd.h:245]:
```suggestion
 * @param[in]  page     Page number to start reading from
```

File: drivers/include/mtd.h [hunk 9]
```diff
@@ -199,6 +278,31 @@ int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count);
...
+ *
+ * The MTD layer will take care of splitting up the transaction into multiple
+ * writes if it is required by the underlying storage media.
+ *
+ * @p offset must be smaller than the page size
+ *
+ *
+ * @param      mtd      the device to write to
+ * @param[in]  src      the buffer to write
+ * @param[in]  page     the start page to write to
```
Comment (bergzand) [inline drivers/include/mtd.h:292]:
```suggestion
 * @param[in]  page     Page number to start writing to
```

File: drivers/include/mtd.h [hunk 10]
```diff
@@ -217,6 +321,22 @@ int mtd_write(mtd_dev_t *mtd, const void *src, uint32_t addr, uint32_t count);
  */
 int mtd_erase(mtd_dev_t *mtd, uint32_t addr, uint32_t count);
 
+/**
+ * @brief   Erase sectors of a MTD device
+ *
+ * @param      mtd    the device to erase
+ * @param[in]  sector the first sector to erase
```
Comment (bergzand) [inline drivers/include/mtd.h:328]:
```suggestion
 * @param[in]  sector the first sector number to erase
```

File: drivers/include/mtd.h [hunk 11]
```diff
@@ -136,6 +178,20 @@ struct mtd_desc {
                  uint32_t addr,
                  uint32_t size);
 
+    /**
+     * @brief   Erase sector(s) of the Memory Technology Device (MTD)
+     *
+     * @param[in] dev       Pointer to the selected driver
+     * @param[in] sector    Starting sector
```
Comment (bergzand) [inline drivers/include/mtd.h:185]:
```suggestion
     * @param[in] sector    the first sector number to erase

```

File: drivers/include/mtd.h [hunk 12]
```diff
@@ -120,6 +141,27 @@ struct mtd_desc {
                  uint32_t addr,
                  uint32_t size);
 
+    /**
+     * @brief   Write to the Memory Technology Device (MTD) using
+     *          pagewise addressing.
+     *
+     * @p offset should not exceed the page size
```
Comment (bergzand) [inline drivers/include/mtd.h:148]: Is it allowed to have `@p size + @p offset > PAGE_SIZE`?, in other words, is it allowed to write into the next page?

**Comment by bergzand** [comment]
For both littlefs(2) and fatfs, this api matches the expectations of the filesystem better, both provide a page number and offset, and can simplify the glue code between the two. spiffs however doesn't handle pages and provides just a destination address. Removing/deprecating the current API would increase the glue code overhead there. Another option is to optionally include the old API when required.

Altogether I definitely see some merit in this API change.

**Comment by maribu** [comment]
> Another option is to optionally include the old API when required.

This could also be done as slim middle, so that implementations of the MTD API don't need to worry. (Some `static inline` utility functions might already fit the bill.)

**Comment by fjmolinas** [comment]
ping @benpicco!

File: drivers/include/mtd.h (hunk 12 above)
Comment (benpicco) [reply drivers/include/mtd.h:148]: Yes, the low-level `read_page` function will only read to the end of the page, `mtd_read_page()` takes care of splitting it up into two reads.

**Comment by benpicco** [comment]
Alright, I've changed `mtd.c` so that the new low-level functions are always used when available.

I had to revert the `mtd_mapper` changes - that falls apart when the backed doesn't implement the new `write_page` etc. functions.

As a follow-up, all mtd backends should be converted to the simpler pagewise functions (and relegate bounds checking and splitting of transfers to `mtd.c`).

File: drivers/mtd/mtd.c [hunk 13]
```diff
@@ -42,12 +43,57 @@ int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count)
         return -ENODEV;
     }
 
-    if (mtd->driver->read) {
-        return mtd->driver->read(mtd, dest, addr, count);
+    /* page size is always a power of two */
+    const uint32_t page_shift = 32 - __builtin_clz(mtd->page_size) - 1;
```
Comment (bergzand) [inline drivers/mtd/mtd.c:47]: I guess this should be something more portable.

File: drivers/mtd/mtd.c [hunk 14]
```diff
@@ -42,12 +43,57 @@ int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count)
...
+            return mtd->driver->read(mtd, dest, mtd->page_size * page + offset, count);
+        } else {
+            return -ENOTSUP;
+        }
     }
+
+    char *_dst = dest;
+
+    /* page size is always a power of two */
+    const uint32_t page_shift = 32 - __builtin_clz(mtd->page_size) - 1;
```
Comment (bergzand) [inline drivers/mtd/mtd.c:72]: Same here.

File: drivers/mtd/mtd.c [hunk 15]
```diff
@@ -42,12 +43,57 @@ int mtd_read(mtd_dev_t *mtd, void *dest, uint32_t addr, uint32_t count)
...
+    const uint32_t page_mask = mtd->page_size - 1;
+
+    page  += offset >> page_shift;
+    offset = offset & page_mask;
+
+    while (count) {
+        int read = mtd->driver->read_page(mtd, _dst, page, offset, count);
```
Comment (bergzand) [inline drivers/mtd/mtd.c:79]: Bit of a nitpick, but this clashes heavily in my mind with `read()`. Care to rename this variable to something slightly different?

Comment (bergzand) [inline drivers/mtd/mtd.c:79]: `mtd_desc::read_page()` should return 0 on success and not the number of bytes read.

File: drivers/mtd/mtd.c [hunk 16]
```diff
@@ -56,12 +102,57 @@ int mtd_write(mtd_dev_t *mtd, const void *src, uint32_t addr, uint32_t count)
...
+
+    /* page size is always a power of two */
+    const uint32_t page_shift = 32 - __builtin_clz(mtd->page_size) - 1;
+    const uint32_t page_mask = mtd->page_size - 1;
+
+    page  += offset >> page_shift;
+    offset = offset & page_mask;
+
+    while (count) {
+        int written = mtd->driver->write_page(mtd, _src, page, offset, count);
```
Comment (bergzand) [inline drivers/mtd/mtd.c:138]: Same, `mtd_desc::write_page` should return 0 on success, not the number of bytes written.

File: drivers/mtd/mtd.c (hunk 15 above)
Comment (benpicco) [reply drivers/mtd/mtd.c:79]: Oh, I should fix the documentation then.
It's vital to keep the page handling logic out of the low-level driver that `write_page` only writes as many bytes as fit into the current page.

Comment (bergzand) [reply drivers/mtd/mtd.c:79]: I agree, and I think modifying the documentation to fit this is the way to go. Is `int` here sufficient as return type for the number of bytes written?

File: drivers/mtd_spi_nor/mtd_spi_nor.c [hunk 17]
```diff
@@ -75,13 +77,7 @@ static int mtd_spi_nor_write(mtd_dev_t *mtd, const void *src, uint32_t addr, uin
...
 static int mtd_spi_nor_power(mtd_dev_t *mtd, enum mtd_power_state power);
 
-const mtd_desc_t mtd_spi_nor_driver = {
-    .init = mtd_spi_nor_init,
-    .read = mtd_spi_nor_read,
-    .write = mtd_spi_nor_write,
-    .erase = mtd_spi_nor_erase,
-    .power = mtd_spi_nor_power,
-};
+static int mtd_spi_nor_power(mtd_dev_t *mtd, enum mtd_power_state power);
```
Comment (bergzand) [inline drivers/mtd_spi_nor/mtd_spi_nor.c:80]: Duplicate?

File: drivers/mtd/mtd.c (hunk 13 above)
Comment (benpicco) [reply drivers/mtd/mtd.c:47]: `__builtin_clz` is provided by a software implementation if no `clz` instruction is available.
Or do you suggest a non-power 2 page size might be possible?

File: drivers/mtd_spi_nor/mtd_spi_nor.c [hunk 18]
```diff
@@ -521,6 +517,35 @@ static int mtd_spi_nor_write(mtd_dev_t *mtd, const void *src, uint32_t addr, uin
...
+static int mtd_spi_nor_write_page(mtd_dev_t *mtd, const void *src, uint32_t page, uint32_t offset,
+                                  uint32_t size)
+{
+    const mtd_spi_nor_t *dev = (mtd_spi_nor_t *)mtd;
+
+    DEBUG("mtd_spi_nor_write_page: %p, %p, 0x%" PRIx32 ", 0x%" PRIx32 ", 0x%" PRIx32 "\n",
+          (void *)mtd, src, page, offset, size);
+
+    size_t remaining = mtd->page_size - offset;
+    size = MIN(remaining, size);
```
Comment (bergzand) [inline drivers/mtd_spi_nor/mtd_spi_nor.c:529]: This compares a `size_t` with an `uint32_t` and is casted later to an `int`. I think this is asking for truncation issues :fearful:

File: drivers/mtd/mtd.c (hunk 13 above)
Comment (bergzand) [reply drivers/mtd/mtd.c:47]: > `__builtin_clz` is provided by a software implementation if no `clz` instruction is available.

That also depends on the compiler used right?

Why not just use `bitarithm_lsb()`?

File: drivers/mtd/mtd.c (hunk 15 above)
Comment (bergzand) [reply drivers/mtd/mtd.c]: Thanks! :)

File: drivers/mtd_spi_nor/mtd_spi_nor.c (hunk 18 above)
Comment (benpicco) [reply drivers/mtd_spi_nor/mtd_spi_nor.c:529]: I can change it to use `uint32_t`.
The return value is <= page size, so it should fit into an `int`.

Comment (bergzand) [reply drivers/mtd_spi_nor/mtd_spi_nor.c:527]: I can't find an example where the page size is more than 32KB on a non internal flash device, so I agree. How about a line or two in the mtd.h file to explain that an `int` is safe to use, and add an assert in the mtd implementation to assert that claim?

Comment (benpicco) [reply drivers/mtd_spi_nor/mtd_spi_nor.c:527]: How about 

```C
    /* Implementation assumes page size is <= INT_MAX and a power of two. */
    /* We didn't find hardware yet where this is not true.                */
    assert(mtd->page_size <= INT_MAX);
    assert(__builtin_popcount(mtd->page_size));
```

Comment (bergzand) [reply drivers/mtd_spi_nor/mtd_spi_nor.c:527]: Then why not use `bitarithm_bits_set`? :)

**Comment by bergzand** [comment]
Could somebody take a look at the changes to the at24cxxx and the at25xxx files?

**Comment by benpicco** [comment]
Maybe @fabian18 can chip in :)

File: drivers/at24cxxx/at24cxxx.c [hunk 19]
```diff
@@ -243,6 +257,22 @@ int at24cxxx_write(const at24cxxx_t *dev, uint32_t pos, const void *data,
     return check;
 }
 
+int at24cxxx_write_page(const at24cxxx_t *dev, uint32_t page, uint32_t offset,
+                        const void *data, size_t len)
+{
+    int check;
+
+    /* write no more than to the end of the current page to prevent wrap-around */
+    size_t remaining = DEV_PAGE_SIZE - offset;
```
Comment (fabian18) [inline drivers/at24cxxx/at24cxxx.c:266]: This could produce an invalid `remaining` size, if a smart user enters an `offset` > `DEV_PAGE_SIZE`.
So I think either this function should normalize `page` and `offset`, or the documentation should prohibit to pass an offset that is larger then the page size. I am in favor of the latter, because  `mtd_write_page()` also performs the normalization. But then I´d also add an `assert()` here.

File: drivers/at25xxx/at25xxx.c [hunk 20]
```diff
@@ -81,12 +81,12 @@ static inline int _wait_until_eeprom_ready(const at25xxx_t *dev)
     return tries == 0 ? -ETIMEDOUT : 0;
 }
 
-static ssize_t _write_page(const at25xxx_t *dev, uint32_t pos, const void *data, size_t len)
+int at25xxx_write_page(const at25xxx_t *dev, uint32_t page, uint32_t offset, const void *data, size_t len)
 {
     /* write no more than to the end of the current page to prevent wrap-around */
-    size_t remaining = PAGE_SIZE - (pos & (PAGE_SIZE - 1));
+    size_t remaining = PAGE_SIZE - offset;
```
Comment (fabian18) [inline drivers/at25xxx/at25xxx.c:87]: Here the same thing could happen as in `at24cxxx_write_page()`, if `offset` > `PAGE_SIZE`.

File: drivers/include/at25xxx.h [hunk 21]
```diff
@@ -109,6 +109,22 @@ void at25xxx_write_byte(const at25xxx_t *dev, uint32_t pos, uint8_t data);
  */
 int at25xxx_write(const at25xxx_t *dev, uint32_t pos, const void *data, size_t len);
 
+/**
+ * @brief Sequentially write @p len bytes to a given @p page.
+ *        The function will up to the page boundary and then return.
```
Comment (fabian18) [inline drivers/include/at25xxx.h:114]:
```suggestion
 *        The function will write up to the page boundary and then return.
```

File: drivers/at25xxx/at25xxx.c [hunk 22]
```diff
@@ -81,12 +81,12 @@ static inline int _wait_until_eeprom_ready(const at25xxx_t *dev)
     return tries == 0 ? -ETIMEDOUT : 0;
 }
 
-static ssize_t _write_page(const at25xxx_t *dev, uint32_t pos, const void *data, size_t len)
+int at25xxx_write_page(const at25xxx_t *dev, uint32_t page, uint32_t offset, const void *data, size_t len)
```
Comment (fabian18) [inline drivers/at25xxx/at25xxx.c:84]: `at25xxx_write_page()` does not acquire the SPI bus but `at24cxxx_write_page()` does acquire the I2C bus.

Comment (benpicco) [reply drivers/at25xxx/at25xxx.c]: Good catch!

File: drivers/at24cxxx/at24cxxx.c (hunk 19 above)
Comment (benpicco) [reply drivers/at24cxxx/at24cxxx.c:268]: I amended the documentation and added an `assert()`.

File: drivers/at25xxx/at25xxx.c [hunk 23]
```diff
@@ -120,18 +133,32 @@ int at25xxx_write(const at25xxx_t *dev, uint32_t pos, const void *data, size_t l
...
     }
 
+    /* page size is always a power of two */
+    const uint32_t page_shift = 32 - __builtin_clz(PAGE_SIZE) - 1;
+    const uint32_t page_mask = PAGE_SIZE - 1;
+
+    uint32_t page   = pos >> page_shift;
+    uint32_t offset = pos & page_mask;
+
     getbus(dev);
```
Comment (fabian18) [inline drivers/at25xxx/at25xxx.c:143]: Now the calls to `getbus()` and `spi_release()` are obsolete here, if `at25xxx_write_page()` also calls them.

**Comment by fabian18** [comment]
The changes to the `at24cxxx` look good to me and I am sure `at24cxxx_write_page` works as expected.
However, the compilation of `tests/mtd_at4cxxx` stops at `drivers/mtd/mtd.c`,
because `INT_MAX` is used but `<limits.h>` is not pulled in, at least if `BOARD=bluepill`.
So I´d suggest to include `<limits.h>` in `drivers/mtd/mtd.c`.

File: drivers/at25xxx/at25xxx.c (hunk 23 above)
Comment (benpicco) [reply drivers/at25xxx/at25xxx.c:143]: Good catch, I was meaning to use the internal `_at25xxx_write_page()` function instead.

**Comment by fabian18** [comment]
<details>
<summary>Now `tests/mtd_at24cxxx` passes:</summary>
<p>

```
2020-08-10 13:27:55,568 # main(): This is RIOT! (Version: 2020.07-devel-1542-g9d59a-mtd_pagewise)
2020-08-10 13:27:55,703 # ....
2020-08-10 13:27:55,705 # OK (4 tests)
```

</p>
</details> 

<details>
<summary>As well as `tests/driver_at24cxxx`:</summary>
<p>

```
2020-08-10 13:20:25,112 # main(): This is RIOT! (Version: 2020.07-devel-1542-g9d59a-mtd_pagewise)
2020-08-10 13:20:25,115 # Starting tests for module at24cxxx
2020-08-10 13:20:25,117 # EEPROM size: 32768 byte
2020-08-10 13:20:25,119 # Page size  : 64 byte
2020-08-10 13:20:25,121 # [SUCCESS] at24cxxx_init
2020-08-10 13:20:25,124 # [SUCCESS] at24cxxx_write_byte
2020-08-10 13:20:25,127 # [SUCCESS] at24cxxx_read_byte
2020-08-10 13:20:25,130 # [SUCCESS] write_byte/read_byte
2020-08-10 13:20:25,135 # [SUCCESS] at24cxxx_write
2020-08-10 13:20:25,139 # [SUCCESS] at24cxxx_read
2020-08-10 13:20:25,141 # [SUCCESS] write/read
2020-08-10 13:20:25,147 # [SUCCESS] at24cxxx_set
2020-08-10 13:20:25,152 # [SUCCESS] set/read
2020-08-10 13:20:25,156 # Finished tests for module at24cxxx
```

</p>
</details>

File: drivers/at25xxx/at25xxx.c [hunk 24]
```diff
@@ -120,18 +133,32 @@ int at25xxx_write(const at25xxx_t *dev, uint32_t pos, const void *data, size_t l
         return -ERANGE;
     }
 
+    /* page size is always a power of two */
+    const uint32_t page_shift = 32 - __builtin_clz(PAGE_SIZE) - 1;
```
Comment (bergzand) [inline drivers/at25xxx/at25xxx.c:137]:
```suggestion
    const uint32_t page_shift = bitarithm_msb(PAGE_SIZE);
```

File: drivers/at25xxx/at25xxx.c [hunk 25]
```diff
@@ -177,21 +204,27 @@ uint8_t at25xxx_read_byte(const at25xxx_t *dev, uint32_t pos)
...
-    size_t total = 0;
 
     if (pos + len > dev->params.size) {
         return -ERANGE;
     }
 
     memset(data, val, sizeof(data));
 
+    /* page size is always a power of two */
+    const uint32_t page_shift = 32 - __builtin_clz(PAGE_SIZE) - 1;
```
Comment (bergzand) [inline drivers/at25xxx/at25xxx.c:215]:
```suggestion
    const uint32_t page_shift = bitarithm_msb(PAGE_SIZE);
```

File: cpu/esp_common/periph/flash.c [hunk 26]
```diff
@@ -58,8 +58,8 @@
 /* the external pointer to the system MTD device */
 mtd_dev_t* mtd0 = 0;
 
-mtd_dev_t  _flash_dev;
-mtd_desc_t _flash_driver;
+mtd_dev_t  _flash_dev = {0};
```
Comment (kaspar030) [inline cpu/esp_common/periph/flash.c:61]: this is not necessary, default is zeroed for global vars.

Comment (benpicco) [reply cpu/esp_common/periph/flash.c:61]: I can also make it `static` while I'm at it, this is not used outside this file.

**Comment by kaspar030** [comment]
I looked through the code, looks ok to me.

I find the result type use (`int` vs `uint32_t`) confusing, reading through that, my brain's linter complained a bit. I remember discussing offline that we don't know devices with page sizes >32k, so I guess we're fine.

**Comment by benpicco** [comment]
Rebased to solve merge conflict

**Comment by fjmolinas** [comment]
All green here are we good to go with this one @bergzand @kaspar030 ?

**Review by bergzand — APPROVED** [review]
ACK
