### PR TITLE
cpu, sam0_common: fix uart TXC check

### LINKED ISSUE #7617: samd21:uart TXC test backwards
In cpu/sam0_common/periph/uart.c, uart_write() has a spin wait on TXC.

        while (!(dev(uart)->INTFLAG.reg & SERCOM_USART_INTFLAG_DRE)) {}
        dev(uart)->DATA.reg = data[i];
        while (dev(uart)->INTFLAG.reg & SERCOM_USART_INTFLAG_TXC) {}

Based on my reading of the TXC bit (for samd21 at least), it's backwards and should be NOT'ed in the spin test. As written, it's going to be set to 0 after the DATA.reg, so the while test is going to immediately fail since it won't be set UNTIL it's done shifting it out. To achieve the effect desired, I think a ! needs to be wrapped around the test.

I'm curious why we test for this at all though. The samd21 doc says:

    "This flag is set when the entire frame in the transmit shift register has been shifted out and there are no new data in DATA."

The second half of the and clause implies it's ok to keep feeding the thing bytes (respecting the DRE flag). The TXC really seems to be there for sensing (via poll or interrupt) when characters are no longer being streamed at it.

So... I can do a PR. Or someone who owns it more can grab it and go. I'd want some direction on the second point there. I personally think the test should just be removed entirely, unless the other sam21 flavors have differing behaviors.

### PR DESCRIPTION
**Pull request by smlng**
should fix #7617, and also adapts some register checks to use read-only bits where possible.

Tested with `samr21-xpro`. @travisgriggs please try this one and verify if that resolves your issue reported in #7617.

### CODE REVIEW

**Comment by travisgriggs** [comment]
Tested. This works.

**Comment by travisgriggs** [comment]
FWIW, I've also tested without the check completely, and that works too. And is slightly faster at spewing characters at 230400 (I didn't try any other speeds).

**Comment by travisgriggs** [comment]
I'd like to suggest a compromise with the TXC test, based on some interaction we had with Microchip/Atmel engineers. We asked them why the ASF version has the TXC check in it:

> "If INTFLAG.DRE bit is set, doesn’t mean that data is transmitted (it just moved to tx shift register). To make sure the entire data frame including stop bit(s) has been transmitted and no new data was written to DATA, the Transmit Complete interrupt flag (INTFLAG.TXC) will be set.
> 
> If you have 10 bytes to send, you may not need to check TXC bit for every byte transfer. You can check the TXC bit for 10th byte transmission.
> 
> In ASF, usart_write_wait() function is to just transmit a character via the USART. This is the reason it checks both bits (DRE and TXC).”

The uart_write() function actually writes `len` bytes. I think the correct thing to do would be move the TXC spin check out of the loop, and just do it once after the whole buffer has been written.

I have tested this as well with positive results. It's worth about 1.5% faster for my tests. Obviously, the larger your buffers are, the more savings you get. But it's not really about the speed. It just seems more consistent with what the TXC bit was meant for.

**Comment by smlng** [comment]
>  I think the correct thing to do would be move the TXC spin check out of the loop, and just do it once after the whole buffer has been written.

Nice idea, I agree - and thanks for the detailed background info!

**Comment by smlng** [comment]
rebased and squashed

**Comment by photonthunder** [comment]
Be great to see this bug fix get merged

File: cpu/sam0_common/periph/uart.c [hunk 1]
```diff
@@ -136,14 +136,14 @@ void uart_poweroff(uart_t uart)
...
+    if (dev(uartnum)->INTFLAG.bit.RXC) {
         /* interrupt flag is cleared by reading the data register */
         uart_ctx[uartnum].rx_cb(uart_ctx[uartnum].arg,
                                 (uint8_t)(dev(uartnum)->DATA.reg));
     }
-    else if (dev(uartnum)->INTFLAG.reg & SERCOM_USART_INTFLAG_ERROR) {
+    else if (dev(uartnum)->INTFLAG.bit.ERROR) {
         /* clear error flag */
-        dev(uartnum)->INTFLAG.reg = SERCOM_USART_INTFLAG_ERROR;
+        dev(uartnum)->INTFLAG.reg |= SERCOM_USART_INTFLAG_ERROR;
```
Comment (haukepetersen) [inline cpu/sam0_common/periph/uart.c]: Please revert this change, not need for read/modify/write here, a simple write is sufficient: `Writing a one to this bit will clear the flag.`

File: cpu/sam0_common/periph/uart.c [hunk 2]
```diff
@@ -69,18 +69,18 @@ int uart_init(uart_t uart, uint32_t baudrate, uart_rx_cb_t rx_cb, void *arg)
 
     /* reset the UART device */
     dev(uart)->CTRLA.reg = SERCOM_USART_CTRLA_SWRST;
-    while (dev(uart)->SYNCBUSY.reg & SERCOM_USART_SYNCBUSY_SWRST) {}
+    while (dev(uart)->SYNCBUSY.bit.SWRST) {}
```
Comment (haukepetersen) [inline cpu/sam0_common/periph/uart.c]: Actually, I like the original check much better, but this might be subjective. At some point we decided to go the the `.reg & ..` notation consistently for all the sam0 periph drivers...

Comment (smlng) [reply cpu/sam0_common/periph/uart.c]: with the updated CMSIS headers from the newer ASF the bit fields are read-only, and `reg` is RW. So I would guess the compiler could optimise things a bit (more) when using read-only registers for read operations on the bit-field instead of using an RW register when using `reg`. 

Do I make sense here?

Comment (smlng) [reply cpu/sam0_common/periph/uart.c]: Plus, I would therefore recommend to adapt all periph drivers accordingly to have it consistent again.

Comment (haukepetersen) [reply cpu/sam0_common/periph/uart.c]: Yepp, code size does not change with this, re-checked it. So yes, with them being read only why not change it. Maybe this would be cleaner done in a separate PR, but just leave it here if you want.

File: cpu/sam0_common/periph/uart.c (hunk 1 above)
Comment (smlng) [reply cpu/sam0_common/periph/uart.c]: I guess you are right, I mis-interpreted the usage of it here and thought might be safer to read/write here - just as we do in other places.

**Comment by kaspar030** [comment]
> Maybe this would be cleaner done in a separate PR, but just leave it here if you want.

Yes, please keep the PR fix-only...

**Comment by smlng** [comment]
factored out into #7709

**Comment by kaspar030** [comment]
Parens missing... Please fix and squash. ACK.
