### PR TITLE
shell: fix strtok_r compile error

### LINKED ISSUE #6248: shell/sc_gnrc_6ctx strtok_r missing
building `examples/gnrc_border_router` throws out the following error when building:
```
...
"make" -C ./RIOT/sys/shell/commands
./RIOT/sys/shell/commands/sc_gnrc_6ctx.c: In function '_gnrc_6ctx_add':
./RIOT/sys/shell/commands/sc_gnrc_6ctx.c:86:16: error: implicit declaration of function 'strtok_r' [-Werror=implicit-function-declaration]
     addr_str = strtok_r(prefix_str, "/", &save_ptr);
                ^
...
```
tested on Ubuntu 16.04.1 LTS with:
`arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.3.1 20160307 (release) [ARM/embedded-5-branch revision 234589]`
`andarm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]`

Building the example with a ~3 weeks old RIOT works flawlessly, so probably something has changed in the newlib?

### PR DESCRIPTION
**Pull request by smlng**
fixes  #6248

### CODE REVIEW

File: sys/shell/commands/sc_gnrc_6ctx.c [hunk 1]
```diff
@@ -12,6 +12,7 @@
  * @file
  */
 
+#define _DEFAULT_SOURCE 1
```
Comment (BytesGalore) [inline sys/shell/commands/sc_gnrc_6ctx.c]: please add a word why this define is in, the ACK

**Comment by smlng** [comment]
@BytesGalore addressed

**Comment by BytesGalore** [comment]
thx, ACK
