### PR TITLE
cpu/nrf52/radio/nrf802154: fix radio after soft ACK

### LINKED ISSUE #21782: Broken IEEE820.15.4 Networking on nrf52 Board
#### Description
15.4 networking seems to be broken for the nrf52 boards. I tested it using the gnrc networking example (`examples/networking/gnrc/gnrc_networking/`) which no longer drops the user into the shell. It hangs before it gets there. Related examples like the border router are also broken.

The bug was introduced in [4b24183](https://github.com/RIOT-OS/RIOT/commit/4b24183e8192df16db86a34b7b811bafbc459700). @fabian18 @benpicco 

#### Steps to reproduce the issue
Build the example on an adafruit feather or nrf52840 dk.

### PR DESCRIPTION
**Pull request by fabian18**
### Contribution description

Fix `nrf52` driver after submac software ACK. 

### Testing procedure

`gnrc_networking` with any `nrf52` board and any other 802.15.4 transceiver.

### Issues/PRs references

Bug introduced with #21533
fixes #21782

### CODE REVIEW

**Comment by Teufelchen1** [comment]
This does appear to fix the issue on my NRF. I did not test the 802154 stack directly but I can see that the side-effect (my app not working at all the cpu is stuck in a busy loop in the 802154 stack) is gone and I can use riot as expected.

**Comment by Teufelchen1** [comment]
(The exact commit that introduced the bug is 4b24183e8192df16db86a34b7b811bafbc459700 according to bisect)

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c [hunk 1]
```diff
@@ -197,7 +195,9 @@ static void _disable_blocking(void)
     _disable();
 
     /* This will take in worst case 21 us */
-    while (NRF_RADIO->STATE != RADIO_STATE_STATE_Disabled) {};
+    while (NRF_RADIO->STATE != RADIO_STATE_STATE_Disabled) {
+        DEBUG("[nrf802154] Waiting for DISABLED state\n");
+    }
```
Comment (mguetschow) [inline cpu/nrf52/radio/nrf802154/nrf802154_radio.c]: I don't think it is a good idea to print this message in a busy-loop, even if it's behind `ENABLE_DEBUG`. Why not do:

```suggestion
    while (NRF_RADIO->STATE != RADIO_STATE_STATE_Disabled) {}
    DEBUG("[nrf802154] Radio in DISABLED state\n");
```

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c [hunk 2]
```diff
@@ -515,16 +527,6 @@ void isr_radio(void)
...
-        case STATE_ACK:
-            _state = STATE_IDLE;
-
-            /* We disable the radio to avoid unwanted emissions (see ERRATA
-             * ID 204, "Switching between TX and RX causes unwanted emissions")
-             */
-            _disable();
-            DEBUG("[nrf52840] TX ACK done.");
-            _set_ifs_timer(false);
-            break;
```
Comment (mguetschow) [inline cpu/nrf52/radio/nrf802154/nrf802154_radio.c:527]: why don't we need this state anymore?

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c [hunk 3]
```diff
@@ -488,21 +502,19 @@ void isr_radio(void)
...
-                 * directly or if the driver should send an ACK frame before
-                 * the indication */
-                else if (l2filter_passed) {
-                    DEBUG("[nrf802154] RX frame doesn't require ACK frame.\n");
-                    _state = STATE_IDLE;
-                    dev->cb(dev, IEEE802154_RADIO_INDICATION_RX_DONE);
-                }
                 /* In case the packet is an ACK and the ACK filter is disabled,
                  * indicate the frame reception */
                 else if (is_ack && !cfg.ack_filter) {
```
Comment (mguetschow) [inline cpu/nrf52/radio/nrf802154/nrf802154_radio.c:505]: So this is essentially moved up before the L2 filter. Why?

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c (hunk 1 above)
Comment (fabian18) [reply cpu/nrf52/radio/nrf802154/nrf802154_radio.c]: The symptom of the bug was that the shell was not reached. This was due to a busy loop like this which could have been found debug enabled if this was the reason. The purpose of the print is only to identify being stuck for some reason.

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c (hunk 2 above)
Comment (fabian18) [reply cpu/nrf52/radio/nrf802154/nrf802154_radio.c:527]: This was a leftover. There is no driver "Ack state" anymore as this is now handled by the submac.

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c (hunk 3 above)
Comment (fabian18) [reply cpu/nrf52/radio/nrf802154/nrf802154_radio.c:505]: In the cases above `_l2filter()` it irrelevant, because ACKs dont carry an address. They match by sequence number. So `_l2filter()` is not needlessly called.

**Comment by fabian18** [comment]
> Could you elaborate a bit on what the problem was and why it can be fixed that way?

I did not notice that there are 2 timers in the driver. One previously for sending an ACK and the other for IFS. I removed both.
I am not sure where it was stuck. I assume because I removed the `timer_init` but `timer_set` and `timer_start` were still called with `_set_ifs_timer`.

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c (hunk 2 above)
Comment (mguetschow) [reply cpu/nrf52/radio/nrf802154/nrf802154_radio.c:527]: I see, maybe splitting the PR into separate commits would have helped my understanding :)

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c (hunk 1 above)
Comment (mguetschow) [reply cpu/nrf52/radio/nrf802154/nrf802154_radio.c]: But that could still mean that the screen gets spammed by this message (if `ENABLE_DEBUG` is 1), even in valid cases, where the radio would take some time to change the state?

File: cpu/nrf52/radio/nrf802154/nrf802154_radio.c (hunk 3 above)
Comment (mguetschow) [reply cpu/nrf52/radio/nrf802154/nrf802154_radio.c:505]: Again, separate commit would have eased reviewing. But maybe I was just too quick given that this is still a draft :)

**Comment by mguetschow** [comment]
> I am not sure where it was stuck. I assume because I removed the `timer_init` but `timer_set` and `timer_start` were still called with `_set_ifs_timer`.

Sounds plausible, although I would rather have expected an assertion failure in that case.

**Comment by fabian18** [comment]
I tested an `nrf52840dk` with a `samr21`. The `sam` has an `at86rf233` which supports hardware generated ACKs and retransmissions.
The issue is that the software ACK is sent too slow and (at least just 1) retransmission is triggered which causes a ping duplicate. If I set the `retrans` to 0 on the `sam` using `ifconfig, I no longer get duplicates.

**Comment by fabian18** [comment]
There is also for example no duplicate when the nrf does not do CSMA for the ACK:
```
    case IEEE802154_FSM_EV_BH:
        if (false && !_does_handle_csma(dev)) {
```

**Comment by fabian18** [comment]
Wait is this only a work around when no CSMA is supported by the driver? I dont know why to wait for a random backoff when sending an ACK

**Comment by fabian18** [comment]
When transmitting an ACK we have to wait ~~`aTurnaroundTime` +~~ `SIFSPeriod` but not a random backoff

**Comment by fabian18** [comment]
I would propose to fix the ACK very simple like in the commit above to not delay the release.
Actually it depends on modulation parameters and I would like to raise attention for #21527: https://github.com/RIOT-OS/RIOT/pull/21527/files#top where I could implement it properly.

**Comment by mguetschow** [comment]
> I would propose to fix the ACK very simple like in the commit above to not delay the release. Actually it depends on modulation parameters and I would like to raise attention for #21527: [#21527 (files)](https://github.com/RIOT-OS/RIOT/pull/21527/files#top) where I could implement it properly.

That's properly the right way to go, fine with me. But could you please add a todo to the respective part in the code that will need to be adapted in the follow-up PR so we don't loose track of it?

As said before, I'd appreciate some git history cleaning separating left-over fixes from the actual fix with the timers. And this is not supposed to be a draft anymore, right?

I've tested ICMP pings between `nrf52840dk` and `adafruit-feather-nrf52840-sense` and can confirm it is working for me with these changes. I am not knowledgeable enough in the radio code to assess the changes and give a confident ACK. Maybe @jia200x could have a quick look?

**Comment by benpicco** [comment]
I do now see duplicate responses to a multicast ping with `socket_zep`

```
2025-10-26 14:16:22,957 # ping ff02::1
2025-10-26 14:16:22,962 # 12 bytes from fe80::ec2e:ab90:ed92:d8b4%7: icmp_seq=0 ttl=64 rssi=-27 dBm time=4.932 ms
2025-10-26 14:16:22,964 # 12 bytes from fe80::ec2e:ab90:ed92:d8b4%7: icmp_seq=0 ttl=64 rssi=-27 dBm time=7.241 ms (DUP!)
2025-10-26 14:16:23,962 # 12 bytes from fe80::ec2e:ab90:ed92:d8b4%7: icmp_seq=1 ttl=64 rssi=-26 dBm time=4.487 ms
2025-10-26 14:16:23,964 # 12 bytes from fe80::ec2e:ab90:ed92:d8b4%7: icmp_seq=1 ttl=64 rssi=-26 dBm time=6.542 ms (DUP!)
2025-10-26 14:16:24,963 # 12 bytes from fe80::ec2e:ab90:ed92:d8b4%7: icmp_seq=2 ttl=64 rssi=-28 dBm time=5.187 ms
2025-10-26 14:16:24,964 # 
2025-10-26 14:16:24,964 # --- ff02::1 PING statistics ---
2025-10-26 14:16:24,964 # 3 packets transmitted, 3 packets received, 2 duplicates, 0% packet loss
2025-10-26 14:16:24,964 # round-trip min/avg/max = 4.487/5.677/7.241 ms
```

This is with two instances of `examples/networking/gnrc/gnrc_networking` with `USE_ZEP=1` and `sudo dist/tools/zep_dispatch/bin/zep_dispatch -w wpan0 ::1 17754`

For the (optional) `wpan0` you'll need `sudo modprobe mac802154_hwsim`, that allows you to capture the traffic in Wireshark

image


Looks fine on `master`

```
2025-10-26 14:21:24,387 # ping ff02::1
2025-10-26 14:21:24,391 # 12 bytes from fe80::a475:1fd:cfac:bed6%7: icmp_seq=0 ttl=64 rssi=-25 dBm time=3.794 ms
2025-10-26 14:21:25,392 # 12 bytes from fe80::a475:1fd:cfac:bed6%7: icmp_seq=1 ttl=64 rssi=-26 dBm time=4.512 ms
2025-10-26 14:21:26,393 # 12 bytes from fe80::a475:1fd:cfac:bed6%7: icmp_seq=2 ttl=64 rssi=-26 dBm time=4.592 ms
2025-10-26 14:21:26,393 # 
2025-10-26 14:21:26,393 # --- ff02::1 PING statistics ---
2025-10-26 14:21:26,394 # 3 packets transmitted, 3 packets received, 0% packet loss
2025-10-26 14:21:26,394 # round-trip min/avg/max = 3.794/4.299/4.592 ms
```

**Comment by fabian18** [comment]
I opened the two `gnrc_networking` with `USE_ZEP=1` and `sudo modprobe mac802154_hwsim`
I have 2 wpans:
```
7: wpan0: <BROADCAST,NOARP,UP,LOWER_UP> mtu 123 qdisc fq_codel state UNKNOWN group default qlen 300
    link/ieee802.15.4 72:cd:62:fd:89:b4:00:d4 brd ff:ff:ff:ff:ff:ff:ff:ff
8: wpan1: <BROADCAST,NOARP,UP,LOWER_UP> mtu 123 qdisc fq_codel state UNKNOWN group default qlen 300
    link/ieee802.15.4 56:de:b5:25:34:25:36:bc brd ff:ff:ff:ff:ff:ff:ff:ff

```
But what is the command I have to use for `zep_dispatch`?

```
$ sudo ./dist/tools/zep_dispatch/start_network.sh -w wpan0 ::1 17754
Cannot find device "17754"
error: invalid interface "17754"
sudo: wpan0: command not found
Cleaning up...
./dist/tools/zep_dispatch/start_network.sh: line 32: kill: (25146) - No such process
```

**Comment by fabian18** [comment]
Hm what could it be ...

I tried to reproduce with border router and gnrc networking as in the original soft ACK PR.
I dont get DUP pongs.
```
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=86 ttl=64 rssi=-27 dBm time=3.198 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=87 ttl=64 rssi=-26 dBm time=3.384 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=88 ttl=64 rssi=-27 dBm time=3.534 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=89 ttl=64 rssi=-26 dBm time=3.547 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=90 ttl=64 rssi=-28 dBm time=3.397 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=91 ttl=64 rssi=-26 dBm time=3.422 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=92 ttl=64 rssi=-27 dBm time=3.191 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=93 ttl=64 rssi=-27 dBm time=3.269 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=94 ttl=64 rssi=-28 dBm time=3.336 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=95 ttl=64 rssi=-25 dBm time=3.404 ms
uhcp_client(): no reply received
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=96 ttl=64 rssi=-28 dBm time=3.305 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=97 ttl=64 rssi=-27 dBm time=3.331 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=98 ttl=64 rssi=-27 dBm time=3.595 ms
12 bytes from fe80::a874:6b8:baff:53a1%7: icmp_seq=99 ttl=64 rssi=-27 dBm time=3.410 ms

--- ff02::1%7 PING statistics ---
100 packets transmitted, 100 packets received, 0% packet loss
round-trip min/avg/max = 3.191/3.424/3.824 ms

```

**Comment by fabian18** [comment]
Do we have to simulate air time? Would the transmission delay else be almost 0?

```
    /* delay transmission to simulate airtime */
    zepdev->ack_timer.callback = _send_frame;
    ztimer_set(ZTIMER_USEC, &zepdev->ack_timer, time_tx);
```

**Comment by benpicco** [comment]
> But what is the command I have to use for `zep_dispatch`?

You can just run

    sudo dist/tools/zep_dispatch/bin/zep_dispatch -w wpan0 ::1 17754

> Do we have to simulate air time? Would the transmission delay else be almost 0?

That might be it!

**Comment by fabian18** [comment]
Without the simulated airtime there is not DUP anymore as expected.
```
> ping ff02::1
2025-10-29 14:56:11,642 # ping ff02::1
2025-10-29 14:56:11,644 # 12 bytes from fe80::e45f:343:e58a:c0ac%7: icmp_seq=0 ttl=64 rssi=-26 dBm time=1.658 ms
2025-10-29 14:56:12,645 # 12 bytes from fe80::e45f:343:e58a:c0ac%7: icmp_seq=1 ttl=64 rssi=-28 dBm time=2.047 ms
2025-10-29 14:56:13,645 # 12 bytes from fe80::e45f:343:e58a:c0ac%7: icmp_seq=2 ttl=64 rssi=-28 dBm time=2.095 ms
2025-10-29 14:56:13,645 # 
2025-10-29 14:56:13,646 # --- ff02::1 PING statistics ---
2025-10-29 14:56:13,646 # 3 packets transmitted, 3 packets received, 0% packet loss
2025-10-29 14:56:13,646 # round-trip min/avg/max = 1.658/1.933/2.095 ms
```

So can I just drop it or do I have to create and opt-in pseudomodule?

**Comment by benpicco** [comment]
Do you mean remove the simulated airtime for ACKs on socket_zep?
Yea if this is causing trouble, just drop it.

**Comment by fabian18** [comment]
Only for ACK? I intended in general.

**Comment by benpicco** [comment]
Hm do you think it would be better to add this to `zep_dispatcher` then?
Simulating the timing behavior seems kind of important to me.

**Comment by fabian18** [comment]
I don`t understand what the difference would be when the artificial delay is moved to the dispatch program. 
I would suspect that the dispatch program adds a little more delay which is enough to trigger an occasional retransmission, because DUPs  are not arriving in the border router + gnrc networking example.

**Comment by benpicco** [comment]
The Problem seems to be that `socket_zep::request_op(IEEE802154_HAL_OP_SET_IDLE)` gets called immediately after `socket_zep::request_transmit()` - this stops the send timer and aborts the transmission. I added a `abort TX` print before the `ztimer_remove()`:

```
2025-10-29 18:22:52,086 # socket_zep::request_transmit(63 bytes, 496 µs)
2025-10-29 18:22:52,086 # socket_zep::request_op: switch to IDLE from 0
2025-10-29 18:22:52,086 # abort TX
2025-10-29 18:22:52,086 # socket_zep::request_op: switch to IDLE from 1
2025-10-29 18:22:52,086 # abort TX
2025-10-29 18:22:52,086 # socket_zep::request_transmit(77 bytes, 720 µs)
2025-10-29 18:22:52,086 # socket_zep::request_op: switch to IDLE from 0
2025-10-29 18:22:52,086 # abort TX
2025-10-29 18:22:54,964 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:54,964 # abort TX
2025-10-29 18:22:54,964 # socket_zep::request_op: switch to IDLE from 1
2025-10-29 18:22:54,964 # abort TX
2025-10-29 18:22:54,964 # socket_zep::request_transmit(70 bytes, 608 µs)
2025-10-29 18:22:54,966 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:54,966 # abort TX
2025-10-29 18:22:55,964 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:55,964 # abort TX
2025-10-29 18:22:55,964 # socket_zep::request_op: switch to IDLE from 1
2025-10-29 18:22:55,964 # abort TX
2025-10-29 18:22:55,964 # socket_zep::request_transmit(70 bytes, 608 µs)
2025-10-29 18:22:55,966 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:55,966 # abort TX
2025-10-29 18:22:56,964 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:56,964 # abort TX
2025-10-29 18:22:56,965 # socket_zep::request_op: switch to IDLE from 1
2025-10-29 18:22:56,965 # abort TX
2025-10-29 18:22:56,965 # socket_zep::request_transmit(70 bytes, 608 µs)
2025-10-29 18:22:56,966 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:56,966 # abort TX
2025-10-29 18:22:56,966 # socket_zep::request_transmit(70 bytes, 608 µs)
2025-10-29 18:22:56,967 # socket_zep::request_op: switch to IDLE from 2
2025-10-29 18:22:56,967 # abort TX
2025-10-29 18:23:01,591 # socket_zep::request_op: switch to IDLE from 1
2025-10-29 18:23:01,591 # abort TX
2025-10-29 18:23:01,591 # socket_zep::request_transmit(77 bytes, 720 µs)
2025-10-29 18:23:01,591 # socket_zep::request_op: switch to IDLE from 0
2025-10-29 18:23:01,591 # abort TX
```

**Comment by fabian18** [comment]
The TX state would be 3, but I only see the switch to IDLE from 0 1 2.
I put an `assert(!ztimer_is_set(ZTIMER_USEC, &zepdev->ack_timer));` in front of where the ztimer is removed.

I get 2 duplicates but no assert trigger on either side..

```
2025-10-29 19:01:19,167 # 
2025-10-29 19:01:19,168 # --- ff02::1 PING statistics ---
2025-10-29 19:01:19,168 # 100 packets transmitted, 100 packets received, 2 duplicates, 0% packet loss
2025-10-29 19:01:19,168 # round-trip min/avg/max = 3.210/3.747/6.096 ms
```

**Comment by benpicco** [comment]
How about 

```patch
--- i/cpu/native/socket_zep/socket_zep.c
+++ w/cpu/native/socket_zep/socket_zep.c
@@ -516,9 +516,16 @@ static int _request_transmit(ieee802154_dev_t *dev)
 
     dev->cb(dev, IEEE802154_RADIO_INDICATION_TX_START);
 
-    /* delay transmission to simulate airtime */
-    zepdev->ack_timer.callback = _send_frame;
-    ztimer_set(ZTIMER_USEC, &zepdev->ack_timer, time_tx);
+    /* native overhead prevents short timers from triggering in time, send directly if delay is less than 200 µs */
+    if (time_tx <= 200) {
+        _send_frame(zepdev->ack_timer.arg);
+    } else {
+        time_tx -= 200;
+
+        /* delay transmission to simulate airtime */
+        zepdev->ack_timer.callback = _send_frame;
+        ztimer_set(ZTIMER_USEC, &zepdev->ack_timer, time_tx);
+    }
 
     return 0;
 }
```

It's hacky, but `native` is not anywhere close to real-time behavior so…

**Review by benpicco — APPROVED** [review]
