### PR TITLE
shell_commands: check ICMPv6 echo reply sender

### LINKED ISSUE #11519: shell/ping6: Incorrect handling of unexpected pongs
#### Description
`ping6` does check received pongs properly

#### Steps to reproduce the issue
- Set up two devices *A* and *B* that can exchange messages                      
- Modify device *B* to send multiple responses over some extended period of time (e.g. seconds)
- On *A*: `ping6` node *B*  more than once
- On *A*: `ping6` node *B* and immediately afterwards `ping6` some unreachable/unassigned IPv6 address

#### Expected results
- `ping6` ignores any pongs not matching a ping it send and filters out duplicates

#### Actual results
- `ping6` correctly filters out duplicates (it does print them marked as duplicates but ignores them for the statistics - which is very nice design choice)
- `ping6` treats every pong it receives as response (skipping duplicates):
    - The first of each duplicated pong matching a ping of the last invocation of `ping6` is counted as a response.
    - Duplicated pongs from a previous invocation of `ping6` are even reported even if the pinged address no longer matches
    - Because the unrelated pongs are counted as responses, `ping6` might end after receiving 3 pongs without having send 3 pings

E.g. see the stats here:
```
> 2019-05-13 17:32:42,837 - INFO #  ping6 fe80::1114:7221:1336:102a
2019-05-13 17:32:42,845 - INFO # 12 bytes from fe80::1114:7221:1336:102a: icmp_seq=1 ttl=64 rssi=-61 dBm time=32.115 ms
2019-05-13 17:32:42,852 - INFO # 12 bytes from fe80::1114:7221:1336:102a: icmp_seq=0 ttl=64 rssi=-67 dBm time=7.957 ms
2019-05-13 17:32:42,861 - INFO # 12 bytes from fe80::1114:7221:1336:102a: icmp_seq=0 ttl=64 rssi=-61 dBm time=15.542 ms (DUP!)
2019-05-13 17:32:42,869 - INFO # 12 bytes from fe80::1114:7221:1336:102a: icmp_seq=0 ttl=64 rssi=-62 dBm time=23.820 ms (DUP!)
2019-05-13 17:32:42,877 - INFO # 12 bytes from fe80::1114:7221:1336:102a: icmp_seq=0 ttl=64 rssi=-62 dBm time=32.099 ms (DUP!)
2019-05-13 17:32:43,854 - INFO # 12 bytes from fe80::1114:7221:1336:102a: icmp_seq=1 ttl=64 rssi=-77 dBm time=9.959 ms
2019-05-13 17:32:43,855 - INFO # 
2019-05-13 17:32:43,859 - INFO # --- fe80::1114:7221:1336:102a PING statistics ---
2019-05-13 17:32:43,866 - INFO # 2 packets transmitted, 3 packets received, 3 duplicates, 2147483598% packet loss
2019-05-13 17:32:43,870 - INFO # round-trip min/avg/max = 7.957/20.248/32.115 ms
```

#### Versions
(At least) current master

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Fix for #11519 by checking the source address when an echo reply is
received by the `ping6` command.

### Testing procedure
See #11519 for testing procedures

### Issues/PRs references
Fix for #11519.

### CODE REVIEW

**Comment by miri64** [comment]
Ping @maribu

**Comment by maribu** [comment]
I do not have the nRF52840DK board at hand. I'll test as soon as possible.

**Comment by miri64** [comment]
> I do not have the nRF52840DK board at hand. I'll test as soon as possible.

Huh? Did I miss something? Why is an nRF52840DK required for that? o.O

File: sys/shell/commands/sc_gnrc_icmpv6_echo.c [hunk 1]
```diff
@@ -338,7 +338,8 @@ static void _print_reply(_ping_data_t *data, gnrc_pktsnip_t *icmpv6,
         uint16_t recv_seq;
 
         /* not our ping */
-        if (byteorder_ntohs(icmpv6_hdr->id) != data->id) {
+        if ((byteorder_ntohs(icmpv6_hdr->id) != data->id) &&
+            !ipv6_addr_equal(from, &data->host)) {
```
Comment (maribu) [inline sys/shell/commands/sc_gnrc_icmpv6_echo.c]: Maybe it would make sense to print a short line to indicate that potential mischief happened? E.g. the potential driver issue with either at85rf2xx or the nrf52 802.15.4 I noticed would no longer be detectable if the unexpected pongs are silently dropped.

Comment (miri64) [reply sys/shell/commands/sc_gnrc_icmpv6_echo.c]: Mh... The original IP implementation does not seem to care about this + it could be legitimate (e.g. when two threads pinging at the same time for some reason) that a packet that holds this condition arrives here. What is the potential driver issue again?

**Comment by miri64** [comment]
The unreachable address problem is a bug separate from the one fixed here. It is addressed in #11938.

**Comment by miri64** [comment]
Sorry... I meant the problem of having late pings come in from a previous `ping6` call to the same address. That is what is fixed in #11938 and that is why you get the same output as in #11519 as you reported.

**Comment by fjmolinas** [comment]
> Sorry... I meant the problem of having late pings come in from a previous ping6 call to the same address. That is what is fixed in #11938 and that is why you get the same output as in #11519 as you reported.

So if I understand right `On A: ping6 node B and immediately afterwards ping6 some unreachable/unassigned IPv6 address` should be fixed by this PR, which I wasn't seeing anyway (Or Am I still wrong In my understanding of the issue?)

When testing this PR rebased on top of #11938 the bug was no longer present.

```
2019-08-09 12:12:20,033 - INFO # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2019-08-09 12:12:37,121 - INFO # main(): This is RIOT! (Version: 2019.10-devel-160-g7a14-pr-11938)
2019-08-09 12:12:37,124 - INFO # RIOT network stack example application
2019-08-09 12:12:37,127 - INFO # All up, running the shell now
> ping6 fe80::d1c1:6d4e:ab6a:1336
2019-08-09 12:12:39,573 - INFO #  ping6 fe80::d1c1:6d4e:ab6a:1336
2019-08-09 12:12:39,616 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=32.168 ms
2019-08-09 12:12:39,624 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=42.902 ms (DUP!)
2019-08-09 12:12:39,633 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=51.383 ms (DUP!)
2019-08-09 12:12:39,641 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=59.864 ms (DUP!)
ping6 fe80::d1c1:6d4e:ab6a:aaaa
2019-08-09 12:12:40,609 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-50 dBm time=26.627 ms
2019-08-09 12:12:40,618 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-50 dBm time=37.294 ms (DUP!)
2019-08-09 12:12:40,627 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-50 dBm time=46.726 ms (DUP!)
2019-08-09 12:12:40,635 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-50 dBm time=55.208 ms (DUP!)
2019-08-09 12:12:40,644 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-50 dBm time=63.691 ms (DUP!)
2019-08-09 12:12:41,610 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=2 ttl=64 rssi=-49 dBm time=28.532 ms
2019-08-09 12:12:41,610 - INFO # 
2019-08-09 12:12:41,615 - INFO # --- fe80::d1c1:6d4e:ab6a:1336 PING statistics ---
2019-08-09 12:12:41,622 - INFO # 3 packets transmitted, 3 packets received, 7 duplicates, 0% packet loss
2019-08-09 12:12:41,626 - INFO # round-trip min/avg/max = 26.627/44.439/63.691 ms
> 2019-08-09 12:12:41,630 - INFO #  ping6 fe80::d1c1:6d4e:ab6a:aaaa
2019-08-09 12:12:44,628 - INFO # 
2019-08-09 12:12:44,632 - INFO # --- fe80::d1c1:6d4e:ab6a:aaaa PING statistics ---
2019-08-09 12:12:44,637 - INFO # 3 packets transmitted, 0 packets received, 100% packet loss
> ping6 fe80::d1c1:6d4e:ab6a:1336
2019-08-09 12:12:46,797 - INFO #  ping6 fe80::d1c1:6d4e:ab6a:1336
2019-08-09 12:12:46,836 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=28.207 ms
2019-08-09 12:12:46,846 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=38.949 ms (DUP!)
2019-08-09 12:12:46,854 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=48.402 ms (DUP!)
2019-08-09 12:12:46,863 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=56.884 ms (DUP!)
2019-08-09 12:12:46,871 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=0 ttl=64 rssi=-50 dBm time=65.366 ms (DUP!)
ping6 fe80::d1c1:6d4e:ab6a:aaaa
2019-08-09 12:12:47,834 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-49 dBm time=27.277 ms
2019-08-09 12:12:47,843 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-49 dBm time=37.839 ms (DUP!)
2019-08-09 12:12:47,852 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-49 dBm time=47.207 ms (DUP!)
2019-08-09 12:12:47,860 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-49 dBm time=55.689 ms (DUP!)
2019-08-09 12:12:47,869 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=1 ttl=64 rssi=-49 dBm time=64.171 ms (DUP!)
2019-08-09 12:12:48,834 - INFO # 12 bytes from fe80::d1c1:6d4e:ab6a:1336: icmp_seq=2 ttl=64 rssi=-49 dBm time=28.859 ms
2019-08-09 12:12:48,835 - INFO # 
2019-08-09 12:12:48,839 - INFO # --- fe80::d1c1:6d4e:ab6a:1336 PING statistics ---
2019-08-09 12:12:48,846 - INFO # 3 packets transmitted, 3 packets received, 8 duplicates, 0% packet loss
2019-08-09 12:12:48,850 - INFO # round-trip min/avg/max = 27.277/45.350/65.366 ms
> 2019-08-09 12:12:48,854 - INFO #  ping6 fe80::d1c1:6d4e:ab6a:aaaa
2019-08-09 12:12:51,851 - INFO # 
2019-08-09 12:12:51,855 - INFO # --- fe80::d1c1:6d4e:ab6a:aaaa PING statistics ---
2019-08-09 12:12:51,860 - INFO # 3 packets transmitted, 0 packets received, 100% packet loss
2019-08-09 12:12:54,794 - INFO # Exiting Pyterm
 ```

**Comment by miri64** [comment]
> So if I understand right `On A: ping6 node B and immediately afterwards ping6 some unreachable/unassigned IPv6 address` should be fixed by this PR, which I wasn't seeing anyway (Or Am I still wrong In my understanding of the issue?)

Nope, everything right :-)

**Comment by miri64** [comment]
If the PR improves things in your opinion and don't make things worse, how about we merge now and then @maribu can evaluate if #11519 can be closed as a result of this?

**Comment by fjmolinas** [comment]
> If the PR improves things in your opinion and don't make things worse, how about we merge now and then @maribu can evaluate if #11519 can be closed as a result of this?

+1, In that case remove `Fixes #11519.` from the PR description so it doesn't get closed automatically.

**Comment by miri64** [comment]
reworded "Fixes" to "Fix for". This way it is ignored by GitHub ;-).

**Comment by fjmolinas** [comment]
GO!

**Comment by benpicco** [comment]
What about broadcast pings? 
`ping6 ff02::1` should receive all the PONGs.
