### PR TITLE
 gnrc_tftp: initialize unititialized 'tftp_context_t'

### LINKED ISSUE #11772: gnrc_tftp: use of uninitialized values
#### Description

The `gnrc_tftp_server` doesn't initialize all members of the `tftp_context_t` in `gnrc_tftp_server` causing an access of ununinitialised values when receiving messages in an unexpected order.

#### Steps to reproduce the issue

1. Build `examples/gnrc_tftp` with `make all-valgrind`
2. Run the application using `make term-valgrind`
3. Start the TFTP server using `tftps start` and wait until it started
4. Send a `DATA` tftp packet to the server, for example:

```
echo AAMAAGZvb2Jhcg== | base64 -d | nc -u '[ip-address%tap0]' 69
```

#### Expected results

Valgrind shouldn't report any accesses of uninitialised values.

#### Actual results

Valgrind reports various conditional jumps or moves which depend on uninitialised values.

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
Fixes #11772.

### Testing procedure
Follow procedure in #11772. It should succeed and also not run into a failed assertion. Also try the instruction in `example/gnrc_tftp`'s README.

### Issues/PRs references
Addresses #11772.

### CODE REVIEW

File: sys/net/gnrc/application_layer/tftp/gnrc_tftp.c [hunk 1]
```diff
@@ -606,6 +608,7 @@ tftp_state _tftp_state_processes(tftp_context_t *ctxt, msg_t *m)
     tmp = gnrc_pktsnip_search_type(pkt, GNRC_NETTYPE_IPV6);
     ipv6_hdr_t *ip = (ipv6_hdr_t *)tmp->data;
     uint8_t *data = (uint8_t *)pkt->data;
+    ctxt->dst_port = byteorder_ntohs(udp->src_port);
```
Comment (miri64) [inline sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: I'm not 100% sure about this one. There are also other sets of this variable below... However, I observed `gnrc_udp_hdr_build()` getting `dst_port` 0 with the fix above.

Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: I pushed a fixup that I _think_ is more correct.

File: sys/net/gnrc/application_layer/tftp/gnrc_tftp.c [hunk 2]
```diff
@@ -405,11 +405,14 @@ int gnrc_tftp_server(tftp_data_cb_t data_cb, tftp_start_cb_t start_cb, tftp_stop
...
 
     /* context will be initialized when a connection is established */
-    tftp_context_t ctxt;
-    ctxt.data_cb = data_cb;
-    ctxt.start_cb = start_cb;
-    ctxt.stop_cb = stop_cb;
-    ctxt.enable_options = use_options;
+    tftp_context_t ctxt = {
+        .dst_port = GNRC_TFTP_DEFAULT_DST_PORT,
+        .src_port = GNRC_TFTP_DEFAULT_DST_PORT,
```
Comment (miri64) [inline sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: I'm not sure this should be `SRC_PORT`... I'd like to do some personal testing for the "normal" operation first.

Comment (MrKevinWeiss) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Please let me how to confirm then in the test procedure (or ping someone more knowledgeable).

Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Since the contributor that provided this is not active anymore, I'd say follow the README. Maybe also @bergzand has some input.

Comment (bergzand) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Assuming my understanding of the protocol and the implementation here is sufficient, this `.src_port` is the UDP port used as source by RIOT and used as destination by the peer. Both *should* be ephermal ports specific for this connection.

Does it make sense to default it to something invalid/unconfigured? (Do we have something like that in gnrc?)

Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: > Assuming my understanding of the protocol and the implementation here is sufficient, this .src_port is the UDP port used as source by RIOT and used as destination by the peer. Both should be ephermal ports specific for this connection.

We are in server context here, so `src_port` should at least be `GNRC_TFTP_DEFAULT_DST_PORT` (which is the default TFTP port). Ephemeral ports in GNRC are part of the `gnrc_sock` implementation, which this implementation does not use :-/

> Does it make sense to default it to something invalid/unconfigured? (Do we have something like that in gnrc?)

If I leave it unconfigured, the testing procedure in #11772 runs into an assertion here

https://github.com/RIOT-OS/RIOT/blob/a01e70a4ab0050331b36ad59946637c62c48ed3a/sys/net/gnrc/transport_layer/udp/gnrc_udp.c#L283-L286

from the call here

https://github.com/RIOT-OS/RIOT/blob/a01e70a4ab0050331b36ad59946637c62c48ed3a/sys/net/gnrc/application_layer/tftp/gnrc_tftp.c#L967-L969

This is the only application protocol purely based on GNRC (and as soon as we have async sock, I prefer to have it ported to `sock_udp`, but first we need to fix the bug ;-)).

**Comment by miri64** [comment]
I just noticed, that the server does not response ever since the shift to `gnrc_netif` (same old problem: link-local address without a given interface). I'll try and see if I can at least fix it for the server (the client would require an API change).

**Comment by miri64** [comment]
I can at least be sure with the latest squash, that the assertion I ran into is avoided.

**Comment by miri64** [comment]
Ok. I added a fix for the link-local address problem I mentioned before, but now I see, that with the fix I can still cause the server to switch source port when I send @nmeum's test message :-/....

**Comment by miri64** [comment]
Ok. It is not the test message causing the port to switch, but the normal message. I'm for merging these fixes soonish and then deprecating the module, as it is obviously flawed and unused.

File: sys/net/gnrc/application_layer/tftp/gnrc_tftp.c (hunk 2 above)
Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Ephemeral port selection is included in the module btw:

https://github.com/RIOT-OS/RIOT/blob/a01e70a4ab0050331b36ad59946637c62c48ed3a/sys/net/gnrc/application_layer/tftp/gnrc_tftp.c#L368-L370

Problem is: it runs also, when the _server_ receives a valid message, causing this https://github.com/RIOT-OS/RIOT/pull/11773#issuecomment-508068123

Comment (nmeum) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: > If I leave it unconfigured, the testing procedure in #11772 runs into an assertion here […]

You did leave it unconfigered in your PR, right? Because doesn't this allow someone to crash a RIOT node running `gnrc_tftp` with `DEVELHELP = 1` by sending a crafted input?

Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Arghs, this must have gotten lost, when I squashed :(

Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Wait no, right. I moved the initialization to 2fce0950bf0d03a2702bba7312fa55119e70a085, as `_tftp_state_processes` relied on certain configurations of `ctxt->dst_port` I was unsure about. I tested it with your crafted input, and it did not crash (the server was not responding anymore, because a legal input changed its port...., see #11778).

Comment (nmeum) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: > I tested it with your crafted input, and it did not crash

My previous test input gets rejected due to the blocknum contained in it. If you compile with `ENABLE_DEBUG` you get (among other things):

```
tftp: not the packet we were waiting for, expected 1, received 0
```

If you change the blocknum in the test input `gnrc_tftp` crashes:

```
echo AAMAAWZvb2Jhcg== | base64 -d | nc -u '[ip-address%tap0]' 69
``

Can you reproduces this or am I simply doing something wrong?

Comment (miri64) [reply sys/net/gnrc/application_layer/tftp/gnrc_tftp.c]: Yepp... Why did I touch this module -.- It's good that I deprecated it.
