### PR TITLE
posix_semaphore: make API POSIX compliant and port to xtimer (+ fixes)

### LINKED ISSUE #4109: posix: semaphores are not POSIX compliant
The POSIX specification states the functions related to semaphores shall return -1 on error. The current implementation replaced that with the corresponding errnos.

### PR DESCRIPTION
**Pull request by authmillenon**
Fixes #4109 by renaming `sem` to `sema` and fix its usage by `posix_semaphore` accordingly.

### CODE REVIEW

File: sys/posix/semaphore/posix_semaphore.c [hunk 1]
```diff
@@ -57,13 +58,13 @@ int sem_trywait(sem_t *sem)
     int result;
     if (sem == NULL) {
         errno = EINVAL;
-        return -EINVAL;
+        return -1;
     }
-    old_state = disableIRQ();
+    ld_state = disableIRQ();
```
Comment (Kijewski) [inline sys/posix/semaphore/posix_semaphore.c]: ?

Comment (authmillenon) [inline sys/posix/semaphore/posix_semaphore.c]: I guess I typed in `:x` a little bit hasty here and forgot the `:` ;-)

Comment (authmillenon) [inline sys/posix/semaphore/posix_semaphore.c]: Fixed.

**Comment by gebart** [comment]
While you're updating the POSIX semaphores, could you change the `#define sem_xxx() (-1)` stub implementations to `inline static int sem_xxx(int abc) { return -1; }`? (to get a proper function declaration)

**Comment by authmillenon** [comment]
Done

**Comment by gebart** [comment]
Quedtion: should we set errno to ENOMEM on sem_open, EINVAL on sem_close, ENOENT on sem_unlink?

**Comment by authmillenon** [comment]
Yes and done.

**Comment by gebart** [comment]
missing `#include "msg.h"` in sema.h

**Comment by authmillenon** [comment]
Done. As a bonus I ported both sema and posix_semaphore to xtimer ;-)

**Comment by authmillenon** [comment]
Wait… something went wrong. The tests aren't working anymore -.-

**Comment by authmillenon** [comment]
Bug seems to exist in master too. Will investigate.

**Comment by authmillenon** [comment]
According to the debugger TEST4 fails  on msg_receive with a SIGALARM on native and on other boards the timer just never fires. in the other tests (timeout == 0) it works just fine. Ideas?

**Comment by authmillenon** [comment]
Herpderp, if you change an API you might want to change the tests testing that API, too. Now everything should be in order :-)

**Comment by gebart** [comment]
ACK, please squash

I'm getting runtime failure of TEST4 `first: waited only 999058 usec => FAILED` but I get that in master as well. I am guessing this is a problem with the current xtimer configuration for mulle.

**Comment by gebart** [comment]
I also see that native closes with `alarm` on master, I guess this is the same as the SIGALRM problem described above. This PR fixes that error, `native` works again.

**Comment by authmillenon** [comment]
Squashed

**Comment by authmillenon** [comment]
> I'm getting runtime failure of TEST4 first: waited only 999058 usec => FAILED but I get that in master as well. I am guessing this is a problem with the current xtimer configuration for mulle.

Maybe I should put the `abstime` generation into the timed bracket. Might be that xtimer on mulle is "too precise" ;-).

**Comment by gebart** [comment]
I have seen that xtimer seem to be firing a bit too early in general on Mulle so don't worry about it. I am working on improvements to xtimer (#4040) and kinetis timer periph (#4065)

**Comment by gebart** [comment]
@authmillenon https://travis-ci.org/RIOT-OS/RIOT/jobs/87419969 Travis fails on msp430.. Something about const correctness it seems.

```
posix_semaphore:msb-430 (no linking):
Building application "posix_semaphore" for "msb-430" with MCU "msp430fxyz".
In file included from /home/travis/build/RIOT-OS/RIOT/tests/posix_semaphore/main.c:27:0:
/home/travis/build/RIOT-OS/RIOT/sys/posix/include/semaphore.h:246:44: error: 'struct timespec' declared inside parameter list [-Werror]
/home/travis/build/RIOT-OS/RIOT/sys/posix/include/semaphore.h:246:44: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
/home/travis/build/RIOT-OS/RIOT/tests/posix_semaphore/main.c: In function 'test4':
/home/travis/build/RIOT-OS/RIOT/tests/posix_semaphore/main.c:251:5: error: passing argument 2 of 'sem_timedwait' from incompatible pointer type [-Werror]
/home/travis/build/RIOT-OS/RIOT/sys/posix/include/semaphore.h:246:5: note: expected 'const struct timespec *' but argument is of type 'struct timespec *'
cc1: all warnings being treated as errors
make[1]: *** [/home/travis/build/RIOT-OS/RIOT/tests/posix_semaphore/bin/msb-430/posix_semaphore/main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
```

**Comment by authmillenon** [comment]
#4182 should fix that.

**Comment by authmillenon** [comment]
Based PR on that PR.

**Comment by authmillenon** [comment]
Rebased to current master.

**Comment by authmillenon** [comment]
(@gebart does your ACK uphold?)

File: sys/sema/sema.c [hunk 2]
```diff
@@ -90,24 +85,22 @@ int sem_wait_timed_msg(sem_t *sem, timex_t *timeout, msg_t *msg)
...
-                           MSG_TIMEOUT, sem);
+        if (timeout != 0) {
+            timeout_msg.type = MSG_TIMEOUT;
+            timeout_msg.content.ptr = (char *)sema;
+            /* we will stay in the same stack context so we can use timeout_msg */
+            xtimer_set_msg64(&timeout_timer, timeout, &timeout_msg, sched_active_pid);
         }
 
         restoreIRQ(old_state);
         msg_receive(msg);
```
Comment (gebart) [inline sys/sema/sema.c]: it is a good idea to explicitly remove the used xtimer before returning from sema_wait_timed_msg as the message `msg` may have originated elsewhere (regardless of content). Both because the xtimer object has local scope, and also in order to prevent future spurious messages from xtimer.

**Comment by gebart** [comment]
@authmillenon sorry, I found a problem that I missed on the first round.
ACK after xtimer_remove is added and Travis is fine

**Comment by gebart** [comment]
after some more consideration I think it would be best to move the timeout xtimer to outside the `while(1)` loop in `sema_wait_timed_msg`, to avoid using another timeout if the semaphore was signalled but another thread took it down to zero again before this thread had a chance to run its loop again.

another question: Would it make sense adding `if (msg_try_receive(msg) > 0) { return -EAGAIN; }` at the beginning of `sema_wait_timed_msg`? (To exit early if there is already a message waiting.)

File: sys/sema/sema.c (hunk 2 above)
Comment (gebart) [inline sys/sema/sema.c]: The same cleanup must be done for `n` as well before returning.

The scope of `n`, `timeout_msg` and `timeout_timer` should be moved to outside the while loop.

**Comment by authmillenon** [comment]
> another question: Would it make sense adding if (msg_try_receive(msg) > 0) { return -EAGAIN; } at the beginning of sema_wait_timed_msg? (To exit early if there is already a message waiting.)

But what if the message is actually for the semaphore?

File: sys/sema/sema.c (hunk 2 above)
Comment (authmillenon) [inline sys/sema/sema.c]: I think I don't have to change the scope.

**Comment by authmillenon** [comment]
Addressed comment

**Comment by gebart** [comment]
@authmillenon 
>But what if the message is actually for the semaphore?

Isn't that only used when the thread is actually blocking waiting for the semaphore? so any SIGNAL message that arrives before the actual wait should really be discarded?

File: sys/sema/sema.c [hunk 3]
```diff
@@ -90,24 +85,26 @@ int sem_wait_timed_msg(sem_t *sem, timex_t *timeout, msg_t *msg)
...
 
-        if (timeout != NULL) {
-            vtimer_remove(&timeout_timer);  /* remove timer just to be sure */
+        if (timeout != 0) {
+            xtimer_remove(&timeout_timer);
         }
-
-        if (msg->content.ptr != (void *) sem) {
+        priority_queue_remove(&sema->queue, &n);
```
Comment (gebart) [inline sys/sema/sema.c]: messing with the queue may cause problems if interrupts are enabled.

**Comment by authmillenon** [comment]
@gebart  no in theory someone can post the semaphore well before another thread waits on it.

**Comment by gebart** [comment]
@authmillenon 
if sema_post is called before sema_wait, then the value of the semaphore will already be > 0 and no message is needed. The implementation in sema_wait_timed_msg doesn't check for any message if the semaphore value is > 0 when entering the loop.

**Comment by authmillenon** [comment]
> if sema_post is called before sema_wait, then the value of the semaphore will already be > 0 and no message is needed.  The implementation in sema_wait_timed_msg doesn't check for any message if the semaphore value is > 0 when entering the loop.

[Of course it does]. And yes: in that case it exits early with return value equal to 0.

**Comment by gebart** [comment]
@authmillenon do you agree that the xtimer should move outside the message waiting loop? (https://github.com/RIOT-OS/RIOT/pull/4110#issuecomment-152098171)

File: sys/sema/sema.c (hunk 2 above)
Comment (gebart) [inline sys/sema/sema.c]: agreed, with the added cleanups it is no longer necessary to have the variables exist outside the loop iteration.

**Comment by gebart** [comment]
There is still the issue of the timeout not being obeyed if the semaphore is posted and signalled to this thread, but another, higher priority, thread manages to snatch it before this thread has a chance to take it. Then the timeout in this thread will be reset to its original value again before waiting for another signal message. If this repeats we may overrun the timeout indefinitely. If the xtimer is moved to outside of the main waiting loop the timeout will be total waiting time instead of incremental per iteration.

**Comment by authmillenon** [comment]
I'm only to 95% sure I got what you were saying so please check 8c49e19 =).

**Comment by authmillenon** [comment]
Ping?

**Comment by gebart** [comment]
yes, that was what I meant.
The code is a bit difficult to read though with the disableIRQ call coming after the restoreIRQ call in the revised loop. 
From a readability perspective it would make sense to add a restoreIRQ call right after the xtimer_set call and move the second disableIRQ to right before `unsigned value = sema->value;`

**Comment by authmillenon** [comment]
Fixed. This is a lot of discussion for an standardized API change ;-P

File: sys/sema/sema.c [hunk 4]
```diff
@@ -90,29 +95,25 @@ int sem_wait_timed_msg(sem_t *sem, timex_t *timeout, msg_t *msg)
...
+        if (msg->content.ptr != (void *)sema) {
             return -EAGAIN;
         }
 
         switch (msg->type) {
             case MSG_SIGNAL:
+                old_state = disableIRQ();
```
Comment (gebart) [inline sys/sema/sema.c]: remove this leftover

**Comment by gebart** [comment]
https://github.com/RIOT-OS/RIOT/pull/4110/files#diff-4af11e61eb26bcdd3eed69b819563f52R109
please address or add a comment why it is not necessary to disable IRQs there.

**Comment by gebart** [comment]
@authmillenon The reason for this long discussion is mostly because the original semaphore module (before your refactoring in the previous PR) had some bit rot that we are addressing here as well.

**Comment by authmillenon** [comment]
> @authmillenon The reason for this long discussion is mostly because the original semaphore module (before your refactoring in the previous PR) had some bit rot that we are addressing here as well.

True, but that could have been done in a follow-up ;-)

> https://github.com/RIOT-OS/RIOT/pull/4110/files#diff-4af11e61eb26bcdd3eed69b819563f52R109
please address or add a comment why it is not necessary to disable IRQs there.

Addressed

**Comment by gebart** [comment]
ACK, please squash

**Comment by authmillenon** [comment]
Squashed

**Comment by gebart** [comment]
Travis fails:
    /home/travis/build/RIOT-OS/RIOT/sys/posix/semaphore/posix_semaphore.c:45:42: error: passing argument 2 of 'sema_wait_timed' makes integer from pointer without a cast [-Werror]
         res = sema_wait_timed((sema_t *)sem, &timeout);

**Comment by authmillenon** [comment]
Some commits got lost on rebase. Cherry-picked 'em back into place.

**Comment by authmillenon** [comment]
Thanks for the review btw ^^"

**Comment by gebart** [comment]
np, sorry for the long-winded review process.
