### PR TITLE
gnrc_netif_pktq: protect against concurrent access

### LINKED ISSUE #17924: gnrc_netif_pktq leaks memory
#### Steps to reproduce the issue

Use `gnrc_netif_pktq` on a board with two interfaces (e.g. `nrf802154` & `slipdev`) e.g. by running

    make -C examples/gnrc_border_router BOARD=nrf52840dk UPLINK=slip -j flash term

#### Expected results

The node can send and receive packets.

#### Actual results

After a few minutes the node can no longer send any packets

```
2022-04-13 00:57:06,058 # > ping ff02::1
2022-04-13 00:57:06,060 # error: packet buffer full
2022-04-13 00:57:07,060 # error: packet buffer full
2022-04-13 00:57:08,060 # error: packet buffer full
2022-04-13 00:57:09,058 # 
2022-04-13 00:57:09,061 # --- ff02::1 PING statistics ---
2022-04-13 00:57:09,066 # 3 packets transmitted, 0 packets received, 100% packet loss
```

The node never recovers until it is rebooted.

#### Versions

RIOT master

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The `_get_free_entry()` accesses a static buffer, so we must protect it from concurrent access to avoid corruption.

### Testing procedure

Run the `examples/gnrc_border_router` on e.g. a `nrf52840dk` with another node in the network, in my case an `avr-rss2` which got the address `2001:db8::fec2:3d00:0:bb1`.

Now start two pings in parallel on your host machine:

    ping -A 2001:db8::fec2:3d00:0:bb1 -s 512
    sudo ping -f 2001:db8::fec2:3d00:0:bb1

On `master` this will crash & burn:

```
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
Stack pointer corrupted, reset to top of stack
FSR/FAR:
 CFSR: 0x00000092
 HFSR: 0x40000000
 DFSR: 0x00000000
 AFSR: 0x00000000
MMFAR: 0x20000018
Misc
EXC_RET: 0xfffffff1
----> ethos: hello received
```

With this patch we also run out of queue space, but we manage to recover when we stop the flood ping.

```
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending
gnrc_netif: can't queue packet for sending

> ping -s 512 ff02::1
520 bytes from fe80::7837:fcff:fe7d:1aae%5: icmp_seq=0 ttl=64 time=107.856 ms
520 bytes from fe80::7837:fcff:fe7d:1aae%5: icmp_seq=1 ttl=64 time=114.955 ms
520 bytes from fe80::7837:fcff:fe7d:1aae%5: icmp_seq=2 ttl=64 time=107.774 ms

--- ff02::1 PING statistics ---
3 packets transmitted, 3 packets received, 0% packet loss
round-trip min/avg/max = 107.774/110.195/114.955 ms
```

### Issues/PRs references

partially fixes #17924, when doing a `sudo ping -f 2001:db8::fec2:3d00:0:bb1 -s 512` the upstream interface remains 'dead' for several seconds after the flood ping was stopped.

### CODE REVIEW

File: sys/net/gnrc/netif/pktq/gnrc_netif_pktq.c [hunk 1]
```diff
@@ -23,16 +23,24 @@
 #define ENABLE_DEBUG 0
 #include "debug.h"
 
+static mutex_t _pool_lock;
```
Comment (miri64) [inline sys/net/gnrc/netif/pktq/gnrc_netif_pktq.c:26]:
```suggestion
static mutex_t _pool_lock = MUTEX_INIT;
```

**Review by miri64 — COMMENTED** [review]
The mutex should be initialized, otherwise, the change looks good.

**Comment by benpicco** [comment]
btw: What's the reason this pool is not shared with the packet queue for address resolution (`CONFIG_GNRC_IPV6_NIB_QUEUE_PKT`)?

**Review by miri64 — APPROVED** [review]

**Comment by miri64** [comment]
I trust your testing and from the code this should also work fine.

**Comment by benpicco** [comment]
I think it's different though. Unlike cache entries, those queue entries are short lived, when they are full we *will* lose packets either way.

And if we queue the packet because we have to do address resolution first or because the interface is busy doesn't seem like much of a difference conceptually. If we have many packets queued for address resolution we would also have a busy interface as a result, and if our interface is too busy it would also drop the address resolution packets.
