### PR TITLE
cpu/efm32/periph/timer: fix timer_set_absolute() in 16bit case

### LINKED ISSUE #15060: ztimer tests fail on efm32
#### Description

Something seems not to work with ztimer on EFM32. I noticed this when I moved the Rust demos from xtimer over to ztimer, and both the saul_blink and the coap demos got stuck. (I have a 3000-long sleep on the ms timer, and have yet to see it return.)

Based on that, I could reproduce some error on plain RIOT, which is probably the same:

#### Steps to reproduce the issue

```shell
$ make -C tests/ztimer_overhead BOARD=stk3700 all PROGRAMMER=openocd all flash test
[...]
START
main(): This is RIOT! (Version: 2020.10-devel-1468-gc270a)
ZTIMER_USEC->adjust = 0
Timeout in expect script at "child.expect(r"min=-?\d+ max=-?\d+ avg_diff=\d+\r\n")" (tests/ztimer_overhead/tests/01-run.py:14)
```

(The board and OpenOCD combo was verified to work using the xtimer_overhead example. Same for sltb001a)

#### Expected results

On a different board, things just work:

```shell
START
main(): This is RIOT! (Version: 2020.10-devel-1468-gc270a)
ZTIMER_USEC->adjust = 0
min=6 max=6 avg_diff=6
s
```

#### Versions

Debian GNU/Linux sid, RIOT head c270aadc0

## Next steps

I'll happily look deeper into it, but would appreciate pointers at where to start.

### PR DESCRIPTION
**Pull request by kaspar030**
### Contribution description

Previously, the function would return -1 without setting a timer, should the absolute target time exceed the timer width (this could only happen in the 16bit case). This behaves differently than other periph_timers that use a 16bit, which implicitly sets `value & 0xFFFF`.

### Testing procedure

Test e.g., `tests/ztimer_overhead` on an affected board (sltb0001, stk3700, ...).

### Issues/PRs references

Fixes #15060.

### CODE REVIEW

**Comment by chrysn** [comment]
It works, and I see the parallel to eg. ezr32wg (where the same is achieved by casting to uint16_t)

File: cpu/efm32/periph/timer.c [hunk 1]
```diff
@@ -169,9 +173,8 @@ int timer_set_absolute(tim_t dev, int channel, unsigned int value)
             return -1;
         }
```
Comment (chrysn) [inline cpu/efm32/periph/timer.c:175]:
```suggestion

        /* Truncating the value while the generic timer_set can't know how to
         * wrap; overflows can return an error once that doesn't produce
         * wrapping values any more. */
```

**Comment by chrysn** [comment]
OK, now I *do* understand: The ztimer does know the underlying device's width (as max_value passed in during auto_init via CONFIG_ZTIMER_USEC_WIDTH).

But the common timer's `timer_set` calls the set_absolute with `timer_read(dev) + timeout`, which does the right thing on 32bit timers but will call timer_set_absolute with a >16-bit value whenn the timer_set spans a 16bit timer wraparound.

As generic timer_set would have a hard time knowing the max_value (as it's in preprocessor constants, and timer_set is a regular function), this appears to be a practical construction.

I've written a folllow-up commit that'd add a note to timer_set_absolute saying "Timers that are less wide than `unsigned int` accept and truncate overflown values.", but when I did the rest of the review steps I discovered that #10493 is probably the cleaner solution long-term (as the generic timer_set could then wrap the values properly). Instead, I've added a suggestion for a comment that doesn't normalize this wrap-around (which, from the API description, would be legitimately regarded as an error) but explains why and for how long it needs to be there.

**Comment by kaspar030** [comment]
> probably the cleaner solution long-term (as the generic timer_set could then wrap the values properly).

Well, it would need to call timer_max() on every set(), which is by definition time sensitive. Also, the return of timer_max() would be an integer, which would then require a modulo operation. On all platforms that do use registers, the truncation will be done implicitly again. So I do think it makes sense to put this behavior int the API spec and deal with it right in timer_set_absolute() implementations, if necessary...

**Comment by chrysn** [comment]
You have a point there; as timer_set is not inlined, it won't know the timer value and thus can't do the timer_max truncation efficiently.

I've pushed my original comment to the branch (hey that works :-) ); if that meets with your approval, I ACK this (pending a second pair of eyes from my junior maintainer status).

File: cpu/efm32/periph/timer.c (hunk 1 above)
Comment (chrysn) [reply cpu/efm32/periph/timer.c:175]: Addressed in https://github.com/RIOT-OS/RIOT/pull/15062#issuecomment-697230170

**Comment by kaspar030** [comment]
> I've pushed my original comment to the branch (hey that works :-) ); if that meets with your approval, I ACK this (pending a second pair of eyes from my junior maintainer status).

Looks good. (the commit has some implications on how we understand periph_timer and might need seperate discussion, thus it could have been put in a seperate PR, but I think it just clarifies what was happening before, so hey...)

**Review by chrysn — APPROVED** [review]
Junior developer ACK from me; will merge once senior co-ACK is in.

**Review by bergzand — APPROVED** [review]
Ack, code looks good and I trust @chrysn's tests.

**Comment by kaspar030** [comment]
@chrysn was this your first merge to RIOT? congrats!

**Comment by chrysn** [comment]
My second one (but first one I merged I didn't write myself).

Thanks for the fix; it would have taken me quite a bit longer to find
what was actually wrong.
