### PR TITLE
gnrc_rpl: fix abandoned packet bug in transit option build

### LINKED ISSUE #8098: gnrc: Packet buffer full errors after few hours of uptime
After running for an hour or so, one of my nodes can't ping the border router anymore with three times `error: packet buffer full` as a message. Ping from the border router to the node also doesn't work anymore (I assume also due to the packet buffer being full)

If there are steps I can take to debug this, I'd like to know, for now I can keep the GDB session attached.

setup:
2 nucleo-f446, mrf24j40 radio
1 configured as gnrc_border_router example mrf24j40 settings
1 configured as gnrc_networking example with mrf24j40 settings

### PR DESCRIPTION
**Pull request by miri64**
First and most important fix in ~~a string~~ (managed to fit it into two PRs) of RPL fixes towards #7925 

Due to the transit option build function being passed a NULL pointer,
the previous transit and target options are dropped (and never freed).

This fixes #8098 and #8126.

### CODE REVIEW

File: sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c [hunk 1]
```diff
@@ -744,22 +744,25 @@ void gnrc_rpl_send_DAO(gnrc_rpl_instance_t *inst, ipv6_addr_t *destination, uint
     void *ft_state = NULL;
     gnrc_ipv6_nib_ft_t fte;
     while(gnrc_ipv6_nib_ft_iter(NULL, dodag->iface, &ft_state, &fte)) {
+        gnrc_pktsnip_t *tmp;
         DEBUG("RPL: Send DAO - building transit option\n");
 
-        if ((pkt = _dao_transit_build(NULL, lifetime, false)) == NULL) {
+        if ((tmp = _dao_transit_build(pkt, lifetime, false)) == NULL) {
             DEBUG("RPL: Send DAO - no space left in packet buffer\n");
+            gnrc_pktbuf_release(pkt);
```
Comment (bergzand) [inline sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c]: This release is already handled by the `_dao_transit_build` function [here](https://github.com/miri64/RIOT/blob/96b716fe24c59bbf4c354b300ea024f58c4bceab/sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c#L683).

File: sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c [hunk 2]
```diff
@@ -744,22 +744,25 @@ void gnrc_rpl_send_DAO(gnrc_rpl_instance_t *inst, ipv6_addr_t *destination, uint
...
-
+        pkt = tmp;
         if (ipv6_addr_is_global(&fte.dst)) {
             DEBUG("RPL: Send DAO - building target %s/%d\n",
                   ipv6_addr_to_str(addr_str, &fte.dst, sizeof(addr_str)), fte.dst_len);
 
-            if ((pkt = _dao_target_build(pkt, &fte.dst, fte.dst_len)) == NULL) {
+            if ((tmp = _dao_target_build(pkt, &fte.dst, fte.dst_len)) == NULL) {
                 DEBUG("RPL: Send DAO - no space left in packet buffer\n");
+                gnrc_pktbuf_release(pkt);
```
Comment (bergzand) [inline sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c]: This release is already handled by the `_dao_target_build` function [here](https://github.com/miri64/RIOT/blob/96b716fe24c59bbf4c354b300ea024f58c4bceab/sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c#L664).

File: sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c (hunk 1 above)
Comment (miri64) [reply sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c]: True will fix (both).

**Comment by miri64** [comment]
Done

**Comment by bergzand** [comment]
Tested and fixes #8126, not sure yet about #8098 yet, need a few more minutes to verify that.

File: sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c [hunk 3]
```diff
@@ -744,22 +744,23 @@ void gnrc_rpl_send_DAO(gnrc_rpl_instance_t *inst, ipv6_addr_t *destination, uint
...
+        gnrc_pktsnip_t *tmp;
         DEBUG("RPL: Send DAO - building transit option\n");
 
-        if ((pkt = _dao_transit_build(NULL, lifetime, false)) == NULL) {
+        if ((tmp = _dao_transit_build(pkt, lifetime, false)) == NULL) {
             DEBUG("RPL: Send DAO - no space left in packet buffer\n");
             return;
         }
-
+        pkt = tmp;
```
Comment (bergzand) [inline sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c]: Minor nitpick: This whole `tmp` to `pkt` sequence is not required anymore now that the release lines are gone right?

Comment (miri64) [reply sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c]: Yes... will fix as well ^^"

Comment (miri64) [reply sys/net/gnrc/routing/rpl/gnrc_rpl_control_messages.c]: Doen

**Comment by bergzand** [comment]
Ready for squashing by the way.

**Comment by miri64** [comment]
Squashed
