### PR TITLE
sys/base64: corrected output size determination

### LINKED ISSUE #6166: base64_encode calculates wrong output size
The formula of base64_encode  for calculating base64_out_size is wrong (RIOT/sys/base64/base64.c  lines 62,63). For example for data_in_size = 16 it outputs 26, whereas the correct size is 24.

### PR DESCRIPTION
**Pull request by BytesGalore**
Until now the output size determination calculated a wrong expected output size when encoding.
This PR also adds an additional unittets. 

Fixes #6166

### CODE REVIEW

File: sys/base64/base64.c [hunk 1]
```diff
@@ -59,8 +59,7 @@ static char getsymbol(unsigned char code)
 int base64_encode(unsigned char *data_in, size_t data_in_size, \
                   unsigned char *base64_out, size_t *base64_out_size)
 {
-    size_t padding_bytes = ((data_in_size % 3) ? (3 - (data_in_size % 3)) : 0);
-    size_t required_size = (4 * (data_in_size + 2 - ((data_in_size + 2) % 3)) / 3) + padding_bytes;
+    size_t required_size = ((4 * data_in_size / 3) + 3) & ~3;
```
Comment (Kijewski) [inline sys/base64/base64.c]: Multiplying before dividing may introduce an integer overflow. What's wrong with the formula @x3ro posted? `4 * ((input_length + 2) / 3)`

**Comment by x3ro** [comment]
ACK

**Comment by BytesGalore** [comment]
nice, then I will squash

**Comment by BytesGalore** [comment]
squashed

**Comment by OlegHahm** [comment]
```
Running './dist/tools/whitespacecheck/check.sh master' x
Command output:

	tests/unittests/tests-base64/tests-base64.c:323: trailing whitespace. + tests/unittests/tests-base64/tests-base64.c:351: trailing whitespace. + tests/unittests/tests-base64/tests-base64.c:383: trailing whitespace. + tests/unittests/tests-base64/tests-base64.c:323: trailing whitespace. + tests/unittests/tests-base64/tests-base64.c:351: trailing whitespace. + tests/unittests/tests-base64/tests-base64.c:383: trailing whitespace. + ERROR: This change introduces new whitespace errors
```

**Comment by BytesGalore** [comment]
Oh no, it feels a bit like a deja vu (#4856):
```
...
region `rom' overflowed by 484 bytes
```

**Comment by PeterKietzmann** [comment]
Two approvals and Murdock green. Go!
