### PR TITLE
pkg: relic: fix compiling on OS X

### LINKED ISSUE #4590: pkg: building relic with clang fails
To successfully build relic with clang these additional flags work as a workaround. `-Wno-gnu-zero-variadic-macro-arguments -Wno-newline-eof -Wno-unused-function` I did however didn't figure out how to introduce them without touching the boards Makefile or CMakeLists.txt. Adding them in `generate-cmake-xcompile.perl` didn't work.

### PR DESCRIPTION
**Pull request by kYc0o**
Fixes #4590 

An alternative of #7780 which uses the native `sed` command on OS X, which is the cause of compile failure in some OS X installations.

### CODE REVIEW

File: pkg/relic/os_util.sh [hunk 1]
```diff
@@ -2,5 +2,5 @@ OSNAME=`uname -s`
 SEDBIN="sed -i"
 if [ "${OSNAME}" = "Darwin" ] ; then
     SEDBIN="sed -i ''"
-    LANG=C
```
Comment (smlng) [inline pkg/relic/os_util.sh]: maybe leave this too, it was needed in the past -> maybe for some older version of macOS it should stay?

Comment (kYc0o) [reply pkg/relic/os_util.sh]: Ok, will change.

**Comment by kYc0o** [comment]
Comments addressed.

**Comment by smlng** [comment]
please squash

**Comment by kYc0o** [comment]
Go!
