### PR TITLE
cpu/native: use async read for stdio_read()

### LINKED ISSUE #16834: native getchar is blocking RIOT
#### Description

On native: 
getchar and therefor shell are blocking RIOT (lower than getchar priority tasks) (it does not change thread since it does no use the internal mutex)

This is an stdio on native problem ztimer is just used for demonstration purposes.

#### Steps to reproduce the issue
I just attached en example  (inside the zip since zip is much saver than demo.c  and a Makefile - maybe there is another reasoning for the choice of attachables)

[bug_stdio.zip](https://github.com/RIOT-OS/RIOT/files/7187367/bug_stdio.zip)

```
$ make
$ make term

> hello HULK
```
second arg to hello will be interpreted as int offset for the priority of the hello (-1 will put it in front and block shell, this is expecteted as it is spinning on a ztimer)

The same problem exists if ztimer sleep is used but it does not show as nice

#### Expected results

HULK shall be greeted every 2 seconds while the shell keeps running

running that same thing on non native e.g. nucleo... works as expected

#### Actual results

no greetings to HULK shell keeps running 

#### Versions
current RIOT

was discovered while processing #16808

 #16822 does not yet help

[bug_stdio.zip](https://github.com/RIOT-OS/RIOT/files/7187367/bug_stdio.zip)

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

The real_read() function will block the thread but won't preempt it.
That means all other threads on the same (or higher) priority level are blocked as RIOT still considers the thread that called `stdio_read()` as running.

Use async_read/isrpipe to properly block the thread when reading from stdin.

### Testing procedure

Run a 2nd thread with the same priority as the main thread:

```patch
--- a/tests/shell/main.c
+++ b/tests/shell/main.c
@@ -132,10 +132,28 @@ static int _xfa_test2(int argc, char **argv)
 SHELL_COMMAND(xfa_test2, "xfa test command 2", _xfa_test2);
 SHELL_COMMAND(xfa_test1, "xfa test command 1", _xfa_test1);
 
+#include "thread.h"
+#include "ztimer.h"
+
+static char _stack[1024];
+
+static void *_func(void *arg)
+{
+    while (1) {
+        ztimer_sleep(ZTIMER_MSEC, 1000);
+        puts(arg);
+    }
+
+    return NULL;
+}
+
 int main(void)
 {
     printf("test_shell.\n");
 
+    thread_create(_stack, sizeof(_stack), THREAD_PRIORITY_MAIN, THREAD_CREATE_STACKTEST,
+                  _func, "Hello shell", "periodic");
+
     /* define own shell commands */
     shell_run_once(shell_commands, line_buf, sizeof(line_buf));
```

On `master` the periodic `"Hello shell"` message is never printed.

### Issues/PRs references

fixes #16834

### CODE REVIEW

**Comment by benpicco** [comment]
@leandrolanzieri do you have an idea how to solve the Kconfig issue?

File: cpu/native/stdio_native/Kconfig [hunk 1]
```diff
@@ -0,0 +1,13 @@
+# Copyright (c) 2021 HAW Hamburg
+#
+# This file is subject to the terms and conditions of the GNU Lesser
+# General Public License v2.1. See the file LICENSE in the top level
+# directory for more details.
+#
+
+config MODULE_STDIO_NATIVE
```
Comment (leandrolanzieri) [inline cpu/native/stdio_native/Kconfig:8]: This already exists in https://github.com/RIOT-OS/RIOT/blob/83a433c8e76fea5515006002c4e4a00b6b44827e/sys/Kconfig.stdio#L41-L44

Comment (leandrolanzieri) [reply cpu/native/stdio_native/Kconfig:8]: According to the current practice, you could just `select MODULE_ISRPIPE`

File: cpu/native/async_read.c [hunk 2]
```diff
@@ -52,7 +52,10 @@ void native_async_read_cleanup(void) {
     unregister_interrupt(SIGIO);
 
     for (int i = 0; i < _next_index; i++) {
-        real_close(_fds[i].fd);
+        /* don't close stdin */
```
Comment (gschorcht) [inline cpu/native/async_read.c:55]: Why is this necessary, it works also without this change?

File: cpu/native/include/async_read.h [hunk 3]
```diff
@@ -29,7 +29,7 @@ extern "C" {
  * @brief   Maximum number of file descriptors
  */
 #ifndef ASYNC_READ_NUMOF
-#define ASYNC_READ_NUMOF 2
+#define ASYNC_READ_NUMOF 8
```
Comment (gschorcht) [inline cpu/native/include/async_read.h:32]: Is this increase only necessary because 
```
CFLAGS += -DASYNC_READ_NUMOF=$(shell expr $(ZEP_DEVICES) + 1)
```
is removed from the makefile?

File: cpu/native/async_read.c (hunk 2 above)
Comment (benpicco) [reply cpu/native/async_read.c:55]: Otherwise stdin won't work after a `reboot`

File: cpu/native/include/async_read.h (hunk 3 above)
Comment (benpicco) [reply cpu/native/include/async_read.h:32]: Kinda, the default would now need to be +1
But then again why place such a low limit in `native` where a few bytes extra RAM use really don't matter.

Comment (gschorcht) [reply cpu/native/include/async_read.h:32]: Yeah, on native it doesn't matter.

File: cpu/native/async_read.c (hunk 2 above)
Comment (gschorcht) [reply cpu/native/async_read.c:55]: Hm, I tested to comment it out and it still works after reboot.

Comment (benpicco) [reply cpu/native/async_read.c:55]: That's odd, `tests/shell` would fail because `stdin` would not get re-opened.

Comment (gschorcht) [reply cpu/native/async_read.c:55]: Ah, it just looks like the stdin still works after reboot, but the node doesn't react.

**Review by gschorcht — APPROVED** [review]
Looks good and works as expected.

**Comment by gschorcht** [comment]
Please squash.

**Comment by benpicco** [comment]
CI will still fail as some tests that use `float` will now preempt, which triggers #495

**Comment by mguetschow** [comment]
This seems to break when more than `STDIO_RX_BUFSIZE` characters are input at once on the shell, with

https://github.com/RIOT-OS/RIOT/blob/db345a77bf97fcd647e7fba272e22ae1a85f7770/cpu/native/stdio_native/stdio_native.c#L21-L30

not checking the return value of `isrpipe_write`. This seems to produce undeterministically garbaged output for `shell_readline`. This is especially confusing to the user of the shell who configured the shell size to a larger value than the the default 64B.

Not sure what it actually should do with the return value, however :/

Any ideas how to fix that?

**Comment by mguetschow** [comment]
Oh, interesting:

https://github.com/RIOT-OS/RIOT/blob/e6a570a605e8b697aabab58259603e8e3a09b7d0/sys/include/shell.h#L102-L118
