### PR TITLE
sys/vfs: Exclude stdio file numbers from auto allocation

### LINKED ISSUE #8309: VFS Module does not reserve file descriptors 0, 1, and 2
#### Description

The VFS module does not reserve file descriptors 0, 1, and 2 for stdin, stdout, and stderr. As a result, the following bugs exist:
* Opening a file could be assigned to one of these descriptors.
* Utilities in newlib such as `printf` do not work. The output is written to file descriptor 1 and `uart_stdio_write` never gets called.

More generally, there seems to be no `vfs_init` procedure, so it seems that all the `_vfs_open_files` array is unintialized. In my opinion, the correct solution is to add a `vfs_init` procedure that initializes the `_vfs_open_files` array and reserves file descriptors 0, 1, and 2.

#### Steps to reproduce the issue

Method 1: Call printf().
Method 2: Open a socket with the posix_sockets module.

#### Expected results

Expected Results for Method 1: The output is written to the screen.
Expected Results for Method 2: The resulting file descriptor is greater than 2.

#### Actual results

Actual Results for Method 1: Nothing is written to the screen.
Actual Results for Method 2: The resulting file descriptor is 0.

#### Versions

I am building the code from a Linux computer running Ubuntu 16.04.
The platform I am targeting is HAMILTON (@immesys).

Output from `print_toolchain_versions.sh`:
```
./print_toolchain_versions.sh 
Installed toolchain versions
----------------------------
          native gcc: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
          msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
             avr-gcc: missing/error
   arm-none-eabi-gcc: arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
    mips-mti-elf-gcc: missing/error
               clang: clang version 3.8.0-2ubuntu4 (tags/RELEASE_380/final)
arm-none-eabi-newlib: "2.2.0"
 mips-mti-elf-newlib: missing/error
            avr-libc: missing/error (missing/error)
            cppcheck: missing
          coccinelle: missing
```

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

Do not auto-allocate the stdio file descriptor numbers to avoid conflicts between normal file system users and stdio drivers such as uart_stdio, rtt_stdio which need to be able to bind to these specific file descriptor numbers.
Adds a regression test for vfs_bind to check that it never returns stdio file descriptors (which fails without the other commit)

Tested on native and mulle.

### Issues/PRs references

Fixes #8309 
An alternative to #8310

### CODE REVIEW

**Comment by vincent-d** [comment]
OK for me, you can merge at will

File: sys/vfs/vfs.c [hunk 1]
```diff
@@ -867,6 +868,13 @@ static inline int _allocate_fd(int fd)
 {
     if (fd < 0) {
         for (fd = 0; fd < VFS_MAX_OPEN_FILES; ++fd) {
+            if ((fd == STDIN_FILENO) || (fd == STDOUT_FILENO) || (fd == STDERR_FILENO)) {
```
Comment (kaspar030) [inline sys/vfs/vfs.c]: POSIX defines them as 0, 1 and 2. (e.g. here: http://pubs.opengroup.org/onlinepubs/000095399/functions/stdin.html). Can't we just start counting with 3?

Comment (kaspar030) [reply sys/vfs/vfs.c]: (sorry, didn't realise the two ACKs.) ACK.

**Comment by gebart** [comment]
I checked the disassembly, and the compiler does optimize the check into the equivalent of `if (fd <= 2)` instead of three separate equality comparisons.

**Comment by kaspar030** [comment]
> I checked the disassembly, and the compiler does optimize the check into the equivalent of if (fd <= 2) instead of three separate equality comparisons.

Perfect!
