### PR TITLE
cpu/nrf5x/radio/nrfmin: Enhance nrfmin reliability

### LINKED ISSUE #10878: nrfmin can get stuck and never reach RX (while TX works)
#### Description

nrfmin radio driver can become stuck in a state where it can no longer receive packets over the radio.

This issue triggers sporadically and can happen within seconds or hours of operation. Increased number of nodes concurrently trying to send seems to increase the chance of it.

My original research showed when driver is in this state, there is a packet received, but it appears to be never passed on and cleared, so it prevents the driver from switching periphery into receive mode. I.e. second condition fails:

https://github.com/RIOT-OS/RIOT/blob/3e6336ce89d64d58ab07764ef7f65fc86800cb85/cpu/nrf5x_common/radio/nrfmin/nrfmin.c#L160

For more info please see attempted fixes at the end.

#### Steps to reproduce the issue

1. Use nrfmin, 6LoWPAN, and GNRC in a program that periodically (broad|multi)casts.
2. Leave two or more nodes on.

#### Expected results

Packets should be received until conditions become unsatisfactory for chip operation or radio connection.

#### Actual results

Packets can be sent over the radio, but receiving does not work.

#### Versions

[9fadbf6](https://github.com/RIOT-OS/RIOT/commit/9fadbf60b421d15269431cb80cbd7c97027c8472)
```
Operating System Environment
-----------------------------
        Operating System: "Manjaro Linux"
                  Kernel: Linux 4.19.16-1-MANJARO x86_64 unknown
Installed compiler toolchains
-----------------------------
              native gcc: gcc (GCC) 8.2.1 20181127
       arm-none-eabi-gcc: arm-none-eabi-gcc (Arch Repository) 8.2.0
                 avr-gcc: missing
        mips-mti-elf-gcc: missing
              msp430-gcc: missing
    riscv-none-embed-gcc: missing
    xtensa-esp32-elf-gcc: missing
    xtensa-lx106-elf-gcc: missing
                   clang: missing
Installed compiler libs
-----------------------
    arm-none-eabi-newlib: "3.0.0"
     mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
xtensa-esp32-elf-newlib: missing
xtensa-lx106-elf-newlib: missing
                avr-libc: missing (missing)
Installed development tools
---------------------------
                   cmake: cmake version 3.13.2
                cppcheck: missing
                 doxygen: missing
                  flake8: missing
                     git: git version 2.20.1
                    make: GNU Make 4.2.1
                 openocd: Open On-Chip Debugger 0.10.0
                  python: Python 3.7.2
                 python2: Python 2.7.15
                 python3: Python 3.7.2
              coccinelle: missing
```

My particular NRF51 chip **is not affected by** PAN 20 (which means `STATE` register can be used in my case)

#### Attempted fixes

I attempted to fix this by making certain code run in the interrupt handler (assuming that's the most correct place in effort to avoid blowing something else's stack):

```c
void isr_radio(void)
{
    if (NRF_RADIO->EVENTS_END == 1) {
        NRF_RADIO->EVENTS_END = 0;
        /* did we just send or receive something? */
        if (state == STATE_RX || rx_buf.pkt.hdr.len > 0) {
            /* drop packet on invalid CRC */
            if ((NRF_RADIO->CRCSTATUS != 1) || !(nrfmin_dev.event_callback)) {
                rx_buf.pkt.hdr.len = 0;
                NRF_RADIO->TASKS_START = 1;
            } else {
                rx_lock = 0;
                nrfmin_dev.event_callback(&nrfmin_dev, NETDEV_EVENT_ISR);
            }
        }
        if (state == STATE_TX) {
            goto_target_state();
        }
    }

    cortexm_isr_end();
}
```

This greatly improved reliability, yet now sending function would sometimes spinlock waiting for `state` to change from `STATE_TX`:

https://github.com/RIOT-OS/RIOT/blob/3e6336ce89d64d58ab07764ef7f65fc86800cb85/cpu/nrf5x_common/radio/nrfmin/nrfmin.c#L335

After a few attempts I ~managed to avoid~<ins>reduce chance of</ins> that by adding code that waits for `EVENT_READY` after triggering `TASK_TXEN` and `TASK_RXEN`:

https://github.com/RIOT-OS/RIOT/blob/3e6336ce89d64d58ab07764ef7f65fc86800cb85/cpu/nrf5x_common/radio/nrfmin/nrfmin.c#L166

https://github.com/RIOT-OS/RIOT/blob/3e6336ce89d64d58ab07764ef7f65fc86800cb85/cpu/nrf5x_common/radio/nrfmin/nrfmin.c#L357

Changed to:

```c
        NRF_RADIO->EVENTS_READY = 0;
        NRF_RADIO->TASKS_RXEN = 1;
        while (NRF_RADIO->EVENTS_READY == 0) {}
```

With these changes, after a lot of time, system sometimes hard faults. I was unable to recover the details because UART disconnected prior to that.

#### Other observations

`cortexm_isr_end()` is docummented as to be called at the end of every interrupt routine, but in this driver, in `isr_radio`, line https://github.com/RIOT-OS/RIOT/blob/3e6336ce89d64d58ab07764ef7f65fc86800cb85/cpu/nrf5x_common/radio/nrfmin/nrfmin.c#L315 can return early and not fufill that specification. Should this be corrected?

Also, when `NRF_RADIO->POWER` is set to `0` (off), it appears to reset some of the registers. When waking periphery up, `nrfmin_init` should probably be called again.

### PR DESCRIPTION
**Pull request by SemjonKerner**
### Contribution description

This PR provides fix for 3 independent flaws of the nrfmin radio driver:

The most profound commit fixes a bug discovered by @PeterKietzmann that allows to receive packets with a false receiver address. This Bug happend for receiver boards nrf52840dk and nrf52dk and was fixed with a workaround given by the errata sheet of the nrf52832.

Further this PR provides testing of power state when sending or receiving. Instead of throwing an assert, it now returns `ENETDOWN /*Network is down (POSIX.1-2001).*/`, when the device is powered off. This is, to avoid assertion fails on development, but rather avoid unspecified behavior when not in debug mode.

Also it adds a minor fix, lend from nrf52840 radio driver, to wait for the Ready-Event, which is triggered when the device is Ready to send/receive. This helped to increase reliability when flooding, as presented by @pystub in #10878.

I can split this PR, if prefered.

### Testing procedure

Test with examples/default on boards with nrf52840 or nrf52832 cpus. Make sure to use nrfmin with `USEMODULE=nrfmin`. Send packets with `txtsnd`.

On master, try to find an invalid address, that is accepted by the receiver by substituting single figures of the receiver address, preferably the last figure.
With this PR invalid addresses, generated with this approach will not work anymore.

Further testing could cover flooding with a small intervall of 0.1 seconds, as given in #10878.

### Issues/PRs references

Fixes #10878

### CODE REVIEW

**Comment by SemjonKerner** [comment]
Rebased

File: cpu/nrf5x_common/radio/nrfmin/nrfmin.c [hunk 1]
```diff
@@ -342,10 +347,13 @@ static int nrfmin_send(netdev_t *dev, const iolist_t *iolist)
     NRF_RADIO->PACKETPTR = (uint32_t)(&tx_buf);
     NRF_RADIO->BASE0 = (CONF_ADDR_BASE | hdr->dst_addr);
 
+
```
Comment (haukepetersen) [inline cpu/nrf5x_common/radio/nrfmin/nrfmin.c]: remove newline

**Comment by haukepetersen** [comment]
also tested the address filtering successful on `nrf52dk` baords -> ACK holds.

**Comment by SemjonKerner** [comment]
Applied requested changes and squashed.
