### PR TITLE
gnrc_pktbuf_static: fix #5748

### LINKED ISSUE #5748: gnrc: nodes crashing with too small packet buffer
I just ran into a problem, when I manually configured the packet buffer too small in the `gnrc_networking` example. In fact, I copied the size from the `gnrc_minimal` example (512 bytes). Testing this on the iotlab testbed with ~350 nodes (Neighbor cache size set to 100, FIB size to 350) I ran into several crashes. Nodes were dying with hard faults after some time.

(On the pro side: with the default packet buffer size, I was able to transmit a UDP datagram from the one end of the testbed to the other without problems. :))

### PR DESCRIPTION
**Pull request by miri64**
I think I found the problem causing #5748 (and maybe even #4048): If the packet buffer gets full it might happen that the `_unused_t` segment is written to the very end, though it will overflow. This PR fixes that.

### CODE REVIEW

**Comment by OlegHahm** [comment]
With `+CFLAGS += -DGNRC_PKTBUF_SIZE=512 -DGNRC_IPV6_NC_SIZE=100 -DGNRC_IPV6_FIB_TABLE_SIZE=350` added to the Makefile of `gnrc_networking`, 200 nodes in IoT-Lab (Lille) and start one node as RPL root node, I still experience some crashes.

**Comment by miri64** [comment]
Mh okay. Then let's postpone this one for now. I will investigate this for 2017.01.

File: sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c [hunk 1]
```diff
@@ -437,6 +437,7 @@ static void *_pktbuf_alloc(size_t size)
         DEBUG("pktbuf: no space left in packet buffer\n");
         return NULL;
     }
+    /* _unused_t struct would fit => add new space at ptr */
     if (sizeof(_unused_t) > (ptr->size - size)) {
```
Comment (smlng) [inline sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c]: shouldn't this be `if ((_unused_t != NULL) && (sizeof(_unused_t) > (ptr->size - size)))`, compare L454 where `_first_unused = NULL;`?

Comment (smlng) [inline sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c]: ah no, I misread ...

File: sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c [hunk 2]
```diff
@@ -447,7 +448,12 @@ static void *_pktbuf_alloc(size_t size)
     }
     else {
         _unused_t *new = (_unused_t *)(((uint8_t *)ptr) + size);
-        if (prev == NULL) { /* ptr was _first_unused */
+
+        if (((((uint8_t *)new) - &_pktbuf[0]) + sizeof(_unused_t)) > GNRC_PKTBUF_SIZE) {
```
Comment (miri64) [inline sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c]: Huh? Since when?

Comment (OlegHahm) [inline sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c]: To me: since ever. ;-) Just to make clear that the address of `_pktbuf[0]` is meant and not the address of `_pktbuf`.

Comment (miri64) [inline sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c]: IMHO that's perfectly clear, because even forgetting all about operator priorities it still wouldn't make sense to me to give `&` priority over `[]`, but fine.

Comment (miri64) [inline sys/net/gnrc/pktbuf_static/gnrc_pktbuf_static.c]: Done

**Comment by OlegHahm** [comment]
IIRC the last time we talked about this PR you wanted to look into it again or should we proceed and merge this ASAP?

**Comment by miri64** [comment]
> IIRC the last time we talked about this PR you wanted to look into it again or should we proceed and merge this ASAP?

I would rather merge it ASAP. The error with the crash on large networks seems to be unrelated.

**Comment by miri64** [comment]
Squashed
