### PR TITLE
gnrc/sock: recv avoid spinning xtimer

### LINKED ISSUE #16808: benchmark_udp: hammering with low interval causes issues
#### Description

I'm trying benchmark_udp on an nrf52840dk over usbus_cdc_ecm.
I'm seeing some reliability issues with high load.

With down to `-i 30`,  everything is fine.
From `-i 29`, the shell becomes unresponsive, but the node still pings and I can run more benchmark_udp (restart host tool).
~~From `-i 14`, the node seems to freeze.~~ Fixed with #16831.

#### Steps to reproduce the issue

compile tests/usbus_cdc_ecm with benchmark_udp:

`BOARD=nrf52840dk USEMODULE="benchmark_udp" make -Ctests/usbus_cdc_ecm clean all flash -j8`

in riots shell:

`bench_start <host-link-local-addr> 12345`,

then on host:

`./benchmark_server -i 14 :: 12345`

#### Expected results

Shell and node stay responsive.

#### Actual results

Shell freeze or (seemingly) full node freeze.

#### Versions

Compiled on arch with gcc version 11.2.0.

### PR DESCRIPTION
**Pull request by kfessel**
### Contribution description

avoid spinning xtimer on socket receive with short timeout by increasing the timeout to XTIMER_BACKOFF

### Testing procedure

run benchmark_udp with short intervalls

### Issues/PRs references

possibly Fixes #16808

### CODE REVIEW

File: sys/net/gnrc/sock/gnrc_sock.c [hunk 1]
```diff
@@ -117,6 +117,12 @@ ssize_t gnrc_sock_recv(gnrc_sock_reg_t *reg, gnrc_pktsnip_t **pkt_out,
 #ifdef MODULE_XTIMER
     xtimer_t timeout_timer;
 
+    /* xtimer_spin would make this never receive anything avoid it by setting
+    /* the minimal not spinning timeout */
+    if (timeout < XTIMER_BACKOFF){
```
Comment (benpicco) [inline sys/net/gnrc/sock/gnrc_sock.c:122]:
```suggestion
    if (timeout < XTIMER_BACKOFF) {
```

**Comment by benpicco** [comment]
Good catch!

**Comment by benpicco** [comment]
Just squash directly

**Review by benpicco — APPROVED** [review]

**Comment by kaspar030** [comment]
my gcc says this:
```
/home/kaspar/src/riot/sys/net/gnrc/sock/gnrc_sock.c: In function 'gnrc_sock_recv':
/home/kaspar/src/riot/sys/net/gnrc/sock/gnrc_sock.c:121:5: error: "/*" within comment [-Werror=comment]
  121 |     /* the minimal not spinning timeout */
      |

File: sys/net/gnrc/sock/gnrc_sock.c [hunk 2]
```diff
@@ -117,6 +117,12 @@ ssize_t gnrc_sock_recv(gnrc_sock_reg_t *reg, gnrc_pktsnip_t **pkt_out,
 #ifdef MODULE_XTIMER
     xtimer_t timeout_timer;
 
+    /* xtimer_spin would make this never receive anything avoid it by setting
+    /* the minimal not spinning timeout */
```
Comment (kaspar030) [inline sys/net/gnrc/sock/gnrc_sock.c:121]:
```suggestion
     * the minimal not spinning timeout */
```

File: sys/net/gnrc/sock/gnrc_sock.c [hunk 3]
```diff
@@ -117,6 +117,12 @@ ssize_t gnrc_sock_recv(gnrc_sock_reg_t *reg, gnrc_pktsnip_t **pkt_out,
 #ifdef MODULE_XTIMER
     xtimer_t timeout_timer;
 
+    /* xtimer_spin would make this never receive anything avoid it by setting
```
Comment (kaspar030) [inline sys/net/gnrc/sock/gnrc_sock.c:120]:
```suggestion
    /* xtimer_spin would make this never receive anything. avoid that by setting
```

File: sys/net/gnrc/sock/gnrc_sock.c [hunk 4]
```diff
@@ -117,6 +117,12 @@ ssize_t gnrc_sock_recv(gnrc_sock_reg_t *reg, gnrc_pktsnip_t **pkt_out,
 #ifdef MODULE_XTIMER
     xtimer_t timeout_timer;
 
+    /* xtimer_spin would make this never receive anything.
```
Comment (benpicco) [inline sys/net/gnrc/sock/gnrc_sock.c:120]:
```suggestion
    /* xtimer_spin would make this never receive anything. */
```

Comment (kfessel) [reply sys/net/gnrc/sock/gnrc_sock.c:120]: somehow the / made it back in again when adding the linebreak in front of the Avoid

**Comment by miri64** [comment]
Might also need to be fixed in the other `sock` implementations.

**Comment by miri64** [comment]
(but that can be done as a follow-up)

**Comment by benpicco** [comment]
Hm, now `tests/gnrc_sock_udp` and `tests/gnrc_sock_ip/native` are failing

**Comment by kfessel** [comment]
special case of 0 timout
