### PR TITLE
driver/sdp3x: Resolved irq pin code used even if irq pin not connected

### LINKED ISSUE #14603: drivers/sdp3x: IRQ module used even if IRQ pin not connected
#### Description

SDP3x IRQ module included even if not using irq pins
#### Steps to reproduce the issue

Compile and run driver sdp3x sensor test and run using :
`BOARD=... make clean flash term -C tests/driver_sdp3x`
This issue can be worked on after the issue #14601 is resolved.

#### Expected results

IRQ module not defined when not using irq pin of the sensor and therefore, timers related to no irq pin used
#### Actual results

Timers corresponding to no IRQ pin module not used. Instead the code tries to obtain mutex lock and times out trying to get it since the interrupt is never raised when the irq pin is not connected.

#### Versions

Operating System Environment
----------------------------
```
         Operating System: "Ubuntu" "18.04.4 LTS (Bionic Beaver)"
                   Kernel: Linux 4.15.0-112-generic x86_64 x86_64
             System shell: /bin/dash (probably dash)
             make's shell: /bin/dash (probably dash)
```

Installed compiler toolchains
-----------------------------
```
               native gcc: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
                  avr-gcc: avr-gcc (GCC) 5.4.0
         mips-mti-elf-gcc: missing
               msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
```

Installed compiler libs
-----------------------
```
     arm-none-eabi-newlib: "3.1.0"
      mips-mti-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: "2.0.0" ("20150208")
```

Installed development tools
---------------------------
```
                   ccache: ccache version 3.4.1
                    cmake: cmake version 3.10.2
                 cppcheck: Cppcheck 1.82
                  doxygen: 1.8.13
                      git: git version 2.17.1
                     make: GNU Make 4.1
                  openocd: Open On-Chip Debugger 0.10.0+dev-01000-gdb23c13d (2020-01-06-15:02)
                   python: Python 2.7.17
                  python2: Python 2.7.17
                  python3: Python 3.6.9
                   flake8: error: /usr/bin/python3: No module named flake8
               coccinelle: spatch version 1.0.4 with Python support and with PCRE support
```

### PR DESCRIPTION
**Pull request by Nishchay-sopho**
### Contribution description
Adds functionality to only compile and run IRQ pin part of code if sensor is connected with the interrupt pin and `sdp3x_irq` MODULE is used.

### Testing procedure

To run sensor with interrupt pin, change Makefile to:
```
include ../Makefile.tests_common

DRIVER ?= sdp3x_irq

USEMODULE += $(DRIVER)
USEMODULE += printf_float

TEST_ITERATIONS ?= 10
# export iterations for continuous measurements
CFLAGS += -DTEST_ITERATIONS=$(TEST_ITERATIONS)

include $(RIOTBASE)/Makefile.include

```
To run sensor without interrupt pin, change Makefile to:
```
include ../Makefile.tests_common

DRIVER ?= sdp3x

USEMODULE += $(DRIVER)
USEMODULE += printf_float

TEST_ITERATIONS ?= 10
# export iterations for continuous measurements
CFLAGS += -DTEST_ITERATIONS=$(TEST_ITERATIONS)

include $(RIOTBASE)/Makefile.include

```

Then compile, flash and run the test file with: `BOARD=... make clean flash term -C tests/driver_sdp3x`

### Issues/PRs references

Fixes #14603

### CODE REVIEW

File: drivers/include/sdp3x.h [hunk 1]
```diff
@@ -49,6 +49,7 @@ typedef struct {
     i2c_t i2c_dev;                  /**< I2C device which is used */
     uint8_t i2c_addr;               /**< I2C address */
     gpio_t irq_pin;                 /**< IRQ pin to check data ready */
+    bool irq_device;                /**< IRQ pin connected */
```
Comment (benpicco) [inline drivers/include/sdp3x.h:52]: No need for an extra variable - you can check for `irq_pin != GPIO_UNDEF` to see if a IRQ pin is defined.

Comment (Nishchay-sopho) [reply drivers/include/sdp3x.h]: fixed

File: drivers/sdp3x/include/sdp3x_params.h [hunk 2]
```diff
@@ -71,12 +71,10 @@ extern "C" {
...
 #define SDP3X_PARAMS                { .i2c_dev       = SDP3X_PARAM_I2C_DEV,  \
                                       .i2c_addr      = SDP3X_PARAM_I2C_ADDR, \
-                                      .irq_pin       = SDP3X_PARAM_IRQ_PIN, \
-                                      .irq_device	 = true }
+                                      .irq_pin       = SDP3X_PARAM_IRQ_PIN }
 #else
 #define SDP3X_PARAMS                { .i2c_dev       = SDP3X_PARAM_I2C_DEV,  \
-                                      .i2c_addr      = SDP3X_PARAM_I2C_ADDR, \
-                                      .irq_device    = false }
+                                      .i2c_addr      = SDP3X_PARAM_I2C_ADDR }
```
Comment (benpicco) [inline drivers/sdp3x/include/sdp3x_params.h:77]: You want to put `.irq_pin = GPIO_UNDEF` here.

Comment (Nishchay-sopho) [reply drivers/sdp3x/include/sdp3x_params.h:77]: Is it not automatically initialized to `GPIO_UNDEF` ?

Comment (benpicco) [reply drivers/sdp3x/include/sdp3x_params.h:77]: No, it's automatically initialized with `0`, but the value of `GPIO_UNDEF` depends on the platform.

Comment (Nishchay-sopho) [reply drivers/sdp3x/include/sdp3x_params.h]: Oh I see. Fixed

File: drivers/sdp3x/include/sdp3x_params.h [hunk 3]
```diff
@@ -61,14 +61,22 @@ extern "C" {
...
 #ifndef SDP3X_PARAMS
+#ifdef  MODULE_SDP3X_IRQ
 #define SDP3X_PARAMS                { .i2c_dev       = SDP3X_PARAM_I2C_DEV,  \
                                       .i2c_addr      = SDP3X_PARAM_I2C_ADDR, \
                                       .irq_pin       = SDP3X_PARAM_IRQ_PIN }
+#else
+#define SDP3X_PARAMS                { .i2c_dev       = SDP3X_PARAM_I2C_DEV,  \
+                                      .i2c_addr      = SDP3X_PARAM_I2C_ADDR, \
+                                      .irq_pin       = GPIO_UNDEF }
+#endif
```
Comment (benpicco) [inline drivers/sdp3x/include/sdp3x_params.h:79]: You can drop this whole block if you do

File: drivers/sdp3x/include/sdp3x_params.h [hunk 4]
```diff
@@ -61,14 +61,22 @@ extern "C" {
 #ifndef SDP3X_PARAM_I2C_ADDR
 #define SDP3X_PARAM_I2C_ADDR        SDP3X_ADDR1
 #endif
+#ifdef  MODULE_SDP3X_IRQ
 #ifndef SDP3X_PARAM_IRQ_PIN
 #define SDP3X_PARAM_IRQ_PIN         (GPIO_PIN(0, 2))
```
Comment (benpicco) [inline drivers/sdp3x/include/sdp3x_params.h:66]:
```suggestion
#define SDP3X_PARAM_IRQ_PIN         GPIO_UNDEF
```

File: drivers/sdp3x/include/sdp3x_params.h [hunk 5]
```diff
@@ -61,14 +61,22 @@ extern "C" {
 #ifndef SDP3X_PARAM_I2C_ADDR
 #define SDP3X_PARAM_I2C_ADDR        SDP3X_ADDR1
 #endif
+#ifdef  MODULE_SDP3X_IRQ
```
Comment (benpicco) [inline drivers/sdp3x/include/sdp3x_params.h:64]: Defines can be made unconditionally

Comment (Nishchay-sopho) [reply drivers/sdp3x/include/sdp3x_params.h]: Fixed

File: drivers/sdp3x/include/sdp3x_params.h (hunk 4 above)
Comment (Nishchay-sopho) [reply drivers/sdp3x/include/sdp3x_params.h]: Fixed

File: drivers/sdp3x/include/sdp3x_params.h (hunk 3 above)
Comment (Nishchay-sopho) [reply drivers/sdp3x/include/sdp3x_params.h]: Fixed.

File: drivers/sdp3x/sdp3x.c [hunk 6]
```diff
@@ -103,7 +108,7 @@ int sdp3x_init(sdp3x_t *dev, const sdp3x_params_t *params)
 int32_t sdp3x_read_single_temperature(sdp3x_t *dev, uint8_t flags)
 {
     _SDP3x_start_triggered(dev, flags);
-#ifndef SDP3X_PARAM_IRQ_PIN
+#ifndef MODULE_SDP3X_IRQ
```
Comment (benpicco) [inline drivers/sdp3x/sdp3x.c:111]:
```suggestion
if (!IS_USED(MODULE_SDP3X_IRQ) || dev->params.irq_pin == GPIO_UNDEF)
```

Comment (Nishchay-sopho) [reply drivers/sdp3x/sdp3x.c:111]: If the ifdef is changed to if conditional statement, then the code will unnecessarily compiled even the irq pin is not used.

Also, technically we wouldn't need to put the condition ` dev->params.irq_pin == GPIO_UNDEF` since the code would anyways wait for `DATA_READY_SLEEP_US` with the `xtimer_mutex_lock_timeout()` function without interrupts.

Comment (leandrolanzieri) [reply drivers/sdp3x/sdp3x.c:111]: `!IS_USED(MODULE_SDP3X_IRQ)` is expanded and resolved in compile time, so the compiler will optimize this part out in the case it's not used.

Comment (Nishchay-sopho) [reply drivers/sdp3x/sdp3x.c:111]: Neat! So basically if the `MODULE_SDP3X_IRQ` is satisfied at compile time, then only the corresponding if conditional statement with `dev->params.irq_pin == GPIO_UNDEF` will be compiled. Am I right ?

Comment (leandrolanzieri) [reply drivers/sdp3x/sdp3x.c:111]: In the snipped proposed by @benpicco, if the module is not there `!IS_USED(MODULE_SDP3X_IRQ)` expands to `1`, so it would short-circuit the if. The check for the `irq_pin` would then only be compiled when the module is there.

Comment (Nishchay-sopho) [reply drivers/sdp3x/sdp3x.c:111]: If it is only compiled if the if condition is not short circuited, then if I do the following in the init function() at line 91, it should work and get compiled even without the irq module (i.e. periph_gpio_irq not being used, thus gpio_int_int() function being unavailable):
```
    if (IS_USED(MODULE_SDP3X_IRQ) && dev->params.irq_pin != GPIO_UNDEF) {
        mutex_init(&dev->mutex);
        /* lock mutex initially to be unlocked when interrupt is raised */
        mutex_lock(&dev->mutex);
        /* Interrupt set to trigger on falling edge of interrupt pin */
        gpio_init_int(params->irq_pin, GPIO_IN, GPIO_FALLING, _sdp3x_irq_callback,
                     dev);
    }
```

Comment (Nishchay-sopho) [reply drivers/sdp3x/sdp3x.c:111]: Ah, ohkay got it!

Comment (Nishchay-sopho) [reply drivers/sdp3x/sdp3x.c]: Fixed

File: drivers/sdp3x/Makefile.dep [hunk 7]
```diff
@@ -1,4 +1,7 @@
 FEATURES_REQUIRED += periph_i2c
-FEATURES_REQUIRED += periph_gpio_irq
 USEMODULE += checksum
 USEMODULE += xtimer
+
+ifneq (,$(filter sdp3x_irq,$(USEMODULE)))
+  USEMODULE += periph_gpio_irq
```
Comment (benpicco) [inline drivers/sdp3x/Makefile.dep:6]:
```suggestion
  FEATURES_REQUIRED += periph_gpio_irq
```

File: tests/driver_sdp3x/README.md [hunk 8]
```diff
@@ -18,4 +18,6 @@ make BOARD=... TEST_ITERATIONS=... -C tests/driver_sdp3x
 The sensor has an IRQn pin which indicates data ready on the sensor. This pin can be
 connected on the GPIO ports and configured in the variable `SDP3X_PARAM_IRQ_PIN`. This
 helps getting measurements as soon as they are ready instead of the 46ms wait (which is
-the maximum time the sensor might take the get the measurement ready).
\ No newline at end of file
+the maximum time the sensor might take the get the measurement ready).
+
+If using irq pin, instead of `USEMODULE = sdp3x`, use `USEMODULE = sdp3x_irq`.
```
Comment (benpicco) [inline tests/driver_sdp3x/README.md:23]: I would always use `sdp3x_irq` in the test so that code path is always compiled by CI.

Comment (Nishchay-sopho) [reply tests/driver_sdp3x/README.md:23]: So, this is to include the periph_gpio_irq stuff in every test performed by CI, isn't it ?

Comment (benpicco) [reply tests/driver_sdp3x/README.md:23]: CI will just perform compile-tests here since there is no test runner equipped with such a sensor.
Using `sdp3x_irq` will make sure that all the IRQ code still compiles.

Comment (Nishchay-sopho) [reply tests/driver_sdp3x/README.md]: Yeah, I understand :+1:
