### PR TITLE
gnrc_ipv6_nib: Ignore PIO with on-link flag

### LINKED ISSUE #20377: 6ln RA PIO with L flag set is not ignored
#### Description

(This was noticed because of the tests failing in #20371 )

>  A router MUST NOT set the L (on-link) flag in the PIOs, since that
   might trigger hosts to send multicast NSs.
- https://datatracker.ietf.org/doc/html/rfc6775#section-6.1

>  Should the host erroneously receive a PIO with the L (on-link) flag
   set, then that PIO MUST be ignored.
- https://datatracker.ietf.org/doc/html/rfc6775#section-5.4

The latter quote is not implemented in either tests or tested code.

Code implementation (tested code) adjustment would be a new PIO validity check failure condition: `|| (gnrc_netif_is_6ln(netif) && (pio->flags & NDP_OPT_PI_FLAGS_L))`
Test adjustment is slightly more changes.

#### Steps to reproduce the issue

For example, observe failing tests in #20371

#### Expected results

These tests that currently fail in #20371 should not do so.

#### Actual results

They do fail.

#### Versions

Murdock on #20371

### PR DESCRIPTION
**Pull request by xnumad**
### Contribution description

This PR directly addresses the changes suggested in #20377 

### Testing procedure

Tests are adjusted accordingly.

### Issues/PRs references

Fixes #20377

### CODE REVIEW

File: sys/net/gnrc/network_layer/ipv6/nib/nib.c [hunk 1]
```diff
@@ -1621,7 +1621,11 @@ static uint32_t _handle_pio(gnrc_netif_t *netif, const icmpv6_hdr_t *icmpv6,
     valid_ltime = byteorder_ntohl(pio->valid_ltime);
     pref_ltime = byteorder_ntohl(pio->pref_ltime);
     if ((pio->len != NDP_OPT_PI_LEN) || (icmpv6->type != ICMPV6_RTR_ADV) ||
-        ipv6_addr_is_link_local(&pio->prefix) || (valid_ltime < pref_ltime)) {
+        ipv6_addr_is_link_local(&pio->prefix) || (valid_ltime < pref_ltime)
+        || (gnrc_netif_is_6ln(netif) &&
+        /*https://datatracker.ietf.org/doc/html/rfc6775#section-5.4*/
+        (pio->flags & NDP_OPT_PI_FLAGS_L))
+        ) {
```
Comment (benpicco) [inline sys/net/gnrc/network_layer/ipv6/nib/nib.c:1628]:
```suggestion
        ipv6_addr_is_link_local(&pio->prefix) || (valid_ltime < pref_ltime) ||
        /* https://datatracker.ietf.org/doc/html/rfc6775#section-5.4 */
        (gnrc_netif_is_6ln(netif) && (pio->flags & NDP_OPT_PI_FLAGS_L)) {
```

makes it a bit more readable.
Those monster if-statements should probably be broken up into smaller ones, but they are littered through the network code already.

**Review by benpicco — COMMENTED** [review]
Looks good to me!
Just a small formatting suggestion:

**Comment by benpicco** [comment]
Please squash!

**Review by benpicco — APPROVED** [review]
I gave it a quick test on `native`, `examples/gnrc_networking` (with `USE_ZEP=1`) still gets a prefix from `examples/gnrc_border_router`.

File: sys/net/gnrc/network_layer/ipv6/nib/nib.c [hunk 2]
```diff
@@ -1621,7 +1621,9 @@ static uint32_t _handle_pio(gnrc_netif_t *netif, const icmpv6_hdr_t *icmpv6,
     valid_ltime = byteorder_ntohl(pio->valid_ltime);
     pref_ltime = byteorder_ntohl(pio->pref_ltime);
     if ((pio->len != NDP_OPT_PI_LEN) || (icmpv6->type != ICMPV6_RTR_ADV) ||
-        ipv6_addr_is_link_local(&pio->prefix) || (valid_ltime < pref_ltime)) {
+        ipv6_addr_is_link_local(&pio->prefix) || (valid_ltime < pref_ltime) ||
+        /* https://datatracker.ietf.org/doc/html/rfc6775#section-5.4 */
+        (gnrc_netif_is_6ln(netif) && (pio->flags & NDP_OPT_PI_FLAGS_L)) {
```
Comment (benpicco) [inline sys/net/gnrc/network_layer/ipv6/nib/nib.c:1626]:
```suggestion
        (gnrc_netif_is_6ln(netif) && (pio->flags & NDP_OPT_PI_FLAGS_L))) {
```
