### PR TITLE
dist/tools: don't redefine EXCLUDE when not necessary

### LINKED ISSUE #15660: dist/tools/ci or tests: `EXCLUDE` not assigned correctly?
#### Description
Multiple static tests use [changed_files.sh](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/ci/changed_files.sh) to exclude files from being tested, for example, [codespell](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/codespell/check.sh#L27). If I understand it correctly, the exclude list is generated from a [local `EXCLUDE` variable](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/codespell/check.sh#L26) and the one in [changed_files](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/ci/changed_files.sh#L11).

1. Is it on purpose to have two locations of exclusion?
2. The expansion of `EXCLUDE` does not work properly. 

#### Steps to reproduce the issue
- Edit a test script to print the list of files to be tested [here](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/codespell/check.sh#L28) by adding:
`echo "${FILES}"`
- Execute the script and grep for a file/folder that should be excluded, for example [*dist/tools/coccinelle/include*](https://github.com/RIOT-OS/RIOT/blob/master/dist/tools/ci/changed_files.sh#L11):
 `dist/tools/codespell/check.sh | grep dist/tools/coccinelle/include`

#### Expected results
The list should not include files from *dist/tools/coccinelle/include* since it is excluded.

#### Actual results
The printed list contains *dist/tools/coccinelle/include/riot-standard.h*.

### Versions
<details>

```
Operating System Environment
----------------------------
         Operating System: "Ubuntu" "18.04.5 LTS (Bionic Beaver)"
                   Kernel: Linux 4.15.0-126-generic x86_64 x86_64
             System shell: /bin/dash (probably dash)
             make's shell: /bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 7-2018-q3-update) 7.3.1 20180622 (release) [ARM/embedded-7-branch revision 261907]
                  avr-gcc: missing
         mips-mti-elf-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
  riscv64-unknown-elf-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.0.0"
      mips-mti-elf-newlib: missing
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
riscv64-unknown-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: ccache version 3.4.1
                    cmake: cmake version 3.10.2
                 cppcheck: Cppcheck 1.82
                  doxygen: 1.8.13
                      git: git version 2.17.1
                     make: GNU Make 4.1
                  openocd: Open On-Chip Debugger 0.10.0
                   python: Python 2.7.17
                  python2: Python 2.7.17
                  python3: Python 3.6.9
                   flake8: 3.6.0 (mccabe: 0.6.1, pycodestyle: 2.4.0, pyflakes: 2.0.0) CPython 3.6.9 on Linux
               coccinelle: missing
```
</details>

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

There's no need to redefine the EXCLUDE variables in vera++ and codespell checks. This PR fixes that.

### Testing procedure

- Green CI (when the REMOVEME commit is removed, otherwise false)

### Issues/PRs references

fixes #15660

### CODE REVIEW

**Comment by PeterKietzmann** [comment]
I can confirm that this PR fixes the issue described in #15672 (see that description for testing procedure). codespell, vera++, and flake8 seem to be the only tests affected. Not fixing flake8 seems not ideal, however, since it only applies to .py it should be okay as long as no .py files are added to `changed_files`.

Will set the reviewed labels but not approve since I'm not very familiar with the ci/test environment.

File: dist/tools/vera++/check.sh [hunk 1]
```diff
@@ -13,8 +13,7 @@ CURDIR=$(cd "$(dirname "$0")" && pwd)
 
 . "$RIOTBASE"/dist/tools/ci/changed_files.sh
 FILEREGEX='\.([CcHh]|[ch]pp)$'
```
Comment (miri64) [inline dist/tools/vera++/check.sh:15]: This is the same as in `changed_files`. I don't think it is needed to set this either.

**Review by miri64 — APPROVED** [review]
I do agree that since `flake8` checks a completely different set of file, the `EXCLUDE` pattern needs to be different as well, so not changing it is justified. However, I don't think `FILEREGEX` needs to be set externally for `vera++`.

**Review by miri64 — CHANGES_REQUESTED** [review]
Oops, should have been a change request.

File: dist/tools/vera++/check.sh (hunk 1 above)
Comment (aabadie) [reply dist/tools/vera++/check.sh]: removed

**Review by miri64 — APPROVED** [review]
Now I can ACK this :-). Please squash and remove the test commit.
