### PR TITLE
boards/iotlab-m3: disable DMA with SPI

### LINKED ISSUE #10761: iotlab-m3: poor ping6 performance and a possibly broken 6lo fragmentation?
#### Description
I was pinging between two iotlab-m3 nodes on the iotlab testbed using the grenoble site, when I noticed a poor ping performance and a possible state corruption of the 6lo fragmentation. I am not sure whether this is due to other experiments/interferences on the testbed. I certainly tried other channels with the same result. Tomorrow I can try to reproduce locally with two iotlab-m3 boards and use the debugger to find out more.

#### Steps to reproduce the issue
2 iotlab-m3 nodes (A and B) with `gnrc_networking`.
A pings B with an increasing payload size.

#### Expected results
ping should work with nearly 100% success rate

#### Actual results
The run below contains the following steps:
1. Node-A pings Node-B with payload 100 (works)
2. Node-A pings Node-B with payload 200 (100% timeout)
3. Node-A pings Node-B with payload 100 (100% timeout)
4. Reboot Node-A
5. Node-A pings Node-B with payload 100 (100% timeout)
6. Reboot Node-B
7. Node-A pings Node-B with payload 100 (works again)

There are no hardfaults during the run.

Side note: The Version string shows `Version: 2018.10-RC1-963-g35868`, but I am definitely on master.

```
main(): This is RIOT! (Version: 2018.10-RC1-963-g35868)
RIOT network stack example application
All up, running the shell now

> ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping timeout
108 bytes from fe80::1711:6b10:65fc:5c22: id=83 seq=2 hop limit=64 time = 21.438 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=83 seq=3 hop limit=64 time = 27.580 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=83 seq=4 hop limit=64 time = 25.025 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=83 seq=5 hop limit=64 time = 22.078 ms
--- fe80::1711:6b10:65fc:5c22 ping statistics ---
5 packets transmitted, 4 received, 20% packet loss, time 1.06505139 s
rtt min/avg/max = 21.438/24.030/27.580 ms

> ping6 5 fe80::1711:6b10:65fc:5c22 200 100
ping6 5 fe80::1711:6b10:65fc:5c22 200 100
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
--- fe80::1711:6b10:65fc:5c22 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss

> ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
--- fe80::1711:6b10:65fc:5c22 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss

> reboot
reboot
main(): This is RIOT! (Version: 2018.10-RC1-963-g35868)
RIOT network stack example application
All up, running the shell now

> ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping timeout
ping timeout
ping timeout
ping timeout
ping timeout
--- fe80::1711:6b10:65fc:5c22 ping statistics ---
5 packets transmitted, 0 received, 100% packet loss

HERE NODE-B REBOOTS

> ping6 5 fe80::1711:6b10:65fc:5c22 100 100
ping6 5 fe80::1711:6b10:65fc:5c22 100 100
108 bytes from fe80::1711:6b10:65fc:5c22: id=84 seq=1 hop limit=64 time = 23.674 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=84 seq=2 hop limit=64 time = 22.715 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=84 seq=3 hop limit=64 time = 27.893 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=84 seq=4 hop limit=64 time = 24.510 ms
108 bytes from fe80::1711:6b10:65fc:5c22: id=84 seq=5 hop limit=64 time = 22.716 ms
--- fe80::1711:6b10:65fc:5c22 ping statistics ---
5 packets transmitted, 5 received, 0% packet loss, time 0.06531306 s
rtt min/avg/max = 22.715/24.301/27.893 ms
```

#### Versions
RIOT master

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

This PR is an attempt to improve the situation with #10761. The idea is just to disable the use of DMA on the SPI interface used by the radio on iotlab-m3.

Even if it needs further investigation with the DMA implementation with stm32f1, for the moment this should make networking usable again.

Not tested.

### Testing procedure

See #10761 

### Issues/PRs references

fixes #10761, fixes regression introduced in #9171

### CODE REVIEW

File: boards/common/iotlab/include/periph_conf_common.h [hunk 1]
```diff
@@ -74,16 +74,12 @@ extern "C" {
  */
 #ifdef MODULE_PERIPH_DMA
 static const dma_conf_t dma_config[] = {
-    { .stream = 1 },    /* DMA1 Channel 2 - SPI1_RX */
```
Comment (vincent-d) [inline boards/common/iotlab/include/periph_conf_common.h]: You could keep this, even though it's not used. I would just wast a couple of bytes in flash.

**Comment by miri64** [comment]
Wil test ASAP, was digged deep into #10701 ;-).

**Comment by miri64** [comment]
What about the other boards from #9171? Do they have similar problems?

**Comment by miri64** [comment]
> What about the other boards from #9171? Do they have similar problems?

This should be validated though.

**Comment by aabadie** [comment]
> What about the other boards from #9171? Do they have similar problems?

I tested SPI (with DMA) on b-l072z-lrwan1, nucleo-l152re and maybe nucleo-f091 with LoRa (sx1276 with SPI interface), all worked. For nucleo144, I didn't test SPI but I will do asap (tomorrow or on thursday).
I have way to perform more stressful tests.

**Comment by miri64** [comment]
@MrKevinWeiss @smlng is there a way to test something like that in the HiL tests?

**Comment by MrKevinWeiss** [comment]
Not yet, I need to add the functionality to PHiLIP (I haven't had a chance to touch it since August).
