### PR TITLE
sys/analog_util: Refactor, add test

### LINKED ISSUE #8567: sys/analog_util is not tested/used anywhere
#### Description
The functionality in sys/analog_util is not tested or even used anywhere.

#### Steps to reproduce the issue
```
git grep adc_util
git grep dac_util
```

#### Expected results
Unit test

#### Actual results
no test

#### Versions
current master branch 2018-02-15

### PR DESCRIPTION
**Pull request by gebart**
### Contribution description

Add unit test for `adc_util_map` in analog_util
Refactor analog_util and fix some issues which have not been detected because of missing tests.
Change arguments to use int32_t instead of int to allow more flexible scaling options.

### Issues/PRs references

fixes #8567 
depends on ~~#8624~~ (merged)

### CODE REVIEW

File: sys/analog_util/adc_util.c [hunk 1]
```diff
@@ -14,28 +15,51 @@
...
+     * multiplied by sample requires more bits than int offers */
+    int scaled = (((int64_t)(max - min) * sample) >> _adc_res_bits(res));
+    DEBUG("scaled: %d\n", scaled);
+    return (min + scaled);
 }
 
 float adc_util_mapf(int sample, adc_res_t res, float min, float max)
 {
-    return ((((max - min) * sample) / val_max[res]) + min);
+    return ((((max - min) * sample) / (1 << _adc_res_bits(res))) + min);
```
Comment (cladmi) [inline sys/analog_util/adc_util.c]: As `_adc_res_bits(res)` can have a value of 16, I think this `1` should be set to be 32 bit wide or it will break on 16bit platforms.

Also right now, there is a by one difference from the previous version when dividing. Not sure if it matters but just noticing.

File: tests/unittests/tests-analog_util/tests-analog_util.c [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+    int expected;
+    int sample;
+    int min;
+    int max;
+    adc_res_t res;
+} test_values_t;
+
+/* Arbitrarily chosen test vectors */
+/* TODO: Choose test vectors in a more qualified manner to catch any edge cases */
+static test_values_t test_data[] = {
```
Comment (cladmi) [inline tests/unittests/tests-analog_util/tests-analog_util.c]: I was wondering what it meant to have min >= max, and by checking the API I found its forbidden:

https://github.com/RIOT-OS/RIOT/blob/2018.01/sys/include/analog_util.h#L36

Really adding an `assert` there could be better.

File: tests/unittests/tests-analog_util/tests-analog_util.c [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+typedef struct {
+    int expected;
+    int sample;
+    int min;
+    int max;
+    adc_res_t res;
+} test_values_t;
+
+/* Arbitrarily chosen test vectors */
+/* TODO: Choose test vectors in a more qualified manner to catch any edge cases */
```
Comment (cladmi) [inline tests/unittests/tests-analog_util/tests-analog_util.c]: Compared to the previous version, its dividing by a resolution value which is one bigger, would be good I think to show a edge case like this.

Comment (cladmi) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: Also test does not pass on `samr21-xpro` with the previous version on commit `8edcbd1... unittests: Add analog_util tests`, so would be nice to have a working test fand an updated test when changing the function.

Comment (gebart) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: I don't see the point in rewriting the test to fit the broken unused version in current master, it seems like a lot of work just for immediately dumping something to the history archive.

The broken implementation in master does not even link for the STM32 because the scaling factor array becomes several hundred megabytes large because of the enum values used as indices.

Regarding the division, I should have mentioned it in the PR description: Since the ADC measures a continuous range of physical values, each quantized ADC output value corresponds to a continuous range of input values. Since the ADC has `2^N` counts, each output corresponds to a range of `range/2^N` values (LSB).
Also, it is much more efficient to divide by `2^N` than `(2^N)-1`
Some relevant sources:
 - Kinetis K22F reference manual, ADC chapter
  >The ADC quantizes the ideal straight-line transfer function into 65536 steps (in the 16-bit mode). Each step ideally has the same height, that is, 1 code, and width. The width is defined as the delta between the transition points to one code and the next. The ideal code width for an N-bit converter, where N can be 16, 12, 10, or 8, defined as 1 LSB, is:
  >1LSB=(Vrefh)/2^N

 - https://electronics.stackexchange.com/a/258497 (mentions that the same formula applies for Atmega128)

File: sys/analog_util/adc_util.c (hunk 1 above)
Comment (gebart) [reply sys/analog_util/adc_util.c]: Good catch on the integer width, will fix

File: tests/unittests/tests-analog_util/tests-analog_util.c (hunk 2 above)
Comment (gebart) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: I think it is better to update the docs than to add an artificial limitation like this.
Times where it can be useful to have min > max is when measuring a sensor where a higher measured voltage means a lower physical value. For example a thermistor can be connected so that the measured voltage goes down when the temperature goes up.

Comment (gebart) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: I updated the docs for the function to remove the requirement on min<max

**Comment by gebart** [comment]
Updated the API to use int32_t instead of int for most arguments.

File: tests/unittests/tests-analog_util/tests-analog_util.c (hunk 3 above)
Comment (cladmi) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: "Was broken and unused before" is a good justification for not doing additional work on this.

File: tests/unittests/tests-analog_util/tests-analog_util.c (hunk 2 above)
Comment (cladmi) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: Ok for the updated doc. It would be perfect if you could put your comment in the commit message when changing the API.

File: tests/unittests/tests-analog_util/tests-analog_util.c [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+    {  3972L,  9876,      10000L,          0L, ADC_RES_14BIT},
+};
+
+#define TEST_DATA_NUMOF (sizeof(test_data) / sizeof(test_data[0]))
+
+static void test_adc_util_map(void)
+{
+    for (unsigned int k = 0; k < TEST_DATA_NUMOF; ++k) {
+        test_values_t *testp = &test_data[k];
+        int res = adc_util_map(testp->sample, testp->res, testp->min, testp->max);
```
Comment (cladmi) [inline tests/unittests/tests-analog_util/tests-analog_util.c]: This `res` should be an `int32_t` to match the return value type.

**Comment by cladmi** [comment]
I tried on IoT-LAB with `wsn430-v1_3` for a 16 bit board and I get

    adc_util_tests.test_adc_util_map (tests/unittests/tests-analog_util/tests-analog_util.c 56) exp 65535 was -1

By checking I found that `sample` is evaluated as `-1` and not `65535` so the test values are wrong on a 16b board.

The broken tests:

    { 65535L, 65535,          0L,      65536L, ADC_RES_16BIT},
    adc_util_tests.test_adc_util_map (tests/unittests/tests-analog_util/tests-analog_util.c 56) exp 65535 was -1

    {  -134L, 56789,      -1000L,          0L, ADC_RES_16BIT},
    adc_util_tests.test_adc_util_map (tests/unittests/tests-analog_util/tests-analog_util.c 58) exp -134 was -1134

    { 16062L, 45671,      30000L,      10000L, ADC_RES_16BIT},
    adc_util_tests.test_adc_util_map (tests/unittests/tests-analog_util/tests-analog_util.c 60) exp 16062 was 36062

    {     0L, 65535,      65535L,          0L, ADC_RES_16BIT},
    adc_util_tests.test_adc_util_map (tests/unittests/tests-analog_util/tests-analog_util.c 60) exp 0 was 65535

When disabling these one, tests pass.

File: sys/analog_util/adc_util.c [hunk 5]
```diff
@@ -14,28 +15,52 @@
...
  *
  * @author      Hauke Petersen <hauke.petersen@fu-berlin.de>
+ * @author      Joakim Nohlgård <joakim.nohlgard@eistec.se>
  *
  * @}
  */
 
+#include <stdint.h>
+#include <inttypes.h>
+#include "cpu.h"
```
Comment (smlng) [inline sys/analog_util/adc_util.c]: nit-picky: please add empty line above, to separate sys from riot includes

File: sys/analog_util/adc_util.c [hunk 6]
```diff
@@ -14,28 +15,52 @@
...
+            return 8;
+        case ADC_RES_10BIT:
+            return 10;
+        case ADC_RES_12BIT:
+            return 12;
+        case ADC_RES_14BIT:
+            return 14;
+        case ADC_RES_16BIT:
+        default:
+            return 16;
```
Comment (smlng) [inline sys/analog_util/adc_util.c]: does this make sense, wouldn't `-1` as default be more appropriate - just in case some weird CPU defines an `adc_res_t` with values not expected here?

File: sys/include/analog_util.h [hunk 7]
```diff
@@ -21,6 +21,7 @@
 #ifndef ANALOG_UTIL_H
 #define ANALOG_UTIL_H
 
+#include <stdint.h>
 #include "periph/adc.h"
```
Comment (smlng) [inline sys/include/analog_util.h]: would suggest empty line here too, see above

File: sys/analog_util/adc_util.c [hunk 8]
```diff
@@ -14,28 +15,52 @@
...
+    }
+}
+
+int32_t adc_util_map(int sample, adc_res_t res, int32_t min, int32_t max)
 {
-    return ((((max - min) * sample) / val_max[res]) + min);
+    /* Using 64 bit signed int as intermediate to prevent overflow when range
+     * multiplied by sample requires more bits than int offers */
+    int32_t scaled = (((int64_t)(max - min) * sample) >> _adc_res_bits(res));
```
Comment (smlng) [inline sys/analog_util/adc_util.c]: while it makes sense to use `int64_t` for(correct) internal maths, I don't understand why you changed parameters and return type to `int32_t` when our ADC API returns only `int`

File: sys/analog_util/adc_util.c (hunk 6 above)
Comment (gebart) [reply sys/analog_util/adc_util.c]: We are using the result to perform a shift, and shifting by negative number of bits is undefined behaviour in C99. It will only work if we also add error returns for the adc_map functions. I know that the cc2538 periph adc driver provides some weird resolutions, like 7 bit etc. But right now I just want to focus on getting this working again so it can be used for the general use cases. I could add an always failing assert on the default instead, if that is better?

File: sys/analog_util/adc_util.c (hunk 8 above)
Comment (gebart) [reply sys/analog_util/adc_util.c]: I changed the return type to int32_t because the scaled value may very well be useful to express larger numbers than what int offers on the smaller architectures. Using int32_t means we can use min and max values > 32768 safely on all architectures. There are many situations where the values are more useful if you can convert them to some scientific measure directly, and using a wider data type mean we can perform the conversion using integer math without needing to shift down and losing more precision. This function is intended to be usable in more than just for creating phydat_t values.

**Comment by kaspar030** [comment]
@gebart this should be good to go?
@cladmi @smlng can you take a look?

**Comment by cladmi** [comment]
Will do a final check this afternoon.

File: tests/unittests/tests-analog_util/tests-analog_util.c (hunk 2 above)
Comment (gebart) [reply tests/unittests/tests-analog_util/tests-analog_util.c]: Added a notice in the main refactor commit regarding why it can be useful.

**Comment by gebart** [comment]
This should be tested on a 16-bit or 8-bit CPU before merging (atmega or msp430)

**Comment by gebart** [comment]
OK to squash?

**Comment by kaspar030** [comment]
> OK to squash?

Yes! Let's merge as is. Further release testing will show any 16bit or 8bit problems left.

**Comment by gebart** [comment]
squashed

**Comment by gebart** [comment]
@smlng ping
