### PR TITLE
gnrc_ipv6: make no pre-assumption about any marked headers

### LINKED ISSUE #4462: IPHC/NHC broken
Following setup:
Linux <-> `gnrc_border_router` example (N1) <-> `microcoap_server` example (N2)

I am able to ping N2 from linux, but I am not able to make CoAP requests.
If I disable iphc with `ifconfig x -iphc` on N1 and N2, then I can do CoAP requests (with Copper) from Linux <-> N2.

I have no time to investigate further right now. Can anyone confirm this behavior? @kaspar030 didn't you state something similar on IRC yesterday?

### PR DESCRIPTION
**Pull request by authmillenon**
One more PR that aims to fix #4462 (might need #4485 to fully fix the issue). With NHC activated the highest layer payload isn't directly adjacent to IPv6 anymore nor is the IPv6 header necessarily the first or second snip in a received `pkt` as it was before, since UDP (and later probably some extension headers or GHC supported headers) will be inserted between them. These assumptions are completely removed by this PR and the IPv6 header is searched as in any other layer + the pktsnip list is completely reversed for forwarding.

### CODE REVIEW

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c [hunk 1]
```diff
@@ -720,25 +720,14 @@ static void _receive(gnrc_pktsnip_t *pkt)
...
-            DEBUG("ipv6: Received packet was not IPv6, dropping packet\n");
-            gnrc_pktbuf_release(pkt);
-            return;
-        }
-#ifdef MODULE_GNRC_IPV6_WHITELIST
-        if (!gnrc_ipv6_whitelisted(&((ipv6_hdr_t *)(ipv6->data))->src)) {
-            DEBUG("ipv6: Source address not whitelisted, dropping packet\n");
-            gnrc_pktbuf_release(pkt);
-            return;
+    for (ipv6 = pkt; ipv6 != NULL; ipv6 = ipv6->next) { /* find IPv6 header if already marked */
```
Comment (OlegHahm) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: Can't we use `LL_SEARCH_SCALAR` here?

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: No, since I search for three conditions (one not directly related to a value in the node struct).

Comment (OlegHahm) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: Is there any legit case where the list would contain a snip marked as IPv6 where the other two conditions won't match?

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: Yes, the non-6Lo drivers mark the first snip as IPv6.

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: And the extension headers marked by NHC could also be IPv6.

Comment (OlegHahm) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: I still don't get it. Either the first snip is marked wrongly as IPv6 (shouldn't we rather raise an assert for that?) or there are several valid IPv6 headers in which case we would simply find the first?

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c [hunk 2]
```diff
@@ -720,25 +720,14 @@ static void _receive(gnrc_pktsnip_t *pkt)
...
+        if ((ipv6->type == GNRC_NETTYPE_IPV6) && (ipv6->size == sizeof(ipv6_hdr_t)) &&
+            (ipv6_hdr_is(ipv6->data))) {
+            break;
         }
-#endif
     }
-    else {
+
+    if (ipv6 == NULL) {
```
Comment (cgundogan) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: you may want to remove the check below this line, because `pkt` was already checked in the loop above

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c (hunk 1 above)
Comment (cgundogan) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: >No, since I search for three conditions (one not directly related to a value in the node struct).

couldn't we just reduce the conditions to `ipv6->type == GNRC_NETTYPE_IPV6` and transform the other ones into asserts?
The ipv6 packet size and the header type should be fine if the functions are used that `gnrc` provides to build ipv6 packets.

Besides of that, we also used `LL_SEARCH_SCALAR` for the netif header above. This would also required the ckecks for the packet size, but we omitted them..

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: No. I quote myself from two days ago:
> Yes, the non-6Lo drivers mark the first snip as IPv6.

Those won't fullfil the preconditions your proposed asserts would require. The for-loop I wrote is basically `LL_SEARCH_SCALAR` in resolved form, so I don't really see the need for a discussion here.

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c (hunk 2 above)
Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: No.... This is not an error case, but the case that the header was previously not marked (because it came e.g. through a non-sixlowpan interface).

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c (hunk 1 above)
Comment (OlegHahm) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: I still don't understand. What is a non-6lo driver (or a 6lo driver) and why does it mark anything as IPv6 that is not IPv6 and how is this a valid behavior?

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: @OlegHahm:
> I still don't get it. Either the first snip is marked wrongly as IPv6 (shouldn't we rather raise an assert for that?) or there are several valid IPv6 headers in which case we would simply find the first?

We have (and always had) two scenarios:
1. The packet comes from a non-6Lo device, than the make-up of the packet is (capital letters denote NETTYPE, value in parens size) [IPV6(x)->NETIF(y)]
2. The packet comef from a 6Lo device. 
  * Without NHC this was always: [IPV6(x)->IPV6(40)->NETIF(y)]
  * Now with NHC this looks like this: [IPV6(x)->UDP(8)->IPV6(8)->[other extension headers]->IPV6(40)->NETIF(y)]

This loop (as the previous implementation did poorly, because it did not handle the second case) tries to get all those cases.

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: > I still don't understand. What is a non-6lo driver (or a 6lo driver) and why does it mark anything as IPv6 that is not IPv6 and how is this a valid behavior?

Because this is how GNRC works: the payload of the current handler is marked with the nettype of the next handler (in this case IPv6).

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: A non-6lo driver is e.g. an Ethernet device driver or SLIP or anything else that does not hand its packets through the 6Lo adaption layer.

Comment (OlegHahm) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: What does the value in parens express? Why are their more than one IPv6 snips?

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: > What does the value in parens express?

Quoting myself again (I wrote it above): "value in parens size".

> Why are their more than one IPv6 snips?

Because they are marked as such… NETTYPE is not just marking THE IPv6 header, but any IPv6 related header (like extension headers) or payload for non-6Lo devices (2b was wrong, the first snip is UNDEF, not IPV6).

Comment (OlegHahm) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: > NETTYPE is not just marking THE IPv6 header, but any IPv6 related header (like extension headers) or payload for non-6Lo devices

Ah, that was the information I was missing. Now I wonder if it wouldn't be more logical to have a separate nettype for these, but now this change seems legit then.

Comment (authmillenon) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: Maybe, but that could potentially bloat the `netreg` unnecessarily. But if you have an idea, please do so. I find it myself pretty ugly.

**Comment by cgundogan** [comment]
after the discussion between @OlegHahm and @authmillenon the code changes make more sense to me. ACK
