### PR TITLE
bootloaders: fix bootloader button logic

### LINKED ISSUE #19364: bootloader: BTN_BOOTLOADER_INVERTED doesn't work as expected.
#### Description
The logic to define the value of `BTN_BOOTLOADER_INVERTED` doesn't work as expected.
This lead to issue in `bootloader/riotboot_dfu` and `bootloader/riotboot_tinyusb_dfu`.
For instance, on my SAML21-XPRO, I can successfully flash any application using dfu-util after flashing `bootloader/riotboot_dfu`

#### Steps to reproduce the issue
Flash the riotboot_dfu bootloader:
`make BOARD=saml21-xpro -C bootloaders/riotboot_dfu flash`
Then, flash any test app:
`PROGRAMMER=dfu-util USEMODULE=usbus_dfu make BOARD=saml21-xpro -C tests/shell riotboot/flash-slot0`

#### Expected results
Application should start after flashing.

#### Actual results
Flash succeed, but application doesn't start.
a quick look at `lsusb` shows that we're stuck in the bootloader (with VID/PID: 1209:7d02)

I'll provide a PR to fix that right away.

### PR DESCRIPTION
**Pull request by dylad**
### Contribution description

In lastest master, the `BTN_BOOTLOADER_INVERTED` logic doesn't work as expected.
This PR fixes the underlying logic by replacing the `BTN_BOOTLOADER_INVERTED` macro definition by a runtime function.
In fact the current code:
```
#ifndef BTN_BOOTLOADER_INVERTED
#if (BTN0_MODE == GPIO_IN_PD)
#define BTN_BOOTLOADER_INVERTED false
#else
#define BTN_BOOTLOADER_INVERTED true
#endif
#endif
```
cannot work because both `BTN0_MODE` and `GPIO_IN_PD` are not known by the precompiler as they are enum values defined at cpu level.
Thus, replaces it by a runtime function in our bootloader applications.
I've also add `GPIO_OD_PU` along side `GPIO_IN_PU` and add a new define (which can be override at board level or app level) in case an external pullup is used.

### Testing procedure
Flash the riotboot_dfu bootloader:
`make BOARD=saml21-xpro -C bootloaders/riotboot_dfu flash`
Then, flash any test app:
`PROGRAMMER=dfu-util USEMODULE=usbus_dfu make BOARD=saml21-xpro -C tests/shell riotboot/flash-slot0`

With master, the application will not start.
With this PR, the application will start after flashing.

### Issues/PRs references
Fixes #19364

### CODE REVIEW

File: bootloaders/riotboot_dfu/main.c [hunk 1]
```diff
@@ -36,9 +36,18 @@
 
 static bool _bootloader_alternative_mode(void)
 {
-#ifdef BTN_BOOTLOADER_PIN
+    bool state;
```
Comment (benpicco) [inline bootloaders/riotboot_dfu/main.c:39]: You want to move that inside the condition below, otherwise the compiler will complain about the unused variable.

**Comment by benpicco** [comment]
Please squash!

**Comment by benpicco** [comment]
Reminds me that we should eventually combine all those riotboot 'applications' into a single one so we can also easily combine e.g. `riotboot_slot` and `riotboot_dfu` for both OTA and direct updates if desired.

bors merge

**Review by benpicco — APPROVED** [review]
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by benpicco** [comment]
bors cancel
bors merge

**Comment by benpicco** [comment]
bors merge

**Comment by dylad** [comment]
> Reminds me that we should eventually combine all those riotboot 'applications' into a single one so we can also easily combine e.g. riotboot_slot and riotboot_dfu for both OTA and direct updates if desired.

Sounds good to me ;)
