### PR TITLE
gnrc_netif: join/leave solicited nodes IPv6 address add/remove

### LINKED ISSUE #8085: Update solicited node multicast groups on IPv6 address addition/deletion
Currently, no extra solicited node multicast addresses are added when an extra IPv6 address that is not derived from the L2 address is added to an interface. This breaks NS/NA.

Steps to reproduce:
1. Start two instances of gnrc_networking
2. Add an extra IPv6 address to the interface of the first node (for example 2001:db8::1/64)
3. Add same prefix to the second node (for example 2001:db8::2/64).
4. Try to ping the address from the second node.

### PR DESCRIPTION
**Pull request by miri64**
Fixes #8085 by actually joining the solicited nodes group on adding a new IPv6 address to an interface. Likewise, the group is left, when no IPv6 address associated to that group is left on the interface.

### CODE REVIEW

File: sys/net/gnrc/netif/gnrc_netif.c [hunk 1]
```diff
@@ -582,13 +600,30 @@ void gnrc_netif_ipv6_addr_remove(gnrc_netif_t *netif,
...
     assert((netif != NULL) && (addr != NULL));
+    ipv6_addr_set_solicited_nodes(&sol_nodes, addr);
     gnrc_netif_acquire(netif);
-    idx = _addr_idx(netif, addr);
-    if (idx >= 0) {
-        netif->ipv6.addrs_flags[idx] = 0;
-        ipv6_addr_set_unspecified(&netif->ipv6.addrs[idx]);
+    for (unsigned i = 0; i < GNRC_NETIF_IPV6_ADDRS_NUMOF; i++) {
+        if (ipv6_addr_equal(&netif->ipv6.addrs[i], addr)) {
+            netif->ipv6.addrs_flags[idx] = 0;
```
Comment (bergzand) [inline sys/net/gnrc/netif/gnrc_netif.c]: I'm getting an unitialized variable error on `idx` here.
```
/home/hydrazine/dev/RIOT/sys/net/gnrc/netif/gnrc_netif.c:611:42: error: ‘idx’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
             netif->ipv6.addrs_flags[idx] = 0;
```

Comment (miri64) [reply sys/net/gnrc/netif/gnrc_netif.c]: Oops. Should be fixed now.

**Comment by miri64** [comment]
(BTW, for the scenario described in #8085 you need to increase `GNRC_NETIF_IPV6_ADDRS_NUMOF` to at least 5 of course.

**Comment by bergzand** [comment]
> (BTW, for the scenario described in #8085 you need to increase GNRC_NETIF_IPV6_ADDRS_NUMOF GNRC_NETIF_IPV6_GROUPS_NUMOF to at least 5 of course.)

I might have forgotten to mention that modification to the config. :(
Fix looks good and works, tested on native, pinging works and group removal was tested with multiple addresses with the same solicited node multicast group.

Ack, please squash.

**Comment by miri64** [comment]
Squashed
