### PR TITLE
gnrc_ipv6: fix SEGFAULT when multicasting with multiple interfaces

### LINKED ISSUE #11980: Sending a packet to the Multicast Address with multiple interfaces causes Segmentation fault
#### Description
On RIOT, if there is more than once network interface, `ping6 ff02::1` will cause a segmentation fault.

#### Steps to reproduce the issue
In `examples/gnrc_networking`:

```
$ ../../dist/tools/tapsetup/tapsetup
$ sed -i '1i#define NETDEV_TAP_MAX 2' ../../cpu/native/include/netdev_tap_params.h
$ make GNRC_NETIF_NUMOF=2
$ bin/native/gnrc_networking.elf tap0 tap1
> ping6 ff02::1

Program received signal SIGSEGV, Segmentation fault.
0x5656dc02 in _fill_ipv6_hdr (netif=0x5659dcd8 <_netifs+312>, ipv6=0x5659de68 <_pktbuf+40>)
    at /home/benpicco/dev/RIOT/sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c:308
308	    hdr->len = byteorder_htons(gnrc_pkt_len(ipv6->next));
(gdb) p hdr
$1 = (ipv6_hdr_t *) 0x40
```

#### Expected results
The packet should be send over both interfaces.
Also, `ipv6->data` should point to a valid address.

#### Actual results
RIOT crashes. This happens both on native and on actual hardware.

#### Versions
RIOT master (ca2b00875a9e91458ba361e293cc4e97d281ecf8)

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
When writing to the IPv6 header the implementation currently doesn't take the packet with the (potentially) duplicated header, but the packet with the original one, which leads to the packet sent and then released in `gnrc_netif_ethernet.c` first and then accessed again in further iterations of the "writing to the IPv6 header" loop, which causes access to an invalid pointer, causing a crash.

### Testing procedure
When repeating the "Steps to reproduce" in #11980, the node should not crash and you get a lot of (duplicate) replies. When using two interfaces with one being a 6LoWPAN interface, the node should not crash, pinging might however not work due to the bug fixed in #10499.

### Issues/PRs references
Fixes #11980

### CODE REVIEW

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c [hunk 1]
```diff
@@ -563,28 +563,30 @@ static void _send_multicast(gnrc_pktsnip_t *pkt, bool prep_hdr,
         gnrc_pktbuf_hold(pkt, ifnum - 1);
 
         while ((netif = gnrc_netif_iter(netif))) {
+            gnrc_pktsnip_t *send_pkt = pkt;
             if (prep_hdr) {
                 DEBUG("ipv6: prepare IPv6 header for sending\n");
                 /* need to get second write access (duplication) to fill IPv6
                  * header interface-local */
-                gnrc_pktsnip_t *tmp = gnrc_pktbuf_start_write(pkt);
+                send_pkt = gnrc_pktbuf_start_write(pkt);
```
Comment (miri64) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: I also renamed that variable because `tmp` was a bit unintuitive ;-)

File: sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c [hunk 2]
```diff
@@ -563,28 +563,30 @@ static void _send_multicast(gnrc_pktsnip_t *pkt, bool prep_hdr,
...
+                    if (send_pkt != pkt) {
+                        gnrc_pktbuf_release(send_pkt);
                     }
                     gnrc_pktbuf_release(pkt);
                     return;
                 }
             }
-            _send_multicast_over_iface(pkt, prep_hdr, netif, netif_hdr_flags);
+            _send_multicast_over_iface(send_pkt, prep_hdr, netif,
+                                       netif_hdr_flags);
```
Comment (benpicco) [inline sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: What about the `!prep_hdr` case? There `send_pkt` would still just point to `pkt` without being duplicated by `gnrc_pktbuf_start_write()`.

Comment (miri64) [reply sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: Yep. The duplication happens 
a) write-protection reasons
b) because the source address and hop-limit might differ from interface to interface.

If the header doesn't need to change, the IPv6 header is the same for all cases and isn't touched, so it doesn't need to be write-protected or duplicated.

Comment (miri64) [reply sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: I'll add a comment ;-).

Comment (miri64) [reply sys/net/gnrc/network_layer/ipv6/gnrc_ipv6.c]: Done and squashed.

**Comment by miri64** [comment]
Thanks for reviewing and testing!

**Comment by miri64** [comment]
Backport provided in #12521

**Comment by benpicco** [comment]
And for completeness' sake:

```
2019-10-21 11:47:51,579 #  ping6 ff02::1
2019-10-21 11:47:51,593 # 12 bytes from fe80::5806:59c9:2c36:7d79: icmp_seq=0 ttl=64 rssi=-17 dBm time=6.612 ms
2019-10-21 11:47:51,601 # 12 bytes from fe80::5807:59c9:2c36:7d79: icmp_seq=0 ttl=64 rssi=-33 dBm time=14.306 ms (DUP!)
2019-10-21 11:47:52,599 # 12 bytes from fe80::5806:59c9:2c36:7d79: icmp_seq=1 ttl=64 rssi=-17 dBm time=6.620 ms
2019-10-21 11:47:52,607 # 12 bytes from fe80::5807:59c9:2c36:7d79: icmp_seq=1 ttl=64 rssi=-33 dBm time=14.314 ms (DUP!)
2019-10-21 11:47:53,636 # 12 bytes from fe80::5806:59c9:2c36:7d79: icmp_seq=2 ttl=64 rssi=-17 dBm time=6.631 ms
2019-10-21 11:47:53,637 # 
2019-10-21 11:47:53,639 # --- ff02::1 PING statistics ---
2019-10-21 11:47:53,645 # 3 packets transmitted, 3 packets received, 2 duplicates, 0% packet loss
2019-10-21 11:47:53,650 # round-trip min/avg/max = 6.612/9.696/14.314 ms
```
