### PR TITLE
dist/cppcheck: fix missing cppcheck-suppression reasons

### LINKED ISSUE #1895: cppcheck: add rationale to suppressed warnings
All suppressions for warnings/errors in cppcheck should be annotated with a rationale why the warning/error is suppressed instead of being fixed.

Also it would make sense to add a statement about this to the coding conventions in the wiki, if there is consent about this.

### PR DESCRIPTION
**Pull request by smlng**
### Contribution description

Fixes #1895

This adds or corrects missing rationale on existing cppcheck-suppression comments.

### Testing procedure

run `git grep -A1 cppcheck-suppression` on master and review if the line below `cppcheck-suppress <something>` looks like ` * (reason: <explanation>) */` and compare with this PR, which should fix all mismatches.

### CODE REVIEW

**Comment by miri64** [comment]
Murdock isn't happy though (apparently there is another error in `dist/tools/tunslip/tunslip6.c`) and Travis also found another problem.

**Comment by smlng** [comment]
seems to be the old cppcheck versions in travis and murdock, my macOS cppcheck (version 1.84) is totally fine with all the changes.

File: dist/tools/tunslip/tunslip6.c [hunk 1]
```diff
@@ -650,9 +650,10 @@ devopen(const char *dev, int flags)
 {
     char t[1024];
     strcpy(t, "/dev/");
-    /* cppcheck-suppress bufferAccessOutOfBounds
-     * reason: seems to be a cppcheck bug */
-    strncat(t, dev, sizeof(t) - 5);
+    /* need to consider `\0` terminator and strlen("dev") = 5, hence 6
+     * cppcheck-suppress bufferAccessOutOfBounds
+     * (reason: seems to be a bug in cppcheck 1.7x) */
+    strncat(t, dev, sizeof(t) - 6);
```
Comment (miri64) [inline dist/tools/tunslip/tunslip6.c]: I think the comment on top is completely wrong. Anyway, this should rather go in a separate PR so it can be independently tested.

Comment (miri64) [inline dist/tools/tunslip/tunslip6.c]: Also: `cppcheck` still isn't happy with this line: https://ci.riot-os.org/RIOT-OS/RIOT/10010/acdbd77214e4aefa76f539075643591cc64d8bc2/output.html

Comment (smlng) [reply dist/tools/tunslip/tunslip6.c]: just because it works, the comment is wrong? 

Looking at http://www.cplusplus.com/reference/cstring/strncat/ it states that the destination must be large enough to include both strings *plus* the `\0` terminator, so the calculation in the comment is correct, or not. One could rewrite this to `sizeof(t) - (strlen(dev) + 1)` to make it more obvious, but why bother to run `strlen(dev)` when we know its fixed to 5.

Comment (smlng) [reply dist/tools/tunslip/tunslip6.c]: strange, I simply squashed and rebased, why was murdock happy before?

Comment (miri64) [reply dist/tools/tunslip/tunslip6.c]: Please let's discuss this in a separate PR. Regardless of right or wrong, this change does not belong here.

**Comment by smlng** [comment]
removed the controversy 😬 Both CI look happy, squash?

**Comment by smlng** [comment]
happy besides fixup commits, that is.

**Comment by miri64** [comment]
> Both CI look happy, squash?

Yes please!

**Comment by smlng** [comment]
to verify run `git grep -A1 "/* cppcheck-suppress "` and review the output, with this PR all places adhere to format:

```
/* cppcheck-suppress <CONDITION 
 * (reason: <RATIONALE/COMMET> */
```

so should resolve  #1895

**Comment by miri64** [comment]
Good point! Found one remaining tiny deviation ;-):

```
tests/cpp11_condition_variable/main.cpp:      /* cppcheck-suppress unreadVariable
tests/cpp11_condition_variable/main.cpp-       * (reason variable is read in the thread created above) */
```

**Comment by smlng** [comment]
amended fix (colon) directly

**Comment by miri64** [comment]
Thanks for finally tackling this!
