### PR TITLE
sys/usb/cdc_acm: fix garbage input when disconnected

### LINKED ISSUE #20305: stdio_cdc_acm causing corruption of first shell input
#### Description

Test programs that use `shell` and have `stdio_cdc_acm` enabled show corruption of the first input to `shell`. So far I have just seen this on my `sodaq-sara-sff` boards, but I assume this is true for all sam0 (arduino style boards).

#### Steps to reproduce the issue

* build one of the test programs
* connect a "term"
* look at the output
* type `help` and ENTER

#### Expected results

The banner should be printed, the test program's introduction and a prompt.

#### Actual results

With `make ... term` you'd see something like this:
```
$ make CC_NOCOLOR=1 BOARD=sodaq-sara-sff -C tests/periph/gpio flash term
make: Entering directory '/home/kees/src/RIOT/tests/periph/gpio'
Building application "tests_gpio" for "sodaq-sara-sff" with MCU "samd21".

"make" -C /home/kees/src/RIOT/pkg/cmsis/ 
...
/home/kees/src/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200"  
Twisted not available, please install it if you want to use pyterm's JSON capabilities
2024-01-27 22:24:12,586 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
2024-01-27 22:24:13,590 # shell: command not found: c.
> 2024-01-27 22:24:13,590 # 
> 2024-01-27 22:24:13,590 # 
> 2024-01-27 22:24:13,591 # 
> help
2024-01-27 22:24:38,079 # NOTE: make suc.help
2024-01-27 22:24:38,079 # shell: command not found: NOTE:
> help
2024-01-27 22:28:12,523 # help
2024-01-27 22:28:12,523 # Command              Description
2024-01-27 22:28:12,524 # ---------------------------------------
2024-01-27 22:28:12,524 # init_out             init as output (push-pull mode)
...
> 

```

Sometimes I see part of the banner on the shell input.
```
Welcome to pyterm!
Type '/exit' to exit.
help
2024-01-27 22:34:26,163 # in(): This is Rmahelp
2024-01-27 22:34:26,163 # shell: command not found: main():
> 
```

### LINKED ISSUE #20544: Standard output is truncated and sent to the shell input on Arduino Nano 33 BLE for the default example
### Description

The default example is supposed to print two lines then let the user type the commands, but on the Nano 33 BLE the two lines are not printed correctly and some characters are mixed in the shell input which imply that the user has to erase them.

### Steps to reproduce the issue

With a Nano 33 BLE linked to the computer :

```
BOARD=arduino-nano-33-ble RIOT_TERMINAL=picocom make -C default flash term 
```

Note that I'm using picocom instead of pyserial which doesn't change anything to the result.

### Expected results

The output is clean with the lines printed in the right order and the input is empty and let the user type his command without erasing anything.

The output is supposed to be the following one :
 ```
main(): This is RIOT! (Version : 2024-)
Welcome to RIOT!
>
 ```

### Actual results

The actual output is  :
 ```
Welcome to RIOT!
> mai):Th is
 ```

The first line is not printed and instead seems to be partially sent to the input of the shell.

### Versions

All tests performed on a fresh master branch.

Operating System Environment

Operating System: "Ubuntu" "22.04.4 LTS (Jammy Jellyfish)"
Kernel: Linux 6.5.0-26-generic x86_64 x86_64
System shell: /usr/bin/dash (probably dash)
make's shell: /usr/bin/dash (probably dash)

Installed compiler toolchains

native gcc: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
arm-none-eabi-gcc: arm-none-eabi-gcc (15:10.3-2021.07-4) 10.3.1 20210621 (release)
clang: Ubuntu clang version 14.0.0-1ubuntu1.1

Installed compiler libs

arm-none-eabi-newlib: "3.3.0"

Installed development tools

cmake: cmake version 3.22.1
doxygen: 1.9.1
git: git version 2.34.1
make: GNU Make 4.3
openocd: Open On-Chip Debugger 0.11.0
python: Python 3.12.2
python3: Python 3.12.2

### PR DESCRIPTION
**Pull request by benpicco**
### Contribution description

`usbus_cdc_acm` tries to buffer output while disconnected, but fails hard at this. 

### Testing procedure

Enable the `stdio_cdc_acm` on any application that comes with a shell.
I added an output of the received data to `cdc_acm_stdio.c`:

```patch
--- i/sys/usb/usbus/cdc/acm/cdc_acm_stdio.c
+++ w/sys/usb/usbus/cdc/acm/cdc_acm_stdio.c
@@ -51,6 +51,9 @@ static void _cdc_acm_rx_pipe(usbus_cdcacm_device_t *cdcacm,
                              uint8_t *data, size_t len)
 {
     (void)cdcacm;
+    data[len] = 0;
+    printf("got %u bytes '%s'\n", len, (char *)data);
+
     for (size_t i = 0; i < len; i++) {
         isrpipe_write_one(&stdin_isrpipe, data[i]);
     }
```

#### master

```
2025-11-17 21:09:01,404 # Reconnected to serial port /dev/ttyACM1
2025-11-17 21:09:01,405 # got 1 bytes ':'
2025-11-17 21:09:01,405 # got 1 bytes 'T'
2025-11-17 21:09:01,405 # got 1 bytes 'h'
2025-11-17 21:09:01,405 # got 1 bytes 's'
2025-11-17 21:09:01,405 # got 1 bytes 'i'
2025-11-17 21:09:01,406 # got 1 bytes ' '
2025-11-17 21:09:01,406 # got 1 bytes 'I'
ps
2025-11-17 21:09:05,552 # i(:Thsi Igot 3 bytes 'ps
2025-11-17 21:09:05,552 # '
2025-11-17 21:09:05,552 # ps
2025-11-17 21:09:05,553 # shell: command not found: i(:Thsi
```

#### with this patch

```
2025-11-17 21:06:54,685 # Reconnected to serial port /dev/ttyACM1
ps
2025-11-17 21:07:45,989 # got 3 bytes 'ps
2025-11-17 21:07:45,989 # '
2025-11-17 21:07:45,989 # ps
2025-11-17 21:07:45,990 # 	pid | name                 | state    Q | pri | stack  ( used) ( free) | base addr  | current     
2025-11-17 21:07:45,991 # 	  - | isr_stack            | -        - |   - |    512 (  224) (  288) | 0x20000000 | 0x200001c8
2025-11-17 21:07:45,991 # 	  1 | main                 | running  Q |   7 |   1536 (  764) (  772) | 0x200008c8 | 0x20000d14 
2025-11-17 21:07:45,992 # 	  2 | pktdump              | bl rx    _ |   6 |   1472 (  172) ( 1300) | 0x200036d0 | 0x20003be4 
2025-11-17 21:07:45,993 # 	  3 | 6lo                  | bl rx    _ |   3 |    960 (  264) (  696) | 0x200046f0 | 0x200049f4 
2025-11-17 21:07:45,993 # 	  4 | ipv6                 | bl rx    _ |   4 |    960 (  372) (  588) | 0x2000100c | 0x20001304 
2025-11-17 21:07:45,995 # 	  5 | udp                  | bl rx    _ |   5 |    448 (  192) (  256) | 0x20004af4 | 0x20004bf4 
2025-11-17 21:07:45,996 # 	  6 | usbus                | bl anyfl _ |   1 |   1024 (  696) (  328) | 0x200004c8 | 0x2000074c 
2025-11-17 21:07:45,997 # 	  7 | nrf802154            | bl anyfl _ |   2 |    896 (  304) (  592) | 0x20001a60 | 0x20001d24 
2025-11-17 21:07:45,997 # 	  8 | RPL                  | bl rx    _ |   5 |   1024 (  204) (  820) | 0x20003ed8 | 0x2000420c 
2025-11-17 21:07:45,997 # 	    | SUM                  |            |     |   8832 ( 3192) ( 5640)
```

### Issues/PRs references

Fixes #20305.
Fixes #20544.

### CODE REVIEW

**Comment by maribu** [comment]
Does this fix https://github.com/RIOT-OS/RIOT/issues/20544 ?

**Comment by crasbe** [comment]
> Does this fix #20544 ?

It certainly fixes #20305, I tried it with a Feather-M0. I'll try to check with an nRF52840DK tomorrow.

Behavior with `master`:
```
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ BOARD=feather-m0 make -C tests/sys/shell term
make: Entering directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/sys/shell'
/home/cbuec/RIOTstuff/riot-vanilla/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2025-11-18_00.31.20-tests_shell-feather-m0"
2025-11-18 00:31:20,396 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
help
2025-11-18 00:31:22,540 # main(): This is help
2025-11-18 00:31:22,540 # shell: command not found: main():
>
```

Behavior with this PR:
```
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ BOARD=feather-m0 make -C tests/sys/shell term
make: Entering directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/sys/shell'
/home/cbuec/RIOTstuff/riot-vanilla/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2025-11-18_00.29.55-tests_shell-feather-m0"
2025-11-18 00:29:55,929 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
help
2025-11-18 00:30:00,008 # help
2025-11-18 00:30:00,010 # Command              Description
2025-11-18 00:30:00,011 # ---------------------------------------
2025-11-18 00:30:00,012 # bufsize              Get the shell's buffer size
2025-11-18 00:30:00,013 # start_test           starts a test
2025-11-18 00:30:00,014 # end_test             ends a test
2025-11-18 00:30:00,016 # echo                 prints the input command
2025-11-18 00:30:00,018 # empty                print nothing on command
2025-11-18 00:30:00,019 # periodic             periodically print command
2025-11-18 00:30:00,020 # xfa_test1            xfa test command 1
2025-11-18 00:30:00,021 # xfa_test2            xfa test command 2
2025-11-18 00:30:00,022 # app_metadata         Returns application metadata
2025-11-18 00:30:00,023 # pm                   interact with layered PM subsystem
2025-11-18 00:30:00,024 # ps                   Prints information about running threads.
2025-11-18 00:30:00,025 # version              Prints current RIOT_VERSION
2025-11-18 00:30:00,028 # bootloader           Reboot to bootloader
2025-11-18 00:30:00,029 # reboot               Reboot the node
>
```

I had to create an UF2 file because the Feather-M0 and WSL don't really play together that well.

**Comment by crasbe** [comment]
It might therefore also fix #21231.

**Comment by crasbe** [comment]
No, it does not fix #21231:

```
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ git status
On branch usbus/cdc/acm-fix_garbage
nothing to commit, working tree clean
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ BOARD=seeedstudio-xiao-nrf52840-sense make -C tests/sys/pthread_flood/ test
make: Entering directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/sys/pthread_flood'
r
/home/cbuec/RIOTstuff/riot-vanilla/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2025-11-18_00.44.16-tests_pthread_flood-seeedstudio-xiao-nrf52840-sense" --no-reconnect --noprefix --no-repeat-command-on-empty-line
Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
READY
s
START
main(): This is RIOT! (Version: 2026.01-devel-138-g494e1-usbus/cdc/acm-fix_garbage)
Spawning pthreads
......
created 6 pthreads
created 6 threads
wait for created pthreads to exit...
{ "threads": [{ "name": "pthread", "stack_size": 256, "stack_used": 128}]}
{ "threads": [{ "name": "pthread", "stack_size": 256, "stack_used": 128}]}
{ "threads": [{ "name": "pthread", "stack_size": 256, "stack_used": 128}]}
Timeout in expect script at "child.expect_exact("SUCCESS")" (tests/sys/pthread_flood/tests/01-run.py:14)

make: *** [/home/cbuec/RIOTstuff/riot-vanilla/RIOT/makefiles/tests/tests.inc.mk:32: test] Error 1
make: Leaving directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/sys/pthread_flood'
```

**Comment by crasbe** [comment]
> > Does this fix #20544 ?
> 
> It certainly fixes #20305, I tried it with a Feather-M0. I'll try to check with an nRF52840DK tomorrow.
> 

I remembered that I have a Seeedstudio Xiao nRF52840 Sense laying around, which is also based on the nRF52840 as is the Arduino Nano 33 BLE.
Therefore I'd dare to say it also fixes that issue.

Behavior on `master`:
```
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ BOARD=seeedstudio-xiao-nrf52840-sense make -C tests/sys/shell term
make: Entering directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/sys/shell'
/home/cbuec/RIOTstuff/riot-vanilla/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2025-11-18_00.38.42-tests_shell-seeedstudio-xiao-nrf52840-sense"
2025-11-18 00:38:42,746 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
help
2025-11-18 00:38:59,877 # main(): This is help
2025-11-18 00:38:59,881 # shell: command not found: main():
```

Behavior with this PR:
```
cbuec@W11nMate:~/RIOTstuff/riot-vanilla/RIOT$ BOARD=seeedstudio-xiao-nrf52840-sense make -C tests/sys/shell term
make: Entering directory '/home/cbuec/RIOTstuff/riot-vanilla/RIOT/tests/sys/shell'
/home/cbuec/RIOTstuff/riot-vanilla/RIOT/dist/tools/pyterm/pyterm -p "/dev/ttyACM0" -b "115200" -ln "/tmp/pyterm-cbuec" -rn "2025-11-18_00.40.42-tests_shell-seeedstudio-xiao-nrf52840-sense"
2025-11-18 00:40:42,597 # Connect to serial port /dev/ttyACM0
Welcome to pyterm!
Type '/exit' to exit.
help
2025-11-18 00:40:44,657 # help
2025-11-18 00:40:44,663 # Command              Description
2025-11-18 00:40:44,664 # ---------------------------------------
2025-11-18 00:40:44,666 # bufsize              Get the shell's buffer size
2025-11-18 00:40:44,669 # start_test           starts a test
2025-11-18 00:40:44,672 # end_test             ends a test
2025-11-18 00:40:44,676 # echo                 prints the input command
2025-11-18 00:40:44,680 # empty                print nothing on command
2025-11-18 00:40:44,684 # periodic             periodically print command
2025-11-18 00:40:44,687 # xfa_test1            xfa test command 1
2025-11-18 00:40:44,690 # xfa_test2            xfa test command 2
2025-11-18 00:40:44,695 # app_metadata         Returns application metadata
2025-11-18 00:40:44,699 # pm                   interact with layered PM subsystem
2025-11-18 00:40:44,704 # ps                   Prints information about running threads.
2025-11-18 00:40:44,708 # version              Prints current RIOT_VERSION
2025-11-18 00:40:44,711 # bootloader           Reboot to bootloader
2025-11-18 00:40:44,714 # reboot               Reboot the node
> 
```

**Comment by maribu** [comment]
This cannot easily be backported, as the thread unsafe ring buffer did not make it into the release.

Maybe we should just leave this for next release?

Or should we port this to the old state of the CDC ACM driver?

File: sys/usb/usbus/cdc/acm/cdc_acm.c [hunk 1]
```diff
@@ -152,25 +152,14 @@ size_t usbus_cdc_acm_submit(usbus_cdcacm_device_t *cdcacm, const uint8_t *buf, s
 {
     size_t n;
     unsigned old;
-    if (cdcacm->state != USBUS_CDC_ACM_LINE_STATE_DISCONNECTED) {
-        old = irq_disable();
-        n = turb_add(&cdcacm->tsrb, buf, len);
-        irq_restore(old);
-        return n;
+    if (cdcacm->state == USBUS_CDC_ACM_LINE_STATE_DISCONNECTED) {
+        return len;
```
Comment (mguetschow) [inline sys/usb/usbus/cdc/acm/cdc_acm.c:156]: Shouldn't this rather return 0, as no bytes were actually added to the ring buffer? See

https://github.com/RIOT-OS/RIOT/blob/bcd09d39f77aceb66404ea4f865580e5549431a8/sys/include/usb/usbus/cdc/acm.h#L194-L204

Comment (maribu) [reply sys/usb/usbus/cdc/acm/cdc_acm.c:156]: That would cause problems with stdio, as `stdio_write()` is expected to either return the number of bytes written in absence of an error, or an error if writing bytes won't work.

If it would return `0`, the `stdio` implementation on top would just keep calling `stdio_write()` in a loop until all data has been written - which would be an endless loop here.

We should either change the doc to "number of bytes handled" with discarding being handled, or change the return type to `ssize_t` and return an error when discarding data.

Discarding the data here and not reporting an error doesn't really change the API contract, btw. Even if we would go for `ssize_t`, getting a success return code is no guarantee that the data will be transferred to the Linux host: They may have been successfully added to the ringbuffer and subsequently a disconnect may happen before the data left the ringbuffer.

Comment (mguetschow) [reply sys/usb/usbus/cdc/acm/cdc_acm.c:156]: Thanks for the explanation. I think I'd favor a telling error code over a silent drop. "bytes handled" does not really tell the user much.
