### PR TITLE
posix_sockets: use sin6_scope_id of struct sockaddr_in6

### LINKED ISSUE #14207: example/posix_sockets: udp send is broken
#### Description
Sending UDP datagrams via posix sockets is broken.

Problem shows with posix_sockets example, but seems to affect posix_sockets in general. 

#### Steps to reproduce the issue
Open a netcat receiver:
```
netcat -vu6 -l 5556
```

Run posix_sockets example in another terminal:
```
make -C examples/posix_sockets
make -C examples/posix_sockets term
udp send IPV6ADDR 5556 hello
```
IPV6ADDR be the address of tapbr0 interface.

#### Expected results
Netcat receiver should show string "hello".

#### Actual results
Netcat does not receive anything.

Running gnrc_networking instead of posix_sockets with same udp command produces expected result.

#### Versions
Affected is current master (4th June 2020).
I have tested on Ubuntu 20.04.

Can provide wireshark dumps if needed.

### PR DESCRIPTION
**Pull request by fengelhardt**
### Contribution description

This PR improves the POSIX compatibilitiy regarding scoped IPv6 addresses ([RFC4007](https://tools.ietf.org/html/rfc4007)).

Scoped IPv6 addresses are known by their `%`-notation especially with link-local addresses. The scope (aka netif id) can be mapped to the `sin6_scope_id` field of `struct sockaddr_in6` that is specified in [`<netinet/in.h>`](https://pubs.opengroup.org/onlinepubs/009695399/basedefs/netinet/in.h.html).

The PR includes a modified `posix_sockets` example that now accepts netif definitions like `fe80::x:x:x:x%5`. It can therefore, for example, be used on the `native` target that requires link-local addresses.

### Testing procedure

Initialize tap interace(s). Open a netcat receiver:

```
netcat -vu6 -l 5555
```

Run posix_sockets example in another terminal on native:

```
make -C examples/posix_sockets
make -C examples/posix_sockets term
udp send IPV6ADDR 5555 hello
```
IPV6ADDR be the host link-local address, potentially with appended scope definition `...%netif`.

### Issues/PRs references

Fixes #14207

### CODE REVIEW

File: examples/posix_sockets/udp.c [hunk 1]
```diff
@@ -98,6 +118,19 @@ static int udp_send(char *addr_str, char *port_str, char *data, unsigned int num
...
+#ifdef SOCK_HAS_IPV6
+    char *iface;
+    uint32_t netif;
+    iface = ipv6_addr_split_iface(addr_str); /* also removes interface id */
+    if (!iface) {
+        netif = _get_first_netif();
+    }
+    else {
+        netif = atoi(iface);
+    }
```
Comment (benpicco) [inline examples/posix_sockets/udp.c:131]: I think you want to replicate what [`ping6`]( https://github.com/RIOT-OS/RIOT/blob/master/sys/shell/commands/sc_gnrc_icmpv6_echo.c#L196) does. (Would probably be a good idea to move that to common code).

Otherwise you might always set the `sin6_scope_id` for a global address to the first interface.

File: examples/posix_sockets/udp.c [hunk 2]
```diff
@@ -33,6 +33,13 @@
 #include <sys/socket.h>
 #include <unistd.h>
 
+#ifdef SOCK_HAS_IPV6
+#include <net/ipv6/addr.h>     /* for interface parsing */
+#endif /* SOCK_HAS_IPV6 */
+#ifdef MODULE_GNRC_SOCK_UDP
+#include <net/gnrc/netif.h>    /* for finding default ipv6 interface */
```
Comment (miri64) [inline examples/posix_sockets/udp.c:40]: [Please use `"` for non-POSIX headers](https://github.com/RIOT-OS/RIOT/blob/master/CODING_CONVENTIONS.md#includes).

File: examples/posix_sockets/udp.c [hunk 3]
```diff
@@ -43,6 +50,19 @@ static char server_buffer[SERVER_BUFFER_SIZE];
 static char server_stack[THREAD_STACKSIZE_DEFAULT];
 static msg_t server_msg_queue[SERVER_MSG_QUEUE_SIZE];
 
+/* find first valid network interface */
+#ifdef SOCK_HAS_IPV6
+static uint32_t _get_first_netif(void) {
+#ifdef MODULE_GNRC_SOCK_UDP
+    gnrc_netif_t *iface = gnrc_netif_iter(NULL);
```
Comment (miri64) [inline examples/posix_sockets/udp.c:57]: As `posix_sockets` is not GNRC specific, I would prefer the usage of [`net/netif.h`](https://github.com/RIOT-OS/RIOT/blob/master/sys/include/net/netif.h).

File: examples/posix_sockets/udp.c (hunk 1 above)
Comment (fengelhardt) [reply examples/posix_sockets/udp.c:131]: Yes, I found that code snipplet in RIOT, in [examples/gnrc_networking](https://github.com/RIOT-OS/RIOT/blob/01d0e30229f1f80d622abd28bac178115066e0f8/examples/gnrc_networking/udp.c#L47). 

After some thought I am also not happy with that solution. It would be better to avoid RIOT internal functions as much as possible here. Maybe I remove the `_get_first_netif()` function , since that is a convenience feature. 
The user can/should specify an interface explicitly when using link-local addresses, which is the standard for most Unix commands.

File: examples/posix_sockets/udp.c (hunk 3 above)
Comment (fengelhardt) [reply examples/posix_sockets/udp.c:57]: > As this application is by its nature supposed to be independent from the network stack below, we should really carefully think about how we get the network interface:

Thank you very much, I will have a look.

Comment (miri64) [reply examples/posix_sockets/udp.c:57]: If you want to collect bonus points, a POSIX wrapper around `net/netif.h` would be the ideal solution ;-), but for now I would be happy with just using `net/netif.h`

Comment (fengelhardt) [reply examples/posix_sockets/udp.c:57]: I think I can do that, too. [`net/if.h`](https://pubs.opengroup.org/onlinepubs/009619199/netifh.htm#tagcjh_04_02) would be it and looks not too complicated. :)

**Comment by fengelhardt** [comment]
Added a fixup regarding @miri64 s comments. I use `net/netif.h` for the moment and would rather start a new PR for implementing POSIX `net/if.h` as soon as I have time.

**Comment by miri64** [comment]
> Added a fixup regarding @miri64 s comments. I use `net/netif.h` for the moment and would rather start a new PR for implementing POSIX `net/if.h` as soon as I have time.

Sounds good!

File: sys/posix/sockets/posix_sockets.c [hunk 4]
```diff
@@ -238,6 +238,9 @@ static int _sockaddr_to_ep(const struct sockaddr *address, socklen_t address_len
             out->family = AF_INET6;
             memcpy(&out->addr.ipv6, &in6_addr->sin6_addr, sizeof(out->addr.ipv6));
             out->port = ntohs(in6_addr->sin6_port);
+            if(in6_addr->sin6_scope_id != 0) {
+                out->netif = (kernel_pid_t) in6_addr->sin6_scope_id;
```
Comment (miri64) [inline sys/posix/sockets/posix_sockets.c:242]: Ah, rather cast to `uint16_t` here. That's the type for `out->netif`.

Comment (fengelhardt) [reply sys/posix/sockets/posix_sockets.c:242]: Sure! I missed that...

**Comment by miri64** [comment]
Please squash

File: sys/posix/sockets/posix_sockets.c [hunk 5]
```diff
@@ -238,6 +238,9 @@ static int _sockaddr_to_ep(const struct sockaddr *address, socklen_t address_len
             out->family = AF_INET6;
             memcpy(&out->addr.ipv6, &in6_addr->sin6_addr, sizeof(out->addr.ipv6));
             out->port = ntohs(in6_addr->sin6_port);
+            if(in6_addr->sin6_scope_id != 0) {
```
Comment (miri64) [inline sys/posix/sockets/posix_sockets.c:241]: While squashing please also note this style nit by vera++:

```
	sys/posix/sockets/posix_sockets.c:241: warning: keyword 'if' not followed by a single space
```

https://travis-ci.org/github/RIOT-OS/RIOT/builds/698438541#L191

File: examples/posix_sockets/udp.c [hunk 6]
```diff
@@ -98,6 +103,20 @@ static int udp_send(char *addr_str, char *port_str, char *data, unsigned int num
     src.sin6_family = AF_INET6;
     dst.sin6_family = AF_INET6;
     memset(&src.sin6_addr, 0, sizeof(src.sin6_addr));
+    /* parse interface id */
+#ifdef SOCK_HAS_IPV6
+    char *iface;
+    iface = ipv6_addr_split_iface(addr_str); /* also removes interface id */
+    if (iface) {
+        netif_t *netif = netif_get_by_name(iface);
+        if(netif) {
```
Comment (miri64) [inline examples/posix_sockets/udp.c:112]: Here too.

**Comment by benpicco** [comment]
All green here
