### PR TITLE
cpu: native: fix thread_yield_higher isr_is_in() case

### LINKED ISSUE #6642: xtimer: broken on 'native` when with thread_flags
refining #6624

The following code hangs after the first timeout on native:
```c
static void time_evt(void *arg)
{
    thread_flags_set((thread_t *)arg, 0x1);
}

int main(void)
{
    xtimer_t timer;
    timer.callback = time_evt;
    timer.arg = (void *)sched_active_thread;

    while (1) {
        xtimer_set(&timer, 1000000);
        thread_flags_wait_any(0x1);
        printf("+++ timeout +++\n");
    }

    return 0;
}
```

After a quick debugging session I might have found a lead: it seems like native is doing an early context switch from its interrupt context back to the main thread when calling `thread_flags_set()`. The second call to `xtimer_set()` exits in `_lltimer_set()` without setting the new timer, because `_in_handler` is still set. If I see it correctly, the `_in_handler` being set because the `_timer_callback()` function never actually exists -> hence it seems like the switch from interrupt to thread context is happening early.

I am not sure however, how this should be fixed?! Are there maybe some `if (in_isr())` checks missing in the thread_flags implementation?

### PR DESCRIPTION
**Pull request by kaspar030**
Previously, native created a new "setcontext" context whenever ```thread_yield_higher()``` was called. That's unnecessary and broken. At the end of interrupt our interrupt handlers, ```sched_context_switch_request``` is checked and triggers an eventually needed context switch.

Fixes #6642.

### CODE REVIEW

**Comment by OlegHahm** [comment]
I came to a similar solution. What I don't quite understand:
at the end of native's IRQ handler (`native_irq_handler()`) the function `cpu_switch_context_exit()` gets called. However, the documentation of this function says: "Call context switching at thread exit". Apparently, this function serves more than this purpose on native.

**Comment by OlegHahm** [comment]
The change seems valid to me, but I'd like to run a few more tests before I ACK.

File: cpu/native/native_cpu.c [hunk 1]
```diff
@@ -225,7 +225,7 @@ void thread_yield_higher(void)
         irq_enable();
     }
     else {
-        isr_thread_yield();
+        sched_context_switch_request = 1;
```
Comment (LudwigKnuepfer) [inline cpu/native/native_cpu.c]: I think `isr_thread_yield` is not called from anywhere else - please remove if this is correct.

Comment (OlegHahm) [inline cpu/native/native_cpu.c]: It's not correct, see https://github.com/RIOT-OS/RIOT/pull/6660/files#diff-ae383327c6bd21463d3010729a9284b3R221

**Comment by kaspar030** [comment]
> What I don't quite understand:
> at the end of native's IRQ handler (native_irq_handler()) the function cpu_switch_context_exit() gets called.

Yeah, that's weird. IMHO unrelated, though.

**Comment by OlegHahm** [comment]
True

**Comment by kaspar030** [comment]
@OlegHahm Does this patch also solve the stability issues you had when testing yout thesis?

**Comment by OlegHahm** [comment]
Trying hard to remember which issues you're talking about...

**Comment by OlegHahm** [comment]
I thought they were already fixed with #2071.

**Comment by OlegHahm** [comment]
But I found 9930e17ca42c20d1243847ab7d72c4b86cc398c6 in my working branch that may be related.

**Comment by kaspar030** [comment]
> But I found 9930e17 in my working branch that may be related.

Yes, that's the one I meant, also in #6135.
