### PR TITLE
sys: fmt: fix fmt_lpad() documentation and (str==NULL) case

### LINKED ISSUE #6806: Inconsistent return values / documentation in fmt
See for instance `fmt_u32_dec` or `fmt_lpad`.

### PR DESCRIPTION
**Pull request by kaspar030**
Fixes #6806.

### CODE REVIEW

**Comment by kaspar030** [comment]
low hanging fruit!

File: sys/fmt/fmt.c [hunk 1]
```diff
@@ -249,24 +249,27 @@ size_t fmt_lpad(char *out, size_t in_len, size_t pad_len, char pad_char)
...
-    }
-    else {
-        char *pos = out + pad_len - 1;
-        out += in_len -1;
+    if (out) {
+        size_t n = pad_len - in_len;
 
-        while(in_len--) {
-            *pos-- = *out--;
+        if (FMT_USE_MEMMOVE) {
```
Comment (miri64) [inline sys/fmt/fmt.c]: (explained offline)
