### PR TITLE
cord_ep: allow not specify netif if only one interface exist

### LINKED ISSUE #14399: cord_ep example timed out when registering to a resource directory
#### Description

The `cord_ep` example application timed out when registering to `aiocoap-rd` resource directory (RD). Latest known working release is 2020.01.

#### Steps to reproduce the issue

With the latest master (e8389a58470edf53800c3a9ad202c25d7c663112) or release 2020.04, start a `cord_ep` example application and try to register to the RD.

I'm using aiocoap version `0.4b3`. Install with `pip3 install --upgrade "git+https://github.com/chrysn/aiocoap@0.4b3#egg=aiocoap[all,docs]"`, the latest from aiocoap master seems to have some issue.

1. Start the RD: `aiocoap-rd`
2. From `cord_ep` example terminal: `cord_ep register [<RD ipv6 ip>]:5683`

#### Expected results

Using RIOT release version 2020.01:

```
main(): This is RIOT! (Version: 2020.01)
CoRE RD client example!

Client information:
  ep: RIOT-9F2723239F272323
  lt: 60s
> cord_ep register [fe80::a4b8:d3ff:feb5:d5aa]:5683
cord_ep register [fe80::a4b8:d3ff:feb5:d5aa]:5683
Registering with RD now, this may take a short while...
RD endpoint event: now registered with a RD
registration successful

CoAP RD connection status:
RD address: coap://[fe80::a4b8:d3ff:feb5:d5aa]:5683
   ep name: RIOT-9F2723239F272323
  lifetime: 60s
    reg if: /resourcedirectory
  location: /reg/1/
```

#### Actual results

Using latest master (e8389a58470edf53800c3a9ad202c25d7c663112) or release 2020.04:

```
main(): This is RIOT! (Version: 2020.07-devel-1658-ge8389)
CoRE RD client example!

Client information:
  ep: RIOT-272A2323272A2323
  lt: 60s
> cord_ep register [fe80::a4b8:d3ff:feb5:d5aa]:5683
cord_ep register [fe80::a4b8:d3ff:feb5:d5aa]:5683
Registering with RD now, this may take a short while...
error: registration failed

```

#### Versions

```
user@riot-vm:~/RIOT$ make print-versions

Operating System Environment
----------------------------
         Operating System: "Ubuntu" "18.04.4 LTS (Bionic Beaver)"
                   Kernel: Linux 4.15.0-76-generic x86_64 x86_64
             System shell: /bin/dash (probably dash)
             make's shell: /bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 9-2019-q4-major) 9.2.1 20191025 (release) [ARM/arm-9-branch revision 277599]
                  avr-gcc: avr-gcc (GCC) 5.4.0
         mips-mti-elf-gcc: mips-mti-elf-gcc (Codescape GNU Tools 2018.09-03 for MIPS MTI Bare Metal) 6.3.0
               msp430-gcc: msp430-gcc (GCC) 4.6.3 20120301 (mspgcc LTS 20120406 unpatched)
     riscv-none-embed-gcc: riscv-none-embed-gcc (GNU MCU Eclipse RISC-V Embedded GCC, 64-bit) 8.2.0
     xtensa-esp32-elf-gcc: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a) 5.2.0
   xtensa-esp8266-elf-gcc: xtensa-esp8266-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
                    clang: clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.1.0"
      mips-mti-elf-newlib: "2.5.0"
  riscv-none-embed-newlib: "3.0.0"
  xtensa-esp32-elf-newlib: "2.2.0"
xtensa-esp8266-elf-newlib: "2.2.0"
                 avr-libc: "2.0.0" ("20150208")

Installed development tools
---------------------------
                   ccache: ccache version 3.4.1
                    cmake: cmake version 3.10.2
                 cppcheck: Cppcheck 1.82
                  doxygen: 1.8.13
                      git: git version 2.17.1
                     make: GNU Make 4.1
                  openocd: Open On-Chip Debugger 0.10.0+dev-01047-g09ac9ab1 (2020-02-19-16:15)
                   python: Python 2.7.17
                  python2: Python 2.7.17
                  python3: Python 3.6.9
                   flake8: error: /usr/bin/python3: No module named flake8
               coccinelle: spatch version 1.0.4 with Python support and with PCRE support
```

### PR DESCRIPTION
**Pull request by pokgak**
### Contribution description

This PR modifies the `make_sock_ep()` function in `cord_ep` shell function to allow not specifiying the interface when using link-local address.

### Testing procedure

1. Use `aiocoap-rd` version 0.4b3 provided by aiocoap as RD: `pip3 install --upgrade "git+https://github.com/chrysn/aiocoap@0.4b3#egg=aiocoap[all,docs]"`
2. Start the RD: aiocoap-rd
3. From cord_ep example terminal: `cord_ep register/discover [<RD ipv6 ip>]:5683`

Test running `cord_ep register`, `cord_ep discover`:
- using link-local address with and without specifiying the interface
- using global address should also

All of it should not timeout and should register correclty for `cord_ep register` and return the correct registration interface for `cord_ep discover`.

### Issues/PRs references

Fixes #14399

### CODE REVIEW

File: sys/shell/commands/sc_cord_ep.c [hunk 1]
```diff
@@ -32,8 +32,12 @@ static int make_sock_ep(sock_udp_ep_t *ep, const char *addr)
     if (sock_udp_str2ep(ep, addr) < 0) {
         return -1;
     }
+    /* if netif not specified in addr */
+    if ((ep->netif == SOCK_ADDR_ANY_NETIF) && (gnrc_netif_numof() == 1)) {
+        /* assign the single interface found in gnrc_netif_numof() */
+        ep->netif = (uint16_t)gnrc_netif_iter(NULL)->pid;
```
Comment (miri64) [inline sys/shell/commands/sc_cord_ep.c:38]:
```suggestion
        ep->netif = (int16_t)gnrc_netif_iter(NULL)->pid;
```

Comment (miri64) [reply sys/shell/commands/sc_cord_ep.c:38]: Scratch that. Was confused by `netif_get_id()`.

File: sys/shell/commands/sc_cord_ep.c [hunk 2]
```diff
@@ -32,8 +32,12 @@ static int make_sock_ep(sock_udp_ep_t *ep, const char *addr)
     if (sock_udp_str2ep(ep, addr) < 0) {
         return -1;
     }
+    /* if netif not specified in addr */
+    if ((ep->netif == SOCK_ADDR_ANY_NETIF) && (gnrc_netif_numof() == 1)) {
+        /* assign the single interface found in gnrc_netif_numof() */
+        ep->netif = (int16_t)gnrc_netif_iter(NULL)->pid;
```
Comment (miri64) [inline sys/shell/commands/sc_cord_ep.c:38]: Don't include my deleted errors ;-)
```suggestion
        ep->netif = (uint16_t)gnrc_netif_iter(NULL)->pid;
```

Comment (pokgak) [reply sys/shell/commands/sc_cord_ep.c:38]: I thought pid is kernel_pid_t which is [typedef of int16_t](http://api.riot-os.org/kernel__types_8h.html#a8375139300d7cbf23bd8bd89ddddbe84)?

Comment (pokgak) [reply sys/shell/commands/sc_cord_ep.c:38]: okay nvm, `ep->netif` is `uint16_t`.
