### PR TITLE
cpu/nrf5x: handle multiple exti pins in gpio driver

### LINKED ISSUE #10827: boards/nrf51dk: multiple external interrupts not working
#### Description
On nRF51DK platform, cannot enable multiple external interrupts. Only the latest will work.

#### Steps to reproduce the issue

Use the hello-world program, and add the following lines to enable callback functions cbButton*.
`  gpio_init_int(BTN0_PIN, GPIO_IN_PU, GPIO_FALLING, &cbButton0, NULL);  `
`  gpio_init_int(BTN1_PIN, GPIO_IN_PU, GPIO_FALLING, &cbButton1, NULL);  `
`  gpio_init_int(BTN2_PIN, GPIO_IN_PU, GPIO_FALLING, &cbButton2, NULL);  `
`  gpio_init_int(BTN3_PIN, GPIO_IN_PU, GPIO_FALLING, &cbButton3, NULL);  `

#### Expected results
When one of the four on-board button is pressed, the callback should be called.

#### Actual results
Only the latest callback is working. Here, only cbButton3 is working. If I invert the two last lines (ie cbButton2 and cbButton3), only cbButton2 will work.

#### Versions

Operating System Environment :
       Operating System: "Ubuntu" "18.04.1 LTS (Bionic Beaver)"
                 Kernel: Linux 4.15.0-43-generic x86_64 x86_64

Installed compiler toolchains :
             native gcc: gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
      arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 8-2018-q4-major) 8.2.1 20181213 (release) [gcc-8-branch revision 267074]
                avr-gcc: avr-gcc (GCC) 5.4.0
       mips-mti-elf-gcc: missing
             msp430-gcc: missing
   riscv-none-embed-gcc: missing
                  clang: missing

Installed compiler libs :
   arm-none-eabi-newlib: "3.0.0"
    mips-mti-elf-newlib: missing
riscv-none-embed-newlib: missing
               avr-libc: "2.0.0" ("20150208")

Installed development tools :
                  cmake: cmake version 3.10.2
               cppcheck: missing
                doxygen: 1.8.13
                 flake8: missing
                    git: git version 2.17.1
                   make: GNU Make 4.1
                openocd: Open On-Chip Debugger 0.10.0
                 python: Python 2.7.15rc1
                python2: Python 2.7.15rc1
                python3: Python 3.6.7
             coccinelle: missing

### PR DESCRIPTION
**Pull request by aabadie**
### Contribution description

The GPIO driver of nrf cpu family is only able the manage one pin interrupt line. This PR is modifying the GPIOTE driver to make it "multi channel" capable, like it's done with the other CPUs I checked (STM32, SAM0).

I'm not 100% sure of the proposed solution, though. But it works.

The bug reported in #10827 is not only affecting nrf51 but also nrf52 and nrf52840.

### Testing procedure

To test this PR you need a physical access to nrf51dk, nrf52dk and nrf52840dk, because they all provide 4 buttons.
- Build/flash/run the `tests/buttons` application
- Press any of the 4 user buttons

With this PR, each button pressed triggers a message "Pressed BTNx". With master only pressing the last button triggers a message.

### Issues/PRs references

fixes #10827

### CODE REVIEW

**Comment by leandrolanzieri** [comment]
With this solution `gpio_irq_enable` and `gpio_irq_disable` actually just enable/disable only the first registered interrupt, that may be confusing. I think that if we are allowing to init multiple interrupts we should also provide the way to enable and disable them.

**Comment by leandrolanzieri** [comment]
BTW tested on nrf52840dk and works Ok

**Comment by aabadie** [comment]
> With this solution gpio_irq_enable and gpio_irq_disable actually just enable/disable only the first registered interrupt, that may be confusing

You are right, I pushed e40f6374abc7af36a095b38dfc1f5912ee67a0aa to fix this.

File: cpu/nrf5x_common/periph/gpio.c [hunk 1]
```diff
@@ -125,44 +145,62 @@ void gpio_write(gpio_t pin, int value)
 int gpio_init_int(gpio_t pin, gpio_mode_t mode, gpio_flank_t flank,
                   gpio_cb_t cb, void *arg)
 {
+    assert(_gpiote_chan_index < GPIOTE_CHAN_NUMOF);
+
     /* disable external interrupt in case one is active */
     NRF_GPIOTE->INTENSET &= ~(GPIOTE_INTENSET_IN0_Msk);
```
Comment (leandrolanzieri) [inline cpu/nrf5x_common/periph/gpio.c]: Other interrupts should not be disabled.

File: cpu/nrf5x_common/periph/gpio.c [hunk 2]
```diff
@@ -125,44 +145,62 @@ void gpio_write(gpio_t pin, int value)
...
+    }
 }
 
 void gpio_irq_disable(gpio_t pin)
 {
-    (void) pin;
-    NRF_GPIOTE->INTENCLR |= GPIOTE_INTENSET_IN0_Msk;
+    for (unsigned int i = 0; i < _gpiote_chan_index; ++i) {
+        if (_exti_pins[i] == pin) {
+            NRF_GPIOTE->INTENCLR |= GPIOTE_INTENCLR_IN0_Msk << i;
```
Comment (leandrolanzieri) [inline cpu/nrf5x_common/periph/gpio.c]: There seems to be a problem when clearing the IN[n] event. When printing the register value before and after it appears that is set to 0.

**Comment by aabadie** [comment]
> could you confirm this?

yes, and I'm on it

**Comment by aabadie** [comment]
@leandrolanzieri, I fixed remaining problems and am now able to enable/disable all interrupt independently. There was also another issue with the previous code when one initialize several time the same pin: the `_chan_index` was always incremented. Now if the pin is already there, the same index is reused.
Thanks for reviewing and testing using `tests/periph_gpio`, it helped a lot :+1:

File: cpu/nrf5x_common/periph/gpio.c [hunk 3]
```diff
@@ -125,44 +145,77 @@ void gpio_write(gpio_t pin, int value)
...
 void gpio_irq_disable(gpio_t pin)
 {
-    (void) pin;
-    NRF_GPIOTE->INTENCLR |= GPIOTE_INTENSET_IN0_Msk;
+    for (unsigned int i = 0; i < _gpiote_next_index; i++) {
+        if (_exti_pins[i] == pin) {
+            uint32_t inten = NRF_GPIOTE->INTENCLR;
+            NRF_GPIOTE->INTENCLR = (GPIOTE_INTENCLR_IN0_Msk << i);
+            inten &= ~(GPIOTE_INTENSET_IN0_Msk << i);
+            NRF_GPIOTE->INTENSET = inten;
```
Comment (leandrolanzieri) [inline cpu/nrf5x_common/periph/gpio.c]: While testing I noticed that this is not needed. Just by doing ` NRF_GPIOTE->INTENCLR = (GPIOTE_INTENCLR_IN0_Msk << i);` the correspondent bit gets to 0.

Comment (aabadie) [reply cpu/nrf5x_common/periph/gpio.c]: You are right, I re-tested without and it is still working. I tried many things yesterday before I could have a working version.

See also the last commit which contains another change: pressing a button with disabled interrupt was triggering the interrupt when re-enabling it. I fixed by clearing any pending interrupt when re-enabling. This is weird.

Comment (leandrolanzieri) [reply cpu/nrf5x_common/periph/gpio.c]: > pressing a button with disabled interrupt was triggering the interrupt when re-enabling it. I fixed by clearing any pending interrupt when re-enabling. This is weird.

It seems that `INTENCLR` only disables interrupts from happening but not events from being registered. I changed that behavior by setting the `mode` bits of the `config` register to 'disabled', and setting them back to 'event' when re-enabling the irq.

I don't know if that is the correct way, in any case your solution only needs 1 line so I think that's fine.

**Comment by PeterKietzmann** [comment]
@aabadie please squash. @leandrolanzieri would you mind to test on one nrf51 based platform? I think we should be good to go then

**Comment by aabadie** [comment]
Wait a minute, I'd like to test @leandrolanzieri suggestion about the disabling events in the config register because I think this might be better if it works.

**Comment by aabadie** [comment]
@leandrolanzieri, I tested with the event disabled and it works much better. I think it's what should be done. Can you re-test ?

**Comment by leandrolanzieri** [comment]
> @leandrolanzieri, I tested with the event disabled and it works much better. I think it's what should be done. Can you re-test ?

Ok re-tested on nrf52840dk and nrf51dk and works fine! @aabadie you can squash now.

**Comment by aabadie** [comment]
Squashed. And I was testing on nrf52dk, this covers all cpu variants.
