### PR TITLE
tests/periph_rtt: Fix for tick conversion test 

### LINKED ISSUE #15940: Basic test for periph/rtt introduced in #15431 is incorrect
#### Description
Basic tests introduced in #15431 failed for RTT_FREQUENCY that are not a multiple of 2^n. 
The test assumes RTT time frequency is 1 Hz, 1024 Hz, 16384 Hz or 32768 Hz.
This assumption is wrong for RTT on ATMega128RFR2 and ATMega256RFR2. On these MCU the RTT has frequency 62500 Hz because RTT is based on 802.15.4 MAC symbols counter.

#### Steps to reproduce the issue
Run periph_rtt test on any board based on Atmel ATMega*RFR2: deRFmega128, deRFmega256, atmega256rfr2-xpro, avr-rss2.

#### Expected results
Test passes for platforms that use RTT_FREQUENCY that is not a multiple of 2^n.

#### Actual results
```
RIOT RTT low-level driver test<\n>
RTT configuration:<\n>
RTT_MAX_VALUE: 0x0000ffff<\n>
RTT_FREQUENCY: 62500<\n>
<\n>
Testing the tick conversion<\n>
Trying to convert 1 to seconds and back<\n>
Trying to convert 256 to seconds and back<\n>
Trying to convert 65536 to seconds and back<\n>
error: TICK conversion not working as expected
```

#### Versions
RIOT Version: 2020.10
Compiler version irrelated to the issue

### PR DESCRIPTION
**Pull request by chudov**
### Contribution description

Type casting and `printf` formatting for the `RTT_MAX_VALUE` and `RTT_FREQUENCY` are fixed so 32-bit value is properly handled by  'avr-libc'.
The original tick conversion test assumes that `RTT_FREQUENCY` is power of 2 so forward and backward ticks to seconds conversion results in the original ticks value. To fix it the result of the forward-backward conversion is compared with `ticktest / RTT_FREQUENCY * RTT_FREQUENCY` that considers rounding errors.

Changes were tested on deRFmega256 and nrf52840dongle.

### Testing procedure

tests/periph_rtt on a board with ATmega256RFR2 shall:
* show correct RTT_MAX_VALUE 
* conversion check shall report no error.

### Issues/PRs references

Fixes #15940

### CODE REVIEW

**Comment by chudov** [comment]
@benpicco is it better now?

**Comment by benpicco** [comment]
Yes, thank you!
But CI found that the build now [fails for ESP32](https://ci.riot-os.org/details/a68920ecdbcd494e9eee96c41cf7b166)

File: tests/periph_rtt/main.c [hunk 1]
```diff
@@ -105,17 +105,17 @@ int main(void)
     puts("\nRIOT RTT low-level driver test");
 
     puts("RTT configuration:");
-    printf("RTT_MAX_VALUE: 0x%08x\n", (unsigned)RTT_MAX_VALUE);
-    printf("RTT_FREQUENCY: %u\n\n", (unsigned)RTT_FREQUENCY);
+    printf("RTT_MAX_VALUE: 0x%08lx\n", (uint32_t)RTT_MAX_VALUE);
```
Comment (benpicco) [inline tests/periph_rtt/main.c:108]:
```suggestion
    printf("RTT_MAX_VALUE: 0x%08" PRIx32 "\n", (uint32_t)RTT_MAX_VALUE);
```

File: tests/periph_rtt/main.c [hunk 2]
```diff
@@ -105,17 +105,17 @@ int main(void)
...
+    printf("RTT_FREQUENCY: %lu\n\n", (uint32_t)RTT_FREQUENCY);
```
Comment (benpicco) [inline tests/periph_rtt/main.c:109]:
```suggestion
    printf("RTT_FREQUENCY: %" PRIu32 "\n\n", (uint32_t)RTT_FREQUENCY);
```

**Review by benpicco — APPROVED** [review]
bors merge
