### PR TITLE
cpu/stm32f1: Fix i2c for stm32f1 based boards

### LINKED ISSUE #10395: stm32f103xx: I2C has no internal pullups and af config
#### Description
When using the nucleo-f103rb the standard configuration is i2c0 on PB8 and PB9 the AFIO periph clock must be enabled 
`RCC->APB2ENR |= 0x00000001;` 
and the pin must be remapped to those pins 
`AFIO->MAPR |= AFIO_MAPR_I2C1_REMAP;`
Also due to the hardware constraints it seems like the internal pullup cannot be enabled since the pins must be set to `GPIO_AF_OUT_OD`.

In the [reference manual](https://www.st.com/content/ccc/resource/technical/document/reference_manual/59/b9/ba/7f/11/af/43/d5/CD00171190.pdf/files/CD00171190.pdf/jcr:content/translations/en.CD00171190.pdf) it seems like it is impossible to do so (in section 9.1.9 Alternate function configuration it states that 'The weak pull-up and pull-down resistors are disabled.')

I am not sure if anything can be done about requiring external pullups.

#### Steps to reproduce the issue
Try to use the i2c0 on any nucleo103xx on PB8 and PB9.

#### Expected results
It works.

#### Actual results
It doesn't work and will hang

### PR DESCRIPTION
**Pull request by MrKevinWeiss**
### Contribution description
This was discovered by the HiL testing.

This PR adds remapping if PB8 or PB9 are being used for i2c.  Previously the remapping didn't occur and would cause errors when trying to use this configuration.  This should only effect stm32F1XX based boards.  It also updated documentation to indicate pullup resistors are needed.  With this something like the nucleo-f103rb should now work.

### Testing procedure
Try to use the i2c on a nucleo-f103rb in master and with this PR.  It should at least respond (though the cpu implementation may not be correct)

### Issues/PRs references
fixes #10395

### CODE REVIEW

File: cpu/stm32_common/periph/i2c_2.c [hunk 1]
```diff
@@ -109,6 +109,14 @@ void i2c_init(i2c_t dev)
     gpio_init(i2c_config[dev].scl_pin, GPIO_OD_PU);
     gpio_init(i2c_config[dev].sda_pin, GPIO_OD_PU);
 #ifdef CPU_FAM_STM32F1
+    /* This is needed in case the remapped pins are used */
+    if (i2c_config[dev].scl_pin == GPIO_PIN(PORT_B, 8) ||
+        i2c_config[dev].sda_pin == GPIO_PIN(PORT_B, 9)) {
+        /* The remaping periph clock must first be enabled */
+        RCC->APB2ENR |= 0x00000001;
```
Comment (aabadie) [inline cpu/stm32_common/periph/i2c_2.c]: (Very minor but) Is there a macro from the CMSIS that could be used instead of the hard coded bit position ?

Comment (MrKevinWeiss) [reply cpu/stm32_common/periph/i2c_2.c]: Yup, lazy me. All done!

**Comment by aabadie** [comment]
Codewize, this PR is ok. Unfortunately, I don't have a nucleo-f103 (anymore) for testing but I tried the iotlab-m3 (no remapping) and it works as before which is expected.

**Comment by MrKevinWeiss** [comment]
@leandrolanzieri Has many of these boards for testing!

File: cpu/stm32_common/periph/i2c_2.c [hunk 2]
```diff
@@ -109,6 +109,14 @@ void i2c_init(i2c_t dev)
     gpio_init(i2c_config[dev].scl_pin, GPIO_OD_PU);
     gpio_init(i2c_config[dev].sda_pin, GPIO_OD_PU);
 #ifdef CPU_FAM_STM32F1
+    /* This is needed in case the remapped pins are used */
+    if (i2c_config[dev].scl_pin == GPIO_PIN(PORT_B, 8) ||
+        i2c_config[dev].sda_pin == GPIO_PIN(PORT_B, 9)) {
+        /* The remaping periph clock must first be enabled */
```
Comment (aabadie) [inline cpu/stm32_common/periph/i2c_2.c]: remaping => remap**p**ing

Comment (MrKevinWeiss) [reply cpu/stm32_common/periph/i2c_2.c]: Nice one, just keeping everyone on their toes :wink:

**Comment by leandrolanzieri** [comment]
Seems ok. Tested on nucleo-f103rb and works as expected.
