### PR TITLE
tests: fix compilation problems with NDEBUG

### LINKED ISSUE #13265: tests: compilation of some test applications fail with NDEBUG
#### Description

Some test applications use `assert` to check the test results for correctness. Applications that rely on `assert` should undefine `NDEBUG` at the beginning of their source code. Otherwise their compilation fail in
```
dist/tools/compile_and_test_for_board/compile_and_test_for_board.py
```
with defined environment variable `CLFAGS='-NDEBUG'`.

The following test application could already be identified:
```
- tests/gnrc_sock_ip
- tests/periph_eeprom
- tests/thread_msg_block_race
```

#### Steps to reproduce the issue

Compile these application for any board, for example:
```
CFLAGS='-DNDEBUG' make BOARD=arduino-mega2560 -C tests/gnrc_sock_ip
CFLAGS='-DNDEBUG' make BOARD=arduino-mega2560 -C tests/periph_eeprom
CFLAGS='-DNDEBUG' make BOARD=arduino-mega2560 -C tests/thread_msg_block_race
```

### PR DESCRIPTION
**Pull request by gschorcht**
### Contribution description

This PR fixes compilation problems (hopefully all remaining) when `NDEBUG` is defined.

Now where PR #13268 is merged, test applications should use `expect` instead of `assert` for testing conditions and results. Otherwise, they are not compilable when `NDEBUG` is defined. In difference to `assert`, `expect`  is not compiled out when compiling with  `NDEBUG`.

**NOTE** commit https://github.com/RIOT-OS/RIOT/pull/13466/commits/0c1baf267eb57344e41f411e4a8fb4213eb1f46d is just for the compilation test with `NDEBUG` and has to be dropped before the PR is merged.

### Testing procedure

The compilation in Murdock should succeed with commit https://github.com/RIOT-OS/RIOT/pull/13466/commits/0c1baf267eb57344e41f411e4a8fb4213eb1f46d.

### Issues/PRs references

Fixes #13265
Depends on ~#13465~
Depends on ~#13474~

### CODE REVIEW

**Comment by gschorcht** [comment]
The two remaining compilation errors are caused by increasing the RAM usage by the `expect` macro and should be fixed by PR #13474.

**Comment by gschorcht** [comment]
Murdock is happy now. Should the CPU-related part be moved to a separate PR? Commit https://github.com/RIOT-OS/RIOT/pull/13466/commits/46a82e5ce53eecbd63d7b51b8a3061e33bb09b02 has to be dropped before merging.

**Comment by gschorcht** [comment]
Could someone please set the status to `Changes requested` to avoid an accidental merge without first removing the commit https://github.com/RIOT-OS/RIOT/pull/13466/commits/0c1baf267eb57344e41f411e4a8fb4213eb1f46d before?

**Comment by gschorcht** [comment]
Should the fixes in `pkg` (1), `cpu` (2) and `examples` (1) be moved to separate PRs, or is it OK to leave them as part this PR?

**Comment by gschorcht** [comment]
@kaspar030 How do we continue with this PR? I had to rebase and fix the first conflicts already. Because of the number of affected tests, further conflicts are quite probable. Since required PRs #13268, #13465 and #13474 are merged for several weeks, there is no reason to keep this PR on hold. All tests should only use `expect` instead of `assert` from now.

**Comment by miri64** [comment]
In #13615 I added new asserts to `tests/lwip` and `tests/gnrc_sock_async_event` (and that one is only waiting for Murdock now). How should we handle this? I could use `expect()` instead of the new `assert()`s already there or I could keep it as is for now and leave it for you to clean-up :-/. Either way, we will have another merge conflict, I believe >.<

**Comment by gschorcht** [comment]
> In #13615 I added new asserts to `tests/lwip` and `tests/gnrc_sock_async_event` (and that one is only waiting for Murdock now). How should we handle this? I could use `expect()` instead of the new `assert()`s already there or I could keep it as is for now and leave it for you to clean-up :-/. Either way, we will have another merge conflict, I believe >.<

In this case, I'm fine if you could leave it for me clean-up. It shouldn't be a big thing. But I would prefer if we could merge the changes in this PR in near future :smile:

**Comment by miri64** [comment]
> But I would prefer if we could merge the changes in this PR in near future :smile:

I can empathize with that, but since there is still a block by @aabadie (which you requested... so can this maybe dismissed?)

**Comment by gschorcht** [comment]
> I can empathize with that, but since there is still a block by @aabadie (which you requested... so can this maybe dismissed?)

Yeah, I asked for this to avoid an accidental merge because all lights were green at the beginning. I only have to drop commit https://github.com/RIOT-OS/RIOT/pull/13466/commits/a0ad12421b6fb226f2809538c74b63a8107a9214 (it was just for compilation tests) and squash afterwards.

**Comment by miri64** [comment]
Interesting that merging #13615 did not cause a merge conflict. However, there were a couple asserts added, that should be transformed to expect here, IMHO.

**Comment by gschorcht** [comment]
> Interesting that merging #13615 did not cause a merge conflict. However, there were a couple asserts added, that should be transformed to expect here, IMHO.

That's correct. Since Murdock doesn't compile with `NDEBUG` nobody awares that `assert` is used instead of `expect` or where an `assert` might lead to compilation problems with `NDEBUG`.

We have to test the compilation from time to time with `NDEBUG`, for example with the nightly build. At the moment, I'm doing that manually with my PR #13266. Another possibility could be to always compile in Murdock with `NDEBUG`. Furthermore, we could add a small static test in CI which simply scans for asserts in `tests` and `examples`, but this wouldn't catch potential compilation problems in all other parts. @kaspar030 probably knows the best what the right approach would be.

**Comment by kaspar030** [comment]
> We have to test the compilation from time to time with `NDEBUG`, for example with the nightly build. At the moment, I'm doing that manually with my PR #13266. Another possibility could be to always compile in Murdock with `NDEBUG`. Furthermore, we could add a small static test in CI which simply scans for asserts in `tests` and `examples`, but this wouldn't catch potential compilation problems in all other parts. @kaspar030 probably knows the best what the right approach would be.

I've always looked at "DEVELHELP" as our "debug / development" build. We could define non-DEVELHELP as "release" build, compiling with "NDEBUG".

**Comment by gschorcht** [comment]
The last run show problems with PR #13615 and PR #13202. I will fix them.

**Comment by miri64** [comment]
@gschorcht is there a build _with_ `NDEBUG` you can point to?

File: tests/driver_at86rf2xx/cmd.c [hunk 1]
```diff
@@ -192,7 +192,7 @@ static size_t _parse_addr(uint8_t *out, size_t out_len, const char *in)
     const char *end_str = in;
     uint8_t *out_end = out;
     size_t count = 0;
-    int assert_cell = 1;
+    int expect_cell = 1;
```
Comment (miri64) [inline tests/driver_at86rf2xx/cmd.c]: Accidental search and replace?

File: tests/embunit/main.c [hunk 2]
```diff
@@ -20,7 +20,7 @@
 #include <stdlib.h>
 #include <string.h>
 
-#include "assert.h"
+#include "test_utils/expect.h"
```
Comment (miri64) [inline tests/embunit/main.c]: Neither `assert()` nor `expect()` are used in this file.

**Comment by gschorcht** [comment]
> @gschorcht is there a build _with_ `NDEBUG` you can point to?

The build were the tests from PR #13615 failed.

File: tests/thread_msg_block_race/main.c [hunk 3]
```diff
@@ -84,7 +85,7 @@ int main(void)
     timer_init(TIMER_DEV(0), TIMER_FREQ, _timer, NULL);
     random_init(timer_read(TIMER_DEV(0)));
     puts("Test is \"successful\" if it runs forever without halting\n"
-         "on any of the assertion in this file\n");
+         "on any of the expection in this file\n");
```
Comment (miri64) [inline tests/thread_msg_block_race/main.c]: Search & replace error, I believe.

File: tests/unittests/tests-core/tests-core-ringbuffer.c [hunk 4]
```diff
@@ -33,18 +33,18 @@ static ringbuffer_t rb = RINGBUFFER_INIT(rb_buf);
 static mutex_t mutex;
 static kernel_pid_t pid_add, pid_get;
 
-static void assert_avail(unsigned assumed)
+static void expect_avail(unsigned assumed)
```
Comment (miri64) [inline tests/unittests/tests-core/tests-core-ringbuffer.c]: Same in this file.

Comment (miri64) [reply tests/unittests/tests-core/tests-core-ringbuffer.c]: (IMHO the change on this whole file should be reverted)

File: tests/driver_at86rf2xx/cmd.c (hunk 1 above)
Comment (gschorcht) [reply tests/driver_at86rf2xx/cmd.c]: Of course, I tried to replace as much as possible automatically. Obviously, the regexp was not good enough. Good catch.

File: tests/unittests/tests-core/tests-core-ringbuffer.c (hunk 4 above)
Comment (gschorcht) [reply tests/unittests/tests-core/tests-core-ringbuffer.c]: I have it dropped the commit already.

File: tests/driver_at86rf2xx/cmd.c (hunk 1 above)
Comment (gschorcht) [reply tests/driver_at86rf2xx/cmd.c]: Dropped the commit.

**Comment by miri64** [comment]
Please squash your changes directly

File: tests/thread_msg_block_race/main.c (hunk 3 above)
Comment (gschorcht) [reply tests/thread_msg_block_race/main.c]: > Search & replace error, I believe.

Not in this case. I wasn't really sure. At least the right word would be `expectation`. I can change it back or correct. What would you prefer?

Comment (miri64) [reply tests/thread_msg_block_race/main.c]: I think its semantics at this point, as an assertion is an expectation, but if you prefer an expect-base word, I would prefer correct english (pretty sure there is no word `expection` unless its a typo of `exception` ;-))

**Comment by gschorcht** [comment]
@miri64 I found one more commit https://github.com/RIOT-OS/RIOT/commit/3e33372980e58ffc6f6bb1786d302ab919795371 that could be dropped. It was simply an include of `assert.h` without using it.

**Comment by gschorcht** [comment]
@miri64 Thanks for reviewing and merging so fast.

> I've always looked at "DEVELHELP" as our "debug / development" build. We could define non-DEVELHELP as "release" build, compiling with "NDEBUG".

@kaspar030 That is, Murdock would compile with `NDEBUG` if `DEVELHELP` isn't defined explicitly? But most of our examples and some of our tests define `DEVELHELP ?= 1` by default:
```
examples/arduino_hello-world/Makefile
examples/asymcute_mqttsn/Makefile
examples/bindist/Makefile
examples/ccn-lite-relay/Makefile
examples/cord_ep/Makefile
examples/cord_epsim/Makefile
examples/default/Makefile
examples/dtls-echo/Makefile
examples/dtls-sock/Makefile
examples/dtls-wolfssl/Makefile
examples/emcute_mqttsn/Makefile
examples/filesystem/Makefile
examples/gcoap/Makefile
examples/gnrc_border_router/Makefile
examples/gnrc_lorawan/Makefile
examples/gnrc_networking_mac/Makefile
examples/gnrc_networking/Makefile
examples/hello-world/Makefile
examples/ipc_pingpong/Makefile
examples/javascript/Makefile
examples/lorawan/Makefile
examples/lua_basic/Makefile
examples/lua_REPL/Makefile
examples/ndn-ping/Makefile
examples/nimble_gatt/Makefile
examples/nimble_heart_rate_sensor/Makefile
examples/nimble_scanner/Makefile
examples/posix_sockets/Makefile
examples/riot_and_cpp/Makefile
examples/saul/Makefile
examples/timer_periodic_wakeup/Makefile
examples/usbus_minimal/Makefile
examples/wakaama/Makefile
tests/Makefile.tests_common
tests/pkg_wolfcrypt-ed25519-verify/Makefile
tests/riotboot/Makefile
```
Even more problematic is that some of our tests hardcode the value `DEVELHELP := 1`:
```
tests/gnrc_dhcpv6_client_6lbr/Makefile
tests/gnrc_ipv6_ext_frag/Makefile
tests/gnrc_ipv6_ext/Makefile
tests/gnrc_ipv6_fwd_w_sub/Makefile
tests/gnrc_rpl_srh/Makefile
tests/thread_msg_block_race/Makefile
```
