### PR TITLE
cpu/cc26xx_cc13xx: enable periph clocks on sleep

### LINKED ISSUE #15130: cpu/cc26xx_cc13xx: CPU gets stuck on sched_arch_idle
#### Description

When executing any example contaning a firmware that depends on user input like `tests/shell`, `tests/periph_i2c` the shell will stop responding to user inputs as soon as possible.

#### Steps to reproduce the issue

- Flash any test/example that does have a shell. e.g.: `tests/shell`.
- As soon as main code is executed, it will stop responding to user input.
- Attaching a debugger and putting a breakpoint at `sched_arch_idle` may "workaround" the issue, so reproducing it on a debugger is a little bit harder.
- @bergzand pointed a workaround by removing the `FEATURES_PROVIDED +=  no_idle_thread` line at `cpu/cortexm_common/Makefile.features`, after this the bug doesn't happen.

#### Expected results

Run normally.

#### Actual results

CPU execution seems to stop at `sched_arch_idle` on the last lines at `__enable_irq/__disable_irq`.

#### Versions

RIOT master branch.

<details>
<summary>`make print-versions`</summary>

```
Operating System Environment
----------------------------
         Operating System: "elementary OS" "5.1.7 Hera"
                   Kernel: Linux 5.4.0-48-generic x86_64 x86_64
             System shell: /bin/dash (probably dash)
             make's shell: /bin/dash (probably dash)

Installed compiler toolchains
-----------------------------
               native gcc: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)
                  avr-gcc: missing
         mips-mti-elf-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
  riscv64-unknown-elf-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: xtensa-esp32-elf-gcc (crosstool-NG crosstool-ng-1.22.0-80-g6c4433a5) 5.2.0
   xtensa-esp8266-elf-gcc: missing
                    clang: missing

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.3.0"
      mips-mti-elf-newlib: missing
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
riscv64-unknown-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: "2.2.0"
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: missing
                    cmake: cmake version 3.10.2
                 cppcheck: missing
                  doxygen: 1.8.13
                      git: git version 2.17.1
                     make: GNU Make 4.1
                  openocd: Open On-Chip Debugger 0.10.0
                   python: Python 2.7.17
                  python2: Python 2.7.17
                  python3: Python 3.6.9
                   flake8: 3.5.0 (mccabe: 0.6.1, pycodestyle: 2.3.1, pyflakes: 1.6.0) CPython 3.6.9 on Linux
               coccinelle: missing
```
</details>

### PR DESCRIPTION
**Pull request by jeandudey**
### Contribution description

Fixes #15130 .

All registers for the peripherals that RIOT uses from `cc26xx_cc13xx` CPUs were gated only for run mode (normal mode), when entering idle mode the CPU  (`sched_arch_idle`), an interrupt (of the peripherals) would never fire because the peripherals weren't gated for "sleep"/"deepsleep".

### Testing procedure

- `make -C tests/shell flash term BOARD=cc1312-launchpad` and serial communication should work as usual.

### Issues/PRs references

#15130

### CODE REVIEW

File: cpu/cc26xx_cc13xx/power_arch.c [hunk 1]
```diff
@@ -96,18 +96,24 @@ void power_enable_domain(const power_domain_t domain)
 void power_clock_enable_gpio(void)
 {
     PRCM->GPIOCLKGR = GPIOCLKGR_CLK_EN;
+    PRCM->GPIOCLKGS = GPIOCLKGS_CLK_EN;
+    PRCM->GPIOCLKGDS = GPIOCLKGDS_CLK_EN;
```
Comment (benpicco) [inline cpu/cc26xx_cc13xx/power_arch.c:100]: Worth adding a comment as to what those modes are

File: cpu/cc26xx_cc13xx/power_arch.c [hunk 2]
```diff
@@ -96,18 +96,24 @@ void power_enable_domain(const power_domain_t domain)
...
     PRCM->GPTCLKGR |= (1 << tim);
+    PRCM->GPTCLKGS |= (1 << tim);
+    PRCM->GPTCLKGDS |= (1 << tim);
 
     prcm_commit();
 }
 void power_clock_enable_i2c(void) {
     PRCM->I2CCLKGR = I2CCLKGR_CLK_EN;
+    PRCM->I2CCLKGS = I2CCLKGS_CLK_EN;
+    PRCM->I2CCLKGDS = I2CCLKGDS_CLK_EN;
```
Comment (benpicco) [inline cpu/cc26xx_cc13xx/power_arch.c:116]: Do you really want to keep I2C powered on during sleep?

File: cpu/cc26xx_cc13xx/power_arch.c [hunk 3]
```diff
@@ -96,18 +96,24 @@ void power_enable_domain(const power_domain_t domain)
...
+    PRCM->GPIOCLKGDS = GPIOCLKGDS_CLK_EN;
 
     prcm_commit();
 }
 
 void power_clock_enable_gpt(uint32_t tim)
 {
     PRCM->GPTCLKGR |= (1 << tim);
+    PRCM->GPTCLKGS |= (1 << tim);
+    PRCM->GPTCLKGDS |= (1 << tim);
```
Comment (benpicco) [inline cpu/cc26xx_cc13xx/power_arch.c:109]: Probably worth amending the timer config struct so that timers can be flagged to keep running in deep sleep explicitly.

**Comment by jeandudey** [comment]
Made some tests and enabling deep sleep clock gating is not explicitly required, only sleep clock gate to work.

@benpicco what do you think about leaving only the fix (only run and sleep clock gates) and later implementing the proper power management using `pm_layered`?

**Comment by benpicco** [comment]
Yea that’s fine too.
In that case, just add some comments as to what the registers writes do, now that there are three of those in a single place 😉

File: cpu/cc26xx_cc13xx/power_arch.c (hunk 2 above)
Comment (benpicco) [reply cpu/cc26xx_cc13xx/power_arch.c:116]: Also, no `|=` here?

Comment (jeandudey) [reply cpu/cc26xx_cc13xx/power_arch.c]: Fixed at https://github.com/RIOT-OS/RIOT/pull/15134/commits/5d9f06cdd854c34fcd26779b1f654c519a474ef1 and https://github.com/RIOT-OS/RIOT/pull/15134/commits/276df2ed6a23e068c58f56bbd441044b6c381b88 respectively.

File: cpu/cc26xx_cc13xx/power_arch.c (hunk 3 above)
Comment (jeandudey) [reply cpu/cc26xx_cc13xx/power_arch.c]: I removed the deep sleep clock gating as it might not be desirable right now (we don't enter deep sleep). On a further PR I'll implement `pm_layered` properly.

File: cpu/cc26xx_cc13xx/power_arch.c (hunk 2 above)
Comment (benpicco) [reply cpu/cc26xx_cc13xx/power_arch.c]: Didn’t look into the data sheet yet, if this is a single purpose register we could save us the read-modify-write.

**Comment by benpicco** [comment]
Please squash

File: cpu/cc26xx_cc13xx/power_arch.c (hunk 2 above)
Comment (jeandudey) [reply cpu/cc26xx_cc13xx/power_arch.c]: The register actually has other fields so it makes sense to `|=`. However this could be a good place to apply bit-banding which I haven't tried yet.

**Comment by jeandudey** [comment]
Squashed and reworded the commit message to reflect correctly the changes.

File: cpu/cc26xx_cc13xx/power_arch.c (hunk 2 above)
Comment (benpicco) [reply cpu/cc26xx_cc13xx/power_arch.c]: When you use the functions from [`bit.h`](https://github.com/RIOT-OS/RIOT/blob/master/cpu/cortexm_common/include/bit.h#L75), bit-banding will be used automatically.

But this is for another PR :wink:

File: cpu/cc26x0/include/cc26x0_prcm.h [hunk 4]
```diff
@@ -341,6 +341,18 @@ typedef struct {
...
 #define I2CCLKGR_CLK_EN        0x1
 #define UARTCLKGR_CLK_EN_UART0 0x1
+
+#define GPIOCLKGS_CLK_EN       0x1
+#define I2CCLKGS_CLK_EN        0x1
+#define UARTCLKGS_CLK_EN_UART0 0x1
+
+#define GPIOCLKGS_CLK_EN       0x1
+#define I2CCLKGS_CLK_EN        0x1
+#define UARTCLKGS_CLK_EN_UART0 0x1
```
Comment (benpicco) [inline cpu/cc26x0/include/cc26x0_prcm.h:351]: Why define those twice?

**Review by benpicco — APPROVED** [review]

**Comment by jeandudey** [comment]
Thanks for the review :-)
