### PR TITLE
boards/nucleo-l152: configure LSI by default

### LINKED ISSUE #8024: boards/cpu: nucleo-l152 (stm32l1) broken on master
While testing #7687 we discovered, that the `nucleo-l152` (`stm32l1`) is broken since quite a while now. Bisecting lead to the changes in #7385 (specifically to dd49f225321d3929f41c6108749c04eab0eb9571).

The change from `__irq_enable()` to `irq_restore(state)` breaks the L1 for some reason, can't really tell why... 
When doing `s/irq_restore(state);/__enable_irq();/`, everything is working (again). The difference seems to be `/__ASM volatile ("MSR primask, %0" : : "r" (priMask) : "memory");`
vs
`__ASM volatile ("cpsie i" : : : "memory");`

 Any ideas?

### LINKED ISSUE #8240: periph/rtc breaks nucleo-l152
While re-testing #7712 I realised that it didn't work at all, then I tested other examples and nothing seems to work.

After bisecting and looking everywhere, I realised that #6900 was the culprit. Unfortunately I didn't have time to dig more into the issue, so I don't know exactly with commit is the real cause of the crash.

Even if I revert the changes, my PR still not work, but I'm investigating if there are more bugs related to this platform.

### PR DESCRIPTION
**Pull request by kYc0o**
### Contribution description
Some nucleo-l152 boards, namely revision C-01, don't have a LSE to rely on for low speed clocking, which is mostly used for RTC.

This PR makes it optional, and define LSI by default.

### Issues/PRs references
Fixes #8024 and fixes #8240, depends on ~#8518~ to fix everything.

### CODE REVIEW

**Comment by aabadie** [comment]
I don't think this PR fully fix #8024 and #8240, because it doesn't work when using LSE when the board has an external oscillator.

**Comment by kYc0o** [comment]
I think your problem is not related to the LSE in itself, but maybe something else. This PR makes LSI the default Low Speed clock source for the nucleo-l152 under any revision. If for some reason LSE breaks the board it needs to be investigated.

The real problem in #8024 was what it was fixed in #8518, this is only complementary to make work the nucleo-l152 by default (and not related to the stm32l152 CPU, which was affected by #7687).

I can't provide a fix for LSE (I don't even know what's the problem) since I don't have a board with it.

File: boards/nucleo-l152/include/periph_conf.h [hunk 1]
```diff
@@ -34,9 +34,17 @@ extern "C" {
...
 #define CLOCK_CORECLOCK     (32000000U)             /* targeted core clock frequency */
-/* 0: no external low speed crystal available,
- * 1: external crystal available (always 32.768kHz) */
-#define CLOCK_LSE           (1)
+/*
+ * 0: no external low speed crystal available,
+ * 1: external crystal available (always 32.768kHz)
+ *
+ * LSE might not be available by default in early (C-01) Nucleo boards.
+ * If you're sure it is present, define CLOCK_LSE=1 in your project
```
Comment (aabadie) [inline boards/nucleo-l152/include/periph_conf.h]: If someone with an C-03 board revision follows what is described here, it will result in a failing board (e.g. no stdio for example).
I suggest removing this line until we have a solution with LSE.

**Comment by aabadie** [comment]
BTW, with the current change nucleo-l152 works like a charm.

File: boards/nucleo-l152/include/periph_conf.h (hunk 1 above)
Comment (kYc0o) [reply boards/nucleo-l152/include/periph_conf.h]: Hmm... I'm still not completely convinced by this. I think that's obvious that if your board is not working after you set CLOCK_LSE=1 the reason is obviously that LSE is not working properly, so this message still make sense.

Besides, the fact that this board is broken with CLOCK_LSE is a bug, which should be documented somewhere e.g. an issue. Afterwards, of course it needs to be fixed, and it's out of the scope of this PR.

Comment (aabadie) [reply boards/nucleo-l152/include/periph_conf.h]: ok, but this is not what this comment is saying: 'If you're sure it is present' doesn't mean LSE might be broken.

Comment (kYc0o) [reply boards/nucleo-l152/include/periph_conf.h]: Ok I can add such information.

Comment (kYc0o) [reply boards/nucleo-l152/include/periph_conf.h]: Can you open an issue for this BTW?

**Comment by kYc0o** [comment]
Changed description and directly amended.

File: boards/nucleo-l152/include/periph_conf.h [hunk 2]
```diff
@@ -34,9 +34,17 @@ extern "C" {
...
-/* 0: no external low speed crystal available,
- * 1: external crystal available (always 32.768kHz) */
-#define CLOCK_LSE           (1)
+/*
+ * 0: no external low speed crystal available,
+ * 1: external crystal available (always 32.768kHz)
+ *
+ * LSE might not be available by default in early (C-01) Nucleo boards.
+ * For newer revisions, LSE crystal is present, but currently is not working.
+ * (issue #8545).
```
Comment (aabadie) [inline boards/nucleo-l152/include/periph_conf.h]: @kYc0o, use the full url, e.g. https://github.com/RIOT-OS/RIOT/pull/8545

Comment (kYc0o) [reply boards/nucleo-l152/include/periph_conf.h]: It's evident that the comment it's in the context of a github issue. Though I've put the complete address and amended directly the change.
