### PR TITLE
boards/lora-e5-dev: enable 3.3V and 5V output by default

### LINKED ISSUE #17052: Problem with onboard LM75 I2C devices on lora-e5-dev board
#### Description

Problem with I2C devices on board lora-e5-dev

The problem occurs with the onboard LM75

#### Steps to reproduce the issue

For onboard LM75
```
driver_lm75]> gmake BOARD=lora-e5-dev
```

#### Actual results

```
main(): This is RIOT! (Version: 2022.01-devel-217-g43bef)                    
Sensor test...                                                               
Initialization...                       
lm75: error reading device ID           
lm75: device ID Register doesnt matchInitialization  failed
```
#### Versions
```
RIOT]> gmake print-versions

Operating System Environment
----------------------------
         Operating System: macOS 11.6
                   Kernel: Darwin 20.6.0 x86_64 i386
./dist/tools/ci/print_toolchain_versions.sh: line 78: realpath: command not found
             System shell:  (probably dash)
             make's shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)

Installed compiler toolchains
-----------------------------
               native gcc: Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
        arm-none-eabi-gcc: arm-none-eabi-gcc (GNU Tools for Arm Embedded Processors 8-2018-q4-major) 8.2.1 20181213 (release) [gcc-8-branch revision 267074]
                  avr-gcc: missing
         mips-mti-elf-gcc: missing
           msp430-elf-gcc: missing
       riscv-none-elf-gcc: missing
  riscv64-unknown-elf-gcc: missing
     riscv-none-embed-gcc: missing
     xtensa-esp32-elf-gcc: missing
   xtensa-esp8266-elf-gcc: missing
                    clang: Apple clang version 12.0.5 (clang-1205.0.22.11)

Installed compiler libs
-----------------------
     arm-none-eabi-newlib: "3.0.0"
      mips-mti-elf-newlib: missing
        msp430-elf-newlib: missing
    riscv-none-elf-newlib: missing
riscv64-unknown-elf-newlib: missing
  riscv-none-embed-newlib: missing
  xtensa-esp32-elf-newlib: missing
xtensa-esp8266-elf-newlib: missing
                 avr-libc: missing (missing)

Installed development tools
---------------------------
                   ccache: ccache version 4.4.2
                    cmake: cmake version 3.19.2
                 cppcheck: missing
                  doxygen: missing
                      git: git version 2.30.1 (Apple Git-130)
                     make: GNU Make 3.81
                  openocd: Open On-Chip Debugger 0.11.0
                   python: Python 2.7.16
                  python2: Python 2.7.16
                  python3: Python 3.9.7
                   flake8: error: /usr/local/opt/python@3.9/bin/python3.9: No module named flake8
               coccinelle: missing

```

### PR DESCRIPTION
**Pull request by fjmolinas**
### Contribution description

While trying to fix #17052, I realized that when connecting  groove sensor the power led did not turn on, when checking the [schematic](https://files.seeedstudio.com/products/113990934/LoRa-E5%20Dev%20Board%20v1.0.pdf) I realized two GPIO's enable/disable 3.3V and 5V output. This being disabled was the only reason why i2c was not working and therefore the lm75 sensor.

image

image

### Testing procedure

`BOARD=lora-e5-dev make -C tests/saul/ clean flash term -j`
```
2021-11-07 18:52:39,010 # ##########################
2021-11-07 18:52:39,991 # 
2021-11-07 18:52:39,992 # Dev: LED(red)	Type: ACT_SWITCH
2021-11-07 18:52:39,992 # Data:	              1 
2021-11-07 18:52:39,992 # 
2021-11-07 18:52:39,997 # Dev: Button(B1 Boot)	Type: SENSE_BTN
2021-11-07 18:52:39,998 # Data:	              0 
2021-11-07 18:52:39,998 # 
2021-11-07 18:52:40,003 # Dev: Button(B2 D0)	Type: SENSE_BTN
2021-11-07 18:52:40,003 # Data:	              0 
2021-11-07 18:52:40,003 # 
2021-11-07 18:52:40,008 # Dev: lm75	Type: SENSE_TEMP
2021-11-07 18:52:40,009 # Data:	          20.87 °C
2021-11-07 18:52:40,009 # 
2021-11-07 18:52:40,010 # ##########################
2021-11-07 18:52:40,991 # 
2021-11-07 18:52:40,992 # Dev: LED(red)	Type: ACT_SWITCH
2021-11-07 18:52:40,992 # Data:	              1 
2021-11-07 18:52:40,992 # 
2021-11-07 18:52:40,997 # Dev: Button(B1 Boot)	Type: SENSE_BTN
2021-11-07 18:52:40,998 # Data:	              0 
2021-11-07 18:52:40,998 # 
2021-11-07 18:52:41,003 # Dev: Button(B2 D0)	Type: SENSE_BTN
2021-11-07 18:52:41,004 # Data:	              0 
2021-11-07 18:52:41,004 # 
2021-11-07 18:52:41,008 # Dev: lm75	Type: SENSE_TEMP
2021-11-07 18:52:41,009 # Data:	          24.87 °C
2021-11-07 18:52:41,009 # 
2021-11-07 18:52:41,010 # ##########################
2021-11-07 18:52:41,991 # 
2021-11-07 18:52:41,992 # Dev: LED(red)	Type: ACT_SWITCH
2021-11-07 18:52:41,992 # Data:	              1 
2021-11-07 18:52:41,992 # 
2021-11-07 18:52:41,997 # Dev: Button(B1 Boot)	Type: SENSE_BTN
2021-11-07 18:52:41,998 # Data:	              0 
2021-11-07 18:52:41,998 # 
2021-11-07 18:52:42,003 # Dev: Button(B2 D0)	Type: SENSE_BTN
2021-11-07 18:52:42,003 # Data:	              0 
2021-11-07 18:52:42,003 # 
2021-11-07 18:52:42,008 # Dev: lm75	Type: SENSE_TEMP
2021-11-07 18:52:42,009 # Data:	          25.87 °C
2021-11-07 18:52:42,009 # 
2021-11-07 18:52:42,010 # ##########################
```

### Issues/PRs references

Fixes #17052

### CODE REVIEW

File: boards/lora-e5-dev/include/board.h [hunk 1]
```diff
@@ -82,6 +82,27 @@ extern void lora_e5_dev_sx126x_set_rf_mode(sx126x_t *dev, sx126x_rf_mode_t rf_mo
 #define FE_CTRL2            GPIO_PIN(PORT_A, 5)
 /** @} */
 
+/**
+ * @brief    Enable 3.3V output
+ */
+#ifndef CONFIG_LORA_E5_DEV_ENABLE_3p3V
```
Comment (aabadie) [inline boards/lora-e5-dev/include/board.h:88]: Should the config symbol only use capital letter ?

```suggestion
#ifndef CONFIG_LORA_E5_DEV_ENABLE_3P3V
```

File: boards/lora-e5-dev/include/board.h [hunk 2]
```diff
@@ -82,6 +82,27 @@ extern void lora_e5_dev_sx126x_set_rf_mode(sx126x_t *dev, sx126x_rf_mode_t rf_mo
...
+#define CONFIG_LORA_E5_DEV_ENABLE_3p3V      1
+#endif
+/**
+ * @brief    Enable 5V output
+ */
+#ifndef CONFIG_LORA_E5_DEV_ENABLE_5V
+#define CONFIG_LORA_E5_DEV_ENABLE_5V        1
+#endif
+/**
+ * @brief    lora-e5-dev 3.V gpio enable pin
```
Comment (aabadie) [inline boards/lora-e5-dev/include/board.h:98]:
```suggestion
 * @brief    lora-e5-dev 3.3V gpio enable pin
```

**Review by aabadie — COMMENTED** [review]
Looks good but I have nitpicks.

Maybe also add Kconfig entries to enable the 3.3V and 5V pins ?

**Comment by fjmolinas** [comment]
> Looks good but I have nitpicks.
> 
> Maybe also add Kconfig entries to enable the 3.3V and 5V pins ?

addressed

**Review by aabadie — APPROVED** [review]
Looks good and test output was provided.

ACK

**Comment by aabadie** [comment]
Please squash!

**Comment by fjmolinas** [comment]
Thanks for the quick review!
