### PR TITLE
gnrc_icmpv6_error / gnrc_ipv6: fixes for unspecified address

### LINKED ISSUE #10419: gnrc_icmpv6_error: Able to bounce up to 64 ICMPv6 error messages between 2 instances
#### Description

It is possible to cause a node to transmit up to 64 ICMPv6 destination unreachable messages. Other ICMPv6 error messages are probably also possible.

This took a bit of time to reproduce after discovering it.

#### Steps to reproduce the issue

I was able to trigger this when using two native instances in combination with a Linux host using scapy.
 1. Start 2 native instances.
 2. Assign an global address to the first node, e.g. `fd02::5/64`
 3. wait a bit for the router solicitations to stabilize.
 4. send a packet with scapy to the second instance (the one that got the address from the router advertisement of the first instance):
```
sendp( Ether(dst=DST_HWADDR) / IPv6(src="fd02::1", dst=DST_ADDR) / UDP(), iface="tapbr0")
```

With
`DST_HWADDR` = the link layer address of the second instance.
`DST_ADDR` = The globally unique IPv6 address of the second instance (`fd02::something`)
`fd02::1` = An **"non-existing"** address on the subnet.

#### Expected results

Nothing is send, as neighbour discovery will fail.

#### Actual results

64 destination unreachable messages are bounced between two instances, each with the all zeros IPv6 address as destination (`::`). I suspect that the messages are bounced between the two hosts as the mac addresses are switched between each frame.

See attached pcapng for capture.

[multi_icmpv6_error.zip](https://github.com/RIOT-OS/RIOT/files/2590702/multi_icmpv6_error.zip)

@miri64 Please let me know if you're able to reproduce, it took me quite some time before I was able to trigger it on purpose.

### PR DESCRIPTION
**Pull request by miri64**
### Contribution description
This fixes the two bugs regarding the unspecified address I described in https://github.com/RIOT-OS/RIOT/issues/10419#issuecomment-439573538

1. Don't build and send ICMPv6 error messages destined to the unspecified address (::).
2. Don't send (and try to resolve) IPv6 messages addressed to the unspecified address.

### Testing procedure
Repeat the steps to reproduce in https://github.com/RIOT-OS/RIOT/issues/10419. The expected results (except for probing neighbor solicitations which are legitimate) should come to be.

### Issues/PRs references
Fixes #10419.

### CODE REVIEW

File: sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c [hunk 1]
```diff
@@ -192,16 +192,16 @@ static gnrc_pktsnip_t *_param_prob_build(uint8_t code, void *ptr,
     return pkt;
 }
 
-static void _send(gnrc_pktsnip_t *pkt, const gnrc_pktsnip_t *orig_pkt)
+static void _send(gnrc_pktsnip_t *pkt, const gnrc_pktsnip_t *orig_pkt
+                  gnrc_pktsnip_t *ipv6)
```
Comment (bergzand) [inline sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c]: Missing `,` between the last two arguments ;)

Comment (miri64) [reply sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c]: I was sure I compiled that oO

Comment (miri64) [reply sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c]: Addressed

**Comment by miri64** [comment]
Note to self, compile test code from yesterday night, even if you think you did...

**Comment by bergzand** [comment]
Wit this PR, I'm unable to trigger a Destination unreachable from a native instance by sending an UDP frame :/

**Comment by miri64** [comment]
I don't understand your ":/". Isn't this a good thing? Or do you mean something else than described in #10419?

File: sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c [hunk 2]
```diff
@@ -237,39 +237,69 @@ static void _send(gnrc_pktsnip_t *pkt, const gnrc_pktsnip_t *orig_pkt)
...
+    /* discarding const qualifier is safe here */
+    gnrc_pktsnip_t *ipv6 = gnrc_pktsnip_search_type((gnrc_pktsnip_t *)orig_pkt,
+                                                    GNRC_NETTYPE_IPV6);
+    const ipv6_hdr_t *ipv6_hdr = ipv6->data;
+    assert(ipv6 != NULL);
+
+    if (ipv6_addr_is_unspecified(&ipv6_hdr->src)) {
+        ipv6 = NULL;
+    }
+    return NULL;
```
Comment (bergzand) [inline sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c]: Shouldn't this be `ipv6` instead of `NULL`?

**Comment by bergzand** [comment]
> I don't understand your ":/". Isn't this a good thing? Or do you mean something else than described in #10419?

What I was trying to say is that I don't get a Destination Unreachable response anymore for "valid" cases where I expect to receive a Destination Unreachable from the instance, so for example with:
```
srp1( Ether(dst=DST_HWADDR) / IPv6(dst=DST_ADDR, src=SRC_ADDR)  / UDP(dport=1337), iface="tapbr0")
```

File: sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c (hunk 2 above)
Comment (miri64) [reply sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c]: Can only quote myself here ...

> Note to self, compile test code from yesterday night, even if you think you did...

Comment (miri64) [reply sys/net/gnrc/network_layer/icmpv6/error/gnrc_icmpv6_error.c]: Fixed

**Comment by miri64** [comment]
Yepp... Fixed that.

**Comment by bergzand** [comment]
I was also wondering if multicast addresses should be filtered out. Is it valid to respond with an ICMPv6Error to a frame with a multicast address as source (and transmit the error response to a multicast address)

**Comment by bergzand** [comment]
To expand my previous comment, should I receive an error response from a frame like this? Assuming there is nothing listening on UDP port 1337 on the instance. And should the error then have the multicast address as destination
```
srp1( Ether(dst=DST_HWADDR) / IPv6(dst=DST_ADDR, src="ff02::1")  / UDP(dport=1337), iface="tapbr0")
```

**Comment by miri64** [comment]
> To expand my previous comment, should I receive an error response from a frame like this? Assuming there is nothing listening on UDP port 1337 on the instance.

Yes of course there should also be an error message.

> And should the error then have the multicast address as destination[?]

No why? We send the packet back as always to the *source* of the IPv6 packet and that's the only interested party.

**Comment by miri64** [comment]
Ahh... I get what you mean now. You are right! Multicast should be filtered out as well, but let me check if `gnrc_ipv6` not already does that ;-)

**Comment by bergzand** [comment]
> Fixed and also amended the new behavior to the documentation.

Thanks!

ACK, please squash!

**Comment by miri64** [comment]
Squashed and rebased

**Comment by miri64** [comment]
Fixed and force-pushed error pointed out by `cppcheck`.

**Comment by bergzand** [comment]
:+1: on the force push

**Comment by miri64** [comment]
Murdock's happy :-)

**Comment by bergzand** [comment]
And go!
