### PR TITLE
net/skald: Update Kconfig implementation

### LINKED ISSUE #15776: skald: advertising channel configuration broken by kconfig remodel
#### Description
The adaption to kconfig broke the advertising channel configuration for `skald`: the purpose of the `SKALD_ADV_CHAN` define is to allow for any arbitrary number and order of channels to be defined. Although only 3 of the possible 39 channels should be used for advertising by the spec, there might be situations to also use some of the remaining data channels, e.g. for testing or experimentation.

Also the current form of parameters does not allow for changing the order of the given channels through kconfig...

It seems to me, that one should be able to simply specify a list of comma separated values (e.g. `37,38,39`) as configuration value through kconfig. However, I have no idea how to do that, so I leave this to the pros :)

#### Steps to reproduce the issue
n/a

#### Expected results
should be possible to define any set of channels to use for advertising, e.g. `17,39,7,12`

#### Actual results
fixed order and limited to the 3 advertising channels

#### Versions
master

### PR DESCRIPTION
**Pull request by akshaim**
### Contribution description

This PR fixes issue #15776 

### Testing procedure

1. New documentation was built using Doxygen 

   The build works fine.

  2. Build successful. Tested this [example](https://github.com/akshaim/RIOT/commit/1d13658430c0ad77de08429e174c292a2e16dc85). Results below

      Compiled binaries for nrf52dk

##### Firmware Output

```
main(): This is RIOT! (Version: 2021.04-devel-177-ga9da09-Kconfig_skald_update)
CONFIG_SKALD_INTERVAL=(1 * (1000000LU))
3
37
38
39
```

#### Usage with menuconfig :

`make menuconfig`

#### Default values

```
main(): This is RIOT! (Version: 2021.04-devel-177-ga9da09-Kconfig_skald_update)
CONFIG_SKALD_INTERVAL=1000000
3
37
38
39
```
##### Macros Configured output

```
main(): This is RIOT! (Version: 2021.04-devel-177-ga9da09-Kconfig_skald_update)
CONFIG_SKALD_INTERVAL=1000000
5
37
10
11
38
39
```

**MACROS were successfully configured.**

### Issues/PRs references

#12888 
#14824
Fixes #15776

### CODE REVIEW

File: sys/net/ble/skald/skald.c [hunk 1]
```diff
@@ -46,7 +56,7 @@
 #define ADV_AA                  (0x8e89bed6)    /* access address */
 #define ADV_CRC                 (0x00555555)    /* CRC initializer */
 
-static const uint8_t _adv_chan[] = SKALD_ADV_CHAN;
+static uint8_t _adv_chan[] = CONFIG_SKALD_ADV_CHAN;
```
Comment (leandrolanzieri) [inline sys/net/ble/skald/skald.c:59]: I think this may be messing with the definition of `ADV_CHAN_NUMOF`, which is used to traverse through the channels later.

Comment (akshaim) [reply sys/net/ble/skald/skald.c]: Thanks for the suggestion. Added fixup.

File: sys/net/ble/skald/skald.c [hunk 2]
```diff
@@ -110,6 +124,17 @@ void skald_init(void)
...
 #endif
 
+    /* Extract the channels from string set by Kconfig */
+#if defined(CONFIG_SKALD_ADV_CHAN_NO) //
+    char str[] = CONFIG_SKALD_ADV_CHAN;
+    char *store = NULL, *token;
+    uint8_t offset=0;
+    for (token = strtok_r(str, ", ", &store); token != NULL;
+         token = strtok_r(NULL, ", ", &store), offset++) {
+        _adv_chan[offset] = atoi(token);
```
Comment (leandrolanzieri) [inline sys/net/ble/skald/skald.c:134]: You should check for the array length now, if not it could overflow.

**Review by haukepetersen — CHANGES_REQUESTED** [review]
I find this approach suboptimal to put it in nice words :-) I think its conceptually broken: introducing expensive (`strtok_r`) runtime code to cover up for the shortcomings of an external configuration tool can't be the way to go. Although most of the code is only active if kconfig is used and the `SKALD_ADV_CHAN_CUSTOM` option is active, it still also introduces changes to the, quite optimized non-kconfig code path (e.g. making `_adv_chan` non const).

So as discussed offline, I would strongly prever to loose some flexibility for  kconfig over introducing a runtime penalty. Expanding the code master to allow for each of the 40 channels but miss on the option to re-order them seems fine to me. One can always build without kconfig to get the full flexibility :-)

**Comment by leandrolanzieri** [comment]
> So as discussed offline, I would strongly prever to loose some flexibility for kconfig over introducing a runtime penalty. Expanding the code master to allow for each of the 40 channels but miss on the option to re-order them seems fine to me. One can always build without kconfig to get the full flexibility :-)

I agree that having the parser runtime is not the best. Currently Kconfig allows to select from the channels in the spec., or one can override `SKALD_ADV_CHAN` with the C array initialization directly. I see no big issue in adding the rest of the channels, other than having more symbols.

**Comment by haukepetersen** [comment]
so I guess lets take that route then :-)

**Comment by akshaim** [comment]
@haukepetersen  @leandrolanzieri  As discussed, PR updated.

File: sys/include/net/skald.h [hunk 3]
```diff
@@ -65,70 +66,20 @@ extern "C" {
...
 #ifndef SKALD_ADV_CHAN
-#define SKALD_ADV_CHAN { ADV_CH_37 ADV_CH_38 ADV_CH_39 }
+#define SKALD_ADV_CHAN { ADV_CH_37 ADV_CH_0 ADV_CH_1 ADV_CH_2 ADV_CH_3 \
+                         ADV_CH_4 ADV_CH_5 ADV_CH_6 ADV_CH_7 ADV_CH_8 ADV_CH_9 \
+                         ADV_CH_10 ADV_CH_38 ADV_CH_11 ADV_CH_12 ADV_CH_13 \
+                         ADV_CH_15 ADV_CH_16 ADV_CH_17 ADV_CH_18 ADV_CH_19 \
+                         ADV_CH_20 ADV_CH_21 ADV_CH_22 ADV_CH_23 ADV_CH_24 \
+                         ADV_CH_25 ADV_CH_26 ADV_CH_27 ADV_CH_28 ADV_CH_29 \
+                         ADV_CH_30 ADV_CH_31 ADV_CH_32 ADV_CH_33 ADV_CH_34 \
+                         ADV_CH_35 ADV_CH_36 ADV_CH_38 ADV_CH_39 }
```
Comment (leandrolanzieri) [inline sys/include/net/skald.h:82]: What about instead of this, you have another definition of the array in `skald_kconfig.h` which only applies when Kconfig is used. You can just leave this default as before with the basic channels. In the form of:
```c
{
#if IS_ACTIVE(CONFIG_ADV_CH_1_ENABLE)
1,
#endif
#if IS_ACTIVE(CONFIG_ADV_CH_2_ENABLE)
2,
#endif
[...]
}
```
Instead of all those extra macros?

Comment (akshaim) [reply sys/include/net/skald.h:82]: Yes, makes sense :) . Thanks for the suggestion.

Comment (akshaim) [reply sys/include/net/skald.h]: Done. Multiline `#defines` with conditions seems to behave strangely hence kept the syntax intact.

Comment (leandrolanzieri) [reply sys/include/net/skald.h]: What do you mean?

**Comment by leandrolanzieri** [comment]
Hey, what about we do the parsing of the string version of the configuration on a `Makefile.include` in skald module? Could look something like:

```diff
diff --git a/sys/Makefile.include b/sys/Makefile.include
index f9c46b14ad..875f9c6bcd 100644
--- a/sys/Makefile.include
+++ b/sys/Makefile.include
@@ -101,6 +101,10 @@ ifneq (,$(filter riotboot,$(FEATURES_USED)))
   include $(RIOTBASE)/sys/riotboot/Makefile.include
 endif
 
+ifneq (,$(filter skald, $(USEMODULE)))
+  include $(RIOTBASE)/sys/net/ble/skald/Makefile.include
+endif
+
 ifneq (,$(filter sock_async_event,$(USEMODULE)))
   include $(RIOTBASE)/sys/net/sock/async/event/Makefile.include
 endif
diff --git a/sys/net/ble/skald/Kconfig b/sys/net/ble/skald/Kconfig
index 92950a51e1..c7606bbb7e 100644
--- a/sys/net/ble/skald/Kconfig
+++ b/sys/net/ble/skald/Kconfig
@@ -19,13 +19,8 @@ config SKALD_INTERVAL
         Configure advertising interval in microseconds. Default value is 1
         second which is 1000000 microseconds.
 
-config ADV_CH_37_DISABLE
-    bool "Disable advertising on channel 37"
-
-config ADV_CH_38_DISABLE
-    bool "Disable advertising on channel 38"
-
-config ADV_CH_39_DISABLE
-    bool "Disable advertising on channel 39"
+config SKALD_ADV_CHANNELS
+    string "Advertising channels"
+    default "37, 38, 39"
 
 endif # KCONFIG_USEMODULE_SKALD
diff --git a/sys/net/ble/skald/Makefile.include b/sys/net/ble/skald/Makefile.include
new file mode 100644
index 0000000000..b1b2dbbc2c
--- /dev/null
+++ b/sys/net/ble/skald/Makefile.include
@@ -0,0 +1,4 @@
+ifdef CONFIG_SKALD_ADV_CHANNELS
+  SKALD_ADV_CHAN := { $(shell echo $(CONFIG_SKALD_ADV_CHANNELS)) }
+  CFLAGS += -DSKALD_ADV_CHAN="$(SKALD_ADV_CHAN)"
+endif
```

**Comment by akshaim** [comment]
> Hey, what about we do the parsing of the string version of the configuration on a `Makefile.include` in skald module? Could look something like:
> 
> ```diff
> diff --git a/sys/Makefile.include b/sys/Makefile.include
> index f9c46b14ad..875f9c6bcd 100644
> --- a/sys/Makefile.include
> +++ b/sys/Makefile.include
> @@ -101,6 +101,10 @@ ifneq (,$(filter riotboot,$(FEATURES_USED)))
>    include $(RIOTBASE)/sys/riotboot/Makefile.include
>  endif
>  
> +ifneq (,$(filter skald, $(USEMODULE)))
> +  include $(RIOTBASE)/sys/net/ble/skald/Makefile.include
> +endif
> +
>  ifneq (,$(filter sock_async_event,$(USEMODULE)))
>    include $(RIOTBASE)/sys/net/sock/async/event/Makefile.include
>  endif
> diff --git a/sys/net/ble/skald/Kconfig b/sys/net/ble/skald/Kconfig
> index 92950a51e1..c7606bbb7e 100644
> --- a/sys/net/ble/skald/Kconfig
> +++ b/sys/net/ble/skald/Kconfig
> @@ -19,13 +19,8 @@ config SKALD_INTERVAL
>          Configure advertising interval in microseconds. Default value is 1
>          second which is 1000000 microseconds.
>  
> -config ADV_CH_37_DISABLE
> -    bool "Disable advertising on channel 37"
> -
> -config ADV_CH_38_DISABLE
> -    bool "Disable advertising on channel 38"
> -
> -config ADV_CH_39_DISABLE
> -    bool "Disable advertising on channel 39"
> +config SKALD_ADV_CHANNELS
> +    string "Advertising channels"
> +    default "37, 38, 39"
>  
>  endif # KCONFIG_USEMODULE_SKALD
> diff --git a/sys/net/ble/skald/Makefile.include b/sys/net/ble/skald/Makefile.include
> new file mode 100644
> index 0000000000..b1b2dbbc2c
> --- /dev/null
> +++ b/sys/net/ble/skald/Makefile.include
> @@ -0,0 +1,4 @@
> +ifdef CONFIG_SKALD_ADV_CHANNELS
> +  SKALD_ADV_CHAN := { $(shell echo $(CONFIG_SKALD_ADV_CHANNELS)) }
> +  CFLAGS += -DSKALD_ADV_CHAN="$(SKALD_ADV_CHAN)"
> +endif
> ```

Thanks, @leandrolanzieri . Saved 800 lines in the header!

**Review by haukepetersen — APPROVED** [review]
This looks much better :-) No blocker from my side for this take.

However, I did not run/test anything.

File: sys/include/net/skald.h [hunk 4]
```diff
@@ -67,68 +67,21 @@ extern "C" {
...
-
-/**
- * @brief   Configure advertising channel 39
- *
- * Set CONFIG_ADV_CH_39_DISABLE to disable channel 39
- */
-#ifdef DOXYGEN
-#define CONFIG_ADV_CH_39_DISABLE
+#if defined(DOXYGEN)
+#define CONFIG_SKALD_ADV_CHANNELS
```
Comment (leandrolanzieri) [inline sys/include/net/skald.h:76]: I don't think this needed, it is only used by Kconfig. The user that configures the channels via CFLAGS would use `SKALD_ADV_CHAN` instead. To me adding two knobs creates unnecessary confusion.

Comment (akshaim) [reply sys/include/net/skald.h:76]: Where do you think I should document the symbol `CONFIG_SKALD_ADV_CHANNELS` ?

Comment (leandrolanzieri) [reply sys/include/net/skald.h]: It's not used directly in the source code, so I think we need documentation of it in the header file. It's a Kconfig symbol, it already has documentation in the Kconfig file.

**Comment by leandrolanzieri** [comment]
Looks good. Please squash @akshaim
